[1.21.1] Add a way to have extra Context for Mod Constructor
MinecraftForge/MinecraftForge pull request #10074
Opened 2024-08-20 12:40 UTC by RealMangorage

Allows for passing thru of a Context object to get objects like IModBus without the need for hacks.

Example -> 

public BiomeTestMod(FMLJavaModContext context) {
    var modBus = context.getModBus();
    modBus.addListener(BiomeTestMod::onDataGen);
}

2024-08-20 13:16 UTC, PaintNinja requested changes
- Please rebase rather than manually recommitting existing Forge commits since your branch creation
- The MDK should be updated to use this new feature
- It would be better if it used the existing FMLConstructModEvent instead of a new separate class

2024-08-20 18:25 UTC, PaintNinja requested changes

2024-08-20 18:25 UTC, PaintNinja commented on fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
> +@Deprecated
We probably shouldn't deprecate something before we know its replacement

2024-08-20 18:25 UTC, PaintNinja commented on src/main/java/net/minecraftforge/fml/event/lifecycle/FMLConstructModEvent.java
> +    public IEventBus getModBus() {
Please rename to `getModEventBus()` to match FMLJavaModLoadingContext

2024-08-20 18:25 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +            Class<?> fmlConstructEvent = Class.forName("net.minecraftforge.fml.event.lifecycle.FMLConstructEvent", true, Thread.currentThread().getContextClassLoader());
Currently crashes here, you probably need to use the FML Bindings.

2024-08-20 18:25 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +    private final Object contextObject;
I think you can narrow the type to `Event`

2024-08-20 18:25 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                throw new IllegalStateException("Unable to find Consturctor");
ctor will never be null, because `getDeclaredConstructor()` throws instead

2024-08-20 18:25 UTC, PaintNinja commented on src/main/java/net/minecraftforge/fml/event/lifecycle/FMLConstructModEvent.java
>  public class FMLConstructModEvent extends ParallelDispatchEvent {
Please also copy over the registerConfigScreen methods from the MinecraftForge class

2024-08-20 18:27 UTC, RealMangorage commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +            Class<?> fmlConstructEvent = Class.forName("net.minecraftforge.fml.event.lifecycle.FMLConstructEvent", true, Thread.currentThread().getContextClassLoader());
Wrong Class name :)

2024-08-20 18:28 UTC, RealMangorage commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                throw new IllegalStateException("Unable to find Consturctor");
Alright

2024-08-20 19:10 UTC, PaintNinja requested changes

2024-08-20 19:10 UTC, PaintNinja commented on fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
> +
Stray new line

2024-08-20 19:10 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLJavaModLoadingContext.java
> + * instead in your mods constructor to get access to ModBus.
```suggestion
 * instead in your mod's constructor to get access to its EventBus.
```

2024-08-20 19:10 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +            this.contextObject = (Event) fmlConstructEvent.getConstructor(ModContainer.class, ModLoadingStage.class).newInstance(this, getCurrentState());
`getCurrentState()` is always `ModLoadingStage.CONSTRUCT` here, so can inline the constant
```suggestion
            this.contextObject = (Event) fmlConstructEvent.getConstructor(ModContainer.class, ModLoadingStage.class).newInstance(this, ModLoadingStage.CONSTRUCT);
```

2024-08-20 19:10 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeMod.java
> +        modEvent.registerExtensionPoint(IExtensionPoint.DisplayTest.class, ()->new IExtensionPoint.DisplayTest(()->"ANY", (remote, isServer)-> true));
While you're at it, this can be simplified to:
```suggestion
        modEvent.registerDisplayTest(IExtensionPoint.DisplayTest.IGNORE_ALL_VERSION);
```

2024-08-20 19:10 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                ctor = modClass.getDeclaredConstructor();
Is it possible for this to throw if the mod doesn't *explicitly* declare neither a no-arg ctor nor an event param ctor?

2024-08-20 19:10 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +            Class<?> fmlConstructEvent = Class.forName( "net.minecraftforge.fml.event.lifecycle.FMLConstructModEvent", true, Thread.currentThread().getContextClassLoader());
For performance reasons, this should probably be thrown in a lazy static final, like so:
```java
// above the FMLModContainer ctor
private static final class LazyInit {
    private LazyInit() {}
    private static final Constructor<?> FML_CONSTRUCT_EVENT_CTOR = LamdbaExceptionUtils.uncheck(() ->
            Class.forName("net.minecraftforge.fml.event.lifecycle.FMLConstructModEvent", true, Thread.currentThread().getContextClassLoader())
                    .getConstructor(ModContainer.class, ModLoadingStage.class)
    );
}

// inside the ctor
this.contextObject = (Event) LazyInit.FML_CONSTRUCT_EVENT_CTOR.newInstance(this, ModLoadingStage.CONSTRUCT);
```

2024-08-20 19:13 UTC, RealMangorage commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                ctor = modClass.getDeclaredConstructor();
Yes

2024-08-20 19:35 UTC, PaintNinja requested changes

2024-08-20 19:35 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                        .getConstructor(ModContainer.class, ModLoadingStage.class)
```suggestion
                        .getDeclaredConstructor(ModContainer.class, ModLoadingStage.class)
```

2024-08-20 19:35 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
>              modClass = Class.forName(module, className);
Did you mean to put a new line between this rather than two on top?

2024-08-20 19:35 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/MinecraftForge.java
>      public static void registerConfigScreen(Function<Screen, Screen> screenFunction) {
Currently doesn't render correctly:
<img width="587" alt="image" src="https://github.com/user-attachments/assets/d074a2ea-bc19-4973-8cc6-9217d0cb9953">

```suggestion
     *
     * @deprecated Use {@link net.minecraftforge.fml.event.lifecycle.FMLConstructModEvent#registerConfigScreen(Function)} instead
     */
    @Deprecated(forRemoval = true)
    public static void registerConfigScreen(Function<Screen, Screen> screenFunction) {
```

2024-08-20 19:35 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/MinecraftForge.java
> +    @Deprecated(forRemoval = true)
Missing since="1.21.1"

2024-08-20 19:35 UTC, PaintNinja commented on src/main/java/net/minecraftforge/fml/event/lifecycle/FMLConstructModEvent.java
> + * used in your mods constructor to get access to ModBus and various mod-specific objects.
```suggestion
 * Supplied as a param to your mod's constructor to get access to the mod EventBus and various mod-specific objects.
```

2024-08-20 19:35 UTC, PaintNinja commented on src/main/java/net/minecraftforge/fml/event/lifecycle/FMLConstructModEvent.java
> +        return null;
While other languages aren't in scope of this PR, I can't help but think that adding another ctor with IEventBus as a parameter would make it easier for other language providers to reuse this existing event.

Would also remove the need to touch FMLModContainer, as the event bus can be supplied directly to the event.

2024-08-21 12:18 UTC, PaintNinja requested changes

2024-08-21 12:18 UTC, PaintNinja commented on fmlcore/src/main/java/net/minecraftforge/fml/ModLoadingContext.java
> +     * @deprecated take a look at {@link net.minecraftforge.fml.event.lifecycle.FMLConstructModEvent}
Pointing to the exact method would be a better dev migration UX as it makes it clear the method hasn't changed - only its location. In IntelliJ you can right click on a method -> copy -> copy reference to get the link that'll work with javadocs.
```suggestion
     * @deprecated Use {@link net.minecraftforge.fml.event.lifecycle.FMLConstructModEvent#registerExtensionPoint} instead
```

2024-08-21 12:18 UTC, PaintNinja commented on fmlcore/src/main/java/net/minecraftforge/fml/util/IEventBusSupplier.java
> +public interface IEventBusSupplier extends Supplier<IEventBus> {
What is this for? Can it return any event bus like `MinecraftForge.EVENT_BUS` or is it meant to always be a mod event bus? Why not supply the mod event bus directly to the FMLConstructModEvent constructor to avoid indirection? Having `FMLModContainer.get()` return an EventBus is unintuitive

2024-08-21 13:06 UTC, RealMangorage commented on fmlcore/src/main/java/net/minecraftforge/fml/util/IEventBusSupplier.java
> +public interface IEventBusSupplier extends Supplier<IEventBus> {
I'm not gonna add it to the constructor. This is the solution.

2024-08-21 13:09 UTC, PaintNinja commented on fmlcore/src/main/java/net/minecraftforge/fml/util/IEventBusSupplier.java
> +public interface IEventBusSupplier extends Supplier<IEventBus> {
Please explain why and answer my questions

2024-08-21 14:56 UTC, Ecdcaeb commented on fmlcore/src/main/java/net/minecraftforge/fml/util/IEventBusSupplier.java
> +public interface IEventBusSupplier extends Supplier<IEventBus> {
> I'm not gonna add it to the constructor. This is the solution.

Why do always want to get the mod bus from ModContainer? Not all ModContainers can adapt to this change. In addition, the constructor of FMLConstructModEvent is a private api, so the change here is obviously smaller.

2024-08-22 11:57 UTC, PaintNinja commented on fmlcore/src/main/java/net/minecraftforge/fml/util/IEventBusSupplier.java
> +public interface IEventBusSupplier extends Supplier<IEventBus> {
https://discord.com/channels/1129059589325852724/1129095235889270844/1275823283442552893

2024-08-22 12:10 UTC, PaintNinja requested changes

2024-08-22 12:10 UTC, PaintNinja commented on fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
> +    public @Nullable IEventBus getEventBus() {
```suggestion
    public @Nullable IEventBus getModEventBus() {
```
Considering that the only usage of this is in `FMLConstructModEvent` for grabbing the mod event bus, renaming the method accordingly would be clearer and match the name of the (now deprecated) `FMLJavaModLoadingContext.getModEventBus()` method

2024-08-22 12:10 UTC, PaintNinja commented on mdk/src/main/java/com/example/examplemod/ExampleMod.java
>  import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
This now-unused import can be removed
```suggestion

```

2024-08-22 12:10 UTC, PaintNinja commented on mdk/src/main/java/com/example/examplemod/ExampleMod.java
> +        IEventBus modEventBus = event.getModBus();
Compile error in the MDK, should be this instead:
```suggestion
        IEventBus modEventBus = event.getModEventBus();
```

2024-08-22 20:26 UTC, PaintNinja approved these changes

2024-08-23 13:39 UTC, Ecdcaeb commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                ctor = modClass.getDeclaredConstructor();
Given that most mods currently do not have this constructor, how do we consider the performance issues of using try-catch? How about using `getDeclaredConstructors` and filtering instead?
```java
final Class<?> classFMLConstructEvent = contextObject.getClass();
Arrays.stream(cls.getDeclaredConstructors())
                .filter(c -> c.getParameterTypes().length == 0 || c.getParameterTypes()[0] == classFMLConstructEvent)
                .sorted((Comparator.comparingInt(o -> o.getParameterTypes().length)))
                .findFirst().get();
```

2024-08-23 14:06 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                ctor = modClass.getDeclaredConstructor();
Try-catch is much better optimised in Java 22+ and isn't as much of a concern as it used to be.

I did consider the performance cost, but doing the alternative approach you propose also has its own performance costs, most notably:
- an array copy
- spliterator allocation for the stream
- array sorting
- optional object allocation

Using a non-stream approach would solve a couple of those things, but I suspect it'll be a toss-up if a try/catch vs array copy+sorting+iteration will be faster.

You're welcome to benchmark the two in a large modpack though and let us know, it would be interesting to see the results (not just throughput, but also memory usage/gc pressure) :)

2024-08-23 14:14 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                ctor = modClass.getDeclaredConstructor();
Additionally, we plan on backporting this feature to many MC versions and encourage devs to migrate over to it. New MDKs will use this feature by default.

The performance gain of avoiding potentially multiple threadlocal lookups along with the assurance that devs can adopt this feature early to avoid a breaking change when ModLoadingContext gets removed should be worth the trivial refactoring effort for mod devs, and might offset or more than make up for the performance hit of the try/catch, even on older JDKs.

2024-08-23 20:28 UTC, PaintNinja requested changes

2024-08-23 20:28 UTC, PaintNinja commented on fmlcore/src/main/java/net/minecraftforge/fml/ModContainer.java
> +import org.jetbrains.annotations.Nullable;
Unused imports

2024-08-23 20:28 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/MinecraftForge.java
>      public static void registerConfigScreen(Function<Screen, Screen> screenFunction) {
We should not be removing features that are trivial to maintain and make things easier for mod devs. The whole point of these helper methods are that they're easy to discover and use, being common usages of extension points, without being forced to deal with breaking changes to the extension point system and needing different code for different MC versions for something simple.

This is setting ourselves up for failure, because it encourages devs to move back to the verbose extension point system that we know will be changing at some point.

2024-08-24 21:04 UTC, PaintNinja requested changes
MDK fails at runtime with a ClassCastException :(

2024-08-24 21:04 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +    public IEventBus getModEventBus() {
Likely unintentional breaking change only in this class, please add a duplicate method with the original name or revert the rename.

2024-08-24 21:04 UTC, PaintNinja commented on javafmllanguage/src/main/java/net/minecraftforge/fml/javafmlmod/FMLModContainer.java
> +                ctor = modClass.getDeclaredConstructor(contextExtension.get().getClass());
This involves reading a mutable field and executing the supplier a couple of times. This can be simplified and sped up a bit by instead having:
```java
private final FMLJavaModLoadingContext context;
// ...
this.context =  new FMLJavaModLoadingContext(this);
this.contextExtension = () -> this.context;
// ...
ctor = modClass.getDeclaredConstructor(context.getClass());
// ...
this.modInstance = ctor.getParameterCount() == 0 ? ctor.newInstance() : ctor.newInstance(context);

2024-08-25 20:34 UTC, PaintNinja approved these changes

2024-08-25 20:38 UTC, merged