[1.21.3] Forge CoreMods cleanup
MinecraftForge/MinecraftForge pull request #10159
Opened 2024-11-04 20:15 UTC by Jonathing

This PR aims to clean up and optimize the existing CoreMods found within Forge.

- This work was originally started in #10156 but has since been moved to this PR.
- Requires #10156 to be merged first.
- Fixes #10157.
- This PR will not be backported.

2024-11-04 23:28 UTC, Jonathing commented
The new `method_redirector` CoreMod has been tested and works just as well as it did before. I've modified `finalize_spawn_targets.json` to declare both the class name and method names where we need to redirect method calls. This gets rid of the need for the CoreMod to search the entire class.

2024-12-24 12:46 UTC, PaintNinja requested changes

2024-12-24 12:46 UTC, PaintNinja commented on src/main/resources/coremods/method_redirector.js
> +            const methodDesc = methodString.substring(methodString.indexOf('('));
```suggestion
            // cut up the string since we've put both the name and desc as the target
            const splitPos = methodString.indexOf('(');
            const methodName = methodString.substring(0, splitPos);
            const methodDesc = methodString.substring(splitPos);
```

2024-12-24 14:26 UTC, PaintNinja approved these changes

2024-12-30 22:36 UTC, merged