Add cubeAllMirrored and try of performance improvement  [MinecraftForge#7709] and [MinecraftForge#9003]
MinecraftForge/MinecraftForge pull request #10163
Opened 2024-11-05 17:21 UTC by Yubokoo

Here is my first try of contributing to an Open Source project ! Don't hesitate to give me feedback !

2024-11-05 17:57 UTC, PaintNinja commented
Thank you for your PR, but unfortunately we cannot accept this in its current state. I’ll provide some constructive feedback to help you:
1) Your PR description is lacking. It should explain what your PR does and why. Have a look at other PRs for examples on what it should look like
2) Separate subsystems should be separate PRs. It looks like you’re adding a new rendering feature and doing some cleanup to the unrelated networking APIs in the same PR. We prefer separate ones for more organised discussions and to avoid delaying unrelated things
3) Your commit messages link to issues every commit. You only need to mention it once in your PR description or a relevant commit, you don’t need to reference all issues in all commits
4) You have formatting changes mixed in with code changes in the same commit, this makes it hard for us to see in the diff what actually changed

This isn’t criticism by the way, I’m genuinely trying to help you out with the PR process. Everyone has to start somewhere.

2024-11-05 19:57 UTC, Jonathing requested changes
Hello, welcome to the Forge GitHub! As @PaintNinja said, this PR needs to be cleaned up and split before we can move forward with it.

For now, I've gone ahead and done my usual code review so you can see how I review PRs on this project.

2024-11-05 19:57 UTC, Jonathing commented on build.gradle
> +    id 'net.minecraftforge.gradle' version '5.1+'
No need to add this. You should never need to change the buildscript of the project unless you need to edit the dependencies in some way, which doesn't seem to be the case here.

2024-11-05 19:57 UTC, Jonathing commented on src/main/java/net/minecraftforge/client/model/generators/BlockStateProvider.java
This file is covered in unrelated formatting changes. I suspect what you did is run CTRL + ALT + L in IntelliJ. It makes it very difficult to review and move forward with this PR if it contains code that is out of scope.

My recommendation for reverting this would be to copy the new method you created into a separate file. Then, reset your git workspace back to the original commit where you started this PR (so, probably resetting to the `1.21.x` branch is a good idea). Then, copy in your new method and don't change anything else unless it is strictly needed for your PR. Make sure all your changes are correct before you force push.

IntelliJ comes with a setting for formatting where you can make it only format your new changes by default. If you can, you should enable that. It can help avoid issues like these.

2024-11-05 19:57 UTC, Jonathing commented on src/main/java/net/minecraftforge/client/model/generators/BlockStateProvider.java
> +
These two empty lines after your new method are unnecessary. While it's a nitpick, it's good to maintain consistency within the file.

2024-11-05 19:57 UTC, Jonathing commented on src/main/java/net/minecraftforge/network/NetworkRegistry.java
As @PaintNinja said, all the changes in this file should be its own PR. For now, I will consider the primary purpose of this PR to be the addition of your `cubeMirroredAll()` method. In that case, I ask that you revert all changes to this file and move it to a separate PR.

2024-11-22 10:28 UTC, Yubokoo commented
Hello ! Thank you for your feedback ! I've made the update normally to respect your advises.

2025-02-02 12:44 UTC, Jonathing commented
The focal point of my feedback has not been addressed. You still have a myriad of unnecessary formatting changes which is irrelevant to this PR. You should only be adding what is part of this PR, not changing what is already there. Additionally, this PR is still a two-in-one, and both Paint_Ninja and I have asked you to split it off into two different PRs, one for the datagen and the other for addressing whatever networking issue this PR is trying to fix.

Also, you still haven't actually described in your PR description what you are trying to do. Linking issues in your commits isn't enough.

2025-02-13 00:51 UTC, Jonathing commented
Hello again. I'm going to be closing this, and the primary reason for this is that it has gone stale and feedback has yet to be addressed. You are more than welcome to open a follow-up PR if you'd like.

However, it's also important to note that since 1.21.4, we have deprecated Forge's old blockstate and model providers in favor of vanilla's. The old providers simply don't have the tools to work with the new item model system that mojang has added. Adding new members to these classes that aren't for the sake of fixing bugs is a bit of a fool's errand since we'll be getting rid of these soon. You are always able to use your own methods in your own mods for sake of convenience.

2025-02-13 00:51 UTC, closed without merging