Add config for number of ticks in a day
MinecraftForge/MinecraftForge pull request #3276
Opened 2016-09-28 08:03 UTC by mezz

Modded players often wish for longer days in Minecraft, it feels like we're tied to the bed sometimes.
It would be fun if mod packs and video-makers could make use of it in creative ways as well.

This PR adds a config to Forge for the number of ticks in a day.
The patch is as small as I could get it, 3 files and only one is a new patched file. I avoid editing weather length and baby growth time since there were way too many places to edit, those will stay at their normal rates.

2016-09-28 08:03 UTC, Actuarius commented
@mezz added labels [Feature]

2016-10-04 03:17 UTC, Abastro commented
I think this is a feature for individual mods, since people can have different opinion about it. Day length might vary, or in some case certain length is needed for consistency with other features.

2016-10-04 03:41 UTC, mezz commented
I'm not sure what you mean, can you explain the example more?

2016-10-04 03:46 UTC, Abastro commented
In reality, day length varies depend on the season.  So I used those celestial system in my mod, and there could be some more. This PR does not allow the system.
There might be more systems that I cant come up with now, which is incompatible with this feature.

2016-10-04 03:48 UTC, mezz commented
Oh I see. That's interesting.
I think a mod could still do that just fine, built on top of this. They would just use the new `ForgeModContainer.dayTicks` constant instead of 24000.
I'm not actually changing how any of this works really.

2016-10-04 03:52 UTC, Abastro commented
Will it work with varying length of day? It's also possible to have increasing length of day. (Like reality)
I think there is no way other than ignoring the config constant..

2016-10-04 03:53 UTC, mezz commented
If such a mod worked before this change, it would work after it too. If it was not possible before, I don't see why I would add support for it here.

2016-10-04 04:06 UTC, mezz commented
Ok so I'm looking at your mod, since I assume that's what you're talking about (why by cryptic?) . 

The only thing you would have to change is remove this config:
https://github.com/Abastro/StellarSky/blob/4b2441f76e7dd639a33a738c67693ea6f226cb18/src/main/java/stellarium/common/ServerSettings.java#L30
and use the Forge one. As far as I can tell they're the same thing. Is there something different you have in mind?

2016-10-04 04:33 UTC, Abastro commented
Yes, the mod is currently compatible with this.
What I see the problem is, is that this gives some restriction of day length, like it should be constant'. (I understand that this would be quite arguable, but it still makes point because of restriction on forge features)

2016-12-09 17:38 UTC, liach requested changes

2016-12-09 17:38 UTC, liach commented on patches/minecraft/net/minecraft/command/CommandTime.java.patch
> ++                    i1 = (int) net.minecraftforge.common.ForgeModContainer.dayTicks / 24;
Should this be 
```java
(int) net.minecraftforge.common.ForgeModContainer.dayTicks / 24
```
or
```java
(int) (net.minecraftforge.common.ForgeModContainer.dayTicks / 24)
```
?

2016-12-10 00:09 UTC, mezz commented on patches/minecraft/net/minecraft/command/CommandTime.java.patch
> ++                    i1 = (int) net.minecraftforge.common.ForgeModContainer.dayTicks / 24;
The second one is more correct, I'll change it to something with `Math.round`.

2016-12-10 04:20 UTC, liach approved these changes

2016-12-10 14:07 UTC, SaxonRah commented
So i can get this modification to forge if i grab the base branch, then merge this pull request into the base and recompile correct ?

2017-02-24 03:43 UTC, closed without merging

2017-02-24 05:21 UTC, liach commented
Why?

2017-02-24 05:41 UTC, mezz commented
Lex didn't want it, it would break stuff that occurs at a specific time of day.

2017-02-24 06:01 UTC, liach commented
Oh