Adding a EquipmentChangeEvent for EntityLivingBase
MinecraftForge/MinecraftForge pull request #3285
Opened 2016-10-01 21:02 UTC by TechnicianLP

To get rid of TickHandlers dedicated to detecting changes in Equipment, i added a corresponding EventHook into EntityLivingBase#onUpdate()

2016-10-01 21:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3285) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3285) before we can accept your contribution.<br/>

2016-10-01 21:04 UTC, kashike requested changes

2016-10-01 21:04 UTC, kashike commented on src/main/java/net/minecraftforge/event/entity/living/LivingEquipmentChangeEvent
> +package net.minecraftforge.event.entity.living;
You are missing the `.java` file extension...

2016-10-01 21:07 UTC, TechnicianLP commented on src/main/java/net/minecraftforge/event/entity/living/LivingEquipmentChangeEvent
> +package net.minecraftforge.event.entity.living;
fixed

2016-10-02 02:09 UTC, Actuarius commented
@mezz added labels [Feature]

2016-10-04 09:08 UTC, HenryLoenwind commented
Is this fired server-side only? Plz add this info to the Javadoc, thx.

2016-10-04 12:09 UTC, TechnicianLP commented
Tell me if it should ifre on both sides

2016-10-05 21:09 UTC, elifoster commented on patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch
> ++                    net.minecraftforge.common.ForgeHooks.onLivingEquipmentChange(this, entityequipmentslot, itemstack, itemstack1);
I think it might be better to simply shove the code directly into here. The patch wouldn't be much larger and would be arguably more maintainable.

```
net.minecraftforge.MinecraftForge.EVENT_BUS.post(new net.minecraftforge.event.entity.living.LivingEquipmentChangeEvent(this, entityequipmentslot, itemstack, itemstack1);
```

Adding a new method is really only necessary if you have to do a bunch of processing. In this case the line count is the same.

2016-10-05 21:09 UTC, elifoster commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +    public static void onLivingEquipmentChange(EntityLivingBase entity,EntityEquipmentSlot slot, ItemStack from, ItemStack to)
Missing a space after `entity,`.

2016-10-05 21:12 UTC, elifoster commented
This is a very much needed thing. It would dramatically reduce the amount of code and data I have for handling the addition/removal of perks applied to the player based on armor (step assist, shared monster attributes, etc). Furthermore it would improve performance immensely, as the ridiculously complicated methods for handling this are the slowest in the mod because we have so many things to check.

2016-10-06 05:17 UTC, darkhax commented
This is a very useful event, and would also several mods to move code out of their tick handlers. This would allow me to remove my tick handler all together in several of my upcoming projects.

2016-10-22 10:15 UTC, TechnicianLP commented
does not use ForgeHooks anymore as suggested by @elifoster

2016-11-13 21:56 UTC, rockhymas commented
I agree that this would be a great event to have. Is someone just waiting for @TechnicianLP to rebase the PR?

2016-11-30 23:38 UTC, mezz commented
This was merged into 1.11 but will not be accepted for 1.10.

2016-11-30 23:38 UTC, closed without merging