Patch Block.isVisuallyOpaque() to be state-aware
MinecraftForge/MinecraftForge pull request #3327
Opened 2016-10-23 19:43 UTC by bs2609

This adds an override of `isVisuallyOpaque()` that takes an `IBlockState` parameter. Tried to keep changes as small as possible.

2016-10-23 19:50 UTC, williewillus commented
I'd name it properly too, isVisuallyOpaque is a terrible name:

https://github.com/ModCoderPack/MCPBot-Issues/issues/289

2016-10-24 19:14 UTC, bs2609 commented
OK, renamed method to `causesSuffocation`, and added notes about usage from the [MCP issue](https://github.com/ModCoderPack/MCPBot-Issues/issues/289).

2016-10-24 20:41 UTC, bs2609 commented on patches/minecraft/net/minecraft/block/Block.java.patch
> -+    public boolean isVisuallyOpaque(IBlockState state)
This is the newly-added version that takes an `IBlockState` parameter. The original still exists and has been marked deprecated, see patch line 33.

2016-11-24 07:02 UTC, mezz requested changes
Looks good but I think your new method already exists.

2016-11-24 07:02 UTC, mezz commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public boolean causesSuffocation(IBlockState state)
I'm pretty sure this new function is exactly the same as `Block.func_149637_q`.

2016-11-24 13:49 UTC, bs2609 commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public boolean causesSuffocation(IBlockState state)
That's certainly possible, I need to have a proper look at 1.11 code.
I'll close this once I've done that if Mojang sorted this themselves.

2016-11-27 02:46 UTC, bs2609 commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public boolean causesSuffocation(IBlockState state)
`func_149637_q` is `isBlockNormalCube`. The default logic used is the same, but they are called from different places and overriden differently.

2016-11-27 03:06 UTC, bs2609 commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public boolean causesSuffocation(IBlockState state)
OK, the actual 1.11 methods are `func_191058_s` (`IBlockProperties.isViewBlocking`) and `func_176214_u` (`Block.causesSuffocation`). Mojang didn't update the default implementation though >_>

2016-11-27 03:07 UTC, bs2609 commented
Related: https://github.com/ModCoderPack/MCPBot-Issues/issues/311

2016-11-27 05:47 UTC, mezz commented
I'm very against adding more "is an opaque block with various micro-differences" methods to `Block.java`, it's already very difficult to navigate.
Is the existing method good enough for this purpose?

2016-11-27 06:49 UTC, bs2609 commented
What's in 1.11 is Good Enough(tm), the MCP naming is the bigger issue there.

I'll close this, it's a bit too late for 1.10.x now.

Thanks for the review.

2016-11-27 06:49 UTC, closed without merging

2016-11-27 06:50 UTC, mezz commented
Cool, thanks.