FluidStack Container support for Ore Recipes
MinecraftForge/MinecraftForge pull request #3332
Opened 2016-10-26 10:52 UTC by CovertJaguar

This PR adds the ability to specify a FluidStack in an Ore Recipe and have any Fluid Container that contains the requested Fluid match, regardless of the specific Item used: Bucket, Bottle, Barrel, Cell, etc... The condition being that you be able to drain the required fluid from the item.

I left getRemainingItems() as it was, but an argument could be made that instead of replacing all items with their containers or consuming them entirely you should drain the request Fluid amount. I'm not entirely sure how capability based containers handle this kind of thing. Input is welcome.

I also included an example test mini-mod, but I couldn't figure out how to actually run it unfortunately. Any pointers on that would be welcome as well.

Pokes @mezz

2016-10-26 10:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3332) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3332) before we can accept your contribution.<br/>

2016-10-26 11:04 UTC, HenryLoenwind commented
Yes, either leaving behind the drained item would be needed here. For one, most fluid containers would be consumed as this is at the moment. And voiding e.g. 255B of excess liquid isn't very nice to the player either.

2016-10-26 21:29 UTC, mezz commented
I agree with Henry. 

Default behavior should definitely be to leave behind the item after it has been drained. Filled buckets will leave empty buckets, and consumable containers like Forestry's cans will leave behind nothing.

Also when checking if the fluid container item is a valid ingredient, make sure the fluid drained is exactly equal to what you need (don't use `containsFluid`), right now a recipe that needs 1mb water could end up consuming a whole bucket because the bucket only drains in increments of 1000mb.

2016-10-26 23:41 UTC, CovertJaguar commented
>Also when checking if the fluid container item is a valid ingredient, make sure the fluid drained is exactly equal to what you need (don't use containsFluid), right now a recipe that needs 1mb water could end up consuming a whole bucket because the bucket only drains in increments of 1000mb.

So that would make you unable to craft with say buckets entirely if you specify like 250mb. Are we sure that is desired?

2016-10-26 23:56 UTC, Gaelan commented
Maybe add a red "xxx my will be wasted" message somewhere?

2016-10-26 23:56 UTC, HenryLoenwind commented
It's not as much a choice for the player as an annoyance. Unless there's a popup "Do you really want to void 31.75 buckets of Liquid XP to craft this? (Yes) (No, but I never read messages)"

2016-10-27 00:35 UTC, CovertJaguar commented
I've added a prototype for the shaped getRemainingFluid(), but again I still don't know how to actually test it and it probably needs it. I'm not entirely sure the approach I've taken is the best solution, but I'm reasonably certain is should work. I'll wait for feedback before adding the shapeless one.

2016-10-28 21:44 UTC, mezz commented
All the big fluid containers I know of can be drained in small increments so it's not a very big deal.

2016-10-28 21:45 UTC, mezz commented
Here's cpw's tutorial on setting up the Forge environment with the test mods running: 
https://www.youtube.com/watch?v=pLWQk6ed56Q

2016-10-29 23:16 UTC, liach commented on src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java
> +    protected Map<Integer, FluidStack> fluidMap = new HashMap<Integer, FluidStack>();
trove inthashmap?

2016-10-30 07:12 UTC, HenryLoenwind commented on src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java
> +    protected Map<Integer, FluidStack> fluidMap = new HashMap<Integer, FluidStack>();
```FluidStack[9]``` ?

2016-10-30 07:46 UTC, CovertJaguar commented on src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java
> +    protected Map<Integer, FluidStack> fluidMap = new HashMap<Integer, FluidStack>();
I suppose that would work as well.

2016-10-30 14:48 UTC, liach commented on src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java
> +    protected Map<Integer, FluidStack> fluidMap = new HashMap<Integer, FluidStack>();
@HenryLoenwind Some mods enlarged crafting grid. Your suggestion may bring a break to those mods.

2016-10-30 16:11 UTC, CovertJaguar commented on src/main/java/net/minecraftforge/oredict/ShapedOreRecipe.java
> +    protected Map<Integer, FluidStack> fluidMap = new HashMap<Integer, FluidStack>();
Its already hardcoded into the recipe handlers, they already break in that case.

2016-10-31 14:51 UTC, CovertJaguar commented
I'll get back to this in a few days, distracted by Railcraft and elections atm.

2016-10-31 15:30 UTC, liach commented
Elections😂

2016-11-01 18:00 UTC, JustGregory-zz commented
Functionally, is decrementing fluid or objects from a container any different from decrementing the stack size from an ItemStack? I mean, I always assumed, ItemStack _is_ a container itself, which contains one type of item or block. Why should fluid containers waste unused portions?

2016-11-01 18:45 UTC, diesieben07 commented
Simplest example: a recipe takes 500 mb. User puts in a bucket (1000 mb). Where do the 500mb excess go? The bucket can only hold 1000mb or nothing and we surely can't just fabricate some other container out of thin air.

2016-11-24 07:05 UTC, mezz commented
Any update @CovertJaguar ?

2016-11-30 08:21 UTC, CovertJaguar commented
Sorry, sorry. The elections and the issues surrounding them here in the states have had me somewhat distracted. Need to spend less time on reddit.

2016-11-30 15:46 UTC, liach requested changes

2016-11-30 15:46 UTC, liach commented on src/main/java/net/minecraftforge/oredict/ShapelessOreRecipe.java
> +                    else if(next instanceof FluidStack)
```java
else if (next instanceof FluidStack)
```
Space between if and parentheses.

2016-12-07 02:29 UTC, mezz commented
Can you update this to target 1.11? New features are no longer being merged into 1.10.

2016-12-27 09:31 UTC, mezz commented
Any update @CovertJaguar ?

2016-12-30 21:54 UTC, mezz commented
I am closing this since you have not responded in a long time.
If you decide to update this please open a new PR and link back to this one.

2016-12-30 21:54 UTC, closed without merging

2016-12-31 03:02 UTC, liach commented
Aye, Covert had been away for like one month or so.