Add hook for rendering items as fullbright
MinecraftForge/MinecraftForge pull request #3340
Opened 2016-10-28 18:04 UTC by Silly511

Adds a shouldRenderFullbright() method to Item allowing you to override and return true or false based on render layer and item stack.

2016-10-28 19:50 UTC, williewillus commented
Name the parameter `tintIndex` not `index` and add Javadoc

2016-10-28 19:54 UTC, williewillus requested changes

2016-10-28 19:54 UTC, williewillus commented on patches/minecraft/net/minecraft/client/renderer/RenderItem.java.patch
> ++                for (List<BakedQuad> quads : net.minecraftforge.client.ForgeHooksClient.sortQuadsByIndex(p_180454_2_)) { net.minecraftforge.client.ForgeHooksClient.renderItemLayerPre(p_180454_1_, qu
split this so it's actually readable

2016-10-28 19:54 UTC, williewillus commented on patches/minecraft/net/minecraft/item/Item.java.patch
>  +
Name the parameter tintIndex not index and add Javadoc

2016-10-28 19:54 UTC, williewillus commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        List<List<BakedQuad>> layers = new ArrayList();
no raw types pls .-.

2016-10-28 19:54 UTC, williewillus commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        return layers;
why can't this just be a `List<BakedQuad>` sorted using a comparator that compares tint index?

2016-10-28 20:04 UTC, Silly511 commented on patches/minecraft/net/minecraft/client/renderer/RenderItem.java.patch
> ++                for (List<BakedQuad> quads : net.minecraftforge.client.ForgeHooksClient.sortQuadsByIndex(p_180454_2_)) { net.minecraftforge.client.ForgeHooksClient.renderItemLayerPre(p_180454_1_, qu
I was trying to make all be on one line. But yeah thats practically unreadable.

2016-10-28 20:11 UTC, williewillus commented on patches/minecraft/net/minecraft/client/renderer/RenderItem.java.patch
> ++                for (List<BakedQuad> quads : net.minecraftforge.client.ForgeHooksClient.sortQuadsByIndex(p_180454_2_)) { net.minecraftforge.client.ForgeHooksClient.renderItemLayerPre(p_180454_1_, qu
the rule is not a hard one. minimize sizes where you can but it still needs to be readable.

2016-10-28 20:13 UTC, Silly511 commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        List<List<BakedQuad>> layers = new ArrayList();
What do you mean by raw types? Do you mean using List instead of ArrayList?

2016-10-28 20:23 UTC, diesieben07 commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        List<List<BakedQuad>> layers = new ArrayList();
`ArrayList` is a generic type, you need a type parameter to fully specify the type. `ArrayList` on it's own is a raw type. `ArrayList<String>` for example is not a raw type.

2016-10-28 20:23 UTC, howtonotwin commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        List<List<BakedQuad>> layers = new ArrayList();
Raw types -> generic types without their parameters. `ArrayList` here is raw, use `new ArrayList<List<BakedQuad>>()`

2016-10-28 20:30 UTC, Silly511 commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        List<List<BakedQuad>> layers = new ArrayList();
Ok. I'll push a new commit soon.

2016-10-28 20:31 UTC, Fadenfire commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        return layers;
How would I use a comparator here?

2016-10-30 07:09 UTC, killjoy1221 commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        List<List<BakedQuad>> layers = new ArrayList();
You could also use Guava to avoid having to add so many generics.

`Lists.newArrayList()`

2016-10-31 01:20 UTC, williewillus commented on src/main/java/net/minecraftforge/client/model/obj/OBJModel.java
> +                    material.getColor().w = alpha;
?

2016-10-31 01:23 UTC, Silly511 commented on src/main/java/net/minecraftforge/client/model/obj/OBJModel.java
> +                    material.getColor().w = alpha;
Mess-up. Trying to fix right now.

2016-10-31 01:25 UTC, Silly511 commented on patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch
> + }
Mess-up. Please ignore this.

2016-10-31 01:29 UTC, Silly511 commented
Sorry for all the mess-ups, I really hate the git command line.

2016-11-04 17:05 UTC, Silly511 commented
Any news on this?

2016-11-04 21:17 UTC, LexManos commented
This is not acceptible, a function in the Item should not determine rendering.
The fullbright value should be in the model itself if it wishes to be full bright.
I've spoken to @RainWarrior about this and he says it is possible to extend the model format to specify this data he just needs to do it.

2016-11-04 22:01 UTC, LatvianModder commented
Then this shouldn't be per-model, but per-face or at very least, per-cube. Is that possible, @RainWarrior ?

2016-11-05 02:57 UTC, Silly511 commented
Your right, this should be specified in the model not the item class. Probably something like per face of each element like ``shade`` or ``cullface``. However this would require using something like ``VertexBuffer#putBrightness();`` or something else that works per quad instead of ``EntityRender#disableLightmap();`` which only works per draw.

2016-11-08 21:47 UTC, Silly511 commented
Rewrote it to add a isFullbright state to baked quads. I did not however add the ability to put "fullbright": "true/false" in JSON models since I have not idea how to do that.

2016-11-18 17:25 UTC, Silly511 commented
Any more news on this?

2016-11-19 01:46 UTC, williewillus commented
fry is going to be away for a bit

2016-11-24 07:18 UTC, mezz commented
This implementation looks terrifying from a performance perspective.
Can you provide some before-and-after FPS measurements in a controlled setting?

2016-11-24 15:31 UTC, Silly511 commented
@mezz I know this code is very inefficient, however I don't expect this to be merged. This is more just a reminder for RainWarrior to implement this in a efficient way.

2016-11-24 17:10 UTC, mezz commented
Good to know, thanks.

2016-12-07 06:12 UTC, mezz commented
In the interest of decluttering PRs, I'm going to close this. 
To keep a reminder open, you can create a new issue that explains the problem.

2016-12-07 06:12 UTC, closed without merging