SurvivalTabs for inventory, patch to solve inventory tab conflicts and reduce keybind usage.
MinecraftForge/MinecraftForge pull request #3349
Opened 2016-11-02 12:46 UTC by ArtixAllMighty

Intended to solve conflicts between mods that add inventories for the player and make a tab for them in the survival inventory. also allows for less key-bind usage.

added survival tabs that can be registered instantiating them.
registers their individual id depending on the container they have been attached too.
Only works for GuiContainers.

added SurvivalTablist class, an encasing class that handles all the drawing, button, and page logic to keep the code in GuiContainer minimal.

patched GuiInventory to call the super for actionPerformed, so it will pick up the button's from the survival tabs

patched guicontainer with a few simple lines that refer to the SurvivalTabsList class, a class that handles all logic and drawing for the survival tabs.

2016-11-02 13:22 UTC, HenryLoenwind commented
This might need a test mod to show what it's doing and some docs on how to use it. From your description I think I may like it.

2016-11-02 15:51 UTC, ArtixAllMighty commented
I will make sure to add to the wiki ! closing of with some images and it will be available in a few minutes.
I made sure it was fairly easy to use

2016-11-02 16:45 UTC, ArtixAllMighty commented
wiki now has a short tutorial and some images and gif to show how stuff works.

https://github.com/ArtixAllMighty/MinecraftForge/wiki

2016-11-02 17:41 UTC, shadowfacts commented on patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
> ++
No whitespace changes.

2016-11-02 17:41 UTC, shadowfacts commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/SurvivalTabList.java
> +package net.minecraftforge.client.player.inventory.tabs;
Missing license header.

2016-11-02 17:41 UTC, shadowfacts commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/SurvivalTabList.java
> +        net.minecraftforge.fml.client.config.GuiUtils.drawHoveringText(Arrays.<String> asList(new String[] { I18n.format(tab.getLocalizedName()) }), mouseX,
This isn't a patch so you don't have to use fully-qualified names.

2016-11-02 17:41 UTC, shadowfacts commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/SurvivalTabs.java
> +package net.minecraftforge.client.player.inventory.tabs;
Missing license header

2016-11-02 17:59 UTC, TehNut requested changes

2016-11-02 17:59 UTC, TehNut commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/SurvivalTabList.java
> + * @author Subaraki
Don't add author tags.

2016-11-02 17:59 UTC, TehNut commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/SurvivalTabs.java
> + * @author Subaraki
Don't add author tags.

2016-11-02 18:05 UTC, AbsolemJackdaw commented on patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
> ++
Sorry, but my editor doesn't show any added whitespace, and genPatches results in no new patch, so I havent changed anything to it since I first edited it.

What do I do ?

2016-11-02 18:13 UTC, HenryLoenwind commented on patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
> ++
Line 9 contains 4 spaces. Remove them, then lines 7 and 9 should go away.

2016-11-02 18:18 UTC, ArtixAllMighty commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/SurvivalTabList.java
> +package net.minecraftforge.client.player.inventory.tabs;
Licence header added

2016-11-02 18:18 UTC, ArtixAllMighty commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/SurvivalTabs.java
> +package net.minecraftforge.client.player.inventory.tabs;
Licence header added

2016-11-02 18:32 UTC, AbsolemJackdaw commented on patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
> ++
I'll figure this out later .... i have no spaces in my editor whatsoever :s

2016-11-02 18:36 UTC, HenryLoenwind commented
So, just to make sure I understand this correctly:

This makes it so one can add tabs to any GUI (provided you can reference its class). The original GUI is decorated with tab headers by your code, and when one is clicked one's code takes over and can do whatever it wants...but it is expected to open a new GUI. And there's a way to tell your code that that new GUI would like to have the same tabs as any other GUI so it looks for the user as if it was one GUI. --- Neat.

Now, what about GUIs that need a container (because they are GUIs for some block/machine), like the chest GUI you show in your GIF? I guess adding container-less tabs to such a GUI would be easy but then switching tabs back to the container-GUI would be impossible, as would be adding a container GUI as tab to something else?

The case I'd like to see would be to add the player inventory GUI (and all its tab) to chests. This is something I'd be considering doing to my machines.

Another case would be to add a tab to the player inventory that only shows up if the player has a special item in their inventory (and if there are multiple of this item, then also add multiple tabs). This is something I'd love to do for the Ender IO Inventory Panel Remote.

(Sorry if this reads like a wish list. It is ;)))

2016-11-02 20:06 UTC, ArtixAllMighty commented
If the machines are yours, there should be no problem. If they use nbt to store things in the tile entity, things might get more complicated.

the reason i could attach the workbench (or i could even have attached an ender chest) is because there is no specific tile entity data needed.

the very first utility of this patch thingy is to add an inventory to the player without having to rebind keys, or tracking down other mods that add tabs on their own. (i have had to do both in the past.)

If you want to only add the tabs to your chest, make a tab for the chest, but don't append it to the player inventory. (new SurvivalTabs("crafting_gui", new ItemStack(Blocks.CRAFTING_TABLE), GuiInventory.class) < tab is appended to guiInventory and will be drawn when the guiinventory is opened). instead : 
new SurvivalTabs("crafting_gui", new ItemStack(Blocks.CRAFTING_TABLE), GuiChest.class)
and just call the createcontinuity for chests and the player inventory.
this way, all player tabs are copied to the chest gui, plus your tab, that will not show up on the player. opening the player gui will not show the tab, opening a chest will show all tabs.
(don't know if the mish mash of words above is any clear, or if i even answered your question ...)

the item thingy is a nice idea. i haven't thought about that. That is something we could brainstorm about. I have an irc channel called SubHaven in which we could talk in depth about this, if you'd like to.

2016-11-03 14:39 UTC, ArtixAllMighty commented
The latest commit allows for a more flexible manipulation of the gui tab list.

2016-11-03 17:47 UTC, GotoLink commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTabList.java
> +					if (tab != null && this.isMouseOverTab(tab, x, y, xSize, ySize))
tab can't be null at that point.

2016-11-03 17:53 UTC, GotoLink commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTabList.java
> +			if (container.getClass().equals(tab.getTargetGui()))
Try only calling container.getClass() once ?
I think since you create one list for each gui, better be efficient at creation time.

2016-11-03 17:56 UTC, GotoLink commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTabList.java
> +		maxPages = ((getTabs().size() - 12) / 12) + 1;
Make maxPages final, and have that 12 in a single place instead of everywhere ?

2016-11-03 18:01 UTC, GotoLink commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTabList.java
> +				if (tab.isActiveTab(container.getClass()) && isFront)
If you don't want to use a bit operation for those cases, at least put an "else".

2016-11-03 18:02 UTC, GotoLink commented
You call this "survival tabs" but i see no guard against creative mode. Did i miss it ?

2016-11-04 09:31 UTC, ArtixAllMighty commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTabList.java
> +		maxPages = ((getTabs().size() - 12) / 12) + 1;
maximum tabs per page, and maxPages isn't the same.

2016-11-04 09:43 UTC, AshIndigo commented
I havent seen the CLA bot here, did you sign it?

2016-11-04 09:57 UTC, Heufneutje commented
@AshIndigo If you click the little "Show all checks" link at the bottom of the PR you'll notice that it has indeed been signed. The bot just didn't reply for some reason.

2016-11-04 10:03 UTC, AshIndigo commented
@Heufneutje Oh thats where it is, thanks

2016-11-04 14:38 UTC, diesieben07 commented
Honestly storing the class instance like that is not worth it in my opinion. As far as I know getClass produces similar code to a normal field access, since the class object is just a field in the object header. So really this is redundant for now performance improvement.

2016-11-04 15:29 UTC, ArtixAllMighty commented
I found I can reduce the container.getClass() calls from 6 to 2.
would that be sufficient ?

2016-11-04 15:40 UTC, diesieben07 commented
Well, you have to replace them with something, in this case a field access. The performance difference between those two should be minute, if even measurable.

2016-11-04 19:35 UTC, TechnicianLP commented
Its seems like if i wanted to add the same Tab to multiple Invetoryies i would have to instantiate it multiple times? or did i overlook something?

2016-11-04 19:45 UTC, TechnicianLP commented on patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
> ++    public java.util.List<net.minecraftforge.client.player.inventory.tabs.GuiTab> getTabs(){
shouldn't this be after the ==Forge Start== ?

2016-11-04 20:27 UTC, ArtixAllMighty commented
createContuity(guicontainer,guicontainer) should be the thing you want. it copies over the tabs from one inventory to another, so it creates a continuity.

if you'd like to inject one tab to more then one gui without having the need of a continuity, you can instantiate it once, and add it to the tablist when opening a gui.

i'm not sure what you are aiming for. could you add some info to that please ?

2016-11-04 20:27 UTC, ArtixAllMighty commented on patches/minecraft/net/minecraft/client/gui/inventory/GuiContainer.java.patch
> ++    public java.util.List<net.minecraftforge.client.player.inventory.tabs.GuiTab> getTabs(){
No idea. might be. I am not a forge developper or anything, so I thought i'd keep it outside for now

2016-11-04 21:44 UTC, TechnicianLP commented
Artix: continuities are a bit to much .. think of droppers and dispenser: you want a tab on both a other mod just on the dispenser - if you created a continuity the tab from the other mod gets into uninended places ...
Having to add them to the Guis manually on the other Hand defeats the purpose of binding them to classes

2016-11-05 07:38 UTC, ArtixAllMighty commented
then indeed, creating two instances is the way to go.
I might remove that then, and make a .addTo(class<? extends GuiContainer>);
leaving the createcontinuity for the player inventory or gui's with an unknown number of gui's.

2016-11-08 14:08 UTC, lukas2005 commented
cool idea shloud be merged

2016-11-11 16:16 UTC, ArtixAllMighty commented
removed continuities

2016-11-24 07:28 UTC, mezz commented
There are some errors with spelling in the javadocs, missing spacing, and braces on the same line.
This PR would also really benefit from including an example mod that shows the code being used.
The wiki is sort of nice but it does not fully explain things the way working example code does, and it still references continuities.

2016-12-07 02:29 UTC, mezz commented
Can you update this to target 1.11? New features are no longer being merged into 1.10.

2016-12-27 09:31 UTC, mezz commented
Any update @ArtixAllMighty ?

2016-12-30 21:54 UTC, mezz commented
I am closing this since you have not responded in a long time.
If you decide to update this please open a new PR and link back to this one.

2016-12-30 21:54 UTC, closed without merging

2016-12-31 05:27 UTC, HenryLoenwind commented
@ArtixAllMighty, really? I was waiting for this...

2017-01-17 09:44 UTC, ArtixAllMighty commented
Native language isn't english, I make a lot of spelling errors, and the edits suggested by people are not what I had in mind for the tabs, so I have a heard time implementing them. sorry.

But AshIndigo is taking over the PR. you should see one soon that is the same, by someone else =)