Added new ReplaceEvent
MinecraftForge/MinecraftForge pull request #3355
Opened 2016-11-04 09:22 UTC by chasevedder

The PR adds a new ReplaceEvent. The event currently occurs when Ice melts, Grass changes to Dirt, and when Water and Lava form Cobblestone, Obsidian, or Stone. The event is cancelable and also has a setter `setNextState(BlockState state)` to change what the block is replaced with, and getters `getState()` and `getNextState()` to determine what state change is occuring.

2016-11-04 09:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3355) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3355) before we can accept your contribution.<br/>

2016-11-04 10:20 UTC, killjoy1221 commented on patches/minecraft/net/minecraft/block/BlockDynamicLiquid.java.patch
> ++                this.func_180688_d(p_180650_1_, p_180650_2_);
`pos.down()`?

2016-11-04 10:43 UTC, chasevedder commented
Whoops :p
Should be fixed now.

2016-11-04 10:43 UTC, chasevedder commented
Whoops :p
Should be fixed now.

2016-11-04 10:43 UTC, chasevedder commented
Whoops :p
Should be fixed now.

2016-11-04 10:56 UTC, mattmess1221 commented on patches/minecraft/net/minecraft/block/BlockDynamicLiquid.java.patch
> ++                this.func_180688_d(p_180650_1_, p_180650_2_);
don't forget here, too.

2016-11-04 11:12 UTC, chasevedder commented
Okay that should be all of them now.

2016-11-04 11:26 UTC, ArtixAllMighty commented
sounds interesting ! this gives a few neat possibilities.

2016-11-04 17:44 UTC, Chocohead commented on patches/minecraft/net/minecraft/block/BlockDynamicLiquid.java.patch
> ++                return ;
You don't need the extra space there making the patch longer

2016-11-05 01:37 UTC, chasevedder commented
Got rid of the space

2016-11-05 10:06 UTC, GotoLink commented on patches/minecraft/net/minecraft/block/BlockReed.java.patch
> ++            if (event.isCanceled()) return false;
Doesn't use the "next state" value. This case should be documented.

2016-11-06 03:03 UTC, chasevedder commented
Yeah it probably should use it, no need to make things more complicated than they need to be.

2016-11-24 07:41 UTC, mezz commented
What will you be using this new event for?

2016-11-24 08:36 UTC, chasevedder commented
Mostly change what Blocks are replaced with to allow for more customization. For example, I could make Grass change to a new Dead Grass block or give Water and Lava a chance to form some other block, which would be a cool way to add a new block to the world without custom world gen.

2016-11-24 08:43 UTC, mezz commented
It sounds odd to me that you would want to change fundamental vanilla behavior instead of using your own blocks and liquids to implement new behaviors. This patch touches a lot of files, I think it needs a strong case where you are certainly going to use it.

2016-11-24 09:14 UTC, chasevedder commented
I would definitely use it for the ability to create intermediate blocks. The ability to have a block change into a "middle" state like dead grass, withered reeds, or melting ice would be nice in my opinion. I just realized another instance I should've added it to is when grass spreads, in which case you could have patchy grass or something of the sort. I can see the event being a little pointless when it comes to Water and Lava though. I could remove those to make the patch a bit smaller.

2016-12-07 02:31 UTC, mezz commented
I guess that makes sense. If people need more from this event they can ask for it in the future.
Can you update this to target 1.11? New features are no longer being merged into 1.10.

2016-12-18 13:00 UTC, chasevedder commented
Updated to 1.11.x and got rid of event for BlockLiquid and BlockDynamicLiquid.

2016-12-19 00:44 UTC, mezz requested changes

2016-12-19 00:44 UTC, mezz commented on src/main/java/net/minecraftforge/event/world/BlockEvent.java
> +     * Fired when a block is replaced, like ice changing to water, water and lava to Obsidian/Cobblestone/Stone, and
This comment should be updated to match the changes you made.

2016-12-19 00:44 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockReed.java.patch
> ++            p_176353_1_.func_175656_a(p_176353_2_, event.getNextState());
This file's patch seems unrelated to the other two. 
Why fire this event for reeds setting themselves to air when broken?

2016-12-19 02:00 UTC, chasevedder commented on patches/minecraft/net/minecraft/block/BlockReed.java.patch
> ++            p_176353_1_.func_175656_a(p_176353_2_, event.getNextState());
It was meant to be used when Reed "dies" when it is not next water, but I didnt' think about that case. I can add a check to make sure the event doesn't fire in the case of someone breaking the reeds, unless you think it still wouldn't fit with the event.

2016-12-19 03:08 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockReed.java.patch
> ++            p_176353_1_.func_175656_a(p_176353_2_, event.getNextState());
That sounds pretty different to me, I think it should be part of a different event.

2016-12-19 03:18 UTC, chasevedder commented
Documentation is now accurate and the event is no longer fired from BlockReed

2016-12-22 01:03 UTC, mezz approved these changes

2016-12-23 00:15 UTC, mezz commented
This looks good. Can you add a small test mod that uses the event to change something?
If you have not worked with the Forge test mods before you can follow this tutorial to get set up:
https://www.youtube.com/watch?v=pLWQk6ed56Q

2017-01-02 21:36 UTC, mezz commented
Test mod looks good, works as expected.

2017-02-24 02:31 UTC, LexManos commented
There are A LOT of places where this would have to be hooked in if this were to be added.
Ice: Water->Ice, Ice->Water, Ice->AIR {Light},  Ice->Air (Harvesting)
Grass: Grass->Dirt {being sat on}, Grass -> Dirt {plants growing}, Dirt->Grass (Spread)
Lava: Lava->Obsid, Lava->Cobble
Water: Water->Stone, Water->Cobble, Water->Ice {Weather}

There also isn't any reasoning modders can access... it's just "Block X -> Y" How does a modder know the context and react to it? This is small, so not bad, but it is a can of worms that needs to be addressed.

2017-10-11 08:30 UTC, closed without merging