Added EnchantmentLevelSetEvent
MinecraftForge/MinecraftForge pull request #3373
Opened 2016-11-13 02:19 UTC by rockhymas

Allows enchantment level to be modified before enchantments are chosen
in the enchanting table.

I've got the test mod passing, but I'd like to figure out how to take the forge build I made and test it out with the mod I've built. Figured I would work on that while waiting for this PR to get reviewed. Any pointers on how to do that are welcome, as this is my first foray into forge development.

2016-11-13 02:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3373) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3373) before we can accept your contribution.<br/>

2016-11-13 02:57 UTC, howtonotwin requested changes

2016-11-13 02:57 UTC, howtonotwin commented on patches/minecraft/net/minecraft/inventory/ContainerEnchantment.java.patch
> ++                        field_75167_g[i1] = e.getLevel();
This should probably go into `ForgeEventFactory`.

2016-11-13 02:57 UTC, howtonotwin commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +	private int power;
Indentation needs to be fixed, and since most of these fields are immutable they should be marked `final`.

2016-11-13 03:35 UTC, rockhymas commented on patches/minecraft/net/minecraft/inventory/ContainerEnchantment.java.patch
> ++                        field_75167_g[i1] = e.getLevel();
Will do.

2016-11-13 03:35 UTC, rockhymas commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +	private int power;
yep

2016-11-13 03:58 UTC, rockhymas commented
@howtonotwin updated with your recommendations.

2016-11-13 03:59 UTC, liach requested changes
And providing a world and a position also make the event way more useful.

2016-11-13 03:59 UTC, liach commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +	private int slot;
Slot number means nothing without a container.

2016-11-13 03:59 UTC, liach commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +    private int level;
Add a final field `originalLevel` for listeners to access when `level` is already changed by other listeners.

2016-11-13 04:15 UTC, rockhymas commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +	private int slot;
These are not container slots, they are enchantment slots. Maybe this should be renamed? It looks like EnchantmentHelper uses the term `enchantNum`, I can do that.

2016-11-13 04:15 UTC, rockhymas commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +    private int level;
Good idea.

2016-11-13 04:29 UTC, rockhymas commented
Updated

2016-11-13 05:01 UTC, liach commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +    public int getLOriginalevel()
`getLOriginalevel`

2016-11-13 05:19 UTC, rockhymas commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +    public int getLOriginalevel()
gah! fixed.

2016-11-13 05:41 UTC, liach approved these changes

2016-11-23 00:25 UTC, Draco18s approved these changes

2016-11-23 00:25 UTC, Draco18s commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +    private final int enchantNum;
I would change this to "slotNum" as "enchantNum" makes me think it's the ID of the enchantment being applied (but its not).

2016-11-23 00:41 UTC, rockhymas commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +    private final int enchantNum;
I was using the term slot before, but it was being confused as having something to do with inventory slots. I agree though, that enchantNum still isn't perfect. What about enchantRow? or enchantLine?

2016-11-23 00:50 UTC, Draco18s commented on src/main/java/net/minecraftforge/event/enchanting/EnchantmentLevelSetEvent.java
> +    private final int enchantNum;
That's a fair point.  "enchantRow" makes sense.

2016-12-07 02:34 UTC, mezz commented
Can you explain how you will use this event in your mod?

Also please update this PR to target 1.11. New features are no longer being merged into 1.10.

2016-12-07 02:50 UTC, rockhymas commented
There is already a 1.11 version of this PR at https://github.com/MinecraftForge/MinecraftForge/issues/3433. I will explain how I plan to use the event over there.

2016-12-07 05:07 UTC, mezz commented
Thanks. Closing this one since it has been updated to 1.11 there.

2016-12-07 05:07 UTC, closed without merging