[WIP] [Do not merge] Initial annotations/nullability changes
MinecraftForge/MinecraftForge pull request #3392
Opened 2016-11-17 01:52 UTC by shadowfacts

Adds `@Nonnull` for usages of `ItemStack` and changes old null checks to invalid checks.

**Do not merge**

2016-11-17 02:27 UTC, bs2609 commented
Made a gist of things I saw, mostly more null checks and unannotated itemstack params.
https://gist.github.com/bs2609/4944620fa0b74d3f207469a58a870999

2016-11-17 22:19 UTC, shadowfacts commented
That's everything I've found and everything that @bs2609 has found fixed.

2016-11-18 00:39 UTC, mezz requested changes
Looks good! I have a couple small comments for changes

2016-11-18 00:39 UTC, mezz commented on src/main/java/net/minecraftforge/common/brewing/VanillaBrewingRecipe.java
> +        if (isIngredient(ingredient))
check for the validity of the ingredient here

2016-11-18 00:39 UTC, mezz commented on src/main/java/net/minecraftforge/event/AttachCapabilitiesEvent.java
> +        public Item(net.minecraft.item.Item item, @Nonnull  net.minecraft.item.ItemStack stack)
Item should probably also be nonnull. or removed? Not sure what its purpose is and the getter is deprecated.

2016-11-18 00:54 UTC, shadowfacts commented on src/main/java/net/minecraftforge/event/AttachCapabilitiesEvent.java
> +        public Item(net.minecraft.item.Item item, @Nonnull  net.minecraft.item.ItemStack stack)
That one I left as-is because I'm not sure what's going to happen to it because it's deprecated. I didn't want to remove it without Lex's permission

2016-11-18 04:45 UTC, bs2609 commented on src/main/java/net/minecraftforge/event/entity/player/AnvilRepairEvent.java
should output also be `@Nonnull`?

2016-11-18 04:50 UTC, bs2609 commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +        public LeftClickEmpty(EntityPlayer player, @Nonnull ItemStack stack)
Does this need an `ItemStack` parameter? The other versions had it removed.

2016-11-18 04:54 UTC, bs2609 commented on src/main/java/net/minecraftforge/items/VanillaHopperItemHandler.java
>              return null;
return value needs changing

2016-11-18 04:55 UTC, bs2609 commented on src/main/java/net/minecraftforge/items/wrapper/InvWrapper.java
>      public ItemStack extractItem(int slot, int amount, boolean simulate)
add `@Nonnull` here

2016-11-18 04:58 UTC, bs2609 commented
Otherwise, this looks fairly comprehensive. Good job!

2016-11-18 21:24 UTC, merged

2016-11-18 21:42 UTC, shadowfacts commented on src/main/java/net/minecraftforge/event/entity/player/AnvilRepairEvent.java
Private fields I've been leaving alone because their private and not used outside of the event.

2016-11-18 21:42 UTC, shadowfacts commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +        public LeftClickEmpty(EntityPlayer player, @Nonnull ItemStack stack)
I don't know, I left it as is because I've no idea what Lex wants to do with it

2016-11-18 21:43 UTC, shadowfacts commented on src/main/java/net/minecraftforge/items/wrapper/InvWrapper.java
>      public ItemStack extractItem(int slot, int amount, boolean simulate)
It's already there