EquipmentCHangeEvent for 1.11
MinecraftForge/MinecraftForge pull request #3411
Opened 2016-11-18 08:33 UTC by TechnicianLP

Added a EquipmentChangeEvent into EntityLivingBase (same as #3285 but for 1.11)
Fell free to make suggestions!

2016-11-18 08:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3411) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3411) before we can accept your contribution.<br/><hr/>**Tcnicn** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

2016-11-18 08:34 UTC, TechnicianLP commented
welp will have to edit my name there ...

2016-11-18 08:44 UTC, TechnicianLP commented
i guess it works now ...

2016-11-26 20:23 UTC, mezz commented
Looks good, and should help a bit with performance because people can switch to use this instead of much broader events.

Please create a Forge example mod to show that this works with confidence.
If you need help getting the example mods running, see [cpw's video tutorial](https://www.youtube.com/watch?v=pLWQk6ed56Q).

2016-11-27 08:54 UTC, LatvianModder commented
You got captial H in title :P

2016-11-27 09:40 UTC, TechnicianLP commented
@mezz Examplemod added
@LatvianModder that definitly is on purpose

2016-11-27 10:00 UTC, mezz commented
Tested and looks good to me.
```
[01:58:01] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in FEET from 1xtile.air@0 to 1xitem.bootsIron@0
[01:58:03] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in FEET from 1xitem.bootsIron@0 to 1xtile.air@0
[01:58:08] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in CHEST from 1xtile.air@0 to 1xitem.chestplateGold@0
[01:58:10] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in CHEST from 1xitem.chestplateGold@0 to 1xtile.air@0
[01:58:12] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in CHEST from 1xtile.air@0 to 1xitem.chestplateIron@0
[01:58:12] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in CHEST from 1xitem.chestplateIron@0 to 1xtile.air@0
[01:58:14] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in FEET from 1xtile.air@0 to 1xitem.bootsCloth@0
[01:58:14] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in FEET from 1xitem.bootsCloth@0 to 1xtile.air@0
[01:58:15] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in LEGS from 1xtile.air@0 to 1xitem.leggingsChain@0
[01:58:17] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in LEGS from 1xitem.leggingsChain@0 to 1xtile.air@0
[01:58:18] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in CHEST from 1xtile.air@0 to 1xitem.chestplateChain@0
[01:58:19] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in CHEST from 1xitem.chestplateChain@0 to 1xtile.air@0
[01:58:20] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in MAINHAND from 1xtile.air@0 to 1xitem.helmetDiamond@0
[01:58:22] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in MAINHAND from 1xitem.helmetDiamond@0 to 1xtile.air@0
[01:58:22] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in OFFHAND from 1xtile.air@0 to 1xitem.helmetDiamond@0
[01:58:24] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in MAINHAND from 1xtile.air@0 to 1xitem.leggingsDiamond@0
[01:58:24] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in MAINHAND from 1xitem.leggingsDiamond@0 to 1xitem.helmetGold@0
[01:58:26] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in MAINHAND from 1xitem.helmetGold@0 to 1xitem.helmetDiamond@0
[01:58:26] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in OFFHAND from 1xitem.helmetDiamond@0 to 1xitem.helmetGold@0
[01:58:30] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in MAINHAND from 1xitem.helmetDiamond@0 to 1xtile.air@0
[01:58:32] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in MAINHAND from 1xtile.air@0 to 1xitem.helmetGold@0
[01:58:32] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in OFFHAND from 1xitem.helmetGold@0 to 1xtile.air@0
[01:58:33] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/147, l='New World', x=16.60, y=4.00, z=758.47] changed his Equipment in MAINHAND from 1xitem.helmetGold@0 to 1xtile.air@0
```

2016-11-27 10:01 UTC, mezz requested changes
one tiny change

2016-11-27 10:01 UTC, mezz commented on patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch
> +-
I think you can reduce your patch by leaving this newline in

2016-11-27 10:38 UTC, HenryLoenwind commented
Is this also fired when joining a world or when the player object is cloned?

2016-11-27 10:53 UTC, TechnicianLP commented
It definitly fires when joining the World as the Entity did not have Equipment before - clone i will have to look at

2016-11-27 11:28 UTC, mezz approved these changes

2016-11-27 17:12 UTC, mezz commented
Tested these cases to verify, looks good to me.

Joining world while wearing a helmet:
```
[09:07:45] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/57691, l='Copy of EquipmentChangeEvent', x=-202.50, y=4.00, z=-320.50] changed his Equipment in HEAD from 1xtile.air@0 to 1xitem.helmetIron@0
```

Making a nether portal:
```
[09:08:41] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/57691, l='Copy of EquipmentChangeEvent', x=-202.50, y=4.00, z=-320.50] changed his Equipment in MAINHAND from 1xtile.air@0 to 1xtile.obsidian@0
[09:08:54] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/57691, l='Copy of EquipmentChangeEvent', x=-202.30, y=6.49, z=-319.66] changed his Equipment in MAINHAND from 1xtile.obsidian@0 to 1xitem.flintAndSteel@0
```

Entering the nether:
```
[09:09:05] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/57691, l='Copy of EquipmentChangeEvent', x=-40.71, y=33.00, z=-51.50] changed his Equipment in MAINHAND from 1xitem.flintAndSteel@0 to 1xitem.helmetIron@0
[09:09:05] [Server thread/INFO] [FML]: [Equipment-Change] EntityPlayerMP['mezz'/57691, l='Copy of EquipmentChangeEvent', x=-40.71, y=33.00, z=-51.50] changed his Equipment in MAINHAND from 1xitem.helmetIron@0 to 1xitem.flintAndSteel@0
[09:09:06] [Server thread/INFO] [FML]: [Equipment-Change] EntityPigZombie['Zombie Pigman'/334280, l='Copy of EquipmentChangeEvent', x=-67.50, y=42.00, z=-52.50] changed his Equipment in MAINHAND from 1xtile.air@0 to 1xitem.swordGold@0
[09:09:06] [Server thread/INFO] [FML]: [Equipment-Change] EntityPigZombie['Zombie Pigman'/334281, l='Copy of EquipmentChangeEvent', x=-118.50, y=35.00, z=12.50] changed his Equipment in MAINHAND from 1xtile.air@0 to 1xitem.swordGold@0
[09:09:06] [Server thread/INFO] [FML]: [Equipment-Change] EntityPigZombie['Zombie Pigman'/334287, l='Copy of EquipmentChangeEvent', x=-33.50, y=44.00, z=-140.50] changed his Equipment in MAINHAND from 1xtile.air@0 to 1xitem.swordGold@0
[09:09:06] [Server thread/INFO] [FML]: [Equipment-Change] EntityPigZombie['Zombie Pigman'/334288, l='Copy of EquipmentChangeEvent', x=-36.50, y=44.00, z=-140.50] changed his Equipment in MAINHAND from 1xtile.air@0 to 1xitem.swordGold@0
... lots more pigmen
```

2016-11-29 00:36 UTC, mezz commented
@TechnicianLP did you edit the patch by hand? Never do that, it does not work. 
Please fix the code and generate it correctly with gradle genPatches.

2016-11-29 00:39 UTC, TechnicianLP commented
Semms like there has been some Problem while copying the new Patch ... will fix it as soon as i can

2016-11-30 22:01 UTC, TechnicianLP commented
@mezz Patch is fixed now - i dont know which part failed at my end there ...

2016-11-30 22:49 UTC, mezz commented
Ok looks good.

2016-11-30 23:15 UTC, merged