Allowed blocks to use custom icons
MinecraftForge/MinecraftForge pull request #3436
Opened 2016-11-22 23:39 UTC by liach

Currently, there is no event which could allow **blocks** to use custom classes extending `TextureAtlasSprite` for textures. This is the correct way to fix #3375.

2016-11-22 23:55 UTC, williewillus commented
For the uninitiated, what's wrong with the code as it is and can you explain why your code fixes the problem?

2016-11-23 02:02 UTC, liach commented
@williewillus [Here] (https://github.com/liachmodded/MinecraftForge/blob/fecc3d7eb214b794b6f337e4acaa7f558102f107/src/main/java/net/minecraftforge/client/model/ModelLoader.java#L169) when the icons are registered, if there is currently no existing icon for that resource location, a default `TextureAtlasSprite` will be generated, loading the icon in vanilla's way. But up to that time, mods have no chance to register a custom sprite. If you register through `TextureStitchEvent.Pre`, you will fail because a default sprite already exists in the map.

2016-11-23 03:18 UTC, williewillus commented
How does this only affect blocks?

2016-11-23 04:23 UTC, liach commented
It at least affect blocks, probably something else also.

2016-11-23 06:46 UTC, covers1624 commented
At the time TextureStitchEvent.Pre is called you should be able to swap the sprite inside mapRegisteredSprites before the actual stitching has occurred.

2016-11-23 07:06 UTC, liach commented
@covers1624 As I know, it cannot be swapped. It can only be set once.

2016-11-23 07:42 UTC, liach commented
@LexManos Could you review this? I am really tired of using stupid reflections.

2016-11-24 06:20 UTC, mezz commented
Could you add something like `TextureMap.forceRegisiterSprite` which ignores the check for existing sprites at that resource location? I think it would be simpler than adding a new event.

2016-11-24 09:56 UTC, covers1624 commented
I agree @mezz, I also have uses for this, a forceRegisterSprite method will be best.

2016-11-24 17:22 UTC, liach commented
@mezz See #3375. Lex Manos rejected my proposal to add a method for forcible replacement of texture atlas sprites.

2016-11-24 17:50 UTC, mezz commented
Ok looking at the other issue...
This seems like a crazy hack, but I see Forge actually supports it by adding the methods `TextureAtlasSprite.hasCustomLoader` and `TextureAtlasSprite.load`.

I think that instead of an event, you just need to add a check for `hasCustomLoader` and skip the `map.registerSprite(t);` line. I can't imagine a reason for subclassing `TextureAtlasSprite` unless it has a custom loader.

2016-11-24 18:05 UTC, liach commented
@mezz Not really...

> I think that instead of an event, you just need to add a check for hasCustomLoader and skip the map.registerSprite(t); line. I can't imagine a reason for subclassing TextureAtlasSprite unless it has a custom loader.

These custom sprites are not loaded from json but binded by the mods to the texture map.

2016-11-24 18:26 UTC, mezz commented
I'm sorry, I don't understand how that relates to what I'm saying.

Can you keep a list of textures that are registered with `TextureAtlasSprite.hasCustomLoader() == true` instead of using an event?

2016-11-24 18:30 UTC, liach commented
@mezz: I will change that unnecessary map into a list in the next commit.
@CovertJaguar: Could you make a point here, since the cause of this pull is solely for resolving reflection hacks used by your `TextureAtlasSheet`?

2016-11-24 19:15 UTC, mezz commented
I don't think you are fully reading what I am saying @liach :(

2016-11-24 19:18 UTC, mezz commented
I want to know if the event can be removed.
Can you remove the event, and keep the resource locations for textures that have `TextureAtlasSprite.hasCustomLoader() == true` ?

2016-11-24 19:24 UTC, mezz commented
I am only asking a question, there is no need to change anything until I understand what is possible.

2016-11-24 19:58 UTC, liach commented
@mezz Unfortunately, I say no to the removal of this event. 

`TextureMap#registerSprite(ResourceLocation)` puts a `TextureAtlasSprite` in the `mapRegisteredSprites`. That sprite is generated by a static method that works like `Optional.of()`. This generated sprite will **always** return `false` on `hasCustomLoader()` call. Unfortunately, once that sprite is registered, it cannot be replaced by custom sprites.

Currently, between the creation of `TextureMap` instance in `Minecraft` class and the [registration](https://github.com/liachmodded/MinecraftForge/blob/b50fc1d0b9d80a78d680efa50ee7ff2cb2e7931f/src/main/java/net/minecraftforge/client/model/ModelLoader.java#L164-L173), there is no event allowing modders to put custom sprites at a right time. `IconLoadPreEvent` is one that allows modders to put custom sprites.

2016-11-24 20:03 UTC, mezz commented
Can you move `ForgeHooksClient.onTextureStitchedPre` so it is before `iconCreatorIn.registerSprites` in `TextureMap.loadSprites` ?

2016-11-25 18:09 UTC, liach commented
@mezz Fixed.

2016-11-26 08:09 UTC, mezz commented
Thanks. I tested this in 1.10 with Forestry (which uses `TextureStitchEvent.Pre` a lot) and it works without any issues.

Can you add an example mod that creates a simple `TextureAtlasSprite` like the `White` one in Forge, and an item that uses it? It would prove that this PR solves your issue, and would be useful in the future to make sure this feature does not get broken again.

2016-11-26 19:01 UTC, liach commented
@mezz Can I remove the deprecated version of `setTextureEntry`?

2016-11-26 19:03 UTC, mezz commented
Yes that's a good idea.

2016-11-28 01:18 UTC, mezz requested changes

2016-11-28 01:18 UTC, mezz commented on src/test/java/net/minecraftforge/test/CustomSpriteTest.java
> +    public void init(FMLPreInitializationEvent event)
Please actually test, this doesn't even run. 
Missing `@Mod.EventHandler`
After I added that, it still didn't work properly.
![2016-11-27_17 10 03](https://cloud.githubusercontent.com/assets/916092/20653577/7475fb18-b4c4-11e6-86ab-681f285efddc.png)

2016-11-28 04:10 UTC, liach commented on src/test/java/net/minecraftforge/test/CustomSpriteTest.java
> +    public void init(FMLPreInitializationEvent event)
That is actually a stub.

2016-11-28 05:22 UTC, williewillus commented on src/test/java/net/minecraftforge/test/CustomSpriteTest.java
> +    public void init(FMLPreInitializationEvent event)
s/stub/broken code :P

2016-11-29 16:08 UTC, mezz commented
Any update @liach ? Seems like you're 99% done.

2016-11-29 17:34 UTC, liach commented
@mezz I edited locally (not pushed yet) but I do not understand how should I configure the resource location: I used `textures/blocks/tnt_side.png` for the replacement but it shown up black. Should it be `blocks/tnt_side.png`? If I use `blocks/tnt_side` then the game crashes of missing file.

2016-11-29 17:37 UTC, mezz commented
I'll play around with it and see if I notice anything.

2016-11-29 19:05 UTC, mezz commented
Got it.
![2016-11-29_11 03 54](https://cloud.githubusercontent.com/assets/916092/20724563/9f8c5ac6-b623-11e6-911e-875033a1874f.png)

Use this: 

```java
package net.minecraftforge.test;

import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.client.Minecraft;
import net.minecraft.client.renderer.texture.TextureAtlasSprite;
import net.minecraft.client.renderer.texture.TextureMap;
import net.minecraft.client.resources.IResource;
import net.minecraft.client.resources.IResourceManager;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.event.TextureStitchEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.common.FMLLog;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry;

import javax.annotation.Nonnull;
import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.IOException;

/**
 * Test for {@link TextureStitchEvent.Pre}.
 */
@Mod(modid = CustomSpriteTest.MOD_ID, name = CustomSpriteTest.NAME)
public class CustomSpriteTest
{
    static final String MOD_ID = "custom_sprite_test";
    static final String NAME = "Custom sprite test";

    @Mod.EventHandler
    public void init(FMLPreInitializationEvent event)
    {
        MinecraftForge.EVENT_BUS.register(this);
        Block block = new Block(Material.WOOD).setRegistryName(MOD_ID, "custom_sprite_block").setCreativeTab(CreativeTabs.MISC);
        GameRegistry.register(block);
    }

    @SubscribeEvent
    public void textureStitch(TextureStitchEvent.Pre event)
    {
        DelegateSprite bottom = DelegateSprite.make("bottom", new ResourceLocation("textures/blocks/diamond_block.png"));
        DelegateSprite top = DelegateSprite.make("top", new ResourceLocation("textures/blocks/tnt_side.png"));

        TextureMap textureMap = event.getMap();
        textureMap.setTextureEntry(bottom);
        textureMap.setTextureEntry(top);
    }

    static final class DelegateSprite extends TextureAtlasSprite
    {
        final ResourceLocation delegate;

        private DelegateSprite(ResourceLocation loc, ResourceLocation delegate)
        {
            super(loc.toString());
            this.delegate = delegate;
        }

        static DelegateSprite make(String name, ResourceLocation delegate)
        {
            return new DelegateSprite(new ResourceLocation(MOD_ID, name), delegate);
        }

        @Override
        public boolean hasCustomLoader(@Nonnull IResourceManager manager, @Nonnull ResourceLocation location)
        {
            return true;
        }

        @Override
        public boolean load(@Nonnull IResourceManager manager, @Nonnull ResourceLocation location)
        {
            BufferedImage image;
            try
            {
                IResource resource = manager.getResource(delegate);
                image = ImageIO.read(resource.getInputStream());
            }
            catch (IOException ioe)
            {
                FMLLog.severe("Could not find resource", ioe);
                return true;
            }
            this.width = image.getWidth();
            this.height = image.getHeight();
            int[][] pixels = new int[Minecraft.getMinecraft().gameSettings.mipmapLevels + 1][];
            pixels[0] = new int[image.getWidth() * image.getHeight()];
            image.getRGB(0, 0, image.getWidth(), image.getHeight(), pixels[0], 0, image.getWidth());
            this.clearFramesTextureData();
            this.framesTextureData.add(pixels);
            return false;
        }
    }
}
```

2016-11-29 19:21 UTC, liach commented
Here I am confused because I do not think the code I have on my side has any difference with yours. Will push when I am home and check out the difference (and of course, fix)

2016-11-29 19:25 UTC, mezz commented
I made three fixes to the code on github:

- use the path like `textures/blocks/tnt_side.png`
- set the texture atlas sprite's width and height
- remove the `location` field and do not compare it in `hasCustomLoader`, it does not match.

2016-11-29 19:27 UTC, liach commented
> - set the texture atlas sprite's width and height

This is the point. I did not make that change, and I will.

2016-12-01 02:13 UTC, mezz approved these changes

2016-12-01 02:15 UTC, mezz commented
This looks good.
It is a breaking change because it removes a deprecated method.

2016-12-02 03:44 UTC, liach commented
@LexManos Is this okay?

2016-12-02 04:49 UTC, LexManos commented
No, it's still stupid and not explained correctly but whatever. The code is functional.

2016-12-02 04:49 UTC, merged