Allow connectable blocks to choose what they can connect to
MinecraftForge/MinecraftForge pull request #3437
Opened 2016-11-23 01:02 UTC by LogicTechCorp

1.11 version of #3354

2016-11-23 01:22 UTC, williewillus commented
Why the separate bouncer methods for each block?
Also if we're gonna patch the lines with 6 ternaries might as well separate it and make it readable

2016-11-23 01:27 UTC, LogicTechCorp commented
What do you mean by bouncer methods.
Will do.

Also, how do I resolve the conflicts?

2016-11-23 03:04 UTC, liach commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public boolean canBeConnectedTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
`canConnectTo`

2016-11-23 11:18 UTC, HenryLoenwind commented
@williewillus: because @mezz had LogicTechCorp change it from one big check in Block to the logic spread out to each block.

2016-11-23 18:04 UTC, LogicTechCorp commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public boolean canBeConnectedTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
I would call it `canConnectTo` but it is not **what can this connect to** but **what can connect to this**.

2016-11-23 21:22 UTC, LogicTechCorp commented
Conflicts have been resolved. @mezz do you have any more suggestions?

2016-11-23 21:29 UTC, mezz commented
I think it looks good but @williewillus should clarify what they mean since nobody seems to understand and it could be something to improve the PR.

2016-11-26 20:34 UTC, LogicTechCorp commented
@williewillus Can you clarify what you mean?

2016-11-27 05:39 UTC, liach commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public boolean canBeConnectedTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
`acceptsConnection`

2016-11-27 06:04 UTC, mezz commented
I think what he's saying is that instead of making lines like this:
`return p_176221_1_.func_177226_a(field_176526_a, Boolean.valueOf(canFenceConnectTo(p_176221_2_, p_176221_3_, EnumFacing.NORTH))).func_177226_a(field_176525_b, Boolean.valueOf(canFenceConnectTo(p_176221_2_, p_176221_3_, EnumFacing.EAST))).func_177226_a(field_176527_M, Boolean.valueOf(canFenceConnectTo(p_176221_2_, p_176221_3_, EnumFacing.SOUTH))).func_177226_a(field_176528_N, Boolean.valueOf(canFenceConnectTo(p_176221_2_, p_176221_3_, EnumFacing.WEST)));`

You should make a new private method and do all the logic there where it can be formatted more nicely.

2016-11-27 17:59 UTC, williewillus commented
Oh yeah, that wasn't 6 ternaries, that was 6 withProperties, my bad.
It doesn't need to be a separate method but just separating it onto different lines would make it more readable, since we're patching it anyways might as well.

2016-11-27 18:00 UTC, williewillus commented
And you can also remove the explicit boxing (Boolean.valueOf)

2016-11-27 18:21 UTC, LogicTechCorp commented
@williewillus Working on that now. @mezz should I rename `canBeConnectedTo` as per @liach suggestions?

2016-11-27 19:03 UTC, LogicTechCorp commented
Is there anything else you would like me to change? @williewillus @mezz

2016-11-27 19:06 UTC, mezz commented
You mostly have the right idea, but you should move things around so that the patches to existing methods are 1 line only.

So you need a new private method at the bottom that does all this:
```
++        return p_176221_1_.func_177226_a(field_176526_a, canFenceConnectTo(p_176221_2_, p_176221_3_, EnumFacing.NORTH))
 ++                .func_177226_a(field_176525_b, canFenceConnectTo(p_176221_2_, p_176221_3_, EnumFacing.EAST))
 ++                .func_177226_a(field_176527_M, canFenceConnectTo(p_176221_2_, p_176221_3_, EnumFacing.SOUTH))
 ++                .func_177226_a(field_176528_N, canFenceConnectTo(p_176221_2_, p_176221_3_, EnumFacing.WEST));
```

and your patch to `func_176221_a` would just replace the single line with a call to your new method.

2016-11-27 19:26 UTC, LogicTechCorp commented
Does it look good now? @mezz

2016-11-27 20:06 UTC, mezz requested changes
Ok looking good, some final requests. The helper methods I marked should be private if nothing should override them, or protected otherwise. Outside code does not need to see them or call them so they should not be public.

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockFenceGate.java.patch
> ++        EnumFacing.Axis axis = p_176221_1_.func_177229_b(field_185512_D).func_176740_k();
this line should not be changed

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockFenceGate.java.patch
> ++            p_176221_1_ = p_176221_1_.func_177226_a(field_176467_M, true);
this line should not be changed

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockFence.java.patch
> ++    public IBlockState getFenceState(IBlockState state, IBlockAccess world, BlockPos pos)
make this private or protected

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockFence.java.patch
> ++    public boolean canFenceConnectTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
make this private or protected

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockFenceGate.java.patch
> ++    public boolean canFenceGateConnectTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
make this private or protected

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockPane.java.patch
> ++    public boolean canPaneConnectTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
make this private or protected

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockPane.java.patch
> ++    public IBlockState getPaneState(IBlockState state, IBlockAccess world, BlockPos pos)
make this private or protected

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockWall.java.patch
> ++    public boolean canWallConnectTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
make this private or protected

2016-11-27 20:06 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockWall.java.patch
> ++    public IBlockState getWallState(IBlockState state, IBlockAccess world, BlockPos pos, boolean north, boolean east, boolean south, boolean west, boolean up)
make this private or protected

2016-11-27 20:18 UTC, LogicTechCorp commented
Okay, all changes have been implemented. @mezz

2016-11-27 20:37 UTC, mezz requested changes

2016-11-27 20:37 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockPane.java.patch
> ++    private boolean canPaneConnectTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
Sorry I made a mistake, this existing method must be kept `public` to ensure compatibility with old code. I didn't realize it was here already.

2016-11-27 20:45 UTC, LogicTechCorp commented
'canPaneConnectTo' has been made public. @mezz

2016-11-27 20:58 UTC, mezz approved these changes

2016-11-27 20:58 UTC, mezz commented
Looks good, thanks for your patience. I'll test it out now.

2016-11-28 00:33 UTC, mezz commented
Tested vanilla vs this patch and all connections appear to be working correctly still.

2016-11-30 23:35 UTC, mezz requested changes
Lex requests some changes before this can be accepted

2016-11-30 23:35 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockFence.java.patch
> ++    private IBlockState getFenceState(IBlockState state, IBlockAccess world, BlockPos pos)
Lex says you can move this code into `func_176221_a` even though it's a 4 line long patch. He does not want this helper function.

2016-11-30 23:35 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockPane.java.patch
> ++        return getPaneState(p_176221_1_, p_176221_2_, p_176221_3_);
Lex says you should put this code back the way it was before. He does not want the `getPaneState` helper function.

2016-11-30 23:35 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockWall.java.patch
> ++        return getWallState(p_176221_1_, p_176221_2_, p_176221_3_, canConnectN, canConnectE, canConnectS, canConnectW, canConnectU);
Lex says you should put the `getWallState` helper function back in here like it was before, and do not rename the local variables (flags).

2016-12-01 01:15 UTC, LogicTechCorp commented
Are these correct? @mezz

2016-12-01 01:18 UTC, mezz requested changes

2016-12-01 01:18 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockPane.java.patch
> ++    public boolean canPaneConnectTo(IBlockAccess world, BlockPos pos, EnumFacing facing)
do not rename the parameters here, it should match the old ones:
`public boolean canPaneConnectTo(IBlockAccess world, BlockPos pos, EnumFacing dir)`

2016-12-01 01:18 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockWall.java.patch
> ++        return getWallState(p_176221_1_, p_176221_2_, p_176221_3_, flag, flag1, flag2, flag3, flag4);
can you replace this line with the vanilla line that was there before and remove `getWallState`?

2016-12-01 01:19 UTC, LogicTechCorp commented on patches/minecraft/net/minecraft/block/BlockWall.java.patch
> ++        return getWallState(p_176221_1_, p_176221_2_, p_176221_3_, flag, flag1, flag2, flag3, flag4);
They are the same, will change.

2016-12-01 01:26 UTC, LogicTechCorp commented
Implemented changes. @mezz

2016-12-01 01:44 UTC, mezz approved these changes

2016-12-01 01:45 UTC, mezz commented
Looks good.

2016-12-01 01:51 UTC, merged