[1.11] Add canApplyAtEnchantmentTable to Item
MinecraftForge/MinecraftForge pull request #3463
Opened 2016-11-27 10:16 UTC by blay09

Ported to 1.11 from #3248

This adds a canApplyAtEnchantmentTable function to the Item class, allowing increased control of what enchantments can be put on an item over Vanilla's hard-coded item type checks.

Prior, this was all hard-coded in EnumEnchantmentType, and the only way to make your item receive certain enchantments was to extend a specific Item class (such as ItemTool, ItemSword, ItemBow), which does not cover all cases.

Specifically in my case, to explain in real-world terms, the new Sieve Meshes coming to Ex Nihilo & Ex Compressum, which are meant to be enchantable for increased output or speed. While it would be possible to extend ItemTool for the mesh item and make it accept the Fortune/Efficiency enchantment that way, it would also allow unwanted enchantments such as Silk Touch to be applied and pollute the mesh's item class with methods from ItemTool which are not meant to be implemented for this type of item.

The default behaviour of checking the enchantment type remains unchanged.

2016-11-27 10:27 UTC, covers1624 commented
Looks good.

2016-11-27 10:45 UTC, mezz commented
Looks good, testing.

2016-11-27 11:10 UTC, mezz commented
The test item works correctly in the Anvil, but there is a problem in the Enchanting Table.

![2016-11-27_02 58 26](https://cloud.githubusercontent.com/assets/916092/20647959/be269536-b44e-11e6-872e-f4bb534a6910.png)
![2016-11-27_03 06 50](https://cloud.githubusercontent.com/assets/916092/20647960/be27a1b0-b44e-11e6-8d8d-b6d14951155c.png)

The calls to `ContainerEnchantment.getEnchantmentList` all return empty lists, and the Enchanting Table gui shows 3 options that can't be clicked.

Please try it out and find out what's going on here. It may just be a problem with the test item, but it could also be a bigger problem with items that can only be enchanted with a very limited set of enchantments.

2016-11-27 12:13 UTC, blay09 commented
This happens specifically if a modded item allows only enchantments that require high enchantability and can be solved by adding more bookshelves.

I suggest an additional small patch to GuiEnchantment that disables the "empty" enchantment buttons. That way Vanilla enchantment RNG behaviour can stay unchanged and it would still be clear to the player that the item *can* be enchanted, just not under the current conditions.

![Example](http://blay09.net/pics/example.png)

Possibly additionally with a tooltip (like the current "Level Requirement" tooltip when it's not met), but I don't know how much Forge is willing to add to the enchantment GUI for this. It's probably an edge case that is unlikely to appear in the real world, so just rendering the slot as disabled might be enough.

2016-11-27 16:47 UTC, mezz commented
I think your solution here is good enough for this PR. 
It feels intuitive and doesn't make me immediately think the enchantment table is broken.

2016-11-27 16:51 UTC, mezz commented
Last thing before I pass it on to Lex, can you give the test item a name like "FortuneEnchantableOnly" so it's not "item.null.name" on the tooltip, and make the test enabled by default? This will help streamline things if the feature is ever broken by updates later.

2016-11-27 16:58 UTC, mezz commented
Looks good, thanks!

2016-11-30 23:17 UTC, mezz commented
Lex thinks you should go ahead and see if you can add a tooltip explaining why the slot is disabled for that item. Might as well get a complete and nice fix in for this since there may be single-enchant items.

2016-12-01 17:17 UTC, blay09 commented
I went for "Enchantability Low" instead of "Requires Bookshelves" as in the case of the very top entry even the maximum amount of bookshelves may not be enough if you get unlucky, due to the low xp level required.

For the formatting & casing I followed the existing "Level Requirement:" tooltip.

![Enchantability Low](http://blay09.net/pics/withtooltip.png)

Tried to make the patch as unintrusive as possible without duplicating Vanilla code.

2016-12-01 18:28 UTC, mezz requested changes

2016-12-01 18:28 UTC, mezz commented on patches/minecraft/net/minecraft/client/gui/GuiEnchantment.java.patch
> ++                } else
I think you might be able to smush this into one line
`if (enchantment == null) java.util.Collections.addAll(list, "", TextFormatting.RED + I18n.func_135052_a("forge.container.enchant.enchantabilityTooLow")) else`

2016-12-01 18:28 UTC, mezz commented on src/main/resources/assets/forge/lang/en_US.lang
> +forge.container.enchant.enchantabilityTooLow=Enchantability Low
I want a better name for this but I haven't thought of one... hmm.

2016-12-01 18:32 UTC, mezz commented on src/main/resources/assets/forge/lang/en_US.lang
> +forge.container.enchant.enchantabilityTooLow=Enchantability Low
Something along the lines of "Item has limited enchantments"? I feel like you did a good job coming up with something short but it doesn't fully convey what's going on.

2016-12-01 18:36 UTC, blay09 commented on src/main/resources/assets/forge/lang/en_US.lang
> +forge.container.enchant.enchantabilityTooLow=Enchantability Low
Limited Enchantability?

2016-12-01 18:37 UTC, mezz commented on src/main/resources/assets/forge/lang/en_US.lang
> +forge.container.enchant.enchantabilityTooLow=Enchantability Low
I think that's pretty good, yeah.

2016-12-01 18:57 UTC, mezz approved these changes

2016-12-01 18:59 UTC, mezz commented
I see odd behavior when I put the item into an enchanting table with no bookshelves around.
The middle slot is blank.

![2016-12-01_10 57 04](https://cloud.githubusercontent.com/assets/916092/20807788/215c1874-b7b5-11e6-8de7-c1d9fbc230a6.png)

2016-12-01 19:13 UTC, blay09 commented
Slots are blank when the level cost is zero, which is randomly calculated in `EnchantmentHelper.calcItemStackEnchantability` based on the amount of bookshelves and `Item.getItemEnchantability()`, but independent from which enchants are accepted. It's unaffected by this PR.

Just tried the same on a 1.11 Vanilla instance and got the same outcome on the second enchant.

2016-12-01 19:28 UTC, mezz commented
Ok thanks, somehow I hadn't see that before.

2016-12-03 18:43 UTC, merged