Add piston extend and retract events
MinecraftForge/MinecraftForge pull request #3473
Opened 2016-11-30 20:53 UTC by Selim042

Comes directly from #2240, just updated.

2016-11-30 22:31 UTC, mezz requested changes

2016-11-30 22:31 UTC, mezz commented on src/main/java/net/minecraftforge/event/world/PistonEvent.java
> +     * If canceled the piston will not pull the block it is attached to
This javadoc is confusing. 
Is this only called for sticky pistons? 
What happens if it is canceled on regular pistons? 
Can retraction be completely canceled like extension can?

2016-11-30 22:31 UTC, mezz commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +            return MinecraftForge.EVENT_BUS.post(new net.minecraftforge.event.world.PistonEvent.PistonRetractEvent(world, pos, facing));
Please import `PistonEvent`, this is not a patch so you can import anything you need to.

2016-11-30 22:31 UTC, mezz commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +            return MinecraftForge.EVENT_BUS.post(new net.minecraftforge.event.world.PistonEvent.PistonExtendEvent(world, pos, facing));
Please import `PistonEvent`, this is not a patch so you can import anything you need to.

2016-11-30 22:41 UTC, Selim042 commented
How do I mark that the requested changes have been taken care of?

2016-11-30 22:58 UTC, mezz approved these changes

2016-11-30 22:59 UTC, mezz requested changes
Looks good, just needs some more formatting fixes and then I will test it.

2016-11-30 22:59 UTC, mezz commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +public class EventPistonDebug {
Please fix the formatting of this file, all braces should be on a new line.

2016-12-01 18:40 UTC, Selim042 commented
Did I miss formatting stuff or did you just not get around to approving the changes?

2016-12-01 19:03 UTC, mezz requested changes
Formatting looks mostly good. There are no notifications for when you update the code, if I'm not around you have to let me know by commenting on the issue.
I'll test it out now and can approve if the formatting is fixed and everything works well.

2016-12-01 19:03 UTC, mezz commented on src/main/java/net/minecraftforge/event/world/PistonEvent.java
> +    public EnumFacing getFacing() {
needs brace on new line

2016-12-01 19:03 UTC, mezz commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +        } else {
needs braces on new lines
```
}
else
{
```

2016-12-01 19:03 UTC, mezz commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +                } else {
braces on new lines

2016-12-01 19:05 UTC, mezz commented
Also this should be updated to target the `1.11.x` branch. 
Forge is no longer accepting new events for the `1.10.x` branch.

2016-12-01 20:14 UTC, Selim042 commented
Fixed formatting, closing this to re-push for 1.11 then.  I was hoping to have this in 1.10.x sadly.

2016-12-01 20:14 UTC, closed without merging

2016-12-01 20:28 UTC, mezz commented
Forge moves slow, sorry. I'm working to help speed up the PR process so that this is less of an issue in the future, but Forge will almost always be targeting the latest Minecraft version for features.

2016-12-01 22:25 UTC, liach commented
@Selim042 For a future note, you can edit the target branch of a pull request now. No need for a new pull really.

2016-12-02 19:35 UTC, Selim042 commented
Oh.  Thanks!