Add piston extend and retract events
MinecraftForge/MinecraftForge pull request #3481
Opened 2016-12-01 22:05 UTC by Selim042

From #3473.

2016-12-01 22:12 UTC, mezz commented
Code looks good, testing it out now.

2016-12-01 22:18 UTC, mezz commented
heh the patch is missing, nothing calls `ForgeEventFactory.onPistonMove`.

2016-12-01 22:19 UTC, Selim042 commented
Whoops. Gimme a minute lol

2016-12-01 22:21 UTC, liach requested changes
By the way, where are the patches? Please generate them by executing `./gradlew gP` in the root directory of forge.

2016-12-01 22:21 UTC, liach commented on src/main/java/net/minecraftforge/event/world/PistonEvent.java
> +public class PistonEvent extends BlockEvent
Could you add some documentation like other events?

2016-12-01 22:21 UTC, liach commented on src/main/java/net/minecraftforge/event/world/PistonEvent.java
> +     ***/
```java
/**
 *
 */
```
Use this style for javadocs. Same for below.

2016-12-01 22:21 UTC, liach commented on src/main/java/net/minecraftforge/event/world/PistonEvent.java
> +    public static class PistonExtendEvent extends PistonEvent
```java 
public static class Extend extends PistonEvent
```

2016-12-01 22:21 UTC, liach commented on src/main/java/net/minecraftforge/event/world/PistonEvent.java
> +    public static class PistonRetractEvent extends PistonEvent
```java
public static class Retract extends PistonEvent
```

2016-12-01 22:21 UTC, liach commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +@Mod(modid = EventPistonDebug.MODID)
Please add name and version of the mod to prevent warnings in loading.

2016-12-01 22:21 UTC, liach commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +            for (EntityPlayer player : event.getWorld().playerEntities)
You can just send chat message to `Minecraft.getMinecraft().player` since this code block only executes on the client thread.

2016-12-01 22:21 UTC, liach commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +            if (world.getBlockState(pushedBlockPos).getBlock().equals(shiftOnMove) && event.getFacing() != EnumFacing.DOWN)
Block instance comparison can use `==`

2016-12-01 22:21 UTC, liach commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +        if (!event.getWorld().isRemote)
Is this a logic error? I think it looks like one.

2016-12-01 22:21 UTC, liach commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +                if (isSticky)
Calculate `isSticky` outside of the loop can simplify the code and improve performance.

2016-12-01 22:21 UTC, liach commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +    public static boolean onPistonMove(World world, BlockPos pos, EnumFacing facing, boolean extending)
I suggest you to make two methods instead of passing a `boolean` argument and check.

2016-12-01 22:23 UTC, mezz commented on src/test/java/net/minecraftforge/debug/EventPistonDebug.java
> +                if (isSticky)
it's just a debug mod, performance does not matter for this one

2016-12-01 22:23 UTC, mezz commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +    public static boolean onPistonMove(World world, BlockPos pos, EnumFacing facing, boolean extending)
I think that would be more clear, yes. Harder to mess up the patch when things are named clearly.

2016-12-01 22:45 UTC, Selim042 commented
I got all that stuff fixed, but for whatever reason it is failing to generate the patch.

2016-12-01 22:46 UTC, liach commented
@Selim042 Run with `./gradlew gP -i -S` and post the log to pastebin

2016-12-02 01:50 UTC, mezz commented
When switching branches it's sometimes easier to just clean the workspace, set it up again, add the new lines, then generate.

2016-12-02 16:32 UTC, Selim042 commented
Running into a few problems with other stuff outside of MC.  I'll get back to this in a few days.

2016-12-02 20:19 UTC, mezz commented
No rush, just let me know when I should take a look.

2017-01-02 21:14 UTC, mezz commented
Any update @Selim042 ?

2017-01-12 22:15 UTC, Selim042 commented
Yea, sorry, I will get back into this shortly.

2017-01-23 16:22 UTC, Selim042 commented
Nevermind.  I am closing this for the time being.  I don't have the free time or much desire to work on this at this point.

2017-01-23 16:22 UTC, closed without merging