Allowed CanUpdate event to deny updates
MinecraftForge/MinecraftForge pull request #3506
Opened 2016-12-05 00:49 UTC by Asweez

Allowed CanUpdate event to be called whenever an entity tries to
update, not only when Minecraft decides that it shouldn’t. Also allowed
CanUpdate to deny updates instead of just allowing them.

2016-12-06 20:34 UTC, Asweez commented
Does BreakingChange mean it won't be added? Also what does the feature tag imply?

2016-12-06 21:14 UTC, KnightMiner commented
Feature basically means it is not a bug fix, and Breaking Change means it will most likely only merge with other breaking changes, which tends to happen around major version updates (such as the 1.11 update that is happening right now)

2016-12-06 21:31 UTC, liach requested changes

2016-12-06 21:31 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/EntityEvent.java
> +        private boolean canUpdate;
There should be two fields: `canUpdateOriginal` and `canUpdate` to prevent issues caused by two handlers handling `canUpdate` together.

2016-12-06 22:22 UTC, liach commented
:sweat: You should let mods access the original value but not the changed one to prevent confusions.

2016-12-06 22:25 UTC, Asweez commented
Makes sense. Changed.

2016-12-06 22:27 UTC, liach commented
Aye...
```java
    /**
     * CanUpdate is fired when an Entity is being created. <br>
     * This event is fired every time an entity tries to update <br>
     * <br>
     * {@link CanUpdate#canUpdate} contains the boolean value of whether this entity can update.<br>
     * If the modder decides that this Entity can be updated, they may change canUpdate to true, <br>
     * and the entity with then be updated, or vice versa.<br>
     * <br>
     * This event is not {@link Cancelable}.<br>
     * <br>
     * This event is fired on the {@link MinecraftForge#EVENT_BUS}.<br>
     **/
    public static class CanUpdate extends EntityEvent
    {
        private boolean canUpdate;
        private final boolean canUpdateOriginal;
        public CanUpdate(Entity entity, boolean canUpdate)
        {
            super(entity);
            this.canUpdateOriginal = canUpdate;
            this.canUpdate = canUpdate;
        }

        public boolean getCanUpdateOriginal()
        {
            return canUpdateOriginal;
        }

        public boolean getCanUpdate()
        {
            return canUpdate;
        }

        public void setCanUpdate(boolean canUpdate)
        {
            this.canUpdate = canUpdate;
        }
    }
```
This should be the correct code that allows mods to handle update checking the best.

2016-12-06 22:31 UTC, Asweez commented
Updated

2016-12-06 22:55 UTC, liach requested changes

2016-12-06 22:55 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/EntityEvent.java
> +        public boolean getCanUpdateOriginal(){
brace should be on new line

2016-12-06 23:18 UTC, mezz commented
Unfortunately the window for breaking changes is closed now.
This will have to be implemented in a different way.

If you can explain what you wanted this event change for, we may be able to help find another solution.

2016-12-06 23:35 UTC, Asweez commented
I want to be able to change the tickspeed of certain entities so they update slower. However I couldnt find a way to do that so I was aiming to cancel the updates of the entities and only allow updates every so often to slow them down. How should I do this another way? And is there a way to slow down the tickspeed of an entity? 

Thanks

2016-12-07 00:38 UTC, mezz commented
Hmm I'm not sure I see an easy solution.
One problem with your event is that is will be fired 100s of times per tick, possibly causing a performance problem.

If the entities are created by you, it may be easy to handle, but if you are doing something like a spell that slows down entities in an area it's more complicated.

2016-12-07 03:28 UTC, Asweez commented
So what should I do?

2016-12-07 05:30 UTC, mezz commented
If you just want to slow down their AI, there is `LivingUpdateEvent` which can be used to cancel `Entity.onUpdate`.

If you need to slow down movement, you can look at the slowness potion effect.

Otherwise you might add a boolean flag on the entity called something like `canUpdate` that you can set, which gets checked in the world update entities function. That way you're not firing an event all the time.

It really depend on exactly what you want to do.

2016-12-07 17:52 UTC, Asweez commented
I want to do both of those things, however I want to be able to slow down flying objects and animations as well

2016-12-10 20:30 UTC, liach commented
@mezz In fact, this change is not breaking, since it did not remove old methods.

2016-12-10 20:31 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/EntityEvent.java
> +        private boolean canUpdate;
Done

2016-12-10 20:31 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/EntityEvent.java
> +        public boolean getCanUpdateOriginal(){
@Asweez Can you fix this real quick?

2016-12-10 21:45 UTC, mezz commented
It's breaking because it changes the way the event is used, anyone using the event will have to adapt.

2017-03-06 09:36 UTC, mezz commented
I think this PR is superseded by https://github.com/MinecraftForge/MinecraftForge/pull/3731

2017-03-06 09:36 UTC, closed without merging