[1.11] Add DifficultyChangeEvent
MinecraftForge/MinecraftForge pull request #3525
Opened 2016-12-10 02:06 UTC by sjx233

Reopened #3289 .
Solves #3088 .

2016-12-10 02:13 UTC, mezz commented
Tested and this looks good, but I'm not sure it's a good idea to let an event change the difficulty here.
It makes sense as a way of notifying mods that the difficult changed, but I am not convinced there is a good case for changing the difficulty that the player chooses.

2016-12-10 02:56 UTC, liach requested changes

2016-12-10 02:56 UTC, liach commented on src/test/java/net/minecraftforge/test/DifficultyChangeEventTest.java
> +    public static final boolean ENABLE = true;
Make this `private` and set to `false`

2016-12-10 02:56 UTC, liach commented on src/main/java/net/minecraftforge/event/DifficultyChangeEvent.java
> +        if (difficulty == null)
Use `@Nonnull` for parameters instead of a null check.

2016-12-10 02:56 UTC, liach commented on src/main/java/net/minecraftforge/event/DifficultyChangeEvent.java
> +    private final EnumDifficulty oldDifficulty;
Probably add a field called `difficultyInArgs` or something like that?

2016-12-10 02:56 UTC, liach commented on src/main/java/net/minecraftforge/event/DifficultyChangeEvent.java
> +@Cancelable
I think you should better make it `@HasResult`.

`ALLOW`: final difficulty is given by subscribers.
`DEFAULT`: final difficulty is the same as difficulty in argument
`DENY`: no change

2016-12-10 03:16 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/DifficultyChangeEvent.java
> +        if (difficulty == null)
Not instead, do both. But `null` should not just be silently discarded, it should throw an exception.

2016-12-10 04:01 UTC, liach commented on src/main/java/net/minecraftforge/event/DifficultyChangeEvent.java
> +        if (difficulty == null)
Then `Preconditions.checkNotNull(difficulty)` is the best.

2016-12-10 04:27 UTC, liach approved these changes
Looks great!

2016-12-10 04:28 UTC, mezz commented
Your changes address liach's concerns but not mine.

2016-12-10 04:29 UTC, liach commented
@mezz Sometimes, hardcore mods want to prevent players from using some easy difficulties. Is this the case?

2016-12-10 04:30 UTC, mezz commented
You can already lock the difficulty in vanilla.

2016-12-10 04:38 UTC, mezz commented
To set and lock the difficult to hard, your mod just needs to call 
```java
WorldInfo worldInfo = Minecraft.getMinecraft().theWorld.getWorldInfo();
worldInfo.setDifficulty(EnumDifficulty.HARD);
worldInfo.setDifficultyLocked(true);
```

2016-12-10 05:23 UTC, liach commented
An example use case:
During a task in an RPG-style modification, you cannot change difficulty during the task; if you change, you are likely to receive a punishment--an increased difficulty. You can only change after you have done the task.

2016-12-10 05:52 UTC, mezz commented
Yep, that's a good example.

2016-12-10 15:36 UTC, diesieben07 commented
Note that there is already a mechanic for locking the difficulty, which can be set via `WorldInfo.setDifficultyLocked`. This would actually show the difficulty button as locked in the GUI instead of just making it do nothing, which I find quite bad UX.

2016-12-10 21:53 UTC, mezz commented
I agree with diesieben07, it is best to lock the difficulty to the user instead of letting them change it and punishing them.

2016-12-10 22:07 UTC, liach commented
@diesieben07 @mezz 
>  You can only change after you have done the task.

You can still change the difficulty but only after!

2016-12-10 22:15 UTC, mezz commented
You can unlock the difficulty after.
```java
worldInfo.setDifficultyLocked(false);
```

2016-12-10 22:24 UTC, liach commented
Ex. Removing a difficulty:
If you deny the event, you can never change the difficulty instead of skipping it. Allowing it and redirecting it is the only way to "remove" a difficulty.

2016-12-10 22:34 UTC, mezz commented
It's not right to restrict *player options* this way.
You don't have mod packs that say "you must play at FOV below 75, anything else is cheating".

Especially for difficulty, this is up to the player. If someone's Youtube idol is playing a hard pack on a hard difficulty, and they want to play along too but they're not as good, they should have the choice to set the game to Easy. This is also extremely important for disabled gamers, who need a lower difficulty setting in order to enjoy the game the same way.

2016-12-10 23:04 UTC, liach commented
By the way, in vanilla, is there any other way except setting or commands to change difficulty?

2016-12-11 02:24 UTC, mezz commented
I think those are the only ways.

2016-12-16 16:01 UTC, hyfloac commented
@liach @mezz 
> By the way, in vanilla, is there any other way except setting or commands to change difficulty?

I'm not sure if you want to call this "Vanilla" but using external programs (like [NBTExplorer](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1262665-nbtexplorer-nbt-editor-for-windows-and-mac)) you can change the variables in the world save files (the location in the world save is `%MINECRAFT_DIR%/saves/%WORLD%/level.dat/`, there are many settings here, but the ones that may pertain to this topic are `allowCommands`, `Difficulty`, `DifficultyLocked` and `hardcore`).

2017-01-03 00:54 UTC, liach commented
@sjx233 Now I think you probably need to make this event neither `@Cancellable` nor `@HasResult` like `FMLInitializationEvent` because of security concerns. Can you update this?

2017-01-03 01:30 UTC, williewillus commented
what do you mean "security"?

2017-01-03 01:43 UTC, liach commented
It means that the event can only read the new difficulty, but not change it.

2017-01-03 01:51 UTC, williewillus commented
why is being able to change it a "security risk"?

2017-01-03 03:42 UTC, liach commented
see mezz's comment above

2017-01-03 03:57 UTC, williewillus commented
gotcha

2017-01-11 02:43 UTC, sjx233 commented
@liach @mezz 
Updated.

2017-01-11 06:25 UTC, liach commented
Looks great to me.

2017-01-11 18:59 UTC, mezz commented
Looks good, works as expected.

2017-02-24 02:12 UTC, merged