[1.11] Allow mods to change the default dimension for respawning.
MinecraftForge/MinecraftForge pull request #3528
Opened 2016-12-10 16:55 UTC by gigaherz

This allows mods that add personal dimensions or custom dimensions, to act as the preferred respawn location in place of the overworld.

2016-12-10 16:56 UTC, williewillus commented
Should this be persisted?

2016-12-10 16:56 UTC, gigaherz commented
On it.

2016-12-10 16:59 UTC, williewillus commented
Well, idk if it should be, just thinking out loud

2016-12-10 18:17 UTC, liach commented on patches/minecraft/net/minecraft/world/WorldProvider.java.patch
> ++        return player.getSpawnDimension();
What if this dimension does not exist?

2016-12-10 18:20 UTC, gigaherz commented on patches/minecraft/net/minecraft/world/WorldProvider.java.patch
> ++        return player.getSpawnDimension();
Handled by https://github.com/MinecraftForge/MinecraftForge/pull/3528/files#diff-dd1379486da62415c702bed89ecdff10R119

2016-12-10 21:57 UTC, mezz commented
Can you make a test mod, disabled by default, that respawns the player in whatever dimension they are in? So a death in the nether respawns in the nether, etc.

2016-12-10 22:05 UTC, gigaherz commented
On it.

2016-12-10 22:10 UTC, mezz commented
One potential issue I see: dimensions that override `getRespawnDimension` have no way of knowing if the player's spawn has been set by something, or if it's just the default.

So imagine I have a dimension that normally respawns players in the same dimension, but the player is holding a bauble or something that forces them to respawn at their base in the nether. The dimension will always "win" and it seems like there's no way to write it so that it respects this new feature.

2016-12-10 22:19 UTC, gigaherz commented
That's not what the feature is designed for, though. This is just to allow custom dimensions to say "the player's preferred respawn world is X", instead of always trying to search for a bed in the overworld.

Right now there's two possible situations:
1. The dimension dictates which dimension players should respawn in, or
2. The player respawns in the overworld.

There's no way to give players a different "default" if point 1 is false.

This PR changes the logic to:
1. The dimension dictates which dimension players should respawn in, or
2. The player respawns in the configured preferred dimension (defaulting to overworld if no mods change it).

In order to allow a bauble to "force" the respawn to be elsewhere, we'd need some kind of `PlayerRespawnEvent` that allows changing the dimension AFTER the preferred target is chosen. This was beyond the scope of my PR, but I can work on it if it's wanted.

2016-12-10 22:25 UTC, mezz commented
What I think would be best of both worlds is the ability to do this:
1. Dimension sees if player has a preferred dimension.
2. Dimension uses preferred dimension if it exists
3. Dimension dictates which dimension players should respawn in otherwise.

I think this could be accomplished by making `spawnDimension` a `@Nullable Integer`

2016-12-10 22:48 UTC, gigaherz commented
I think we see this feature differently. My point of view was for allowing the home bed to be in a custom dimension instead of the overworld, not as a special object "forcing" a different spawn than usual. That is:

  * The dimension's special respawn choice > The dimension the player last slept in > The overworld.

What you describe would be a 4th level of "choice":

 * Forced respawn dimension > The dimension's special respawn choice > The dimension the player last slept in > The overworld.

I see how people may be confused by the feature, though. So I guess I'll need to have a more clear distinction somehow.

2016-12-10 22:52 UTC, mezz commented
What I describe still allows for your scenario, it's up to the dimension to decide what to do. I just want the dimension to have information about whether the player has a preferred dimension set.

2016-12-11 00:04 UTC, gigaherz commented
I implemented your suggestion, although I'm not a fan of the nullable Integer.

2016-12-11 00:07 UTC, liach commented on patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
> ++    private Integer spawnDimension;
I suggest using a negative integer instead possible nulls.

2016-12-11 00:21 UTC, gigaherz commented on patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
> ++    private Integer spawnDimension;
That won't do. Negative numbers are also valid dimension IDs.

2016-12-11 00:31 UTC, liach commented on patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
> ++    private Integer spawnDimension;
Or can we just put an invalid number?

2016-12-11 02:26 UTC, mezz commented
There are other ways to do it besides a nullable Integer if you think that's too ugly, like keeping a boolean field for if it was set or not.

2016-12-11 02:40 UTC, gigaherz commented
I wish forge was java8, then I'd just use `OptionalInt`, along with `.orElse(0)` -- the code would be so much cleaner... ;P

Meanwhile, I decided to keep the nullability hidden, and add an extra method to query if the value was set, for anyone that needs to know.

2016-12-11 02:42 UTC, mezz requested changes

2016-12-11 02:42 UTC, mezz commented on patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
> ++    private Integer spawnDimension;
This field should be marked  `@Nullable`, otherwise everything looks good to me.

2016-12-11 02:45 UTC, mezz approved these changes

2016-12-11 02:49 UTC, liach approved these changes

2016-12-11 02:57 UTC, mezz commented
Ok, tested and it's working as intended. Looks good to me.

2017-01-07 12:47 UTC, gigaherz commented
I have rebased to latest 1.11.2 code, reapplied the patches, and fixed some sort of brainfart I had where I would persist the wrong field.

2017-01-07 13:03 UTC, gigaherz commented
Travis failed due to download error, any way to retrigger?

2017-01-07 13:12 UTC, AEnterprise commented
if you do a forced push that usually works, if not a new commit to this branch or manualy triggered build will be needed for it to rebuild

2017-01-07 15:50 UTC, liach commented
@gigaherz close and reopen

2017-02-24 02:08 UTC, merged