Allow block to specify their type for AI pathfinding
MinecraftForge/MinecraftForge pull request #3546
Opened 2016-12-17 22:54 UTC by diesieben07

Allow blocks to specify their `PathNodeType` for AI pathfinding. This allows e.g. mod-added fences to behave like vanilla fences in respect to Mob AI.

2016-12-17 23:14 UTC, liach requested changes

2016-12-17 23:14 UTC, liach commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    @Nullable public net.minecraft.pathfinding.PathNodeType getAiPathNodeType()
1. Annotation should be on a new line;
2. At least this should be state-aware; consider exposing the block positon.

2016-12-17 23:14 UTC, liach commented on patches/minecraft/net/minecraft/pathfinding/WalkNodeProcessor.java.patch
>  +        if(block.isBurning(p_189553_1_, blockpos)) return PathNodeType.DAMAGE_FIRE;
The new method should handle this check. Other opinions welcomed.

2016-12-18 02:30 UTC, mezz commented
I think liach's requests make sense here.

2016-12-18 17:53 UTC, diesieben07 commented
Updated as suggested.

2016-12-18 18:47 UTC, liach commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    @Nullable public net.minecraft.pathfinding.PathNodeType getAiPathNodeType(IBlockState state, IBlockAccess world, BlockPos pos)
All other methods in Forge project is like
```java
@Nullable
public net.minecraft.pathfinding.PathNodeType getAiPathNodeType(IBlockState state, IBlockAccess world, BlockPos pos)
```
instead of putting annotation and the method head in the same line.

2016-12-18 18:49 UTC, liach commented
I suggest making a test mod to show that this change works as intended. You should screenshot a picture like [this](http://minecraft.gamepedia.com/File:Zombie_ways.png). It is a picture from [Minecraft Wiki](http://minecraft.gamepedia.com/Zombie#Behavior) that demonstrates the Zombies' AI.

2016-12-18 18:53 UTC, PaleoCrafter commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    @Nullable public net.minecraft.pathfinding.PathNodeType getAiPathNodeType(IBlockState state, IBlockAccess world, BlockPos pos)
I assume diesieben just wanted to minimize the patch size by putting it all in the same line. A similar thing can be found [here in commit 150566d](https://github.com/diesieben07/MinecraftForge/commit/150566d9a34005e4ec7b91ab0ab99b3fd27d555e#diff-97673260fb0239af80fa467c2f5f5086R1225).

2016-12-18 19:38 UTC, diesieben07 commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    @Nullable public net.minecraft.pathfinding.PathNodeType getAiPathNodeType(IBlockState state, IBlockAccess world, BlockPos pos)
Yeah, but it doesn't really make sense here, the `Block` patch is a huge blob all all already anyways. I just forgot to fix this in my update.

2016-12-18 22:30 UTC, bs2609 commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++     * Set the PathNodeType for this block. null for vanilla behavior.
Suggestion for the comment:
`Get the PathNodeType for this block. Return null for vanilla behavior.`

2016-12-18 22:39 UTC, liach commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++     * Set the PathNodeType for this block. null for vanilla behavior.
`Returns`

2016-12-18 23:01 UTC, diesieben07 commented
Added a test mod, see attached image (zombie thinks the test block is an open door and tries to walk through it).

![2016-12-18_23 42 58](https://cloud.githubusercontent.com/assets/1915984/21297345/303185a6-c57e-11e6-8088-7f61139ff640.png)

2016-12-21 21:24 UTC, bs2609 commented
The Block patch needs regenerating (due to #3547)

2016-12-21 22:25 UTC, diesieben07 commented
Rebased onto current 1.11.x.

2016-12-22 01:38 UTC, mezz commented
Tested and it works as expected.

2016-12-22 18:04 UTC, liach approved these changes

2017-01-12 00:43 UTC, merged