Fix milk not working on anything at all
MinecraftForge/MinecraftForge pull request #3574
Opened 2016-12-27 23:21 UTC by williewillus

In the latest 1.11.2 build milk does not work on any of the vanilla potion effects.
This is because the bucket, with stack size 1, gets `shrink` called on it, turning it into an air stack.

Then this air stack is passed to `curePotionEffects`, which obviously does nothing.

The patch looks a bit wonky, but all this does is move the call to `EntityLivingBase.curePotionEffects` above the call to `stack.shrink(1)`

2016-12-28 00:50 UTC, Chocohead commented on patches/minecraft/net/minecraft/item/ItemBucketMilk.java.patch
> +-        if (!p_77654_2_.field_72995_K)
The patch could be smaller if you did `if (false&&!p_77654_2_.field_72995_K)` then you wouldn't need to remove the 3 lines afterwards.

2016-12-28 09:22 UTC, bs2609 commented
Is there a Mojira ticket for this?
If not, anyone feel like making one?

2016-12-28 16:52 UTC, williewillus commented
nope, just forge, because we patch the vanilla call which is not stack sensitive to become stack sensitive.

2016-12-28 17:10 UTC, bs2609 commented
Ah right, that makes sense. Thanks for clearing that up.

2016-12-29 01:04 UTC, mezz requested changes

2016-12-29 01:04 UTC, mezz commented on patches/minecraft/net/minecraft/item/ItemBucketMilk.java.patch
> +-        if (!p_77654_2_.field_72995_K)
Please use `if (false&&!p_77654_2_.field_72995_K)` as Chocohead suggests

2016-12-29 05:38 UTC, liach commented on patches/minecraft/net/minecraft/item/ItemBucketMilk.java.patch
> +-        if (!p_77654_2_.field_72995_K)
Not really... A line of `if (false)` above or two lines of `/*` and `*/` would be better. I suggest to use the comment.

2016-12-29 05:52 UTC, williewillus commented on patches/minecraft/net/minecraft/item/ItemBucketMilk.java.patch
> +-        if (!p_77654_2_.field_72995_K)
`if false` is the normal forge convention for these sorts of things. I'll use the if

2016-12-29 06:07 UTC, mezz approved these changes

2016-12-29 06:12 UTC, mezz commented
Looks good, works as expected.

2017-01-11 23:19 UTC, merged