Changed custom entity selectors from event based to factory based.
MinecraftForge/MinecraftForge pull request #3579
Opened 2016-12-29 12:56 UTC by maxanier

Fixes #3558.
As MC 1.11 requires any entity selectors to be registered beforehand. The event based solution seemed a bit odd as it requires two independent actions (registering the selector string at startup and creating an event handler), so this PR switches to a factory based way (modders have to register a factory together with the expected selector strings at startup).
Mods (which already  offer custom selectors) have to adapt, but since the event based solution would have required changes a well and switching to the factory method is not very time-consuming, this should be no problem. 
To keep binary compatibility with existent 1.11 mods, the old event still exists, but is deprecated and not fired.

I was not sure where to put the code, so if you have a better location, I will move it.

This also adds a test mod, which registers a 'forge:min_health' selector.
"/kill @e[forge:min_health=20]" should only kill entities with 20 or more health.

2016-12-29 13:38 UTC, maxanier commented
@Mathe172 This should work with your #3545, doesn't it. Should we somehow merge both PRs? I could move the factory registrations to your SelectorHandlerManager or similar. Or should we keep the two systems separate as they do slightly different things (and to increase the chance that your PR is merged anytime soon).

2016-12-29 17:22 UTC, Mathe172 commented
I think the two PRs are too different to be merged in a meaningful way - this one upgrades the vanilla selector, while the other one is for defining new selectors.
Nevertheless, they should work together nicely - a mod defining a new selector could even call `createEntitySelectors` and everything should still work

2016-12-29 17:30 UTC, Mathe172 reviewed
Since they apply to just a test mod, the suggested changes are probably not very important - they're only there for the sake of completeness :)

2016-12-29 17:30 UTC, Mathe172 commented on src/test/java/net/minecraftforge/test/CustomEntitySelectorTest.java
> +                            return invert && !health || !invert && health;
Could be changed to `invert != health`

2016-12-29 17:30 UTC, Mathe172 commented on src/test/java/net/minecraftforge/test/CustomEntitySelectorTest.java
> +                    predicates.add(new Predicate<Entity>()
You could just return `Collections.singletonList(...)`

2016-12-29 17:30 UTC, Mathe172 commented on src/test/java/net/minecraftforge/test/CustomEntitySelectorTest.java
> +            if (health != null)
Probably easier to just return `Collections.emptyList()`

2016-12-29 18:29 UTC, maxanier commented on src/test/java/net/minecraftforge/test/CustomEntitySelectorTest.java
> +            if (health != null)
Vanilla sometimes uses my approach, sometimes yours. I decided to go with this as I personally think it's easier to understand. 
But as modders might take this as an example and as every (tiny) performance increase counts, I changed it according to your suggestions now :)

2016-12-29 18:29 UTC, maxanier commented on src/test/java/net/minecraftforge/test/CustomEntitySelectorTest.java
> +                            return invert && !health || !invert && health;
:man_facepalming:

2017-01-16 13:34 UTC, maxanier commented
Any other concerns about this, or can this be merged?

2017-02-02 02:15 UTC, mezz commented
I think this requires #3545 to be merged first, so I haven't reviewed it yet.

2017-04-25 18:12 UTC, maxanier commented
@mezz can you take a look at this again?
I don't think this requires #3545, they affect similar things, but not the same. This one allows custom selectors "[forge:min_health=5]" to be defined while the other one allows custom prefixes (something like "@k[...]") to be defined.
As far as I can tell they should work together just fine.

The old (not working way) is in the code since beginning of 1.11, so modders might start wondering why this does not work, and I finally got around updating my mods to 1.11 and would like to use it as well :)

2017-04-30 23:38 UTC, mezz commented
Ok, I'll take a look.

2017-05-01 00:01 UTC, mezz requested changes
Looks good, I have some requests for changes in the documentation.

2017-05-01 00:01 UTC, mezz commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> -    public static List<Predicate<Entity>> gatherEntitySelectors(Map<String, String> map, String mainSelector, ICommandSender sender, Vec3d position)
To preserve binary compatibility, deprecate this and leave the code in for now.
Leave a javadoc comment saying it should be removed in 1.12

2017-05-01 00:01 UTC, mezz commented on src/main/java/net/minecraftforge/event/EntitySelectorEvent.java
> + * Replaced by a factory, which has to be registered with {@link net.minecraftforge.fml.common.registry.GameRegistry#registerEntitySelector(IEntitySelectorFactory, String...)}
Leave a javadoc comment saying it should be removed in 1.12

2017-05-01 00:01 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java
> +     * @param arguments Expected string arguments in commands
I think this javadoc should be made more clear for people who have never implemented an entity selector before.
In the javadoc, please give a full example command that someone might type into the console, and point out which part of it is an "expected string argument".

2017-05-01 00:01 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java
> +     * Any non vanilla arguments that you expect has to be registered.
I think it is important to point out *why* the arguments have to be registered. From what I understand, any argument that isn't added here will be ignored by the entity selector system.

2017-05-01 00:01 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/IEntitySelectorFactory.java
> + * Can be registered in {@link net.minecraftforge.fml.common.registry.GameRegistry} to generate entity predicates for custom entity selectors in commands.
This should contain the most important information first. It should also point directly to the registration method, GameRegistry is a large file to look through. Something like this:

```java
/**
 * Allows mods to create custom entity selectors in commands.
 * Registered in {@link net.minecraftforge.fml.common.registry.GameRegistry#registerEntitySelector}.
 * For an example implementation, see CustomEntitySelectorTest.
```

2017-05-01 00:01 UTC, mezz commented on src/test/java/net/minecraftforge/test/CustomEntitySelectorTest.java
> +@Mod(modid = "customentityselectortest", name = "Custom Entity Selector Test", version = "1.0", acceptableRemoteVersions = "*")
Please add a short javadoc with steps to use in-game to confirm that everything is working with this test.
Someone should be able to use this test to confirm everything is working, without reading the code. This also ensures that any bugs in the code can be checked against this javadoc specification if necessary.

2017-05-01 11:39 UTC, maxanier commented
Thank you very much for your feedback. I've updated the javadoc accordingly.

2017-05-01 16:55 UTC, mezz commented
Tested and everything works as expected.

2017-05-01 16:55 UTC, mezz approved these changes

2017-05-02 01:36 UTC, merged