[1.11] Allow any Item to bypass a Sheild
MinecraftForge/MinecraftForge pull request #3583
Opened 2016-12-30 20:36 UTC by Madsthunder

This allows items other than those that extend ItemAxe to bypass a Sheild.

2016-12-30 20:50 UTC, williewillus commented
I would call it "canDisableShield"

2016-12-30 21:35 UTC, mezz commented
This looks good. 
I agree with williewillus about the name, please change it to that.

2016-12-30 23:26 UTC, 61352151511 commented
Well not completely understanding the functionality I would say it should be canBypassShield if it's just bypassing the shield and canDisableShield if it actually disables it. Disabling would be a permanent effect like you hit the shield with it once and then everything else is effective against it.

2016-12-31 00:09 UTC, williewillus commented
No, i suggested that because the feature that your if statement is guarding is literally called "shield disabling" by the vanilla community.

2016-12-31 00:11 UTC, williewillus commented on patches/minecraft/net/minecraft/item/Item.java.patch
> ++    public boolean canBypassSheild(ItemStack stack, ItemStack sheild, Entity entity, Entity attacker)
shield is spelled "shield" not "sheild"

2016-12-31 00:19 UTC, Madsthunder commented
Added a few commits that adds a Javadoc, corrects the spelling of 'sheild', and renames Item#canBypassSheild to #canDisableShield.

2016-12-31 04:43 UTC, williewillus commented
looks good to me

2016-12-31 04:45 UTC, liach commented on patches/minecraft/net/minecraft/entity/monster/EntityMob.java.patch
> ++                if (!itemstack.func_190926_b() && !itemstack1.func_190926_b() && itemstack.func_77973_b().canDisableShield(itemstack1, itemstack, p_70652_1_, this) && itemstack1.func_77973_b() == It
What is `Items.field_185159_cQ`?

2016-12-31 04:53 UTC, williewillus commented on patches/minecraft/net/minecraft/entity/monster/EntityMob.java.patch
> ++                if (!itemstack.func_190926_b() && !itemstack1.func_190926_b() && itemstack.func_77973_b().canDisableShield(itemstack1, itemstack, p_70652_1_, this) && itemstack1.func_77973_b() == It
that's probably testing for the shield itself. that part isn't being changed in this PR

2016-12-31 05:02 UTC, mezz commented on patches/minecraft/net/minecraft/entity/monster/EntityMob.java.patch
> ++                if (!itemstack.func_190926_b() && !itemstack1.func_190926_b() && itemstack.func_77973_b().canDisableShield(itemstack1, itemstack, p_70652_1_, this) && itemstack1.func_77973_b() == It
Yes it's `Items.SHIELD`

2016-12-31 05:07 UTC, liach commented on patches/minecraft/net/minecraft/entity/monster/EntityMob.java.patch
> ++                if (!itemstack.func_190926_b() && !itemstack1.func_190926_b() && itemstack.func_77973_b().canDisableShield(itemstack1, itemstack, p_70652_1_, this) && itemstack1.func_77973_b() == It
Refer to #3557, clean up needed if both are merged. Okay for now.

2017-02-23 20:48 UTC, Madsthunder commented
Any updates on this or #3557?

2017-02-24 01:54 UTC, LexManos commented on patches/minecraft/net/minecraft/item/Item.java.patch
> ++    	return this instanceof ItemAxe;
tabs eww

2017-02-24 01:59 UTC, LexManos commented on patches/minecraft/net/minecraft/entity/monster/EntityMob.java.patch
> ++                if (!itemstack.func_190926_b() && !itemstack1.func_190926_b() && itemstack.func_77973_b().canDisableShield(itemstack1, itemstack, p_70652_1_, this) && itemstack1.func_77973_b() == It
This is probably one of the rare cases where the two PRs should be merged as a general 'expand shield functionality' pr.

2017-02-26 21:53 UTC, Madsthunder commented
@LexManos Should I remove the `itemstack.getItem() instanceof ItemAxe` altogether in favor of `itemstack.getItem().canDisableShield()`? (That would also slightly reduce the patch size)

2017-02-26 21:56 UTC, williewillus commented
patch size is counted by lines added/remove, not how many characters you change in a line.

2017-02-26 22:03 UTC, liach commented
@Madsthunder Your suggestion can cause a stack overflow.

2017-02-26 22:43 UTC, liach requested changes

2017-02-26 22:43 UTC, liach commented on patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
> ++        this.spawnDimension = p_70037_1_.func_74767_n("HasSpawnDimensionSet") ? p_70037_1_.func_74762_e("SpawnDimension") : null;
Why did you add this?

2017-02-26 22:43 UTC, liach commented on patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
> ++
Bad addition

2017-02-26 22:43 UTC, liach commented on patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
> ++
Bad addition

2017-02-26 22:55 UTC, liach commented
You can try to use `git mergetool`

2017-02-26 23:14 UTC, liach approved these changes

2017-02-26 23:19 UTC, Madsthunder commented
@jaredlll08 Would you mind if I merged the content of your pr with this to avoid more merge conflicts?

2017-02-26 23:46 UTC, jaredlll08 commented
Go ahead :)

On Feb 27, 2017 01:19, "Madsthunder" <notifications@github.com> wrote:

> @jaredlll08 <https://github.com/jaredlll08> Would you mind if I merged
> the content of your pr with this to avoid more merge conflicts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/MinecraftForge/MinecraftForge/pull/3583#issuecomment-282597233>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFS9xVxQSDUatj6arrEPegS4zzlJC2a0ks5rgghwgaJpZM4LYYOy>
> .
>

2017-02-28 02:56 UTC, Madsthunder commented
Wow, I screwed up badly on my attempt to resolve merge conflicts...

2017-03-01 04:31 UTC, mezz commented
Closing in favor of #3741

2017-03-01 04:31 UTC, closed without merging