Add smarter getter for block slipperiness
MinecraftForge/MinecraftForge pull request #3620
Opened 2017-01-09 23:15 UTC by howtonotwin

Allow a block access to the blockstate, world, position, and entity when
getting slipperiness with new `Block::getSlipperiness` method. Change usages of `Block::slipperiness` to `Block::getSlipperiness` in
vanilla. Deprecate old field.

[Boat Blaster](https://gist.github.com/howtonotwin/3ff1260ac20d6befbf0784708e30c14f) test mod gist.

2017-01-09 23:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3620) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3620) before we can accept your contribution.<br/>

2017-01-11 19:44 UTC, liach approved these changes

2017-01-12 17:13 UTC, liach commented
You need to fix the merge conflict.

2017-03-02 07:44 UTC, bs2609 commented
This needs updating again to resolve conflicts

2017-04-10 00:45 UTC, howtonotwin commented
Is there a good, tested way to fix patch conflicts? The way I did it was

1. `git reset --hard HEAD`
2. Checkout `slipperiness` branch
3. `./gradlew setupDecompWorkspace`
4. Copy `projects/Forge/src/main/java` into external location
5. Repeat for `1.11.x` branch and for `git merge-base 1.11.x slipperiness` commit
6. `for file in $(find base -type f -printf '%P'); do git merge-file slipperiness/$file base/$file upstream/$file; done`
7. Copy resulting sources back into Forge tree
8. `./gradlew genPatches`

But I'm not sure if this will produce any errors in other cases, or if there's an easier way. I checked the output just in case and it seems fine.

2017-04-10 05:19 UTC, mezz commented
No, fixing patch conflicts is not particularly easy. I think you have the right idea. I tend to just fix the code manually and then `genPatches`. This one just happens to touch a pretty popular file, `Block.java`, so it probably conflicts more often than other PRs.

2017-04-10 05:23 UTC, liach commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++     * Note that entities may reduce slipperiness by a certain factor of their own; for {@link net.minecraft.entity.EntityLivingBase}, this is {@code .91}. {@link net.minecraft.entity.item.EntityIte
Can you split this in multiple lines?

2017-04-10 20:42 UTC, howtonotwin commented
Should there be a `setDeaultSlipperiness(Float)` so that someone can set the field without generating a deprecation warning? It'll come with a Javadoc message that signifies that actual slipperiness comes from `getSlipperiness` and the set value may not be accurate, or even be wholly ignored.

2017-04-10 21:31 UTC, bs2609 commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++     * {@link net.minecraft.entity.projectile.EntityFishHook} uses {@code .92}.
Could you split this so each example gets its own line?

Like:
```
 * Note that entities may reduce slipperiness by a certain factor of their own;
 * for {@link net.minecraft.entity.EntityLivingBase}, this is {@code .91},
 * {@link net.minecraft.entity.item.EntityItem} uses {@code .98},
 * and {@link net.minecraft.entity.projectile.EntityFishHook} uses {@code .92}.
```

2017-04-10 23:29 UTC, howtonotwin commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++     * {@link net.minecraft.entity.projectile.EntityFishHook} uses {@code .92}.
How about a table?

2017-04-11 12:50 UTC, kashike commented
> Should there be a `setDeaultSlipperiness(Float)` so that someone can set the field without generating a deprecation warning? It'll come with a Javadoc message that signifies that actual slipperiness comes from `getSlipperiness` and the set value may not be accurate, or even be wholly ignored.

Wouldn't hurt, and would prevent complaints about deprecation warnings.

2017-05-01 00:09 UTC, mezz requested changes
Looks good. 

Please fix formatting I commented on.

Also please include the `BoatBlaster` test mod as `SlipperinessTest` in this PR. It should go with the other forge test mods, and be disabled by default.

2017-05-01 00:09 UTC, mezz commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public void setDefaultSlipperiness(float slipperiness) {
formatting: braces must be on a new line

2017-07-01 19:01 UTC, howtonotwin commented
Should this be rebased to `1.12.x`?

2017-07-01 22:59 UTC, mezz commented
Yes, this should target 1.12.x.
If you want to also target 1.11.x, make a new 1.12.x PR and leave this one open.

2017-07-03 17:54 UTC, mezz approved these changes

2017-08-02 04:28 UTC, mezz commented
If you want, please update this to match the 1.12 version and I can merge it. Otherwise we should close it.

2017-08-02 15:05 UTC, howtonotwin commented
That should be it.

2017-10-04 06:49 UTC, merged