[1.11]Added Missing Furnace Fuels
MinecraftForge/MinecraftForge pull request #3627
Opened 2017-01-13 12:36 UTC by CoderAtParadise

Initial report found on the forums at
[http://www.minecraftforge.net/forum/index.php?topic=44537.0](url)

2017-01-13 20:23 UTC, liach requested changes

2017-01-13 20:23 UTC, liach commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
> ++                }
Make them like
```java
if (block == Blocks.field_150325_L) return 100;
```
and there should be space between `if` and `(`.

2017-01-13 22:15 UTC, bs2609 commented
The original patch could do with a redo tbh.

Would changing the original `return ...` to `int default = ...` and then doing:
`return default != 0 ? default : ...GameRegistry.getFuelValue(p_145952_0_);` work?

2017-01-13 23:18 UTC, mezz commented
I agree with @bs2609, there is something fishy about having to diligently maintain this patch just to match vanilla.
Also the forge event should be checked before vanilla, or else all wood material items have burn time 300 and it can never be changed.

2017-01-14 01:02 UTC, CoderAtParadise commented
Changed the patch so that forge shouldn't have to modify the vanilla fuels anymore

2017-01-14 01:48 UTC, mezz commented
This patch looks much better now, thanks.

2017-01-14 02:50 UTC, mezz commented
To avoid letting anyone alter the vanilla burn times, can you check if 
`item.getRegistryName().getResourceDomain().equals("minecraft")` 
and bypass the forge part in that case?

Also I'm curious if there is any way to specify a burn time of 0, since Forestry has wooden items that are fireproof. Right now the forge part will fall through to vanilla, and the burn time will be 300 even though I want it to be 0.

2017-01-14 02:54 UTC, bs2609 commented
@mezz return a time < 0 ?

2017-01-14 04:03 UTC, liach commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
> ++            if(burnTime != 0) return burnTime;
Code style.
```java
if (burnTime != 0)
```
instead of 
```java
if(burnTime != 0)
```

2017-01-14 04:05 UTC, liach commented
@mezz That would be involved in another pull request since such a change needs you to change `GameRegistry`.

2017-01-14 04:20 UTC, CoderAtParadise commented
Maybe a change to IFuelHandler that has a flag for fireproof or something and checks against that in the furnace because currently burn time of zero doesn't allow the item to be placed in the fuel slot

2017-01-14 04:23 UTC, CoderAtParadise commented
@mezz the bypass wouldn't work because what if a mod wanted to say add a fuel burn time for cobblestone the bypass check would block that

2017-01-14 04:29 UTC, mezz commented
Fair enough, I can address the fireproof wood issue another time. 

Lex wants to be sure that vanilla item burn times cannot be affected though, please solve that part before this can be accepted. If `vanilla burn time > 0 and resource location is minecraft` skip the forge version? Honestly though, making cobble or any other vanilla item burnable seems pretty questionable... I think the original bypass would be fine.

2017-01-14 05:03 UTC, bs2609 commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
>  +
This line can be removed now

2017-01-14 05:04 UTC, CoderAtParadise commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
>  +
it is being removed

2017-01-14 05:05 UTC, CoderAtParadise commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
>  +
whoops read wrong line

2017-01-14 15:51 UTC, mezz commented
The logic is still not quite right, it needs to fall back on vanilla behavior if Forge burn time is 0.

2017-01-15 20:01 UTC, mezz commented
Looks good.

2017-01-15 22:09 UTC, liach approved these changes

2017-02-24 01:43 UTC, LexManos commented
Actually again, it doesn't allow people to specify unburnable items.
We need to better define what IFuelHandler is. Currently we don't distinguish between 'this 0 is the burn time!' or 'this 0 means I dont care about this object'
Which is why the original implementation had the handlers fired AFTER the normal mechanics. 

IFuelHandler needs to be revamped, but alas, that's a breaking change for 1.12+

2017-02-24 01:46 UTC, merged

2017-03-04 10:23 UTC, CovertJaguar commented
This really should just be a method on Item. Not this horrendously inefficient list of predicates we have now. Maybe combined with an event for overrides.

2017-05-25 04:16 UTC, ezterry commented
Regarding long term an event that can be cancelled is probably the best.

For the current change, I'm here because I just got a bug report on my json recipe edit mod that someone couldn't burn feathers.  Since you no longer allow burn times on vanilla items. (regardless if they are burnable or not)

I really think for now (pre 1.12) the best solution I have is make vanilla items implement getFuelValue and use the normal max logic.. (for vanilla fuels this would let a mod extend burn time but alas not remove/shorten it)