Prevent concurrent modification of ClassInheritanceMultiMap
MinecraftForge/MinecraftForge pull request #3632
Opened 2017-01-16 09:10 UTC by bs2609

`ClassInheritanceMultiMap`'s constructor is not thread-safe as it iterates over a static collection (`ClassInheritanceMultiMap.ALL_KNOWN`).

This makes `new Chunk()` thread-unsafe, which is an issue as it is called from both client and server threads, as well as potentially Forge async chunk-loading threads.

This can cause `ConcurrentModificationException` crashes to occur when crating new chunks. The patch fixes that by synchronising access to the shared field.

This pull request is intended for discussion of the issue as well as proposing a potential solution.

Notes:
Crashes caused by this are rare, and I have never experienced a crash from this with just vanilla Minecraft. However, I couldn't see any way in which vanilla works to prevent this, it seems to be mostly luck with timings.

Even with good practices around mod threading, I can't see that this can be avoided in the case of single-player with both client and server threads both potentially creating chunks.

2017-01-16 09:11 UTC, bs2609 commented
@Barteks2x, I know you had some experiences of this issue, is there anything you'd care to add?

2017-01-16 15:10 UTC, williewillus commented
Should we use `Collections.newSetFromMap(new ConcurrentHashMap<>())` instead?

2017-01-16 15:11 UTC, diesieben07 commented
> Should we use Collections.newSetFromMap(new ConcurrentHashMap<>()) instead?

Most definitely. Especially with Java 8 the `ConcurrentHashMap` is a lot better than just synchronizing everything.

2017-01-16 17:48 UTC, Barteks2x commented
The fix is a bit hard to test, especially when it (almost?) never happens in vanilla/forge. It rarely (I saw it happen about 5 times) happens in my mod, so I added a workaround that will catch the exception and create new ClassInheritanceMultiMap, until it sicceeds. 

The reason I think it happens more frequently for me is that in vanilla creation of these objects is done 16 at a time, but less frequently. In my case, it's done one at a time but more frequently. And there are more of them created in total.

I still don't think this solution will actually work (but I make be wrong, I will see it if could work after analyzing the whole code).  The reason is that CME happens when something modifies the collection while iterator is being used. This seems to only prevent iterating in 2 threads at the same time. Because this crash is so rare, I can't really be sure what is the exact thing that causes it, but as I remember there are places where new elements are added to that collection, possiby from other thread. That would explain why it almost never happens after longer time, only soon after loading the world.

2017-01-16 21:12 UTC, bs2609 commented
Patch has been changed to use `newSetFromMap()` instead of synchronising, I looked for a suitable concurrent set, but missed the `Collections` method.

2017-01-16 21:48 UTC, mezz commented
Looks good to me.

2017-01-16 22:22 UTC, Barteks2x commented
I remember I looked into that and wanted to replace it with Concurrent set, but I remember I abandoned the idea after I saw it wouldn't actually work. I don't have easy access to the code right now so I can't check it for sure, but as I remember, it's some other method being called that modifies the collection while the constructor is iterating.

2017-01-16 22:28 UTC, diesieben07 commented
Concurrent iteration and modification is supported by ConcurrentHashMap. It's iterators are "weakly consistent" as the Javadoc calls it.

2017-01-16 22:29 UTC, williewillus commented
We should probably put a comment explaining why the field is broken without the patch, like
`// FORGE - Accessed from Chunk constructor which runs on multiple threads`

2017-01-16 22:29 UTC, mezz commented
[`ConcurrentHashMap`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html) is threadsafe, including for iteration while something else modifies it. The iteration only covers what was there at the time the iterator was created.
>Similarly, Iterators, Spliterators and Enumerations return elements reflecting the state of the hash table at some point at or since the creation of the iterator/enumeration. They do not throw ConcurrentModificationException. However, iterators are designed to be used by only one thread at a time.

At first glance, that should be good enough for this. If we want stronger guarantees we'll have to `synchronize`.

2017-01-17 05:43 UTC, mezz requested changes

2017-01-17 05:43 UTC, mezz commented on patches/minecraft/net/minecraft/util/ClassInheritanceMultiMap.java.patch
> ++    private static final Set < Class<? >> field_181158_a = java.util.Collections.newSetFromMap(new java.util.concurrent.ConcurrentHashMap<Class<?>, Boolean>());
This needs some kind of `// forge` comment so it survives any changes.

2017-01-17 21:58 UTC, mezz approved these changes

2017-02-24 01:20 UTC, merged