Improve exception messages during construction
MinecraftForge/MinecraftForge pull request #3636
Opened 2017-01-17 18:09 UTC by ichttt

This PR adds the open mods folder and show log button to all exceptions.
It also adds support for showing all WrongMinecraftVersion and MissingModsException at once.
![multipleexceptions](https://cloud.githubusercontent.com/assets/20151702/22033323/620f3e3e-dce8-11e6-9ee8-93fac8c2a9f1.JPG)

2017-01-17 18:39 UTC, 3TUSK commented
Should this close #3631 ?

2017-01-17 20:05 UTC, williewillus commented
yes

2017-01-17 21:26 UTC, Madsthunder commented
Can the buttons be named something, in case somebody gets confused?

2017-01-17 21:39 UTC, LexManos commented on src/main/java/net/minecraftforge/fml/client/GuiMultipleModsErrored.java
> +        }
Why make these different 'pages', why not just make a scroll window and list all of them at once, this would be better.

2017-01-17 21:40 UTC, LexManos commented
Also, having screenshots/test mods for all the different screens you edit would be nice.

2017-01-19 19:57 UTC, ichttt commented
Some screenshots:
![duplicate mods exception](https://cloud.githubusercontent.com/assets/20151702/22122866/c86b8050-de89-11e6-8868-380acc90d3bf.JPG)
![java 8 version exception](https://cloud.githubusercontent.com/assets/20151702/22122867/c86bfaee-de89-11e6-9018-ab484e1b389f.JPG)
![multipleerrors](https://cloud.githubusercontent.com/assets/20151702/22122869/c871b10a-de89-11e6-936d-38dbd88e1cc3.JPG)
![wrongminecraftversionexception](https://cloud.githubusercontent.com/assets/20151702/22122868/c871d3d8-de89-11e6-8868-28d0b2325391.JPG)

Feedback welcome

2017-01-19 20:59 UTC, mezz commented
Looks pretty good! 
I have some feedback, these are my opinion so it is up for debate.

"Java Update Required" error screen
 - The only options should be "Open Mods Folder" and "Go to Java Downloads", the other options are not very useful in this case.

"There were 3 errors loading minecraft" 

- It should be centered between the top of the screen and top of the info box.
- "Minecraft" should be capitalized.
- We need to see what happens when there are enough errors to require scrolling.

"The mods listed below does not want to run in Minecraft version 1.11.2"

 - Should be "The mods listed below can't run on Minecraft version 1.11.2"

"GooglyEyes (googlyeyes) wants Minecraft between 1.10.2 and 1.10.2"

- Should be  "GooglyEyes (googlyeyes) requires Minecraft 1.10.2"

2017-01-20 15:07 UTC, ichttt commented
New screenshots!
![java8versionexception](https://cloud.githubusercontent.com/assets/20151702/22154072/57064c6e-df2a-11e6-9fbc-06e5c8228a1b.JPG)
![multiplescrolleddown](https://cloud.githubusercontent.com/assets/20151702/22154074/5709a210-df2a-11e6-99b3-e58ec9c7d280.JPG)
![multiplescrolledup](https://cloud.githubusercontent.com/assets/20151702/22154073/570782f0-df2a-11e6-8427-1fa3939c5b48.JPG)
![wrongminecraftversion](https://cloud.githubusercontent.com/assets/20151702/22154071/5704f2f6-df2a-11e6-9b38-50ff27d96d25.JPG)

2017-01-20 15:09 UTC, ichttt commented on src/main/java/net/minecraftforge/fml/common/versioning/Restriction.java
> +                return getLowerBound().getVersionString();
Can someone confirm if these changes are ok (it prevents returning something like beetween 1.10.2 and 1.10.2)

2017-01-20 22:07 UTC, LexManos commented on src/main/java/net/minecraftforge/fml/common/versioning/Restriction.java
> +                return getLowerBound().getVersionString();
Yes, we use it on other error screens.

2017-01-21 02:30 UTC, mezz requested changes
Looks good, I just have some requested changes about code style.

2017-01-21 02:30 UTC, mezz commented on src/main/java/net/minecraftforge/fml/client/GuiJava8Error.java
>          // super.super
this comment seems invalid now

2017-01-21 02:30 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/Loader.java
> +            if(wrongMinecraftExceptions.isEmpty()&&missingModsExceptions.isEmpty())
Please format your `if` statements like the rest of Forge:
```java
if (wrongMinecraftExceptions.isEmpty() && missingModsExceptions.isEmpty())
```

2017-01-21 02:30 UTC, mezz commented on src/main/java/net/minecraftforge/fml/client/GuiWrongMinecraft.java
> +        super();
There is no reason to call `super()` without arguments, it is already called automatically when no other `super` call is made.
Please remove all calls to `super()`.

2017-01-21 21:21 UTC, mezz approved these changes

2017-02-24 01:15 UTC, merged