Updated GuiTabs PR to 1.11.x
MinecraftForge/MinecraftForge pull request #3642
Opened 2017-01-18 20:57 UTC by AshIndigo

Changes made from #3349:
- Modified code to work with 1.11 changes
- Added back continuities (You can go back to the vanilla tab easily without exiting the GUI)
- Improved and added Java docs to various methods and fields.
- Made a test mod which will check if the tabs are working and if ResourceLocation and ItemStack icons are working too
 
Credits to @ArtixAllMighty for making the original PR

2017-01-18 20:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3642) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3642) before we can accept your contribution.<br/>

2017-01-19 12:10 UTC, HenryLoenwind commented on src/test/java/net/minecraftforge/test/GuiTabsTest.java
> +                new GuiTab("Tab3", new ItemStack(Blocks.FURNACE), TestGui2.class) {
Have you tested items with enchantment glint?

2017-01-19 16:21 UTC, Alpvax commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> +     * ItemStack version of tabs
Should say ResourceLocation version

2017-01-20 00:22 UTC, AshIndigo commented on src/test/java/net/minecraftforge/test/GuiTabsTest.java
> +                new GuiTab("Tab3", new ItemStack(Blocks.FURNACE), TestGui2.class) {
I added a test to one of the items and checked in-game. The glows do work

2017-01-20 00:22 UTC, AshIndigo commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> +     * ItemStack version of tabs
Fixed

2017-02-28 07:43 UTC, randysdoom commented
Any idea as to when/if this will be pulled?

2017-02-28 07:55 UTC, liach commented
@mezz If this is okay, please assign Lex

2017-02-28 07:59 UTC, liach requested changes

2017-02-28 07:59 UTC, liach commented on patches/minecraft/net/minecraft/client/gui/inventory/GuiInventory.java.patch
> ++    @Override
Don't add this

2017-02-28 07:59 UTC, liach commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> + * @author Subaraki, Modified by Ash Indigo
`@author` tags?

2017-02-28 07:59 UTC, liach commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> +        if (GuiTab.tabRegistry.get(clazz).contains(VANILLA_INVENTORY_TAB) == false)
```java
if (!GuiTab.tabRegistry.get(clazz).contains(VANILLA_INVENTORY_TAB))
```

2017-02-28 07:59 UTC, liach commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> +        if (getIconStack() != null)
Use `!isEmpty()` check

2017-02-28 13:01 UTC, AshIndigo commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> + * @author Subaraki, Modified by Ash Indigo
I'll remove them if you want but any reason? Just curious

2017-02-28 13:30 UTC, williewillus commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> + * @author Subaraki, Modified by Ash Indigo
Just convention, it clutters up the code and we can give credit using the commit logs

2017-02-28 14:00 UTC, AshIndigo commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> +        if (GuiTab.tabRegistry.get(clazz).contains(VANILLA_INVENTORY_TAB) == false)
Fixed in the latest commit

2017-02-28 14:00 UTC, AshIndigo commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> +        if (getIconStack() != null)
Fixed

2017-02-28 14:00 UTC, AshIndigo commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> + * @author Subaraki, Modified by Ash Indigo
Alright fixed

2017-04-02 01:32 UTC, Alpvax commented
@mezz Are there any more problems with this?

2017-04-02 01:38 UTC, liach commented on src/main/java/net/minecraftforge/client/player/inventory/tabs/GuiTab.java
> +    private ItemStack iconStack = null;
Set to `ItemStack.EMPTY`

2017-04-02 14:29 UTC, liach approved these changes

2017-05-01 00:35 UTC, mezz commented
Doing some testing, there are some aesthetic and usability issues.
The arrows for additional tabs should go above the GUI and have page numbers like in the creative menu.

![2017-04-30_17 28 53](https://cloud.githubusercontent.com/assets/916092/25569356/b87c238a-2dca-11e7-95cd-66456ceb3072.png)
![2017-04-30_17 30 13](https://cloud.githubusercontent.com/assets/916092/25569357/b892cc3e-2dca-11e7-9911-8f75f2430509.png)

Without page numbers, navigation through the tabs is very confusing.
By adding arrows above the tabs, this means there isn't enough space for bottom tabs on small screen. That case needs to be handled properly, while still showing bottom tabs when there is enough space for them.

Additionally, clicking through tabs sometimes gets into areas where you can't view all the tabs, which doesn't make sense at all.
![2017-04-30_17 31 18](https://cloud.githubusercontent.com/assets/916092/25569367/0edd981c-2dcb-11e7-8c22-1ffa89266af7.png)

I think there is still a bit of work to do on polish and usability before this is ready to merge.

2017-05-01 08:16 UTC, ArtixAllMighty commented
I must dissaprove with the last point that mezz made, it is up to the modder to add 'backward' tabs on gui's where his tabs lead to.

2017-05-01 14:07 UTC, Alpvax commented
@ArtixAllMighty While that is true, how would that handle tabs added by multiple mods?

2017-05-01 15:34 UTC, ArtixAllMighty commented
if multiple mods add a tab to a chest, you can find them there. you wont find the same tabs on your own gui though. Your own gui should however be able to lead back to the chest, from which you can move to other tabs. the Chest being a HUB of many tabs, and each attached tab being a branch to other options, and hopefully back to where it came from.

It's a tree - type system. It's like navigating windows, but having to use 'go back one folder' instead of having a browser tree on the right of your screen. 

It's not the most ergonomic option there is... I know. but I think it's better then no tabs, because it would be the first step towards massively decreasing keybinds needed for opening all those modded gui's added by 150+ mods in certain modpacks, there's only ever so much keys on a keyboard

2017-05-01 18:09 UTC, mezz commented
I recommended a flat tab structure, where the "main" gui tabs are always shown and there is no nesting of tabs.
I think the tree structure is a bit overengineered for this problem, and poses many UI challenges that haven't been addressed.
With a flat structure you can easily navigate and there is no confusion.

2017-05-01 20:39 UTC, ArtixAllMighty commented
the flat structure would be ideal if it was for the player's main inventory only. (which is what it was at the very begining). once you start wanting to add tabs to other gui's it becomes complicated, and a flat structure would be out of place, if i'm not wrong. but I do agree a flat structure is better for navigation

2017-05-01 20:43 UTC, mezz commented
How does it get more complicated? I think as long as you can't add tabs to other tab guis it should be fine.

2017-05-01 20:47 UTC, ArtixAllMighty commented
ah you mean we're not supposed to be able to go from one tab to another to another to another ?
yeah, if you go from main to alt, and then only back, or the main tab decides what the alt's should have as tabs and an alt gui cannot have other tabs.

(this is getting complicated to understand, but i got the drift)

2017-05-01 20:48 UTC, ArtixAllMighty commented
nah nevermind, i reread your flat structure a couple of times and i think i got the point =)

2017-05-02 13:33 UTC, Alpvax commented
Not sure I quite follow the flat structure. If 2 mods add tabs to the chest GUI and you click on one of them, would the other tab show up in this new GUI? Or would you need to return to the chest tab to be able to swap back to the other tab?
How would the following work with the flat structure?

- Mod1 adds a tab to the chest gui which allows you to view the player inventory (i.e. equipment).
- Mod2 adds a tab to the player inventory which allows you to view an additional "backpack"

When the player opens the chest, would all 3 tabs be displayed? Or just chest and player inventory?
When the inventory tab is selected, would all 3 show up? Or would it keep it as just chest and inventory?

In essence, would the tabs be attached to the "open GUI" instance (i.e. the tab list doesn't change until the GUI is closed) or to the individual GUIs?

2017-05-02 15:44 UTC, ArtixAllMighty commented
what we probably need is groups, to regroup tabs with the same interests over all the gui's registered to that group.

2017-05-02 16:41 UTC, Alpvax commented
Alternatively we could create a GuiTabList for the first GUI opened (as this PR does) but then call a setTabList method on any GUI opened from that GUI and pass in the current tab list.
You could then extend it with registered groups (e.g. a "playerinv" group which missed a could add tags to, then you could add the whole playerinv group to a GUI and it would add all the tabs).

2017-05-02 18:44 UTC, HenryLoenwind commented
lol, the original PR hat continuities for exactly this purpose. https://github.com/MinecraftForge/MinecraftForge/pull/3349#issuecomment-259992875

2017-05-02 18:56 UTC, ArtixAllMighty commented
yeah... thats the problem. there's 2 ways to go about this. now we need to find the one that suits 51% iof the people to let it pass ...

2017-05-02 19:04 UTC, Alpvax commented
For the end user's point of view I think it would be better if the tabs didn't change as you navigated through the GUIs. Which would leave us with either showing all the tabs related to any of the GUIs or showing only the tabs directly linked with the first opened GUI. The 2nd option would be the easier implementation.

2017-05-02 23:40 UTC, HenryLoenwind commented
There are a number of tricky cases here.

e.g. GUI M_A gets GUIa M_B and X_39 attached by mod X. Then mod G attached GUI G_9 to M_B and mod H attaches GUIs M_C and H_0 to G_9.

Which tabs will be shown when showing GUI M_A? Which when showing H_0? If the addition was static, one could say "all of them" for both cases. But if some of the attaching is conditional, it gets really tricky...

One solution may really be to keep a list of tabs until the user closes all GUIs. Collect and add all tabs ever show, so it may grow when going to another tab but no tabs would go away.

Another solution would be to only allow special tab-GUIs to be attached which cannot have other tabs attached to them. Then the tab list would stay static while tabbing through.

2017-05-02 23:52 UTC, mezz commented
I think people do not immediately understand what I mean by flat tabs so I should clarify. The best example we have already for flat tabs is the vanilla creative menu. Mods can add one or more tabs there, and navigation is very easy. You click a tab and it comes to the front, and the tabs never change no matter what page you're looking at. It only gets unwieldy when there are way too many tabs, but I don't think there will be as many tabs added to GUIs using this new system as there are creative tabs.

2017-05-03 02:48 UTC, Alpvax commented
@mezz the creative tabs are significantly simpler as (with the exception of the inventory tab) they don't change the GUI, just the items displayed, whereas these tabs will completely change the GUI being displayed. They are also a global list. So somehow we need to persist the tab list across multiple GUIs.

What determines whether or not something is a "main" screen? Is it just the first one opened? Which "additional tabs" should be added? Just those that are linked to the main screen or should it chain through all the tab GUIs and add their tabs to the list as well?

2017-05-03 02:57 UTC, mezz commented
The creative tabs are simpler, but we should aim to mimic that simplicity from a player point of view.

A "main" screen is one you open initially, before changing any tabs. 
Additional tabs are whatever gets added by mods to the "main" screen.

2017-05-03 02:59 UTC, Alpvax commented
Thinking about simplifying implementation, would it not be easier to have the tabList linked to the player?

When the player opens a GUI from being in-game, the tab list is created from that first GUI. The player can then swap tabs freely without having to worry about persisting the list across multiple GUIs, and when the GUI is exited (back to in-game) the list is set to null.

2017-05-03 09:33 UTC, ArtixAllMighty commented
mezz is more right then any of you i.m.o

it's the player's point of view we need to aim to, and 'static' tabs around one 'main' gui is what we need. per gui.

just like. 

fancy example : baubles inventory, spacecraft and rpg inventory. 
these could all 3 register to the player inventory. this gives 4 tabs. player, baubles, spacecraft nad rpginventory tabs.
these 4 need to be registered to a list that will not change their position.
openign either 4 of these gui's will show all 4 tabs, always in the same order.

the same would go for a block that would be placed on top of a furnace to work. 
2 tabs : furnace + mod block. both have 2 tabs. if someone else would add a block with the same properties, there woudl be 3 tabs, but one of them you wouldn't be able to go to (because the mod block is missing) > note : this check needs to be implemented by the author offcourse, to prevent a crash if said block is absent

2017-05-03 10:23 UTC, Alpvax commented
Yes, I understand that part of it, the only part I want clarification on is what happens when one mod adds a player inventory tab to the chest. Would the baubles, spacecraft and rpginventory tabs also be added to the chest?

And my comment about attaching the list to the player was just a way of making it easier to implement:

1. Player opens GUI
2. GUI provides a list of available tabs (Probably allowing a check to see if each tab is in fact valid at this time)
3. List of tabs is saved to the player
4. Player changes tab, list still attached to the player, but the selected index is updated to render the tab correctly (GUIs retrieve the tab list from the player in order to render it)
5. Player exits GUI and the tab list is set to null, ready for next time.

It would remove the need to pass tab instances between GUIs.

2017-05-03 21:18 UTC, mezz commented
>what happens when one mod adds a player inventory tab to the chest. Would the baubles, spacecraft and rpginventory tabs also be added to the chest?

First this is a strange scenario, you should probably not add a player inventory tab to the chest gui.
However in that case, the player inventory tab would not be treated specially because the chest gui is the main gui. Extra tabs would only be added for the chest. Baubles, spacecraft, and rpginventory tabs which are normally applied to the player inventory would not be added to the chest tabs.

2017-05-03 22:06 UTC, Alpvax commented
Strange but not unreasonable to think that a mod would add access to your equipment from anywhere, and I tried to pick an edge case. That solution seems good to me though.

2017-05-04 11:05 UTC, Alpvax commented
I do also quite like the groups approach, for example an "equipment" group could be created, then things like baubles, tinkers etc. could be added to the group, and the group could then be added to another GUI from another mod.

2017-05-21 05:22 UTC, mezz commented
@AshIndigo are you able to update this PR?

2017-07-03 17:55 UTC, mezz commented
Please update this PR to target 1.12.
What is the status on this PR, is it complete and ready for review again?

2017-07-05 08:19 UTC, pWn3d1337 commented
It would totally like to have this in 1.12 soon before I have to make my own implementation. Please update this.

2017-07-30 06:48 UTC, mezz commented
@AshIndigo any response?

2017-09-13 03:48 UTC, mezz commented
Close this, it has been updated here: #4389

2017-09-13 03:48 UTC, closed without merging