Patch ChunkCache.getTileEntity for thread safety
MinecraftForge/MinecraftForge pull request #3643
Opened 2017-01-19 12:47 UTC by bs2609

See [this](https://github.com/MinecraftForge/Documentation/pull/81) docs PR for details.

This changes `ChunkCache#getTileEntity` to pass `QUEUED` instead of `IMMEDIATE` as the type.
Missing tile entities will be added to a (concurrent) queue and created during the chunk's next update tick.

This will cause the method to return `null` if there is tile entity at the position queried, but the function is annotated `@Nullable`, and currently has a chance of just throwing a `ConcurrentModificationException` anyway, so there shouldn't be any working mods broken by this change.

2017-01-19 13:23 UTC, AEnterprise commented
won't this cause rendering issues? if the TE is missing and the first thing that asks for it is part of the block rendering then the block might not be rendered correctly

2017-01-19 14:29 UTC, diesieben07 commented
It definitely won't for vanilla. Vanilla special-cases this and manually passes in QUEUED if there is a ChunkCache, working around this bug.

2017-01-19 15:52 UTC, bs2609 commented
@AEnterprise, anything in the situation you describe is at risk of simply crashing at present. As far as I can see, when the queued tile entity is loaded, it will cause a block update so the chunk will get rerendered correctly pretty fast.

2017-01-19 15:56 UTC, bs2609 commented
Also, pinging @williewillus

2017-01-19 18:33 UTC, williewillus commented
This is not how vanilla does it; vanilla uses `CHECK`.

2017-01-19 19:14 UTC, AEnterprise commented
i'm thinking maybe make that list threadsafe instead? that way no behaviour changes at all while also preventing that crash

2017-01-19 19:23 UTC, diesieben07 commented
Thread safety always comes at a cost. Making all TileEntity accesses go through a threadsafe collection sounds like a bad idea to me, with how many TileEntities are used in mods and how that already impacts performance.

2017-01-19 21:12 UTC, mezz commented
I agree with willie, we should spend some time to consider `CHECK` instead.
What are the cases where you are given a `ChunkCache`? As far as I know, you shouldn't be creating new tile entities in those cases at all. If someone can create a list of cases where `ChunkCache` is used, we can make a decision on `CHECK` vs `QUEUED`.

2017-01-19 21:41 UTC, williewillus commented
In the original case I highlighted in RTD, ChunkCache is occasionally passed to `getActualState` and `getExtendedState`. It's the object that the multithreaded chunk rebuild threads use to access the world instead of accessing `World` itself.

only other thing it's used for is pathfinding, which doesn't care about TE's

2017-01-19 22:27 UTC, mezz commented
Yeah, none of those cases has any business creating new tile entities. It seems `CHECK` is the way to go.

2017-01-19 22:29 UTC, mezz requested changes

2017-01-19 22:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/ChunkCache.java.patch
> ++        return this.func_190300_a(p_175625_1_, Chunk.EnumCreateEntityType.QUEUED); // Forge: don't modify world from other threads
Please use `CHECK`

2017-01-19 22:33 UTC, bs2609 commented on patches/minecraft/net/minecraft/world/ChunkCache.java.patch
> ++        return this.func_190300_a(p_175625_1_, Chunk.EnumCreateEntityType.QUEUED); // Forge: don't modify world from other threads
Ok, just as long as you're sure [this](https://github.com/MinecraftForge/MinecraftForge/pull/3563#issuecomment-269074986) doesn't apply

2017-01-19 22:40 UTC, mezz commented on patches/minecraft/net/minecraft/world/ChunkCache.java.patch
> ++        return this.func_190300_a(p_175625_1_, Chunk.EnumCreateEntityType.QUEUED); // Forge: don't modify world from other threads
Creating a new tile entity from `getActualState` and other methods that get `ChunkCache` will most likely break things, even if it is not causing a CME.
I think this is a safe fix.

2017-01-19 23:07 UTC, bs2609 commented on patches/minecraft/net/minecraft/world/ChunkCache.java.patch
> ++        return this.func_190300_a(p_175625_1_, Chunk.EnumCreateEntityType.QUEUED); // Forge: don't modify world from other threads
Done. #blamemezz if there's any issues

2017-01-19 23:34 UTC, mezz approved these changes

2017-01-20 08:48 UTC, HenryLoenwind commented
BTW, not getting a TileEntity in the render thread is harmless. What would the block render anyway? The TileEntity would be only initialized with its default data, all the real data from the server version of the TileEntity would be missing.

I'd even go one step farther and say that the only thing on the CLIENT side that should create TileEntities is the network package with their data in it. (Or block placing code that knows how to fill it with correct data before the server data arrives.)

2017-02-24 01:12 UTC, LexManos commented
For note, this can cause errors, but in cases where it could cause errors anyways.. so ya...

2017-02-24 01:12 UTC, merged