[1.11.2] Added support for Village capabilities
MinecraftForge/MinecraftForge pull request #3648
Opened 2017-01-21 02:03 UTC by Madsthunder

This PR adds the fields and methods required for Capabilities into the Village class, similar to Entity, TileEntity, ItemStack, and World.

2017-01-21 02:05 UTC, shadowfacts commented
Why is this necessary/useful?

2017-01-21 02:12 UTC, mezz commented
I also think this seems very strange. What are the village capabilities used for?

2017-01-21 02:15 UTC, Madsthunder commented
@shadowfacts This is useful because it allows a modder to store extra data about a village. For example, if a modder needs a unique identifier for a village they can do so by creating a capability that serializes/deserializes a UUID. This would remove the need for modders to try to determine which village a villager is from by assuming from NBT, because the village would have a unique identifier.

2017-01-21 02:18 UTC, Madsthunder commented
@mezz The village capabilities could be used for multiple things, like if a modder wanted to add economy into the game, the village could represent a nation,, the modder could then add a capability called Wealth or something along those lines  and assign it to the appropriate Village.

2017-01-21 02:22 UTC, mezz requested changes

2017-01-21 02:22 UTC, mezz commented on patches/minecraft/net/minecraft/village/Village.java.patch
> ++
please remove extra newline here

2017-01-21 02:22 UTC, mezz commented on patches/minecraft/net/minecraft/village/Village.java.patch
> ++        this(null);
This seems slightly questionable? May be better to just set the capabilities here too. I'm open to other opinions though.

2017-01-21 02:22 UTC, mezz commented on patches/minecraft/net/minecraft/village/Village.java.patch
> ++
Could use a 
`/* ======================================== FORGE START =====================================*/`
section for good measure

2017-01-21 02:30 UTC, Madsthunder commented
Changed the constructor call to Village(World) in Village() to a gatherCapabilites call, removed the extra line at the end of writeVillageToNBT and added a Forge Start/End surrounding the new methods.

2017-01-21 02:31 UTC, mezz approved these changes

2017-01-21 02:35 UTC, mezz commented
Can you make a small forge debug mod that uses this capability, to ensure it is working as intended and nothing else is needed?
There are several in `net.minecraftforge.debug`, if you need any help getting set up there is a [tutorial video here](https://www.youtube.com/watch?v=pLWQk6ed56Q).

2017-01-21 02:42 UTC, Madsthunder commented
@mezz Would you mind if I integrated it into the existing TestCapabilityMod?

2017-01-21 02:43 UTC, mezz commented
Sure, as long as it's not interacting with the existing stuff there it should be fine.

2017-01-21 09:39 UTC, LatvianModder commented
Forge should figure out a way to store unique IDs for - Worlds/dimensions, villages and the server...

2017-01-21 17:05 UTC, Madsthunder commented
@mezz Fixed the AttachCapabilitiesEvent not firing correctly and added Villages to the TestCapabilityMod

2017-01-22 23:46 UTC, rguy96 commented
@mezz Any idea when the next batch of PRs are being pulled?

2017-01-22 23:48 UTC, mezz commented
@rguy96 Probably after PAX South, so in February.

2017-01-23 00:06 UTC, LexManos commented
between moving, and PAX, I'm tied up till the 3rd. Also this one needs to be looked into quite a but. I'm not a particular fan of just sticking caps on every possible thing. I do think this needs a few more concrete explained if its use case.

2017-03-12 06:28 UTC, mezz commented
@Madsthunder can you address Lex's comment by giving a few more concrete examples of uses for this event?

2017-03-13 02:03 UTC, Madsthunder commented
Other than the examples above, I can't really think of any off the top of my head, and the use cases I have for it are a bit too complex to put into one comment...

2017-05-01 01:00 UTC, mezz commented
@Madsthunder can you update this to resolve conflicts?

I think this is a good way to attach extra data to villages, which is not simple to do otherwise.
I'm not exactly sure capabilities are the perfect fit because I can't easily imagine how mods would share the capabilities. However it's not a very invasive patch and the implementation is simple.
I think it's up to Lex to look into this a bit more when he has more time to explain.

2017-05-01 04:20 UTC, mezz requested changes

2017-05-01 04:20 UTC, mezz commented on src/test/java/net/minecraftforge/test/TestCapabilityMod.java
> +                    for(EntityPlayer player : players)
this `for` loop needs braces

2017-05-01 04:20 UTC, mezz commented on patches/minecraft/net/minecraft/village/Village.java.patch
> ++        if (getCapability(capability, facing) != null)
`hasCapability` is meant to be a faster cheaper check than `getCapability` so it should not call `getCapability`.

2017-05-01 04:57 UTC, LexManos commented on patches/minecraft/net/minecraft/village/Village.java.patch
> ++    public int getPlayerReputation(UUID playerName)
Dunno how you messed this up, but fix it.

2017-05-21 05:24 UTC, mezz approved these changes

2017-05-26 20:51 UTC, merged