Added the TextureStitchEvent.Collected event.
MinecraftForge/MinecraftForge pull request #3660
Opened 2017-01-26 16:38 UTC by OrionDevelopment

When @liach moved the TextureStitchEvent.Pre call to before the collection of the TextureAtlasSprites of Items and Blocks, in PR #3436, he made it also impossible to register additional Textures that are based on already registered TextureAtlasSprites.

A good example are the materialized greyscale textures of TinkersConstruct or my mod called Armory.

This PR creates a new TextureStitchEvent.Collected that is mend to be fired after the TextureAtlasSprites of the Blocks and Items have been collected the normal way, but before the Stitch actually happens. This makes it possible to register textures based on already registered Textures, before the Stitch happens.

I added a method to ForgeHooksClient to minimalize the changes to the patch in TextureMap,java and added the call to that method on the location of old call to ForgeHooksClient.onTextureStitchPre.

2017-01-26 16:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3660) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3660) before we can accept your contribution.<br/>

2017-01-27 04:26 UTC, liach requested changes

2017-01-27 04:26 UTC, liach commented on src/main/java/net/minecraftforge/client/event/TextureStitchEvent.java
> +        public Collected(TextureMap map){ super(map); }
Code style

2017-01-27 04:26 UTC, liach commented
> A good example are the materialized greyscale textures of TinkersConstruct, currently maintained by @bonii-xx, or my mod called Armory.

Can you give a link to the code?

2017-01-27 09:47 UTC, OrionDevelopment commented on src/main/java/net/minecraftforge/client/event/TextureStitchEvent.java
> +        public Collected(TextureMap map){ super(map); }
What is wrong here? The formatting is the same in the other Events.

2017-01-27 09:48 UTC, OrionDevelopment commented
Yeah i am working on a better explanation. Give me a couple of hours.

2017-01-27 10:50 UTC, liach commented on src/main/java/net/minecraftforge/client/event/TextureStitchEvent.java
> +        public Collected(TextureMap map){ super(map); }
Well, yes, all the events are improperly formatted. You can ignore this point, indeed.

2017-01-27 10:54 UTC, liach commented
I still wonder how you use these sprites without references in jsons. That was why I moved this event.

2017-01-27 15:30 UTC, OrionDevelopment commented
The principal system here works in combination with an API and a custom ModelLoader.
The API holds reference to all possible combination that can be made on the Armor in other words:
 - Which materials can be made into the given Base Armor.
 - Which upgrades can be put onto this armor and out of which Materials are they made.

The ModelLoader then loads a JSON which reflects these informations. It holds a base texture for the base Armor, in greyscale, and textures for each upgrade, also in greyscale. (Using events during the loading model somebody who is registering additional upgrades for a model can also provide the greyscale textures for that upgrade during loading.) It then returns a unbaked model that has those greyscale textures as its textures.

Before the change those greyscale textures where registered to the Stitcher and I could grab them during the Pre event. Materialize them, so for example color them in a metal color or overlay them with an existing texture of say a wooden bark for a wooden material, and then register those materialized textures to the map so that they would be stitched in properly.

The fact that the baking of the models happens after the textures are loaded allows me to grab the materialized textures during bake and create a new copied model that is retextured with the correct materialized texture during the baking process and store them in a collected list. When handleItemState is called, using the data stored on the stack it will then grab first the correctly textured basemodels quad for the base armor, and then if applicable the quads of all the correctly materialized models of the upgrades and combines them to that it generates one flattened model.

Now that the TextureStitchEvent.Pre is moved to before the collection of the Textures from the Models. It is impossible to grab the greyscale textures that it needs to generate the materialized ones that depend on those. That is the reason why i added the collected event phase into the TextureStitch. At this point the greyscale textures are collected and i can grab them and then retexture those like i did with the Pre event before it was moved.

Greets, Orion

My implementation:
 * Loader: https://github.com/SmithsGaming/Armory/blob/Development-1.10.2/src/main/com/smithsmodding/armory/client/model/loaders/MultiLayeredArmorModelLoader.java
 * UnbakedModel: https://github.com/SmithsGaming/Armory/blob/Development-1.10.2/src/main/com/smithsmodding/armory/client/model/item/unbaked/MultiLayeredArmorItemModel.java
      * UnbakedComponentModel: https://github.com/SmithsGaming/Armory/blob/Development-1.10.2/src/main/com/smithsmodding/armory/client/model/item/unbaked/components/ArmorCoreComponentModel.java
 * BakedModel: https://github.com/SmithsGaming/Armory/blob/Development-1.10.2/src/main/com/smithsmodding/armory/client/model/item/baked/BakedMultiLayeredArmorItemModel.java
      * UnbakedComponentModel: https://github.com/SmithsGaming/Armory/blob/Development-1.10.2/src/main/com/smithsmodding/armory/client/model/item/baked/components/BakedCoreComponentModel.java

2017-01-27 17:09 UTC, liach approved these changes

2017-01-28 15:48 UTC, Madsthunder approved these changes

2017-02-05 19:09 UTC, OrionDevelopment commented
Should I add a Test Mod for this?

2017-02-05 19:11 UTC, liach commented
Absolutely!

2017-03-16 19:47 UTC, OrionDevelopment commented
I added a test mod and pulled in the latest changes.
Examples of what the test mod does:

![image](https://cloud.githubusercontent.com/assets/5585406/24015714/87a893b0-0a89-11e7-9edb-6839a4626c14.png)

And:

![image](https://cloud.githubusercontent.com/assets/5585406/24015762/ae3755f2-0a89-11e7-83dd-662dd97e880b.png)

2017-03-16 19:47 UTC, OrionDevelopment commented
@liach @RainWarrior Should be good to go.

2017-03-16 19:53 UTC, liach commented
looks great. Just waiting for fry then.

2017-03-18 00:13 UTC, Madsthunder commented
@mezz Any idea when the next round of prs will be pulled?

2017-04-21 16:03 UTC, OrionDevelopment commented
Hello, is there any news on this?

2017-05-01 08:31 UTC, mezz commented
Looks good but I think the test mod is not working as intended.
From the TextureDump output, I just see a square outline instead of the Book and Pickaxe.
![texture_atlas_dump_textures_mipmap_0](https://cloud.githubusercontent.com/assets/916092/25575631/f3e0fe62-2e0d-11e7-8f41-9da49cce6252.png)

2017-05-01 09:24 UTC, OrionDevelopment commented
Hmm The pictures above were taken from the texture dump generated by the same test mod
Let me Check what is going on. I will update the formatting as well.

2017-05-01 09:58 UTC, OrionDevelopment commented
I ran the tests again, and i am getting the same result as above.
I am trying to figure out what is happening.

2017-05-01 10:13 UTC, OrionDevelopment commented
@mezz How are you running the test?

2017-05-01 15:44 UTC, liach commented
Eh, the test look extremely complex to me.

2017-05-01 17:17 UTC, OrionDevelopment commented
@liach it finds the edge of a texture by iterating over all its pixels.
It is not that complicated.

2017-05-01 18:11 UTC, mezz commented
I use IntelliJ to run the test mods within the Forge dev environment.
Here's a video on how to set it up: https://www.youtube.com/watch?v=pLWQk6ed56Q

The trick is to build the Tests project so it creates all the classes, and then set the classes folder as a runtime dependency for the Main project. 

![](http://i.imgur.com/VZj5zPC.png)

That way the test will be run when you run the main project, and to update them you just have to build the Test project.

2017-05-01 18:12 UTC, OrionDevelopment commented
Ah okey
I will give that a try, i usually create a dummy copy in the main module.

2017-05-01 18:45 UTC, mezz commented
I pulled the changes and it works now.
In the diff it looks like you replaced the two calls to `getAtlasSprite` with `getTextureExtry`.

2017-05-01 18:52 UTC, mezz commented
Tested and looks good.

**TLDR** for Lex (sorry Orion but you are extremely verbose!):
This event allows mods to create textures based on other textures in the atlas.
The example mod takes the book and pickaxe texture and creates a new texture that's just their outline.
![](https://cloud.githubusercontent.com/assets/5585406/24015762/ae3755f2-0a89-11e7-83dd-662dd97e880b.png)

2017-05-01 19:14 UTC, RainWarrior commented
What happens if someone wants to depend on one of the textures added in this event? In the [example](https://github.com/SmithsGaming/SmithsCore/blob/Development-1.11/src/com/smithsmodding/smithscore/client/textures/TextureCreator.java#L93), you're using EventPriority.LOWEST, which, from my understanding, means that nothing else will ba able to run after you. Wouldn't a system with an explicit dependencies be better? An event solution like this doesn't actually solve the problem of texture dependencies, it postpones it. Unless I've missed something :)

2017-05-01 19:29 UTC, mezz commented
What you linked to is not the example used in this PR.

2017-05-01 20:02 UTC, OrionDevelopment commented
@Mezz what do you mean?

2017-05-01 20:41 UTC, mezz commented
Fry was looking at the old implementation and not the one in the PR. I talked to him on IRC and his argument still stands.

2017-05-01 22:27 UTC, OrionDevelopment commented
@mezz @RainWarrior I changed it. I tested my test mod again and this works in both cases.
Also to display that event works for textures that depend on a other texture i added log output that shows you that the events gets fired properly for textures i register while i am in the event handler.

2017-05-29 16:45 UTC, tterrag1098 commented
@OrionDevelopment Thank you for this, the earlier PR breaks my json system as well, since I need to parse texture metadata for additional textures to stitch. So one more 👍 from me.

2017-05-29 17:12 UTC, OhCreative commented
@OrionDevelopment I love this, the previous PR by liach messed up my systems as well. so a :+1: from me

2017-05-29 17:25 UTC, liach commented
To all of you @tterrag1098 @OhCreative, if I added one event back then (mezz actually suggested to mess this up, see comments) things would be fine!

2017-05-29 17:28 UTC, tterrag1098 commented
@liach I think these two PRs should have happened at once, there is good reason to have both phases, but clearly there are issues (which this PR solves) with texture dependencies.

2017-05-29 18:39 UTC, OrionDevelopment commented
Sadly enough I am still waiting on it.

2017-05-29 18:42 UTC, OrionDevelopment commented
@liach Things like this can happen, no way you could have for seen somebody actually using it to make texture dependencies. If this gets pulled then it is all forgiven and forgotten :D

2017-05-29 18:48 UTC, liach commented
Waiting for fry. He seems to be away.

2017-07-03 17:56 UTC, mezz commented
#4070 has been accepted and merged, any further improvements are welcome. 
I think it means that this PR can be closed, is that right?

2017-07-03 18:59 UTC, OrionDevelopment commented
Yes i think so.

2017-07-03 18:59 UTC, closed without merging