Show the EULA message early
MinecraftForge/MinecraftForge pull request #3661
Opened 2017-01-26 21:30 UTC by ichttt

This fixes #3659.
It also adds a small GUI message if the server gui is enabled.
![eula](https://cloud.githubusercontent.com/assets/20151702/22351129/d6a415e6-e416-11e6-8b71-fae5f760a9bf.JPG)
I thought it would be usefull and may prevent some bug reports, but I'm open for feedback.

2017-01-26 21:34 UTC, kashike commented on src/main/java/net/minecraftforge/fml/server/FMLServerHandler.java
> +        ServerEula eula = new ServerEula(new File("eula.txt"));
If you're going to move this here it might be a good idea to disable the same code in `DedicatedServer`.

2017-01-27 04:29 UTC, liach requested changes

2017-01-27 04:29 UTC, liach commented on patches/minecraft/net/minecraft/server/gui/MinecraftServerGui.java.patch
> ++    private static JFrame jframe;
This field should be moved to forge classes to reduce patch size.

2017-01-27 04:29 UTC, liach commented on src/main/java/net/minecraftforge/fml/server/FMLServerHandler.java
> +import javax.swing.*;
Star imports are discouraged.

2017-01-27 04:29 UTC, liach commented on src/main/java/net/minecraftforge/fml/server/FMLServerHandler.java
> +                JOptionPane.showMessageDialog(MinecraftServerGui.getJFrame(), "You need to agree to the EULA in order to run the server. Go to eula.txt for more info.", "Cannot continue loading", JOp
If there is a GUI, you can let users accept EULA via it.

2017-01-27 06:11 UTC, ichttt commented on src/main/java/net/minecraftforge/fml/server/FMLServerHandler.java
> +        ServerEula eula = new ServerEula(new File("eula.txt"));
I don't think so as this would create unnecessary patches, and it should not have any impact

2017-01-27 06:26 UTC, liach commented on src/main/java/net/minecraftforge/fml/server/FMLServerHandler.java
> +        ServerEula eula = new ServerEula(new File("eula.txt"));
For performance reasons, you should do that.

2017-01-27 06:29 UTC, LexManos commented
Honestly dislike touching anything to do with the EULA stuff without express permission from Mojang.
Also don't like adding a popup like that its tacky and really annoying. Also brings us to issues of invalidating the EULA by making it click-through which is a major issue. As the logical extension of this is 'heres a pr to make the eula.txt true when you click ok!' which would just cause pain/annoynace because i'd have to explain multiple times why we will NEVER DO THAT.

2017-01-27 06:29 UTC, closed without merging

2017-01-27 21:36 UTC, starg09 commented
@LexManos Being who suggested the movement of the EULA check to the preinit, I just wanna clarify that I didn't suggest neither the popup, nor a "Click to mark the eula as true". Only request was for the check to happen at a reasonable moment, before preloading every single mod (which can save quite a few minutes depending on the device where the server is installed).

However, I understand you not wanting to touch that stuff without permission from Mojang. If I contacted them and got a written reply from allowing it, would you consider placing the check earlier on?

2017-01-28 05:32 UTC, valentin616 commented
If you can contact them it is better to ask them to do it earlier in the vanilla Minecraft