Added a MiddleClick event
MinecraftForge/MinecraftForge pull request #3668
Opened 2017-01-28 15:04 UTC by canitzp

Like the title says, this pr adds a event if the middle mouse button gets pressed.
It is triggered on the client side only, but the result can be modified so that it gets send to the server.
There are two stages, so in the first one the event can be canceled to prevent the analyzing of the RayTraceResult and the second stage is for modifying the result ItemStack.

2017-01-28 15:10 UTC, shadowfacts commented
I like this idea, but I don't think `MiddleClick` is a good name for it. I'd suggest something like `Pick` or `PickBlock` instead.

2017-01-28 15:13 UTC, canitzp commented
A good point, but I think Pick says nothing about it and PickBlock is not correct, cause it works at entities too.

2017-01-28 15:19 UTC, shadowfacts commented
Well pick is the terminology used everywhere else in Minecraft (and MCP) for middle-clicking blocks/entities.

2017-01-28 15:22 UTC, canitzp commented
You're right and I changed it

2017-01-28 20:44 UTC, diesieben07 commented
Why does this need Pre and Post? One cancelable event fired from the current place for Post should be enough. And the current implementation does not let you change the pick-result for AIR.

2017-01-28 20:49 UTC, canitzp commented
The Pre is to prevent the analyzing of the RayTraceResult, for the case that it is enough for you to cancel the event, otherwise you need the post logic, per example if you want to change the result stack and don't want to simple cancel it.
If you mean with your second point that I only gets fired if you middle click on a block or entity, yes I know, but I see no use for middle click into the air or fluids, since there happens nothing anyway

2017-01-28 20:53 UTC, diesieben07 commented
I see why you would want to separate it if the "post logic" as you call it (the stuff between the current Pre and Post) was like super complex and expensive to run. But it isn't, especially because this only runs when you do a pick-block, which is not very often (compared to other things).

> but I see no use for middle click into the air or fluids, since there happens nothing anyway

So nobody is allowed to add something there?

2017-01-28 20:55 UTC, canitzp commented
I can not get the middle click if it is type MISS, in this case the whole method where my event is fired doesn't get called.
Okay I look into my code and only fire one event instead of Pre and Post

2017-01-28 21:07 UTC, canitzp commented
@diesieben07 I collapsed the two events now, but I can't change the AIR click detection, without creating a bigger pr

2017-01-28 21:08 UTC, diesieben07 approved these changes

2017-01-28 21:43 UTC, williewillus requested changes
Your brace formatting is off:
should be `if (foo) { bar; }`, not `if (foo){ bar; }` (missing space)

2017-01-28 21:43 UTC, williewillus commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +     * There is no update packet for it, you have to send your own when needed.
make the wording of this match LeftClickEmpty

2017-01-28 21:43 UTC, williewillus commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +     * Cancel the event if you want that nothing happens.
I don't understand the difference between "prevent further updating" and canceling the event.

2017-01-28 21:43 UTC, williewillus commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +         * @return The same RayTraceResult as {@link net.minecraft.client.Minecraft#objectMouseOver}
this isn't informative. I'd say
`@return The RayTraceResult representing the object the cursor is over`

2017-01-28 21:43 UTC, williewillus commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +         * @return The current analyzed result for the RayTraceResult
drop the word "analyzed" (or drop the javadoc entirely as it should be self explanatory)

2017-01-28 21:52 UTC, liach requested changes

2017-01-28 21:52 UTC, liach commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +
👎

2017-01-28 21:52 UTC, liach commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +        if(pickEvent.isCanceled()) {
According to Forge code style, this should be
```java
if (pickEvent.isCanceled()) {
```

2017-01-28 21:52 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +        public Pick(EntityPlayer player, RayTraceResult target, ItemStack currentResult) {
Left brace `{` should be on a new line. Same for all methods below.
```java
public Pick(EntityPlayer player, RayTraceResult target, ItemStack currentResult)
{
```

2017-01-28 22:06 UTC, liach approved these changes

2017-01-31 22:24 UTC, canitzp commented
@williewillus Can you take a look at my last chages and request changes or approve it, so that everybody has accepted it?

2017-01-31 22:35 UTC, williewillus commented
could we make canceling the event just set the result to `ItemStack.EMPTY`? 

That way the vanilla logic will catch it to return false and we don't need to patch in the `if (canceled) return false`

2017-01-31 22:37 UTC, williewillus commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +     * The server is not aware of when the client left clicks empty space, you will need to tell the server yourself.
`empty space` -> `block/entity`

2017-01-31 22:38 UTC, williewillus commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +     * You can change the Result ItemStack here or set it to {@link ItemStack#EMPTY} or cancel the event to prevent further updating.
`prevent further processing` -> `return nothing from the pick` (or something similar)

2017-01-31 22:39 UTC, williewillus commented on src/test/java/net/minecraftforge/test/PlayerInteractEventTest.java
> +    public void middleClickPre(PlayerInteractEvent.Pick evt)
`middleClickPre` -> `pick`

2017-02-02 00:10 UTC, mezz commented
Looks good but can you explain the use of this event? 
What do you need it for, and what ideas do you have that require it?

2017-02-02 01:11 UTC, williewillus approved these changes
looks good to me now

2017-02-02 08:37 UTC, canitzp commented
I need this so I can return a custom item block when middle click on a tile entity(with custom nbt), no matter if Vanilla or modded, but only. My only use is for creative mode and not applicable to survival at this time.

2017-02-02 08:54 UTC, mezz commented
You can do that for your own blocks by overriding `net.minecraft.block.Block#getPickBlock` without an event.

2017-02-02 08:57 UTC, canitzp commented
you said correctly 'at your own' but I want to do this for vanilla and blocks from other mods too

2017-02-02 08:58 UTC, mezz commented
I think that sounds questionable, so I'm asking what you have in mind. Can you explain more fully?

2017-02-02 10:03 UTC, canitzp commented
I want to add the funktion that if you pick per example a furnace, instead of receiving the block without nbt, you get it with all the nbt currently available (burntime, inventory,...)
There are other options for triggering it, but I think this is the best way to do it

2017-02-02 10:05 UTC, mezz commented
Ok, that makes sense. Thank you for clarifying.

2017-02-02 10:08 UTC, mezz requested changes
Please annotate every `ItemStack` field, parameter, and return value in `Pick` as `@Nonnull` so that it follows the convention and helps people use it correctly.

2017-02-02 12:40 UTC, KnightMiner commented
Your specific example is a vanilla feature, ctrl pick block copies NBT. But i can imagine this being useful for a vanilla block that does not add the feature, or for a mod added feature.

2017-02-02 21:48 UTC, canitzp commented
@mezz Added the annotations

2017-02-02 21:48 UTC, mezz approved these changes

2017-02-02 23:31 UTC, mezz commented
Looks good, tested and it works correctly.

2017-02-07 08:26 UTC, killjoy1221 commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +        public ItemStack getCurrentResult()
`setStack` may be a better name.

2017-02-07 09:22 UTC, kashike commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +        public ItemStack getCurrentResult()
I assume you meant `getStack` here, and `setStack` for the below method. :+1:

2017-02-08 08:34 UTC, canitzp commented
What do you say @mezz to the name changes? I would prefer that if I change them, I name them getResultStack and setResultStack

2017-02-08 08:36 UTC, mezz commented
I think `getResultStack` and `setResultStack` are more clear than the current names.

2017-02-08 08:51 UTC, killjoy1221 commented
Does the event need to extend `PlayerInteractEvent`? It's not really an interaction. It's also only called on the client afaik.

2017-02-08 08:53 UTC, canitzp commented
Since the left click into empty is also their, it has to be there.

2017-02-08 08:56 UTC, canitzp commented
And it only get called if a player middle clicks a entity or block -> a interaction

2017-02-08 09:07 UTC, killjoy1221 commented
I know how the pick block works. I just wasn't sure what else may call that method (nothing else does). I'm saying you should demote the superclass to `PlayerEvent`. It will make the constructor a lot cleaner since you only need to use the player argument (which is always `Minecraft.player` btw.) All the information is provided via the raytraceresult.

Also, I suggest renaming its getter to `getTarget()` since that's what you named the field.

2017-02-08 17:04 UTC, williewillus commented
No, we can't rename methods in PlayerInteractEvent. that will break every single mod using it with the current names. 

if we are subclassing PlayerInteractEvent, the stack passed to the superclass should just be the one the player is holding in their main hand, but I suggest not subclassing PIE and just put it separately.

2017-02-08 17:08 UTC, canitzp commented
@williewillus I only renamed the methods related to my pr and I don't pass a ItemStack to PIE, I save them in a seperated variable

2017-02-08 17:11 UTC, williewillus commented
yes, I am saying even renaming those methods will break everybody's code.

just don't subclass PIE

2017-02-08 17:12 UTC, williewillus commented
I still don't think you should subclass PIE though

2017-02-08 17:13 UTC, canitzp commented
In my eyes that a player clicks a button on a Block or Entity, he interacts with it and so I decided to subclass PIE instead of a other one.
@mezz what do you say about this

2017-02-08 17:46 UTC, williewillus commented
I'd prefer it to be separate, but it's fine like this too :P

2017-02-08 19:26 UTC, killjoy1221 commented
To me, pick block is *not* an interaction. It doesn't change the world nor is it required to inform the server. It only changes your hotbar and tells the server what item you just picked in creative.

Extending `PlayerEvent` is enough, and everything needed can be gotten from the `RayTraceResult`.

2017-02-08 19:35 UTC, canitzp commented
Left click empty one subclass above mine is also a client only event, but it is a PIE. Why? Cause the player does interact with a thing (or in this case with nothing->air/fluids) and my pick event is the same thing, with another trigger (if it is a block or entity) and another mouse button. Why should this be not a PIE?

2017-02-08 19:43 UTC, killjoy1221 commented
That event is still an interaction because the player is "interacting" with air. It's just not a vanilla interaction.

2017-02-08 19:44 UTC, canitzp commented
And with middle click the player interact with things too. Only cause the player isn't using it as often as the left or right click  interaction it is still one.

2017-02-08 20:06 UTC, gigaherz commented
My opinion on this is divided. On one side "picking a block" sounds a lot like an interaction, but it doesn't actually change the world the world per se:

- It does not activate (run code on) an item
- It does not activate a block
- It does not activate an entity

What it does is just say "I the hotbar slot is now using this item", which happens to be selected based on the thing you have in your crosshairs. Which could be argued to be a type of interaction....

2017-02-08 20:11 UTC, canitzp commented
It is possible to let run things with it, after this pr and you can set the stack that get send to the server and change if, after the interaction.
This definition I found online "the action or influence of things on one another", in my mind this sounds like as soon as the player do a thing like click on a other thing, it's an interaction, no matter if server or client side or if it trigger anything

2017-02-08 20:12 UTC, killjoy1221 commented
I think this would be more of an observation. Nothing is being changed or messed with. We're simply looking at the block/entity and copying it.

2017-02-08 20:22 UTC, williewillus commented
After thinking about it a bit more, I actually backtrack. All the other clicks the player does in world (left/right on blocks, entities, and air) are routed through PIE (for better or for worse, you can yell at me later about that :P), so it makes sense for this middle click to be as well.

2017-02-08 20:25 UTC, killjoy1221 commented
I guess that does make sense. Some modder could be creative and allow middle click to have special code, essentially making it an interact.

I just don't like how many ternary operators are in the constructor. It might be nice to do all the logic outside the event so it can be cleaner.

2017-02-23 23:32 UTC, LexManos commented
Seems you have all missed the most important part, explaining why you need this.
As @KnightMiner  said, his want is a vanilla mechanic. So... Why?

2017-02-24 08:30 UTC, canitzp commented
The ctrl middle click way only copies the NBT that is written trough writeNBT, but I want to change this so it also writes per example the inventory, stored fluids or other capability related things and I want to not only apply this to vanilla blocks.

2017-02-24 09:56 UTC, LexManos commented
None of that information is available client side...

2017-02-24 09:57 UTC, canitzp commented
That doesn't mean that I can't send a packet, per example cancel the event and send my own instead of the vanilla one, shouldn't be such a problem

2017-05-01 02:37 UTC, mezz commented
When reviewing this with Lex, it seems like the main objection is that middle click is handled on the client when it really should be on the server, which is a vanilla problem.
I'll talk to him again about what the solution here should be.

In the meantime please resolve the merge conflicts.

2017-05-01 05:13 UTC, mezz commented
Talked to Lex and we're unfortunately rejecting this because it's a bit too much of a mess for a small gain with the current vanilla implementation.
This type of functionality should be possible with a custom item or something else, just not with middle click until we get a vanilla server-side implementation of it.

2017-05-01 05:13 UTC, closed without merging