[1.11.2] Add MerchantTradeEvent
MinecraftForge/MinecraftForge pull request #3686
Opened 2017-02-11 12:58 UTC by CrafterKina

This pr adds MerchantTradeEvent. 

Usecase
---
* Give an achievement
* Let the villagers refuse the trade
* Advanced trading system

etc...

Necessary?
---
* Hook to net.minecraft.village.MerchantRecipe#isRecipeDisabled
* Move event firing forward

2017-02-11 12:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3686) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3686) before we can accept your contribution.<br/>

2017-02-11 20:46 UTC, liach requested changes

2017-02-11 20:46 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/player/MerchantTradeEvent.java
> +    public IMerchant getMerchant(){
formatting

2017-02-11 20:46 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/player/MerchantTradeEvent.java
> +    protected ItemStack right;
Keep two `protected final` fields of original left and right contents.

2017-02-11 23:20 UTC, liach approved these changes

2017-02-16 08:34 UTC, liach commented
Should the 2 subclasses be named `Pre` and `Post`?

2017-02-16 08:35 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/player/MerchantTradeEvent.java
> +    public static class CanTrade extends MerchantTradeEvent
I would name this `OfferRecipe`

2017-02-16 08:37 UTC, liach commented on src/main/java/net/minecraftforge/event/entity/player/MerchantTradeEvent.java
> +    public static class Done extends MerchantTradeEvent
I would name this one `Transact`, specifying that this is fired after the recipe is already created and when the player do the actual transaction.

2017-02-19 06:56 UTC, liach approved these changes

2017-03-07 10:23 UTC, mezz commented
It looks like `@Mod.EventBusSubscriber` does not work for the test mods, I get an error because it's in the same folder as other mods.

`[FML/breedingtest]: Skipping @EventBusSubscriber injection for net.minecraftforge.debug.MerchantTradeEventDebug since it is not for mod breedingtest`

Can you make it subscribe the old way until we can fix this issue?

Also, please make the test mod disabled by default, and add a comment explaining what `onMerchantTradeDone` is supposed to do so that it can be checked more easily in the future.

2017-03-07 21:25 UTC, mezz commented
After some debugging, I found that `@Mod.EventBusSubscriber` works correctly but the methods marked `@SubscribeEvent` need to be `static` to be subscribed.

2017-03-11 08:18 UTC, CrafterKina commented
Fixed

2017-03-11 09:34 UTC, mezz commented
It works correctly, but the way the events are set up make the interaction strange.
Instead of setting what you will get ahead of time, the event changes it as you try to interact.
I think that doing it this way is not as intuitive for players as it could be.

Event says can't trade,  player has no idea what's happening:
![2017-03-11_01 30 38](https://cloud.githubusercontent.com/assets/916092/23822129/ac99c902-05fa-11e7-9cc9-0fe38b02161a.png)

Event says >20 levels means cost is only 1, but there's no way to see that until you try paying the full price:
![2017-03-11_01 31 55](https://cloud.githubusercontent.com/assets/916092/23822128/ac9850cc-05fa-11e7-8aca-bb900b030e45.png)

2017-03-11 12:27 UTC, CrafterKina commented
Should I add a hook to ``isRecipeDisabled`` and set events non-Cancelable?

2017-03-12 04:33 UTC, mezz commented
I think that makes sense.
If the price is changed or the trading is disabled, it should show that in the gui.

2017-03-29 02:13 UTC, liach commented
@CrafterKina @mezz Any updates?

2017-05-01 02:44 UTC, mezz commented
I am closing this PR for now because you have not responded in a long time.
It seems to be nearly complete. Please update and reopen it, or someone else update it and make a new PR.

2017-05-01 02:44 UTC, closed without merging