Update EnergyStorage.java
MinecraftForge/MinecraftForge pull request #3700
Opened 2017-02-15 11:39 UTC by MattiaMalonni

Added function for setting energy to custom value (useful for initializations)

2017-02-15 11:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3700) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3700) before we can accept your contribution.<br/>

2017-02-15 11:59 UTC, mezz requested changes

2017-02-15 11:59 UTC, mezz commented on src/main/java/net/minecraftforge/energy/EnergyStorage.java
> +		}
Be careful not to use tabs, Forge uses spaces and so this is indented strangely.

2017-02-15 14:07 UTC, williewillus commented
You can  use MathHelper.clamp instead of reimplementing its logic

2017-02-15 15:07 UTC, liach commented
Please set up a workspace. A pull based on GitHub edits is never merged. Do not tell me you don't know to import classes!

2017-02-15 15:11 UTC, MattiaMalonni commented
@liach you should take a look at my last commit...

2017-02-15 15:15 UTC, liach commented
Again, MAKE CODE SIMPLE, use net.minecraft.util.math.MathHelper!

2017-02-15 15:16 UTC, liach requested changes
You edited this ON GITHUB! That's BAD. Test?

2017-02-15 15:21 UTC, MattiaMalonni commented
@liach there is nothing to test, is just a MIN and a MAX (deliberately used to keep consistency with the others methods)

2017-02-15 16:48 UTC, LexManos commented
Better to do in the constructor, or use other means of accessing the protected fields, {Hit thats why they are protected not private} We don't want people thinking set is a valid API function.

2017-02-15 17:18 UTC, MattiaMalonni commented
@LexManos aren't API managed by the interface?

2017-02-15 17:36 UTC, LexManos commented
In theory, but you're also expanding the interface with the addition of a new public method which would entice people to use it. Which causes people to make had external deps on internal implementations.  Welcome to the world of developing.

2017-02-15 19:27 UTC, blay09 commented
The change only affected the default implementation, the interface wasn't actually touched at all.

Having a setEnergyStored method in the default implementation would be useful for syncing as well as loading. So far I've always had to extend EnergyStorage just for that purpose.

2017-02-15 19:39 UTC, MattiaMalonni commented
Same here, I actually prefer to create a separate method instead of using the constructor.. But, you know, developers philosophies..

2017-02-15 19:46 UTC, LexManos commented
In a perfect world it'd be fine as we would be dealin with real developers who know the difference between internal and external functions. However the 20 years of dealing with these types of communities has proven to me that we can't assume that. Over those years I've developed a sense for when things will get abused and cause much more trouble then it's worth. And this is throwing giant red flags, so we must code defensively.

2017-02-16 07:26 UTC, mezz approved these changes

2017-02-16 08:27 UTC, liach requested changes

2017-02-16 08:27 UTC, liach commented on src/main/java/net/minecraftforge/energy/EnergyStorage.java
> +        this.energy = Math.max(0 , Math.min(capacity, energy));
Why not use MathHelper?

2017-02-16 13:32 UTC, MattiaMalonni commented on src/main/java/net/minecraftforge/energy/EnergyStorage.java
> +        this.energy = Math.max(0 , Math.min(capacity, energy));
As I previously said, to keep consistency with other methods.. Don't be stubborn..

2017-02-16 15:44 UTC, liach requested changes
Where is the test mod?

2017-02-16 15:44 UTC, liach commented on src/main/java/net/minecraftforge/energy/EnergyStorage.java
> +        this.energy = Math.max(0 , Math.min(capacity, energy));
You can say whatever you like here then.

2017-03-15 02:00 UTC, merged