Add LootTableManager to the LootTableLoadEvent
MinecraftForge/MinecraftForge pull request #3717
Opened 2017-02-20 07:09 UTC by jcranky

So that it is easier to create new `LootTable`s when handling the event. A small discussion that motivated this PR can be found here: http://www.minecraftforge.net/forum/topic/50767-access-to-loottablemanager-from-loottableloadevent/

Now, I'm not 100% sure this is the right way to do this. Any other options / ideas?

2017-02-20 07:09 UTC, jcranky commented on README.md
> + the 1.11.x branch for Minecraft 1.11.2.
Not sure if I should do this, please let me know if I should remove.

2017-02-20 07:10 UTC, jcranky commented on jsons/1.11.2.json
>      "assetIndex": {
All changes to this file where generated by gradle. Let me know if I should revert.

2017-02-20 07:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3717) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3717) before we can accept your contribution.<br/>

2017-02-20 07:11 UTC, jcranky commented on src/main/java/net/minecraftforge/event/LootTableLoadEvent.java
> +    public LootTableLoadEvent(ResourceLocation name, LootTable table, LootTableManager tableManager)
Perhaps there is a better way to do this, other then exposing the `LootTableManager` directly?

2017-02-20 07:12 UTC, jcranky commented
The main goal here is to be able to load a `LootTable` from a json loot table file directly, with `LootTableManager#getLootTableFromLocation`.

2017-02-20 07:16 UTC, mezz commented
I have a workaround for this problem in Forestry that's extremely ugly and hacky to create my own loot table manager just to load tables from file and then add them using the event... This PR would be nice.
Can you add a test mod that shows that it works as expected?

2017-02-20 07:43 UTC, LexManos commented on jsons/1.11.2.json
>      "assetIndex": {
Do not push this

2017-02-20 07:46 UTC, LexManos commented
Why do you need it?
Also, Binary compatibility..... It's a thing, you should keep it.

2017-02-20 20:08 UTC, jcranky commented on jsons/1.11.2.json
>      "assetIndex": {
alright, will remove

2017-02-20 20:14 UTC, jcranky commented
This is what I want to be able to do, from inside a `onLootTableLoadEvent` method:

```
event.setTable(lootTableManager.getLootTableFromLocation(myResourceLocation))
```

Or am I on the wrong path here?

2017-02-20 20:47 UTC, williewillus commented
Lex os asking you to retain binary compat - you changed the signature of the method in forgehooks meaning any mod that calls the old signature breaks. Have the old one still there but deprecated, and delegate it to the new one.

2017-02-20 21:23 UTC, jcranky commented
@williewillus thanks, will do

@mezz Do you mean just a sample mod or some automated one? I'm still trying to figure out how the things in `src/test` works, any pointers to where should I be looking at?

2017-02-20 21:48 UTC, williewillus commented on README.md
> + the 1.11.x branch for Minecraft 1.11.2.
probably doesn't belong in this pr

2017-02-20 22:33 UTC, mezz commented
@jcranky this video from cpw shows you how to get your Forge environment set up so you can run the test mods: https://www.youtube.com/watch?v=pLWQk6ed56Q

Basically we just need a mod that uses the new feature you added, maybe to load a loot table file and add whatever's in it to a specific vanilla chest. It needs to be enough that you can go in-game and confirm it works as intended without unforeseen bugs.

2017-02-22 10:19 UTC, jcranky commented
@mezz I watched that video and it is quite awesome :) - now, are there automated tests executed somehow, or the only way to check if things are working correctly is to open the game and use the test mod?

2017-02-22 15:31 UTC, mezz commented
In this case it will have to be checked by opening the game with the test mod and taking a look.

2017-02-23 06:03 UTC, liach commented on README.md
> + the 1.11.x branch for Minecraft 1.11.2.
Should not be here, and this may cause merge conflict

2017-03-01 06:32 UTC, jcranky commented
@mezz how do I run Forge with the test mod? Is there any specific gradle task for this?

2017-03-01 06:42 UTC, mezz commented
The video tutorial I linked shows you how to run Forge with the test mods.
Sorry it's not simpler, we're working on a wiki version of the video.

2017-03-01 19:07 UTC, jcranky commented
@mezz uhmmm so perhaps I'm looking at the wrong place - I am able to run forge, but I see no test mods in there. I see four mods loaded only:

![minecraft 1 11 2_001](https://cloud.githubusercontent.com/assets/772886/23476247/7bcbd03c-feba-11e6-91f5-36648815577d.png)

Is this what I should be seeing?

2017-03-02 00:11 UTC, mezz commented
You have to build the `Forge_test` module so that the classes are generated, and then go to the project settings for `Forge_main` and add `classes/test/Forge_test` as a runtime dependency.

![setup-forge-tests](https://cloud.githubusercontent.com/assets/916092/23487237/9768fbce-fe99-11e6-98a0-76625919d654.png)

2017-03-03 07:33 UTC, jcranky commented
@mezz thanks, that was the missing link :) I'll update this PR soon-ish

2017-03-06 06:53 UTC, jcranky commented
PR finally updated addressing the comments.

2017-03-06 06:53 UTC, jcranky commented on README.md
> + the 1.11.x branch for Minecraft 1.11.2.
ok, will remove, but isn't this the right information? should it be done in a specific PR?

2017-03-06 07:06 UTC, mezz commented on README.md
> + the 1.11.x branch for Minecraft 1.11.2.
PRs should try to do one thing only, and this fix is unrelated to anything else in the PR.

2017-03-08 00:37 UTC, mezz requested changes
Tested and looks good, just need to fix a couple breaking changes so it can't break any mods.

2017-03-08 00:37 UTC, mezz commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +    public static LootTable loadLootTable(ResourceLocation name, LootTable table, LootTableManager lootTableManager)
This is a breaking change, please keep the old constructor and deprecate it instead of removing it.

2017-03-08 00:37 UTC, mezz commented on src/main/java/net/minecraftforge/event/LootTableLoadEvent.java
> +    public LootTableLoadEvent(ResourceLocation name, LootTable table, LootTableManager lootTableManager)
This is a breaking change, please keep the old constructor and deprecate it instead of removing it.

2017-03-09 05:53 UTC, jcranky commented
@mezz see https://github.com/MinecraftForge/MinecraftForge/pull/3717/commits/07faa07e8aa71f16b539b7a1e46b4148bb5273e7

2017-03-09 05:55 UTC, mezz approved these changes

2017-03-11 04:45 UTC, liach commented on patches/minecraft/net/minecraft/world/storage/loot/LootTableManager.java.patch
> -+                        return net.minecraftforge.common.ForgeHooks.loadLootTable(LootTableManager.field_186526_b, p_186517_1_, s, true);
After all, I think you should change the call to `ClassLoader.getResource` above, which prevents compatibility hacks.

2017-03-11 20:28 UTC, jcranky commented on patches/minecraft/net/minecraft/world/storage/loot/LootTableManager.java.patch
> -+                        return net.minecraftforge.common.ForgeHooks.loadLootTable(LootTableManager.field_186526_b, p_186517_1_, s, true);
I'm not sure I understand what you mean. Which call?

2017-03-11 20:33 UTC, williewillus commented on patches/minecraft/net/minecraft/world/storage/loot/LootTableManager.java.patch
> -+                        return net.minecraftforge.common.ForgeHooks.loadLootTable(LootTableManager.field_186526_b, p_186517_1_, s, true);
@liach that has nothing to do with this PR

2017-04-02 04:54 UTC, jcranky commented
Did I miss some action point here, so that it this PR can be merged?

2017-04-07 23:22 UTC, merged

2017-04-07 23:26 UTC, Madsthunder commented
@LexManos Travis says there's something wrong with your last commit

2017-04-07 23:28 UTC, mezz commented
I think this is a case of Travis being dumb and not working with Github's new "fix merge issues" feature.
The pending Travis build on the actual committed code seems to be running OK so far:
https://travis-ci.org/MinecraftForge/MinecraftForge/builds/219895896