Added a boolean flag for disabling Entity onUpdate
MinecraftForge/MinecraftForge pull request #3731
Opened 2017-02-25 22:57 UTC by Da-Technomancer

The flag is false by default, and if true the Entity will not update. It
is saved and loaded from NBT, and is called updateBlocked.
This would Close #3694 and acts in accordance to LexManos's suggestion in the discussion for that issue.

2017-02-25 22:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3731) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3731) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=3731) it.</sub>

2017-02-26 00:09 UTC, williewillus commented
put a comment so people at know what it does

2017-02-26 00:10 UTC, williewillus commented
also isn't this going to fail for any entity that overrides onUpdate?

2017-02-26 00:41 UTC, LexManos commented
Yes which is why the check should be in the place we have the event now, just less crappy event wise.

2017-02-26 01:11 UTC, Da-Technomancer commented
I don't see what you mean by fail if it is overriden. Yes, overriding the method could stop the flag from having any effect, but overriding the method also can stop the event from having any effect in EntityLivingBase.

2017-02-26 02:48 UTC, williewillus commented
imo the flag checking should happen in world / whatever calls the Entity tick, so that it's always checked for every kind of entity, and you can't accidentally get rid of the check by overriding

2017-02-26 14:04 UTC, Da-Technomancer commented
This commit adds a comment to the updateBlocked flag, and moves the updateBlocked check to the places that call onUpdate.

2017-02-26 22:28 UTC, mezz requested changes

2017-02-26 22:28 UTC, mezz commented on patches/minecraft/net/minecraft/world/World.java.patch
> ++                	if(!p_72866_1_.updateBlocked)
you have a tab here

2017-02-27 01:43 UTC, Da-Technomancer commented
Tab replaced with 4 spaces.

2017-02-27 02:10 UTC, mezz approved these changes

2017-02-27 17:19 UTC, GotoLink commented
I think this deserve some test case to show it doesn't break other behaviors of entities like loading/unloading, or collision.

2017-02-27 21:19 UTC, Da-Technomancer commented
I've been using the test case. There don't seem to be any problems with loading/unloading or collision that I can find.

2017-03-07 09:03 UTC, HenryLoenwind commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    public boolean updateBlocked;//Setting this to true will prevent the world from calling onUpdate for this entity.
can you make this a javadoc comment? Then we'll see it on mouseover everwhere this field is used. Or would this make the patch too big?

2017-03-07 09:09 UTC, mezz commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    public boolean updateBlocked;//Setting this to true will prevent the world from calling onUpdate for this entity.
Not sure Henry. 
@LexManos what is the right way to document this new field, can it be a javadoc?

2017-03-07 23:55 UTC, LexManos commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    public boolean updateBlocked;//Setting this to true will prevent the world from calling onUpdate for this entity.
javadoc is fine,  especially if it's modder facing. Internal stuff with //FIXME, //TODO, or //REMOVE directed twards myself/cpw/fry are fine.

2017-03-08 02:01 UTC, Da-Technomancer commented
Comment replaced with JavaDoc.

2017-03-08 02:25 UTC, mezz commented
Looks good. Tested every vanilla entity and it works as intended.
There are some interesting side effect of blocking updates since everything is basically frozen in time, like zombies will not burn in daylight, and burning zombies will not take damage. In general this PR does what it's supposed to though.

2017-04-07 23:28 UTC, merged