Record which ModContainer creates each crafting recipe
MinecraftForge/MinecraftForge pull request #3739
Opened 2017-02-28 01:56 UTC by mezz

When JEI runs across a broken recipe, it logs as much information as possible about the recipe to help find the cause, but until now there has been no way to find out which mod registered a crafting recipe.

Often there is no good way to track down the broken crafting recipe without knowing which mod registered it. (https://github.com/mezz/JustEnoughItems/issues/749)

This PR wraps the recipe list in a `ModTrackingList` which keeps track of which active mod container added each element in the list.
I went through the trouble of wrapping the list instead of some other way because it's possible to add recipes to the list directly using `CraftingManager#getRecipeList()`.

This would also be useful as a feature for showing which mod created each recipe in-game.

2017-02-28 04:29 UTC, mezz commented
Added a basic performance test to make sure it's not a big regression:

```
[recipedebug]: Vanilla recipe list registration and sorting took 277 ms
[recipedebug]: ModTracking recipe list registration and sorting took 104 ms
[recipedebug]: Vanilla recipe list registration and sorting took 86 ms
[recipedebug]: ModTracking recipe list registration and sorting took 96 ms
[recipedebug]: Vanilla recipe list registration and sorting took 105 ms
[recipedebug]: ModTracking recipe list registration and sorting took 103 ms
[recipedebug]: Vanilla recipe list registration and sorting took 68 ms
[recipedebug]: ModTracking recipe list registration and sorting took 74 ms
[recipedebug]: Vanilla recipe list registration and sorting took 64 ms
[recipedebug]: ModTracking recipe list registration and sorting took 104 ms
```

They seem to be about the same, given most of the time is probably spent constructing the recipes and there is some fluctuation from the JVM.

2017-02-28 08:06 UTC, liach commented
Well, you know that mods can register recipes dynamically instead of only when it is mod loading.

2017-02-28 08:22 UTC, liach commented on src/main/java/net/minecraftforge/fml/common/ModTrackingList.java
> +        return new ModTrackedIterator(delegate.iterator());
You can merge two iterators

2017-02-28 21:54 UTC, bs2609 commented on src/main/java/net/minecraftforge/fml/common/ModTrackingList.java
> +            ModContainer modContainer = Loader.instance().activeModContainer();
Use something like `trackModContainer(@Nonnull Collection<? extends T> elements)` for both `addAll` methods, like you did for `add`?

2017-03-01 01:56 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/ModTrackingList.java
> +        return new ModTrackedIterator(delegate.iterator());
One is an `Iterator` and one is a `ListIterator`, I'm not sure it's correct to use `ListIterator` for both. There may be some extra performance in using `Iterator`?

2017-03-01 02:06 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/ModTrackingList.java
> +            ModContainer modContainer = Loader.instance().activeModContainer();
makes sense, done

2017-03-01 02:09 UTC, liach requested changes

2017-03-01 02:09 UTC, liach commented on src/main/java/net/minecraftforge/fml/common/ModTrackingList.java
> +    private final Map<T, ModContainer> modContainerMap;
Two array lists are more efficient. Track their indexes.

2017-03-01 02:23 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/ModTrackingList.java
> +    private final Map<T, ModContainer> modContainerMap;
I tested, and the performance impact is already very small.

2017-03-01 02:24 UTC, bs2609 commented on src/main/java/net/minecraftforge/fml/common/ModTrackingList.java
> +    private final Map<T, ModContainer> modContainerMap;
`IdentityHashMap` isn't too bad performance wise

2017-03-01 02:28 UTC, liach commented on src/main/java/net/minecraftforge/fml/common/ModTrackingList.java
> +    private final Map<T, ModContainer> modContainerMap;
Then we'd prefer simple implementation.

2017-03-01 02:28 UTC, liach approved these changes

2017-03-18 12:08 UTC, darkhax commented
Not sure if this was intended, but it seems the ModTrackingList is corrupted once Forge sorts the recipe list. The basic extent of the corruption is that every every recipe becomes misatributed to Forge, and during the sorting process many recipes are removed from the list. This isn't an issue when you are checking things before they have been sorted, or if you're adding recipes again after they have been sorted, however it does mean that things like showing who added a recipe in game is not actually possible with this code. The obvious work around for mods would be for them to copy the container map, however given the typical load cycle of mods, and how some annoying mods use postInit for recipe registry, it's not possible to get an accurate depiction. I've written a test mod which highlights this issue, you can find it, and my results [here](https://gist.github.com/darkhax/1805f54dca7f0e55ae2f7ae4f29df93f).

2017-03-23 07:51 UTC, mezz commented
Fixed the issues brought up by darkhax.
Vanilla recipes will be attributed to Forge but that shouldn't be a real issue. If it is. it might be fixed by adding the `MinecraftDummyContainer` to `Loader.instance().activeModContainer()`.

2017-03-23 16:32 UTC, liach commented on src/test/java/net/minecraftforge/debug/RecipeDebug.java
> +        logger.info("10000 {} recipe list registration and sorting took {} ms", listName, stopwatch.elapsed(TimeUnit.MILLISECONDS));
?

2017-03-23 22:39 UTC, mezz commented on src/test/java/net/minecraftforge/debug/RecipeDebug.java
> +        logger.info("10000 {} recipe list registration and sorting took {} ms", listName, stopwatch.elapsed(TimeUnit.MILLISECONDS));
It is run 10,000 times and logs the total time.

2017-04-07 23:35 UTC, mezz commented
Reviewed with Lex, closing since it's too hacky. Fair enough. Maybe 1.12 recipes will make this easier.

2017-04-07 23:35 UTC, closed without merging