[1.11.x] Added support for custom shields and allow specified Items to disable shields
MinecraftForge/MinecraftForge pull request #3741
Opened 2017-02-28 21:58 UTC by Madsthunder

Refer to #3583 and #3557

This pr is here to avoid any merge conflicts, as they would be inevitable if the above prs were merged separately.

2017-03-01 01:57 UTC, liach reviewed
You should use your IDE's search function to find usages of  `ItemAxe` and `Items.SHIELD` and replace those instanceof` usages and `==`s.

2017-03-01 01:57 UTC, liach commented on patches/minecraft/net/minecraft/item/Item.java.patch
> ++    public boolean isShield(ItemStack stack, @Nullable Entity entity)
The parameter can be `EntityLivingBase` type, I guess, and that will be more convenient.

2017-03-01 02:15 UTC, Madsthunder commented on patches/minecraft/net/minecraft/item/Item.java.patch
> ++    public boolean isShield(ItemStack stack, @Nullable Entity entity)
You're referring to both methods, correct?

2017-03-01 02:27 UTC, liach commented on patches/minecraft/net/minecraft/item/Item.java.patch
> ++    public boolean isShield(ItemStack stack, @Nullable Entity entity)
Both can apply, yes.

2017-03-01 17:34 UTC, liach commented
Are you sure that there is no more places to patch? If you are sure, then things look good.

2017-03-04 00:39 UTC, Madsthunder reviewed
Should I change these lines to disable all of the shields in the inventory? Or should I keep it as to where it disables the shield the player is holding?

2017-03-04 00:41 UTC, Madsthunder commented on patches/minecraft/net/minecraft/entity/player/EntityPlayer.java.patch
> ++            this.func_184811_cZ().func_185145_a(this.func_184607_cu().func_77973_b(), 100);
And this ^^^

2017-03-04 00:41 UTC, Madsthunder commented on patches/minecraft/net/minecraft/entity/monster/EntityMob.java.patch
> ++                        entityplayer.func_184811_cZ().func_185145_a(itemstack1.func_77973_b(), 100);
This ^^^

2017-03-04 07:31 UTC, mezz commented
Hm that's a bit complicated. It looks like vanilla wants to disable all shields so you can't just swap them to skip the cooldown. I don't see a great way to do that for modded shields though, since the cooldown tracker only looks at `Item`. Even if you put a cooldown on every item in the inventory, it could be bypassed by picking up a shield from the ground. I'm not sure what the right approach is here.

2017-03-04 19:25 UTC, Madsthunder commented
I think I will just make another pr adding support for `ItemStack`s or `Predicate`s in the `CooldownTracker` after this is merged.

2017-03-05 04:20 UTC, mezz commented
I think that makes sense. The exploit is pretty minor and modded PvP isn't really a thing so it can wait.

2017-03-10 03:05 UTC, mezz commented
It looks like CoFH was able to implement shields using the entity `LivingAttackEvent`.
https://github.com/TheCBProject/CoFHCore/blob/master/src/main/java/cofh/core/proxy/Proxy.java#L69
https://github.com/TheCBProject/CoFHCore/blob/master/src/main/java/cofh/core/item/tool/ItemShieldCore.java

Is this PR required to support the full shield functionality?

2017-03-10 03:40 UTC, Madsthunder commented
Well judging by what they acdomplished, I guess not. The only justification I can think of at this point is for simplicity sake, because that is relatively complex for a beginner modder.

2017-03-10 03:56 UTC, mezz commented
Just talked to KingLemming and this PR creates a way to add items that disable any shield, so both the new shields and new disabling items can know about each other, so it's still good.

2017-04-28 21:48 UTC, elifoster commented
Wouldn't it make more sense to have `Item#isShield` return false, and then provide an implementation in `ItemShield` that returns true?

2017-04-29 00:53 UTC, diesieben07 commented
In a perfect OOP world: Yes. However with Forge the fewer patches the better.

2017-05-01 04:52 UTC, mezz commented
This looks good to me. Please add a test mod that adds a shield-like item and a shield-disabling item.

2017-05-21 19:03 UTC, mezz commented
@Madsthunder Please add a test mod that adds a shield-like item and a shield-disabling item.

2017-05-23 01:58 UTC, Madsthunder commented
With the test mod, the Heavy Diamond Sword can't disable the Diamond Shield, but it can disable the normal Shield.

2017-05-23 02:07 UTC, elifoster requested changes

2017-05-23 02:07 UTC, elifoster commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +    public static final ItemShield DIAMOND_SHIELD = null;
This should be declared using the `Item` type. Using this specific type is not needed anywhere it's used.

2017-05-23 02:07 UTC, elifoster commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +    public static final ItemSword HEAVY_DIAMOND_SWORD = null;
This should be declared using the `Item` type. Using this specific type is not needed anywhere it's used.

2017-05-23 02:07 UTC, elifoster commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +public class ShieldTest
Is it standard in the Forge tests to have so many anonymous and inner classes? It seems messy to me. I would split it up into more focused classes and just put them all in a `shield` subpackage of `test`.

2017-05-23 03:21 UTC, mezz commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +public class ShieldTest
Anonymous and inner classes pretty normal for Forge tests. They don't need to be beautiful, just easy to read and understand.
The formatting of this one is pretty weird though, I have to say.

2017-05-23 03:49 UTC, elifoster commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +            public String getItemStackDisplayName(ItemStack stack)
Is this actually necessary? It doesn't seem like it should be.

2017-05-23 05:16 UTC, liach commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +    public static final ItemSword HEAVY_DIAMOND_SWORD = null;
That is not a big issue. Same above.

2017-05-23 05:17 UTC, liach commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +            public String getItemStackDisplayName(ItemStack stack)
I guess this breaks anvil renames.

2017-05-23 11:14 UTC, Madsthunder commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +            public String getItemStackDisplayName(ItemStack stack)
It is, since `ItemShield` has an override that always defaults the name to Shield instead of what the lang file specifies.

2017-05-23 13:24 UTC, Alpvax commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +            public String getItemStackDisplayName(ItemStack stack)
Maybe we should patch this to allow anvil naming as per usual items.

2017-05-23 16:32 UTC, Madsthunder commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +            public String getItemStackDisplayName(ItemStack stack)
This actually shouldn't affect renaming, as this is copied from the `Item` class.

2017-05-23 16:38 UTC, Madsthunder commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +public class ShieldTest
Should I clean it up?

2017-05-23 20:23 UTC, Alpvax commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +            public String getItemStackDisplayName(ItemStack stack)
My mistake, I misses the fact that this was test mod. Is it worth "fixing" being able to rename ItemShield stacks? (I know it's a vanilla exclusion, but it is an illogical change). We could always keep the vanilla shield exclusion.

2017-05-24 03:41 UTC, elifoster commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +            public String getItemStackDisplayName(ItemStack stack)
I don't think it's important here. However it should absolutely be mentioned in the documentation.

2017-05-24 06:21 UTC, mezz commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +public class ShieldTest
I think it's good enough, the only thing I think you should change is the strange indentation for the `renderTileEntityAt` code. It's indented less than the braces outside.

2017-05-24 08:41 UTC, LexManos commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +        ForgeHooksClient.registerTESRItemStack(DIAMOND_SHIELD, 0, TileEntityCustomShield.class);
Why is this a TESR at all...

2017-05-24 12:38 UTC, Alpvax commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +        ForgeHooksClient.registerTESRItemStack(DIAMOND_SHIELD, 0, TileEntityCustomShield.class);
For the banner textures, but it seems unnecessary for a test mod.

2017-05-24 17:28 UTC, Madsthunder commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +        ForgeHooksClient.registerTESRItemStack(DIAMOND_SHIELD, 0, TileEntityCustomShield.class);
No, all items attempting to use the vanilla shield model must implement `ModelShield` for it to render, hence the TESR. It doesn't have anything to do with custom banner texures.

2017-05-24 23:12 UTC, LexManos commented on src/test/java/net/minecraftforge/test/ShieldTest.java
> +        ForgeHooksClient.registerTESRItemStack(DIAMOND_SHIELD, 0, TileEntityCustomShield.class);
Then use a stick model as the shield. I don't want to endorse people making TESRs for ItemStacks for no reason.

2017-05-25 03:59 UTC, Madsthunder commented
The model should be an exact replica of the normal `ModelShield`.

2017-07-03 18:07 UTC, mezz commented
Please resolve merge conflicts and create a 1.12 version of this PR.

2017-07-20 22:46 UTC, Madsthunder commented
1.12 version has already been pulled.

2017-07-20 22:46 UTC, closed without merging