DimensionPreloadEvent
MinecraftForge/MinecraftForge pull request #3761
Opened 2017-03-04 11:56 UTC by goreacraft

This is a remake of the commit i made earlier : #3758 and following mezz and diesieben07 sugestions

2017-03-05 05:58 UTC, liach requested changes
All the braces need to get fixed.

2017-03-05 05:58 UTC, liach commented on src/main/java/net/minecraftforge/event/world/DimensionPreloadEvent.java
> +public class DimensionPreloadEvent extends Event {
braces on the new line

2017-03-05 19:37 UTC, goreacraft commented on src/main/java/net/minecraftforge/event/world/DimensionPreloadEvent.java
> +public class DimensionPreloadEvent extends Event {
done.. sorry for that

2017-03-05 23:49 UTC, mezz requested changes

2017-03-05 23:49 UTC, mezz commented on src/main/java/net/minecraftforge/common/DimensionManager.java
> +        WorldServer world = (dim == 0 ? overworld : ( alterantiveDimension != null ? alterantiveDimension : ((WorldServer)(new WorldServerMulti(mcServer, overworld.getSaveHandler(), dim, overworld, m
This line has two ternary statements in it now, can you break it up into if / else if / else?

2017-03-06 07:42 UTC, goreacraft commented on src/main/java/net/minecraftforge/common/DimensionManager.java
> +        WorldServer world = (dim == 0 ? overworld : ( alterantiveDimension != null ? alterantiveDimension : ((WorldServer)(new WorldServerMulti(mcServer, overworld.getSaveHandler(), dim, overworld, m
indeed... the readability is much better with clasic if statements

2017-03-06 07:50 UTC, mezz requested changes

2017-03-06 07:50 UTC, mezz commented on src/main/java/net/minecraftforge/common/DimensionManager.java
> +                world = (WorldServer) (new WorldServerMulti(mcServer, overworld.getSaveHandler(), dim, overworld, mcServer.theProfiler).init());
Can you make this section this way?
```java
WorldServer world;
if (dim == 0)
{
    world = overworld;
}
else if (alternativeDimension != null)
{
    world = alterantiveDimension;
}
else
{
    world = new WorldServerMulti(mcServer, overworld.getSaveHandler(), dim, overworld, mcServer.theProfiler);
    world.init();
}
```

2017-03-06 08:01 UTC, goreacraft commented on src/main/java/net/minecraftforge/common/DimensionManager.java
> +                world = (WorldServer) (new WorldServerMulti(mcServer, overworld.getSaveHandler(), dim, overworld, mcServer.theProfiler).init());
sure.. and you just showed me that i misspelled "alterantiveDimension" too :d

2017-03-06 08:09 UTC, mezz approved these changes

2017-03-06 08:25 UTC, liach approved these changes

2017-03-07 15:19 UTC, goreacraft commented
I have made a test mod with some basic functionality, commands to test /mining (when run first time will create a new dimension) and then this command will teleport to mining dimension 
by adding an and int argument the command will work like a basic tp command between dimensions so /mining 0 will tp back to overworld.
 I need some help to figure out some bugs though if any of you is kind enough:
-  i can't make my own WorldProvider as it will not instantiate from DimensionType with newInstance(new Object[0]).
- dimension folder structure is a bit messy as you will see in testing

2017-03-12 05:39 UTC, mezz requested changes

2017-03-12 05:39 UTC, mezz commented on src/test/java/net/minecraftforge/test/MiningDimensionTest.java
> +        System.out.println("MiningDimensionTest Registered  command /mining <int>");
Please use the logger you get from `FMLPreInitializationEvent#getModLog` instead of `System.out`

2017-03-12 05:40 UTC, mezz commented
The commands looks useful, but what action do I take to test your new event?

2017-03-19 10:41 UTC, goreacraft commented on src/test/java/net/minecraftforge/test/MiningDimensionTest.java
> +        System.out.println("MiningDimensionTest Registered  command /mining <int>");
Sorry for delay, i will update this asp and improve it a little bit

2017-03-20 12:21 UTC, goreacraft commented on src/test/java/net/minecraftforge/test/MiningDimensionTest.java
> +        System.out.println("MiningDimensionTest Registered  command /mining <int>");
for now i will push only the changes you requested, i will leave the improvements for later as don't have the time at this moment

2017-03-20 12:26 UTC, goreacraft commented
To actually take full advantage of this event i will need to upload an entire multiverse mod so instead i just made small test that will create a customized mining dimension (custom name, custom save location, keepinventory, allday, worldtype amplified) , so to actually test if this works is to see if the changes applied correctly and there is a beautiful mining dimension generated

2017-04-15 22:04 UTC, goreacraft commented
Hello, was wondering if there is a reason why this has not been accepted yet, do i need to make any changes or add more explanations?

2017-04-15 22:30 UTC, diesieben07 commented
- The test mod is way too big.
- I still have not seen why this is needed. Your usecase is a "mining dimension", what is that supposed to be? Why do you need a custom World implementation for that?

2017-04-16 00:03 UTC, goreacraft commented
The "mining dimension" is just an example i chosen randomly and there are way more situations where a server can benefit from the flexibility added by this event. 
Maybe i am missing something but do you know of another way to make server side dimensions with custom settings different from overworld? (this things are possible for a very long time now with spigot for example and i do not see why this is not supported by forge)
I been hosting and playing forge modpacks for over 6 years now and i always needed to use some kind of mcpc+, cauldron or thermos to be able to manage a public server and i have decided to use 100% forge only to prove to others that forge is all that is needed, but i am facing with some parts that are very inflexible like creating dimensions and i want to help with this.

2017-04-16 10:30 UTC, diesieben07 commented
Your explanation seems long, but it doesn't convey anything. What are these "settings" you want to change? Give a detailed list.

2017-04-16 14:47 UTC, goreacraft commented
I will give a few examples:
1) create a mining dimension: 
  - no animals
  - no monsters
  - no villages
  - all day
(the purpose is to give players another dimension to use quarries or other mass mining tools so they will not make large wholes and destroy the overworld)
2) create a market dimension
  - no monsters
  - no villages
( this dimension will have chunks assigned to players where they can build their market ans trade each other items in one place and organized)
3) creative dimension:
  - players are in creative
  - all day
  (where players can build nice buildings and show off or test and learn different mods)
4) tutorial dimension
  - no monsters
  - all day
 ( different mods setups with messages on how to use more complex mods like Thaumcraft, AE, IC2 etc...)
5) events dimension
 - settings adjusted based on events types
 - different mingames where players can just take a break from normal gameplay

2017-04-16 16:24 UTC, diesieben07 commented
> no animals
no monsters
no villages
all day
(the purpose is to give players another dimension to use quarries or other mass mining tools so they will not make large wholes and destroy the overworld)

These all do not need a custom World class. There are events for animal and monster spawns, there is an event for village generation. And a custom WorldProvider can change the time of day.

> no monsters
no villages
( this dimension will have chunks assigned to players where they can build their market ans trade each other items in one place and organized)

Again, no need for a custom World class, see above.

> players are in creative
all day

Again, no need for a custom World class. Creative can be handled with change dimension event.

> settings adjusted based on events types
different mingames where players can just take a break from normal gameplay

Back to being vague...


All this suggests to me that you haven't actually spent any time trying to do this with existing hooks and mechanics, as such this is a case of tech support for the forum.

2017-04-16 17:38 UTC, goreacraft commented
Thank you for your time,

I will close this

2017-04-16 17:38 UTC, closed without merging