Add AnimalTameEvent for handling animal taming
MinecraftForge/MinecraftForge pull request #3763
Opened 2017-03-05 08:45 UTC by bs2609

This PR adds a new `AnimalTameEvent`, allowing mods to handle animals being tamed.

There was some talk about possible use for something similar in #3046.
Here we just provide an event for mods to subscribe to, rather than adding new methods to `EntityTameable`.

Points to note:
*  The class used to represent the entity involved is `EntityAnimal`.
This is the class that is common to all vanilla animals that can be tamed.
The `EntityPlayer` performing the taming is also available through the event.
*  It supports horses and llamas as well, despite them not extending `EntityTameable`.
The behaviour is inherited from the AI handling of `AbstractHorse`.
*  An event means mods can prevent the taming of animals without interfering with other interactions.
Currently, you would have to anticipate the behaviour of `processInteract()` and then selectively abort the entire interaction.
*  The event is fired via patches to:
    *  `EntityAIRunAroundLikeCrazy.updateTask()`  (for vanilla `AbstractHorse` based entities)
    *  `EntityOcelot.processInteract()`
    *  `EntityWolf.processInteract()`
*  Mods will have to fire this event manually for other `EntityTameable` derived entities as well as other custom animals.

A quick test is included that makes wolves untameable.

2017-03-07 17:35 UTC, liach requested changes

2017-03-07 17:35 UTC, liach commented on src/test/java/net/minecraftforge/test/AnimalTameEventTest.java
> +@Mod.EventBusSubscriber
This does not work in test mods according to @mezz. Register manually.

2017-03-07 21:40 UTC, Madsthunder commented on src/test/java/net/minecraftforge/test/AnimalTameEventTest.java
> +@Mod.EventBusSubscriber
Yes, it does, you just have to ensure that `onAnimalTame` is a `static` method, which it is currently.

2017-03-07 22:11 UTC, liach commented on src/test/java/net/minecraftforge/test/AnimalTameEventTest.java
> +@Mod.EventBusSubscriber
Turned out @mezz was confused. :trollface:

2017-03-07 22:11 UTC, liach approved these changes
:trollface:

2017-03-07 23:35 UTC, mezz commented on src/test/java/net/minecraftforge/test/AnimalTameEventTest.java
> +@Mod.EventBusSubscriber
Yeah it just needs to be `static`. Here is that comment: https://github.com/MinecraftForge/MinecraftForge/pull/3686#issuecomment-284681329

2017-03-08 20:41 UTC, mezz commented
Tested and looks good.

2017-04-07 23:47 UTC, merged