Tweak vertex lighter to avoid causing excess array initialisations
MinecraftForge/MinecraftForge pull request #3771
Opened 2017-03-10 19:08 UTC by bs2609

When looking at some sampling results, I noticed `QuadGatheringTransformer.setVertexFormat()` showed up as requiring a noticable amount of CPU time.

Looking at the code, the main thing this method does is allocate new `int[]` and `float[][][]` arrays to hold quad data.

`setVertexFormat()` is called from `VertexLighterFlat.setParent()`, if the vertex format is not equal to the parent's format.

However, the actual format that is set (via static method `getVertexFormat(...)`) will not necessarily be the same as the parent format, a normal element will be appended if missing from the parent format.

This means that for vertex formats without a normal, the current equality check will always fail, leading to the following code running even though the format used has not changed.

This PR alters the check to compare against the format that would be passed to `setVertexFormat()` instead, preventing unneeded code running and the resulting object creation/disposal overhead.

2017-03-10 19:09 UTC, bs2609 commented
@RainWarrior, as the authority on this code, can you take a look at this when you have time?

2017-03-10 22:25 UTC, bs2609 commented
It also might be better to not create new `Format` and `FormatElement` objects each time as well.

2017-05-01 08:16 UTC, mezz requested changes

2017-05-01 08:16 UTC, mezz commented on src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterFlat.java
> +        if(format.equals(getVertexFormat())) return;
Fry asks that you keep the `Objects.equal` for the unlikely case of NPE.

2017-05-01 08:17 UTC, mezz commented
Please give me some steps to replicate your profiling findings.

2017-05-01 11:23 UTC, bs2609 commented on src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterFlat.java
> +        if(format.equals(getVertexFormat())) return;
I can keep that, but, when looking at the code it seemed that `parent.getVertexFormat()` shouldn't return null. For instance, in that case, there'd just be an NPE later ([see here](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterFlat.java#L144-L145)).

2017-05-01 12:17 UTC, bs2609 commented
Here's some screenshots of sampling snapshots I took with VisualVM.

* Before changes: (regular build 2282)
![mod_before](https://cloud.githubusercontent.com/assets/1447117/25579492/569a128e-2e70-11e7-91e5-93a49b8069fc.png)

* After changes: (dev build)
![mod_after](https://cloud.githubusercontent.com/assets/1447117/25579504/6ce5964e-2e70-11e7-909f-b713e6723b96.png)

2017-05-01 17:03 UTC, mezz commented on src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterFlat.java
> +        if(format.equals(getVertexFormat())) return;
Please humor fry and use `Objects.equal` so this can go smoothly and be accepted. ;P

2017-05-01 17:14 UTC, bs2609 commented on src/main/java/net/minecraftforge/client/model/pipeline/VertexLighterFlat.java
> +        if(format.equals(getVertexFormat())) return;
Sure :P

2017-05-01 17:20 UTC, RainWarrior commented
Would you mind doing the profiling in addition to the sampling? I've found that sampling doesn't always yield accurate results :)

2017-05-01 17:23 UTC, mezz commented
Making my own profiling setup to confirm:
1. Create a new world, go to a jungle, and wait for chunk updates to die down.
2. Start profiling and hit F3+A a few times to re-render everything then stop profiling.
3. Exit game, switch to PR branch and repeat step 2.

Results, looking at `ForgeBlockModelRenderer.renderModelSmooth`:
Before the PR, `VertexLighterFlat.setParent` wasn't taking a ton of time but it did show up. It takes about 1/10 as much time as `ForgeBlockModelRenderer.render`.
After the PR, `setParent` barely shows up, taking about 1/500 as much time as `render`.

Looks good to me, 8-10% is a bigger performance boost than I was expecting. Since the chunk re-rendering is threaded and my computer isn't struggling it's not super noticeable, but definitely not bad.

2017-05-01 17:25 UTC, mezz approved these changes

2017-05-02 18:27 UTC, bs2609 commented
After some hassle, I was able to get some profiling data.

Here's the results I got from basically the same test environment as in the sampling setup.

Profiling this code made a significant difference to general performance, so it took a relatively long time to get data for any real amount of 'work'. Also note that these results are dependent on calibration data, so might not be fully correct themselves.

Method invocation count applies to all methods listed apart from where noted.

*  Without changes: (8,057,272 method invocations recorded)
    *  `QuadGatheringTransformer#setVertexFormat(VertexFormat)`: 10,798ms self, 11,182ms total
    *  `VertexLighterFlat#setParent(IVertexConsumer)`: 5,109ms self, 35,724ms total
    *  `ForgeBlockModelRenderer.render(...)`: 4,565ms self, 282,765ms total
    *  `ForgeBlockModelRenderer#renderModelSmooth(...)`: 3,114ms self, 323,490ms total
    *  `VertexLighterFlat.getVertexFormat(IVertexConsumer)`: 1,657ms self, 16,082ms total

*  With changes: (7,547,688 method invocations recorded)
    *  `QuadGatheringTransformer#setVertexFormat(VertexFormat)`: ~0ms self, ~0ms total (very few invocations)
    *  `VertexLighterFlat#setParent(IVertexConsumer)`: 874ms self, 14,019ms total
    *  `ForgeBlockModelRenderer.render(...)`: 3,862ms self, 241,087ms total
    *  `ForgeBlockModelRenderer#renderModelSmooth(...)`: 2,929ms self, 259,633ms total
    *  `VertexLighterFlat.getVertexFormat(IVertexConsumer)`: 1,071ms self, 10,554ms total

2017-05-26 20:57 UTC, merged