Add player sensitivity to getPickResult in Entity.
MinecraftForge/MinecraftForge pull request #3801
Opened 2017-03-22 06:28 UTC by darkevilmac

This change is to match the corresponding method in Block.

See #3800

2017-03-22 06:29 UTC, CrafterKina requested changes

2017-03-22 06:29 UTC, CrafterKina commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> +-import net.minecraft.block.BlockLiquid;
Don't remove it.

2017-03-22 06:31 UTC, darkevilmac commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> +-import net.minecraft.block.BlockLiquid;
Not sure how that happened, I'll adjust the patch.

2017-03-22 22:06 UTC, bs2609 reviewed
Looks ok, couple of small points:

2017-03-22 22:06 UTC, bs2609 commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    @Deprecated // Use player sensitive version below.
Add a `@deprecated use {@link #getPickedResult(RayTraceResult, EntityPlayer)}` javadoc tag here.
If you think this method can be removed in future, add a `// TODO: remove` comment here as well.

2017-03-22 22:06 UTC, bs2609 commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    public ItemStack getPickedResult(RayTraceResult target, EntityPlayer player)
Give this a `@Nonnull` annotation (use full `javax.annotation` name if needed)

2017-03-24 00:38 UTC, mezz requested changes

2017-03-24 00:38 UTC, mezz commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++import javax.annotation.Nonnull;
Avoid adding this import by using `@javax.annotation.Nonnull` where you need it.

2017-03-24 00:38 UTC, mezz commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    @Deprecated //Use {@link #getPickedResult(RayTraceResult, EntityPlayer)}
Please use a javadoc for this  so it looks this way:
```java
/**
 * Called when a user uses the creative pick block button on this entity.
 *
 * @param target The full target the player is looking at
 * @return A ItemStack to add to the player's inventory, empty ItemStack if nothing should be added.
 * @deprecated use {@link #getPickedResult(RayTraceResult, EntityPlayer)}
 */
 //TODO: Remove in 1.12
 @Deprecated
 public ItemStack getPickedResult(RayTraceResult target)
```

2017-03-24 02:44 UTC, darkevilmac commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    @Deprecated //Use {@link #getPickedResult(RayTraceResult, EntityPlayer)}
Should I keep "Use getPickedResult"?

2017-03-24 02:45 UTC, mezz commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    @Deprecated //Use {@link #getPickedResult(RayTraceResult, EntityPlayer)}
Yes, that part is included in the javadoc

2017-03-24 02:59 UTC, mezz requested changes

2017-03-24 02:59 UTC, mezz commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++                && this.field_70130_N * this.field_70130_N * this.field_70131_O > 0.512F;
It looks like these lines were indented accidentally.

2017-03-24 03:00 UTC, mezz commented
Please give an example of how your mod will use this new feature.

2017-03-24 03:02 UTC, darkevilmac commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++                && this.field_70130_N * this.field_70130_N * this.field_70131_O > 0.512F;
Intellij auto indented when I pasted from a clean source. Fun, generating patches with a fix.

2017-03-24 03:15 UTC, darkevilmac commented
> Please give an example of how your mod will use this new feature.

Well the main reason for this is making it better match the features of a method in Block from vanilla.
To quote from the issue I made prior to making a PR (#3800)

"It allows for developers to block off certain pick results depending on different aspects of the player as well."

I personally would use it to reference a class I have associated with each player to store data about what part of the entity they're looking at. I already have this data stored, so having to raycast again seems like a bit of a waste, and would greatly simplify my codebase.

2017-03-24 03:16 UTC, mezz approved these changes

2017-03-24 03:55 UTC, CrafterKina approved these changes

2017-04-08 00:01 UTC, mezz requested changes

2017-04-08 00:01 UTC, mezz commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    @javax.annotation.Nonnull
This annotation can be removed, everything is Nonnull return value by default in vanilla minecraft code.

2017-04-08 00:01 UTC, mezz commented on patches/minecraft/net/minecraft/entity/Entity.java.patch
> ++    public ItemStack getPickedResult(RayTraceResult target, EntityPlayer player)
Should player be `@Nullable`? I'm trying to think of a case but I'm not sure.

2017-05-01 06:27 UTC, mezz commented
@darkevilmac please respond to my short review and update to solve the merge conflict.

2017-05-22 04:27 UTC, mezz commented
@darkevilmac you have not responded in a long time so I am closing this PR. 
If you want to update this feel free to reopen.

2017-05-22 04:27 UTC, closed without merging