Added in CreatureTypeSpawnEvent Closes #3803
MinecraftForge/MinecraftForge pull request #3819
Opened 2017-04-04 02:22 UTC by LogicTechCorp

With the current entity spawning system, entities are unable to spawn in a fluid that is not water without custom entity spawning code. This PR fixes that issue by adding in an event that allows modders to control if a certain EntityLiving.SpawnPlacementType can spawn at a given location.

2017-04-04 03:21 UTC, Madsthunder commented
I think you meant to refer to #3808 in the title

2017-04-04 08:35 UTC, mezz requested changes

2017-04-04 08:35 UTC, mezz commented on patches/minecraft/net/minecraft/world/WorldEntitySpawner.java.patch
> ++
Please reduce the lines changed here by removing the newlines you have added.

2017-04-05 20:28 UTC, LogicTechCorp commented
Are there any other changes you would like me to make @mezz?

2017-04-06 04:54 UTC, mezz commented
Tested and looks good. 
The logic of the test mod isn't great, for a real mod you probably don't want to use `ALLOW` in most cases, just `DENY` or `DEFAULT`. It does work the way it's written though.

2017-04-06 04:54 UTC, mezz approved these changes

2017-04-08 05:25 UTC, mezz commented
Reviewing with Lex:
Can you make this into a method on Block instead of an event? Then the block can decide if creatures can spawn there.

2017-04-08 06:16 UTC, LogicTechCorp commented
Can you take a look at this MinecraftForge forum thread? It explains the reasoning for the event. @mezz
http://www.minecraftforge.net/forum/topic/47769-1112-spawn-mob-in-lava/

2017-04-12 05:16 UTC, LogicTechCorp commented
Is the reasoning behind the event sound or would you still like me to make it a method in the block class?@mezz

2017-05-01 06:36 UTC, mezz commented
How about a method on the Entity? This event gives a lot of control, but if you're just implementing your own block or entity, it would be more performant to just create methods on those.

2017-05-02 00:51 UTC, LexManos commented
Both entity and block veto would be the best option. We do not want to bypass the block.canCreatureSpawn call, we just want to expand it to also include IN_WATER types?
Or are there other types that are being added that is the issue?

Its a interesting thing, maybe making the default of canCreatureSpawn be true, and only applying the solid logic for type IN_AIR/ON_GROUND like vanilla? Needs more thought.  An event however will not be accepted.

2017-05-02 05:04 UTC, LogicTechCorp commented
When `canCreatureTypeSpawnHere` is called the entity has not yet been created. What would you suggest for me to do? @mezz

2017-05-02 23:37 UTC, mezz commented
Yeah, unfortunately the entity is only available just after a successful "can spawn here" check.

I'll ask Lex to take another look at this after you answer his question about the intention of this PR:
>We do not want to bypass the block.canCreatureSpawn call, we just want to expand it to also include IN_WATER types?
Or are there other types that are being added that is the issue?

2017-05-03 00:46 UTC, LogicTechCorp commented
@mezz Oh, sorry about that. My intention is to not bypass `block.canCreatureSpawn`, but rather allow for the entity to also decide if they can spawn at said location.

@LexManos It would be other types that are being added that is the issue, but let me give you an example in case I understood the question wrong. 

I have an entity that should spawn in a fluid that is not water. There are no `EntityLiving.SpawnPlacementType`'s that cover this case. If I were to add in my own `EntityLiving.SpawnPlacementType` via `EnumHelper` it would not be called anywhere.

2017-07-08 20:28 UTC, LexManos commented
It WOULD be called somewhere, you have to register it in EntitySpawnPlacementRegistry. Or just pass it to canCreatureTypeSpawnAtLocation.
This PR has nothing to do with making custom SpawnPlacementType's 'called'. 
Seems to me like a better option would be a 'isValidSpawn(world, pos)' added to SpawnPlacementType {Or a map of Type->BiPredicate} 
Combine with making the default return of canCreatureSpawn {or a new function to keep compatibility} be true and only applying logic for GROUND/WATER. 

Again, as I stated before. An event for this WILL NOT be accepted. This can be done much better/more efficiently just asking the block/type.

2017-07-08 21:09 UTC, closed without merging

2017-07-08 21:09 UTC, LogicTechCorp commented
Thanks for the feedback, I will look into a better way of achieving this.