Update EntityPlayer armor calculations and ISpecialArmor
MinecraftForge/MinecraftForge pull request #3838
Opened 2017-04-12 05:59 UTC by Flaxbeard

This pull request resolves #3095 and #2720. This is an updated version of  #2765 for 1.11 with the inclusion of the 1.9.1 armor toughness attribute. The PR was updated in response to mezz's request on the original.

It implements three key changes.

First, the ISpecialArmor class now takes EntityEquipmentSlots as arguments instead of integers, modernizing the class to new inventory standards. These changes were a part of WayofTime's initial PR. If they are not desired, I can update the PR to remove them.

Second, ISpecialArmor's ArmorProperties now contains two additional constructor parameters, armor and toughness. These allow for ArmorProperties to provide armor points and toughness in the same manner as vanilla armor. These were included in order to enable changes to the damage reduction formula and to allow armor to be created with a mixture of flat percentage reduction and vanilla armor.

ISpecialArmor now undergoes a two-step hybrid damage reduction / armor damage process. ISpecialArmor's flat percentage damage reduction is applied as before, and armor is damaged accordingly. Then, vanilla calculations are applied for any armor points and toughness assigned to each piece of armor, with armor pieces again damaged accordingly.

Until this point Forge does not handle armor toughness in any way, meaning that Diamond Armor does not operate to vanilla specifications in Forge after 1.9.1.

Finally, this new system enables player attribute modifiers for ARMOR and ARMOR_TOUGHNESS to take effect. This allows items from vanilla adventure maps which carry the attribute to function correctly. This also enables modders to affect the player's armor and armor toughness values, meaning that they could implement armor potions or spells.

A test mod (disabled by default) is included with this PR. It adds diamond-level armor protection to the player while sneaking.

2017-04-12 06:27 UTC, Flaxbeard commented
I've also created a version without the changes to ISpecialArmor's methods and constructor that would (hopefully) be a non-breaking change for 1.11. I can merge [its branch](https://github.com/Flaxbeard/MinecraftForge/tree/nobreak) into this PR if that would be preferable.

2017-05-01 07:08 UTC, mezz commented
Looks good but as you suspected, we can't change `ISpecialArmor`'s method signatures without breaking mods. That will have to wait for 1.12. Please update this PR to the non-breaking version.

2017-05-01 20:30 UTC, Flaxbeard commented
Will do - should be able to push it later this evening

2017-05-01 23:53 UTC, Flaxbeard commented
@mezz PR updated to non-breaking version for 1.11.

2017-05-02 02:12 UTC, mezz requested changes
Tested and looks good, just some minor issues.

2017-05-02 02:12 UTC, mezz commented on src/main/java/net/minecraftforge/common/ISpecialArmor.java
> +                System.out.println(damage);
This `System.out` must be gated behind `if (DEBUG)` or removed

2017-05-02 02:12 UTC, mezz commented on src/main/java/net/minecraftforge/common/ISpecialArmor.java
> +                System.out.println(damage);
This `System.out` must be gated behind `if (DEBUG)` or removed

2017-05-02 02:12 UTC, mezz commented on src/main/java/net/minecraftforge/common/ISpecialArmor.java
> -    //TODO: Change 'int slot' to EnumArmorType
The TODO should be left in, we can fix this in 1.12.

2017-05-02 02:25 UTC, Flaxbeard commented
Should be fixed - sorry about that

2017-05-02 02:32 UTC, mezz approved these changes

2017-05-02 02:36 UTC, mezz commented
Thanks, looks good.

2017-05-02 02:40 UTC, mezz commented
@Flaxbeard since this PR looks complete, can you make a new PR that cleans things up, with breaking changes? There you can include stuff like changing `Slot`'s type and camelCasing all the field names. I can mark it as `1.12` and it can be ready to update when that time comes.

2017-05-26 21:11 UTC, merged

2017-05-26 21:17 UTC, LexManos commented
Do we actually have anything that displays the vanilla mechanics with input/output values of damages?
This is all rather annoying math that I think mojang just pulled out of nowhere.
Looking at the formulas listed here: http://minecraft.gamepedia.com/Armor#Armor_Toughness
each armor still essentially ends up doing a percentage damage reduction.