[1.12] Update ISpecialArmor to use EntityEquipmentSlot
MinecraftForge/MinecraftForge pull request #3866
Opened 2017-05-02 02:55 UTC by Flaxbeard

Breaking component of what was originally included in #3838.

Reworks ISpecialArmor to use EntityEquipmentSlot instead of ints to designate which slot armor pieces occupy. Also does a little cleaning of field names.

2017-05-02 22:57 UTC, mezz commented
Thanks, looks good. 
I'll review once #3838 is merged because it will be easier to see the differences.

2017-05-03 03:57 UTC, liach requested changes

2017-05-03 03:57 UTC, liach commented on src/main/java/net/minecraftforge/common/ISpecialArmor.java
> +    public abstract int getArmorDisplay(EntityPlayer player, @Nonnull ItemStack armor, EntityEquipmentSlot slot);
You don't need `public abstract` here.

2017-05-03 03:57 UTC, liach commented on src/main/java/net/minecraftforge/common/ISpecialArmor.java
> +    public ArmorProperties getProperties(EntityLivingBase player, @Nonnull ItemStack armor, DamageSource source, double damage, EntityEquipmentSlot slot);
You don't need `public` here.

2017-05-03 03:57 UTC, liach commented on src/main/java/net/minecraftforge/common/ISpecialArmor.java
> +    public abstract void damageArmor(EntityLivingBase entity, @Nonnull ItemStack stack, DamageSource source, int damage, EntityEquipmentSlot slot);
You don't need `public abstract` here.

2017-05-04 03:00 UTC, liach commented on src/main/java/net/minecraftforge/common/ISpecialArmor.java
> +            double left =  (  absorbRatio == 0 ? 0 :   absorbMax * 100.0D /   absorbRatio);
No need to multiply by 100

2017-06-11 20:36 UTC, liach commented
@Flaxbeard Can you update this for 1.12?

2017-10-05 05:06 UTC, liach commented
Seems that this one cannot really get actively updated. The owner is not active in the recent months.

2017-10-05 05:08 UTC, mezz commented
That's unfortunate, hopefully they come pack of someone else picks this up.

2017-10-05 05:08 UTC, closed without merging