Fixes BlockLiquidWrapper placing a Static fluid where it should place…
MinecraftForge/MinecraftForge pull request #3893
Opened 2017-05-13 15:08 UTC by bluemonster122

… a Flowing one.

I ran into this issue when attempting to create a block that places fluids in the world as they are pumped into it.

2017-05-13 15:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3893) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3893) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=3893) it.</sub>

2017-05-13 15:09 UTC, liach commented
Why?

2017-05-13 15:12 UTC, bluemonster122 commented
why what?

2017-05-13 15:20 UTC, diesieben07 commented
> Why?

Because otherwise the fluid will not start flowing.

2017-05-13 15:25 UTC, diesieben07 commented on src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockLiquidWrapper.java
> +import javax.annotation.Nullable;
Don't reorganize imports.

2017-05-13 15:26 UTC, bluemonster122 commented on src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockLiquidWrapper.java
> +import javax.annotation.Nullable;
hokay, lemme fix that

2017-05-13 15:34 UTC, diesieben07 requested changes

2017-05-13 15:34 UTC, diesieben07 commented on src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockLiquidWrapper.java
> +import net.minecraftforge.fluids.capability.FluidTankProperties;
Still reorganizing imports.

2017-05-13 15:34 UTC, diesieben07 commented on src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockLiquidWrapper.java
> +            BlockDynamicLiquid block = BlockLiquid.getFlowingBlock(material);
You don't need to change the type here.

2017-05-13 15:35 UTC, bluemonster122 commented on src/main/java/net/minecraftforge/fluids/capability/wrappers/BlockLiquidWrapper.java
> +            BlockDynamicLiquid block = BlockLiquid.getFlowingBlock(material);
ok

2017-05-13 15:38 UTC, bluemonster122 commented
What a scrub I am XD

2017-05-13 15:40 UTC, diesieben07 approved these changes

2017-05-13 21:10 UTC, LexManos commented
You shouldn't need to pass in the flowing state.. you should set the source, and let it flow naturally in the next update tick...

2017-05-13 21:32 UTC, diesieben07 commented
> You shouldn't need to pass in the flowing state.. you should set the source, and let it flow naturally in the next update tick...

... which it doesn't do. Only the flowing thing actually updates when placed.

2017-05-13 22:45 UTC, KnightMiner commented
I've noticed a similar issue when implementing a custom bucket. I had to hardcode a block update for vanilla fluids after placing them as otherwise they never starts flowing.

2017-05-15 00:20 UTC, Actuarius commented
@tterrag1098 added labels [Bug]

2017-05-15 00:24 UTC, liach commented
Wait @Actuarius is back?

2017-05-22 05:06 UTC, mezz commented
Interestingly the code is not used by forge buckets because they defer to the vanilla bucket for lava and water. Modded fluid containers or placers will use it though.
Checking the vanilla fluid placement code (`ItemBucket#tryPlaceContainedLiquid`), this PR is correct.

2017-05-22 05:09 UTC, liach approved these changes

2017-05-22 05:10 UTC, merged