Fix head being angled badly when riding mobs.
MinecraftForge/MinecraftForge pull request #3901
Opened 2017-05-17 02:49 UTC by killjoy1221

Fixes [MC-1207](https://bugs.mojang.com/browse/MC-1207)

When an entity is riding another, some math is done to the body (`f`) to make it sit forward (for the most part). Sadly, these changes were not applied to the head (`f2`), which caused it spin out of control. This simply recalculates the head using the interpolated rotation values.

2017-05-17 04:59 UTC, LexManos commented
Got a before & after?

2017-05-17 05:03 UTC, killjoy1221 commented
https://www.dropbox.com/s/zswpyohkre6s1tl/Minecraft%201.11.2%205_16_2017%209_56_50%20PM.mp4?dl=0

I recorded this earlier, but it's not exactly "up to date". The difference being is it's not so sticky when looking forward.

If you want, I can record a new video of it tomorrow.

2017-05-17 05:23 UTC, killjoy1221 commented
I messed up on the patch, so that's fixed now. (changed `f - f3` to `f1 - f`). Also, here's an updated video.

https://www.dropbox.com/s/0repegvv7uc6kcf/Minecraft%201.11.2%205_17_2017%201_18_36%20AM.mp4?dl=0

2017-05-17 05:25 UTC, me4502 commented
Are you positive this works in all cases? When I tested it the other night, I started with that simple patch but ended up having to revert it as it broke riding on horses, or it broke riding on armour stands.

2017-05-17 05:36 UTC, killjoy1221 commented
Works for pigs, horses (saddled and bareback), but not sure how to test armor stands. Though all this is doing is recalculating head angle after the body has been rotated.

2017-05-17 05:48 UTC, me4502 commented
Yeah, I think this is the same as the fix I have locally. I originally thought it was one that appeared to work but didn't, and then I switched to this one. Honestly we probably took the same steps, fixing it one way then moving to the other :P

2017-05-17 08:19 UTC, LexManos commented
So, @me4502 is this fully tested with all mounts?

2017-05-17 08:25 UTC, me4502 commented
I haven't, no

2017-05-18 02:22 UTC, me4502 commented
Tested now - this is the same as the one I had on my computer at home. My original broken fix involved moving it from where it was to there, but then when I just copied it, it worked.

It works on every default mount, plus a few random ones such as armour stands, creepers, skeletons, and cows.

2017-05-18 05:53 UTC, mezz requested changes

2017-05-18 05:53 UTC, mezz commented on patches/minecraft/net/minecraft/client/renderer/entity/RenderLivingBase.java.patch
> ++
Please reduce this patch to 1 line total instead of 3:
`f2 = f1 - f; // Forge: Fix MC-1207`

2017-05-20 18:05 UTC, mezz approved these changes

2017-05-21 18:46 UTC, mezz commented
Tested with my player with various camera angles, a villager, and a llama. Looks good to me.

2017-05-21 19:37 UTC, merged