Tweak Event.setCanceled To Match Convention
MinecraftForge/MinecraftForge pull request #3926
Opened 2017-05-27 18:42 UTC by RlonRyan

It is generalized Java convention to throw a UnsupportedOperationException whenever an operation is not supported, as in the case of Event.setCanceled() being called on an event where Event.isCancelable() returns false. The prior implementation threw an IllegalArgumentException, which did not make sense, given that it was not the argument that was the issue, but the fact that the method was even called (given that the method, as per its current implementation ignores the value of its parameter when determining if the exception should be thrown). Also, in the hopes of improving logs, the exception message has been changed as to include the canonical name of the Event subclass instance that was not cancelable. Thus, these changes should aid modders in determining the exact path (or mod interaction) that caused the given event instance as to be spawned and then subsequently attempted as to be canceled.

2017-05-27 18:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3926) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=3926) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=3926) it.</sub>

2017-05-27 18:50 UTC, RlonRyan commented
[Example Gist](https://gist.github.com/RlonRyan/ea5418915e5de9f4482ed9ec23fc7384)

2017-05-28 02:13 UTC, mezz requested changes
Makes sense, needs some minor changes.

2017-05-28 02:13 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/eventhandler/Event.java
> +                "Attempted to modify the unmodifiable canceled state of a non-cancelable event of type: "
I think the original wording is much more clear. Just add the class name to the end.

2017-05-28 02:13 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/eventhandler/Event.java
> +    /*
Javadocs should start with `/**`

2017-05-28 04:01 UTC, RlonRyan commented on src/main/java/net/minecraftforge/fml/common/eventhandler/Event.java
> +    /*
Oh dear me, how could I have missed that...

2017-05-28 04:03 UTC, RlonRyan commented on src/main/java/net/minecraftforge/fml/common/eventhandler/Event.java
> +                "Attempted to modify the unmodifiable canceled state of a non-cancelable event of type: "
I was trying to capture the fact that the error would be thrown even if you pass `true` to the method. I concede, however, that my wording is not optimal.

Would say, `"Attempted to call Event#setCanceled() on a non-cancelable event of type: <type goes here>"` be better?

2017-05-28 04:03 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/eventhandler/Event.java
> +                "Attempted to modify the unmodifiable canceled state of a non-cancelable event of type: "
That sounds good to me.

2017-05-28 04:28 UTC, mezz approved these changes

2017-05-28 04:28 UTC, mezz commented
Looks good to me, thanks.

2017-05-28 18:44 UTC, RlonRyan commented
Oh, it looks like the [documentation](http://mcforge.readthedocs.io/en/latest/events/intro/#canceling-results) will have to be updated after this...

2017-06-01 21:34 UTC, merged

2017-06-02 03:39 UTC, mezz commented
@RlonRyan could you submit a PR to fix the docs here? 
https://github.com/MinecraftForge/Documentation/blob/master/docs/events/intro.md

2017-06-04 22:14 UTC, RlonRyan commented
Sorry about the delay Mezz, I've been otherwise occupied recently. I'll look into making that PR for you now though.

2017-06-04 22:15 UTC, mezz commented
No rush. Thanks.