Clean up Logging
MinecraftForge/MinecraftForge pull request #3953
Opened 2017-06-05 01:41 UTC by diesieben07

- FMLRelaunchLog is deprecated all FML logging goes through FMLLog now.
- The methods in FMLLog are deprecated, apart from 4 new ones that actually add value.
- All other logging uses the log4j logger (`FMLLog.log`) directly.
- All reliance on `String.format` has been removed and replaced with log4j's default formatting using `"{}"` as the placeholder.

This fixes https://github.com/MinecraftForge/MinecraftForge/issues/3713 (and maybe others).

2017-06-05 03:24 UTC, liach commented on src/main/java/net/minecraftforge/fml/common/FMLLog.java
> +        System.setErr(new TracingPrintStream(LogManager.getLogger("STDERR"), System.err));
Really, trace for errors?

2017-06-05 03:25 UTC, kashike commented on src/main/java/net/minecraftforge/fml/common/FMLLog.java
> +        System.setErr(new TracingPrintStream(LogManager.getLogger("STDERR"), System.err));
https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/TracingPrintStream.java#L41-L60

2017-06-05 03:34 UTC, liach commented on src/main/java/net/minecraftforge/fml/common/FMLLog.java
> +        System.setErr(new TracingPrintStream(LogManager.getLogger("STDERR"), System.err));
Still doubt if stderr should be error or info.

2017-06-05 03:43 UTC, mezz commented
Logs with bad arguments:
 * `B3DModel`
   * `if(oldKey.getPos() != null) logger.error("Duplicate keys: %s and %s (ignored)", oldKey, key);`
   * `if(oldKey.getScale() != null) logger.error("Duplicate keys: %s and %s (ignored)", oldKey, key);`
   * `if(oldKey.getRot() != null) logger.error("Duplicate keys: %s and %s (ignored)", oldKey, key);`
 * `EntitySpawnHandler` 
   * `FMLLog.log.error("A severe problem occurred during the spawning of an entity at ({}, {}, {})", spawnMsg.rawZ, e);`
 * `FMLLaunchHandler`
   * `FMLLog.log.info("Forge Mod Loader version {}.{}.{}.{} for Minecraft {} loading", FMLInjectionData.major, FMLInjectionData.minor, FMLInjectionData.rev, FMLInjectionData.build, FMLInjectionData.mccversion, FMLInjectionData.mcpversion);`
 * `FMLSanityChecker`
   * `log.error("Technical information: ClientBrandRetriever was at %s, there were {} certificates for it", codeSource.getLocation(), certCount);`
 * `ModAPITransformer`
   * `if (logDebugInfo) FMLLog.log.debug("Optional removal - interface {} removed from type signature");`
 * `ModContainerFactory`
   * `FMLLog.log.error("Critical error : cannot register mod container type {}, it has an invalid constructor", e);`
 * `ModelLoaderRegistryDebug`
   * `logger.info("%b", shouldIncrement);`
 * `TextureDump`
   * `logger.info("Exported png to: %s", output.getAbsolutePath());`

Possible NPE:
 * `TileEntity`
   * `net.minecraftforge.fml.common.FMLLog.log.error("A TileEntity {}({}) has thrown an exception during loading, its state cannot be restored. Report this to the mod author",
                    s, oclass.getName(), throwable1);` 
     * `oclass` may be null there.

2017-06-05 03:57 UTC, mezz commented
String concatenation:
 * `ConfigTest`
   * `logger.debug("Old: " + CONFIG_TYPES.bool);`
   * `logger.debug("New: " + CONFIG_TYPES.bool);`
   * `logger.debug("After sync: " + CONFIG_TYPES.bool);`
 * `DifficultyChangeEventTest`
   * `logger.info("Difficulty changed from " + event.getOldDifficulty() + " to " + event.getDifficulty());`
* `DynBucketTest`
  * `logger.info("Expected 1: " + handler.getStackInSlot(i));`
  * `logger.info("Expected 2: " + handler2.getStackInSlot(i));`
  * `logger.info("Joined: " + joined.getStackInSlot(i));`
* `EnchantmentLevelSetTest`
  * `logger.info("Enchantment row: " + event.getEnchantRow() + ", level: " + event.getLevel());`
* `EntityTravelToDimensionEventTest`
  * `logger.info("Travelling to Dimension " + event.getDimension() + " Entity: " + event.getEntity());`
* `EquipmentChangeTest`
  * `logger.info("[Equipment-Change] " + event.getEntity() + " changed his Equipment in " + event.getSlot() + " from " + event.getFrom() + " to " + event.getTo());`
* `FluidHandlerTest`
  * `logger.info("Draining " + stackString(stack) + " gives " + fluidString(drain) + " and " + stackString(drainedStack));`
  * `logger.info("Filling " + stackString(stack) + " with " + fluidString(new FluidStack(fluid, filled)) + " gives " + stackString(filledStack));`
* `ForgeModContainer`
  * `log.debug("\t" + name);`
* `GradleForgeHacks`
  * `GradleStartCommon.LOGGER.info("Found and added coremod: " + clazz);`
* `HandshakeMessageHandler`
  * `FMLLog.log.debug(stateType.getSimpleName() + ": " + msg.toString(stateType) + "->" + state.getClass().getName().substring(state.getClass().getName().lastIndexOf('.')+1)+":"+state);`
  * `FMLLog.log.debug("  Next: " + newState.name());`
  * `FMLLog.log.debug(stateType.getSimpleName() + ": null->" + state.getClass().getName().substring(state.getClass().getName().lastIndexOf('.')+1)+":"+state);`
  * `FMLLog.log.debug("  Next: " + newState.name());`
* `ItemFishedTest`
  * `logger.info("Item fished in Biome " + biomeFishedAt.getBiomeName());`
* `MinecraftForge`
  * `ForgeModContainer.log.debug("\t" + name);`
* `ModelAnimationDebug`
  * `logger.info("Event: " + event.event() + " " + event.offset() + " " + getPos() + " " + time);`
* `ModelLoaderRegistryDebug`
  * `logger.info("click " + counter);`
* `NeighborNotifyEventTest`
  * `logger.info(event.getPos().toString() + " with face information: " + event.getNotifiedSides());`
* `PermissionAPI`
  * `FMLLog.log.warn("Replacing " + permissionHandler.getClass().getName() + " with " + handler.getClass().getName());`
* `PlayerSetSpawnTest`
  * `logger.info(event.isForced() + " " + event.getNewSpawn().toString());`
* `TestCapabilityMod`
  * `logger.info("Hi I'm a " + inv.getOwnerType());`
  * `logger.info("Test value is now: " + (cap.getVal() ? "TRUE" : "FALSE"));`
* `TileEntityLoadingTest`
  * `logger.info("World: " + world + ", Pos: " + pos + ", State: " + world.getBlockState(pos));`
* `TracingPrintStream`
  * `logger.info(getPrefix() + o);`
  * `logger.info(getPrefix() + s);`
* `Yggdrasil`
  * `LogManager.getLogger("FMLTWEAK").error("-- Login failed!  " + e.getMessage());`

2017-06-05 13:14 UTC, diesieben07 commented
Thank you for the detailed report, I have addressed the missing pieces.

2017-06-05 16:23 UTC, bs2609 commented
@mezz, is this actually intended for 1.11 or 1.12?

2017-06-06 04:29 UTC, mezz commented
@bs2609 This is intended for 1.11 if possible.

2017-06-06 05:01 UTC, mezz commented
Checked things over again and it looks good to me.

2017-06-22 05:20 UTC, mezz requested changes

2017-06-22 05:20 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/FMLModContainer.java
> +                    modLog.warn(modLog.getMessageFactory().newMessage("Attempting to load @%s in class %s for %s and failing", annotationName, targets.getClassName(), mc.getModId()), e);
Please fix the `%s`s here

2017-06-22 08:18 UTC, diesieben07 commented
Fixed. What about 1.12.x?

2017-06-22 15:33 UTC, mezz commented
I can apply this to 1.12 once this is merged.

2017-06-23 05:27 UTC, mezz approved these changes

2017-06-23 05:33 UTC, merged

2017-06-23 06:20 UTC, mezz commented
Merged and applied to 1.12 as well.

2017-06-23 17:30 UTC, bs2609 commented
All the broken PRs ;_;