Remove some deprecated methods
MinecraftForge/MinecraftForge pull request #4000
Opened 2017-06-15 18:31 UTC by bs2609

Now we have a major version change, it's a chance to clean up some old deprecated methods that shouldn't be used.

This is initially just methods from my past PRs. Other commiters, are there any methods that can be safely added to this?

2017-06-15 18:46 UTC, liach commented
You should search for todos and `@deprecared` annotations.

2017-06-15 19:36 UTC, bs2609 commented
Paging the following for various PRs that deprecate things:

@mezz  #3839, #3689 

@williewillus  #3789, #3744, 

@bogger33 #3747 

@Choonster #3736 

@jcranky #3717 

@diesieben07 #3645 

@maxanier #3579 

I will go through and add some of these myself, this serves as notification if anyone wants to comment, and as a helpful reference for anyone reviewing this.

2017-06-15 19:42 UTC, bs2609 commented
Also going to remove `Java6Utils`, as it's no longer needed.

2017-06-15 20:05 UTC, Choonster commented
The deprecated `BonemealEvent` methods and constructors should be fine to remove.

2017-06-15 20:21 UTC, bogger33 commented
Same with `getFluidHeightForRender(IBlockAccess world, BlockPos pos)`

2017-06-15 21:24 UTC, diesieben07 commented
`AttachCapabilityEvent.Item` can go. That means that `AttachCapabilityEvent.caps` can be private again.

2017-06-15 22:44 UTC, bs2609 commented
Ok, `AttachCapabilityEvent.Item` has been removed, @diesieben07, does 5cbf5b5afe62c59342fc843676839d0ba8aa9b58 look alright to you?

2017-06-15 23:14 UTC, maxanier commented
Both things that were deprecated in my PR (#3579) are already removed in 1.12 as far as I can tell.

2017-06-16 06:17 UTC, Choonster commented
`ItemDye.applyBonemeal(ItemStack, World, BlockPos, EntityPlayer)` can also be removed.

2017-06-16 06:23 UTC, SteveKunG commented
Same with this? #3512

2017-06-16 12:10 UTC, bs2609 commented
Should the various -action suffixed methods in ForgeHooks just inherit the original names now?

2017-06-16 12:14 UTC, williewillus commented
@bs2609 yes, those were there to add #3744 without breaking compat (if I'm thinking of the same methods you are)

2017-06-16 15:21 UTC, liach commented on patches/minecraft/net/minecraft/item/ItemDye.java.patch
>  +    public static boolean applyBonemeal(ItemStack p_179234_0_, World p_179234_1_, BlockPos p_179234_2_, EntityPlayer player, @javax.annotation.Nullable EnumHand hand)
You probably should remove the nullable on the hand.

2017-06-16 15:29 UTC, Choonster commented on patches/minecraft/net/minecraft/item/ItemDye.java.patch
>  +    public static boolean applyBonemeal(ItemStack p_179234_0_, World p_179234_1_, BlockPos p_179234_2_, EntityPlayer player, @javax.annotation.Nullable EnumHand hand)
Why? The hand is supposed to be nullable, we went over this in #3736.

2017-06-16 15:31 UTC, liach commented on patches/minecraft/net/minecraft/item/ItemDye.java.patch
>  +    public static boolean applyBonemeal(ItemStack p_179234_0_, World p_179234_1_, BlockPos p_179234_2_, EntityPlayer player, @javax.annotation.Nullable EnumHand hand)
ok then

2017-06-17 22:30 UTC, mezz approved these changes

2017-06-19 20:12 UTC, bs2609 commented
Removed the deprecated mod GUI methods.

@cpw, you deprecated some of this code in 543156a008295efb43f155c40e8aeb5db6080e6c - is this removal ok?

2017-06-24 19:07 UTC, mezz commented
I think you should go ahead and remove `RuntimeOptionGuiHandler` but leave the world compatibility code for now.

2017-06-26 04:16 UTC, mezz requested changes

2017-06-26 04:16 UTC, mezz commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> -        /*
Please keep this commented out section, it's needed for updating.

2017-06-26 05:14 UTC, mezz commented
I'm going to manually resolve and merge this one now so it makes it in before the breaking-changes deadline.

2017-06-26 05:34 UTC, mezz commented
Merged here https://github.com/MinecraftForge/MinecraftForge/commit/9a09ff68aac457d4297355bd9cb30286af92ec05

2017-06-26 05:34 UTC, closed without merging