Added a new method to IFuelHandler that will check if an item is handled
MinecraftForge/MinecraftForge pull request #4007
Opened 2017-06-16 04:41 UTC by jaredlll08

Using this, mods can dictate whether their IFuelHandler handles an item or not, as well as set the burn time of vanilla items to 0.

2017-06-16 05:10 UTC, liach commented
Make the original method return an OptionalInt instead.

2017-06-16 10:38 UTC, Alpvax commented on src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java
> +                handled = true;
You should just return true here, and return false after the for loop. If it has already matched, you can stop searching and avoid the overhead.

2017-06-16 12:33 UTC, diesieben07 commented
You can already do this if you return -1 from your handler. -1 will always be the smaller one of the two values in the `max` call, and thus be ignored.

2017-06-16 13:21 UTC, jaredlll08 commented
@diesieben07 while that is true, it still doesn't help with changing vanilla burn times

2017-06-16 15:23 UTC, liach commented on src/main/java/net/minecraftforge/fml/common/registry/GameRegistry.java
> +            if(handler.getBurnTime(itemStack) !=null && handler.getBurnTime(itemStack).isPresent())
That method is not declared nonnull so I don't suggest you to have the null check.

2017-06-16 15:26 UTC, liach commented
I don't know if some addon mods want to override fuel values in some other mods. I attempted to do that in #2691 but then failed.

2017-06-16 15:28 UTC, jaredlll08 commented
Yea, that is actually why I'm making this PR, Crafttweaker allows users to change fuel values, and it is a bit inconvenient not being able to change vanilla values

2017-06-16 15:32 UTC, liach commented
I wonder if we should introduce a priority system into the fuel handling.

2017-06-16 18:04 UTC, darkhax commented
At this point, I think switching this over to an event system may be the way to go. Similar to how we use events for the anvil rather than an actual anvil recipe system.

2017-06-17 23:17 UTC, mezz requested changes

2017-06-17 23:17 UTC, mezz commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
> ++            if(net.minecraftforge.fml.common.registry.GameRegistry.isFuelHandled(p_145952_0_))
I think I'd prefer you did this without calling everything twice. 
Just get an `OptionalInt` from the `GameRegistry` once and if it exists use it here.
No need for `isFuelHandled`.

2017-06-18 04:58 UTC, mezz requested changes

2017-06-18 04:58 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FuelHandlerTest.java
> +@Mod(modid = "fuelhandlertest", name = "Guel Handler Test", version = "0.0.0")
"Guel"

2017-06-18 04:58 UTC, mezz commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
> ++            if(burnTime >= 0)
should have a space between `if` and the parenthesis.

2017-06-18 04:58 UTC, mezz commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
> +-
The "clean" version has a newline here after the `Item item =` line, you should not remove it.

2017-06-18 04:58 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FuelHandlerTest.java
> +import java.util.OptionalInt;
Remove unused imports

2017-06-18 04:58 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FuelHandlerTest.java
> +import net.minecraftforge.fml.common.*;
Do not import with `*`

2017-06-18 04:58 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FuelHandlerTest.java
> +@Mod(modid = "fuelhandlertest", name = "Guel Handler Test", version = "0.0.0")
Use acceptable remote versions = `*` so that this can run when connected to vanilla clients or servers.

2017-06-18 05:41 UTC, liach requested changes

2017-06-18 05:41 UTC, liach commented on src/main/java/net/minecraftforge/fml/common/IFuelHandler.java
>      int getBurnTime(ItemStack fuel);
Why do we keep it? We should depreate this and use `ToIntFunction<ItemStack>`

2017-06-18 14:03 UTC, jaredlll08 commented on src/main/java/net/minecraftforge/fml/common/IFuelHandler.java
>      int getBurnTime(ItemStack fuel);
I am simply doing what @mezz requested.

2017-06-18 19:53 UTC, HenryLoenwind commented
Has nobody noticed that not being able to change vanilla data here is a feature, not a bug?

2017-06-18 20:01 UTC, jaredlll08 commented
Please enlighten me as to how not being able to change vanilla burn times is a feature?

2017-06-18 23:20 UTC, Alpvax commented
Discussion as part of #3627

2017-06-21 05:15 UTC, mezz commented
Right, unless Lex changed his mind you will need to bypass the Forge handler for items from the `minecraft` domain.

2017-06-21 16:00 UTC, jaredlll08 commented
Mods such as CraftTweaker allow modpacks authors, server owners and players to change the fuel values.
If a modpack author wants to change it that items in their pack only burn for half of their usual time, making players grind more resources, they can easily do so, however, as it currently stands, and the reason this PR was actually created, it is impossible to change vanilla burn time, which could completely break the progression in a modpack.
Preventing vanilla fuels from being modified because "Dunno, changing vanilla fuel values is a weird thing to do" seems like an arbitrary restriction.

2017-06-25 01:11 UTC, mezz commented on patches/minecraft/net/minecraft/tileentity/TileEntityFurnace.java.patch
> +-
@jaredlll08 I think this patch still needs fixing

2017-06-26 07:24 UTC, mezz commented
After talking with jared and with lex, I wrote a new version of this PR here: https://github.com/MinecraftForge/MinecraftForge/pull/4083

2017-06-26 07:24 UTC, closed without merging