[1.10] limit server>client itemstack packet updates to only differences that actually make difference on client
MinecraftForge/MinecraftForge pull request #4045
Opened 2017-06-20 22:57 UTC by P3pp3rF1y

Change to prevent server only itemstack changes triggering server>client sync packets.

This is a 1.11 version of #3283, much smaller change as it uses a method that mezz added for another NBTShareTag PR.

2017-06-20 23:23 UTC, williewillus commented
You should probably update the commit msg and pr name

2017-06-21 08:17 UTC, P3pp3rF1y commented
Updated the title and added a bit more content. 
Do you really need the commit message updated, I would assume the merge would take the PR name so my commit message is irrelevant.

2017-06-21 11:40 UTC, bs2609 commented
I think they were referring to the [1.10] tags.

2017-06-21 12:16 UTC, P3pp3rF1y commented
Ohh right, thanks for that @bs2609! 
That was a late night copy paste error and then apparently blindness to the tag from my side.

2017-06-26 01:25 UTC, mezz requested changes
Looks good, just need a minor change and then I can test it out.

2017-06-26 01:25 UTC, mezz commented on patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch
> ++                    if (!ItemStack.areItemStacksEqualUsingNBTShareTag(itemstack1, itemstack))
This check should also skip the `LivingEquipmentChangeEvent` below.

2017-06-26 18:11 UTC, P3pp3rF1y commented on patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch
> ++                    if (!ItemStack.areItemStacksEqualUsingNBTShareTag(itemstack1, itemstack))
I would argue that the event should still be fired as that is fired server side and thus people can possibly hook into that if they want to react to Equipment changes which may involve nbt or capability changes that are not synced to client.
Or is this event supposed to only ever fire when the SPacketEntityEquipment packet is sent?

2017-06-30 21:49 UTC, P3pp3rF1y commented on patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch
> ++                    if (!ItemStack.areItemStacksEqualUsingNBTShareTag(itemstack1, itemstack))
@mezz any thoughts on my comment above?

2017-07-01 05:48 UTC, mezz commented on patches/minecraft/net/minecraft/entity/EntityLivingBase.java.patch
> ++                    if (!ItemStack.areItemStacksEqualUsingNBTShareTag(itemstack1, itemstack))
Yeah I think you're right, not all "real" changes will get synced to the client.

2017-07-01 05:48 UTC, mezz approved these changes

2017-10-11 08:30 UTC, closed without merging