Fix vanilla map pixel data being used in various places
MinecraftForge/MinecraftForge pull request #4068
Opened 2017-06-24 21:41 UTC by williewillus

#3952 for 1.12

2017-06-30 08:43 UTC, covers1624 commented
Yes, Oh god yes. This solves all my issues. +40 :D

2017-07-05 06:36 UTC, mezz commented
This looks good, but can you make a test mod?
There are still some places where `== Items.FILLED_MAP` is used and I want to be sure this PR works as intended.

2017-07-11 05:36 UTC, mezz commented
@williewillus any update?

2017-07-11 05:46 UTC, williewillus commented
Been busy for the past week, will get one made soon ^tm and the 1.11 one updated

2017-07-30 17:16 UTC, williewillus commented
Added a test mod.
How to use:
1. Open a superflat world, and open a vanilla filled map (see a green field)
2. Put it on a frame
3. `/give @p mapdatatest:custom_map`
4. It should render as a solid chunk of red, both in hand an on a frame
5. Without these patches, the custom map would render the same data as the vanilla map (green field)

2017-07-30 22:45 UTC, mezz requested changes
Tested and it didn't work as expected.

![2017-07-30_15 43 28](https://user-images.githubusercontent.com/916092/28757716-f24b24ac-753d-11e7-87c0-4870834d2d84.png)

![2017-07-30_15 43 42](https://user-images.githubusercontent.com/916092/28757717-f51f5a5e-753d-11e7-945c-62a18419bd9a.png)

![2017-07-30_15 45 57](https://user-images.githubusercontent.com/916092/28757732-3a678014-753e-11e7-9371-2ae701297bb0.png)

Also please give the map item a name and icon.

2017-07-30 22:45 UTC, mezz commented on src/test/java/net/minecraftforge/debug/MapDataTest.java
> +        public static ItemStack setupNewMap(World worldIn, double worldX, double worldZ, byte scale, boolean trackingPosition, boolean unlimitedTracking) {
This is never called

2017-07-31 00:07 UTC, williewillus commented
Fixed. Should now use the `mapdatatest:empty_custom_map` item to test instead of giving filled map directly.

2017-07-31 00:21 UTC, mezz commented
Ok looks like it's working. The test mod's solid red demonstration is not very good but I was able to poke at it and show that it can draw the original map if it wanted to. Looks good to me.

2017-07-31 00:21 UTC, mezz approved these changes

2017-08-09 20:28 UTC, LexManos commented
Again, why can't you just use the normal map files and just stick your data in the correct metadata'd nbt file?

2017-08-10 04:30 UTC, williewillus commented
I don't quite get the question.

Vanilla maps are stored in `MapData`, subclass of `WorldSavedData` in the WSD keys `map_<meta>`. The methods on vanilla map items work only like this.

Let's say we need to use a custom subclass of MapData, `CustomMapData`. Ignoring the issue of getting such a subclass synced clientside, the map renderers only call `Items.FILLED_MAP.getMapData` instead of polymorphically calling `ItemMap.getMapData`. As noted above, the vanilla method only queries for the vanilla data. Meaning if I have a meta 0 of my own map, the client will attempt to load and render data from the meta 0 vanilla map because the aforementioned method is not called virtually.

Hope that made some sort of sense.

2017-08-10 04:47 UTC, LexManos commented
Yes I understand that it's not called in subclasses what I'm asking is why does it matter? All you're doing is shoving your own data into the map data. From what I see it's all compatible with the vanilla system so literally your map COULD be a vanilla map.

2017-08-21 23:16 UTC, williewillus commented
Here's a concrete example with a slightly different rationale: Twilight Forest's Maze Maps.

* They are Y-level aware when mapping
* Thus they need a custom subclass of MapData and thus a custom WSD "mazemap_\<meta\>" to store the y level of creation
  * The y level cannot be stored in the map item itself because all copies of the map need it. One should be able to type `/give @p twilightforest:maze_map 1 \<meta\>` and continue mapping at the same y level.
* Since they use their own WSD, they don't use the vanilla WSD "map_\<meta\>"
* However, everything clientside only uses the vanilla WSD
* Then, a maze_map of meta 1 will not render the right pixel data, but instead the pixel data of minecraft:filled_map meta 1

Basically the rationale is:
Need custom MapData -> Needs custom WSD name -> client doesn't query my custom WSD name

2017-08-21 23:17 UTC, williewillus commented
Another reason for needing custom MapData would be to keep additional metadata with the map (for example, custom decorations #4027)

2017-08-28 19:34 UTC, williewillus commented
bump re ^

2017-09-06 20:54 UTC, merged