Improve furnace fuel handling
MinecraftForge/MinecraftForge pull request #4083
Opened 2017-06-26 07:21 UTC by mezz

This is a replacement for https://github.com/MinecraftForge/MinecraftForge/pull/4007, without breaking changes.

It adds `Item#getItemBurnTime` which mods can use to set their item's burn times.
It allows mods to set their burn time, set it to 0, or set it to -1 to use the default vanilla behavior.
It also fires an event `FurnaceFuelBurnTimeEvent` for mods that want to change burn times of other mods or vanilla  (like CraftTweaker).
This deprecates the old `IFuelHandler` system but maintains backward compatibility with it.

2017-06-26 12:25 UTC, liach requested changes

2017-06-26 12:25 UTC, liach commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +        int burnTime = item.getItemBurnTime(itemStack);
Where is the patch for this method in `Item.java`? I don't see a change in `Item.java.patch`.

2017-06-26 15:52 UTC, mezz commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +        int burnTime = item.getItemBurnTime(itemStack);
Thanks, added the patch.

2017-06-28 00:34 UTC, liach approved these changes

2017-07-03 19:54 UTC, merged