Added fog color inside material event.
MinecraftForge/MinecraftForge pull request #4090
Opened 2017-06-26 19:56 UTC by covers1624

With the addition of this new event it is possible to Modify the fog color for the material the entity is "inside". 

Returning DENY on the event will cause vanilla's "entity inside material fog color" logic to not fire. 

The current FogColors event has been renamed to FogColorEvent.Post as the intent is to get this PR pulled inside the breaking changes window.
### Uses
This will allow for Modded fluids to easily change the fog color without fighting the rest of the logic above the location for the current event with the added ability to completely disable fog color for inside vanilla materials. By default the test mod adds a fluid with the material of WATER, vanilla's handling would make the fog color blue; the test mod overrides this making the fog color that of lava, proving that both the vanilla logic cancellation and color setting work as intended.

2017-06-27 03:48 UTC, mezz requested changes
Looks good, needs some formatting fixes and then I need to test it out. Before/after screenshots would be nice!

2017-06-27 03:48 UTC, mezz commented on patches/minecraft/net/minecraft/block/Block.java.patch
> ++    public Vec3d getFogColor(World world, BlockPos pos, IBlockState state, Entity entity, Vec3d originalColor, float partialTicks) {
This brace should go on a new line

2017-06-27 03:48 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockLiquid.java.patch
> ++        if (state.func_185904_a().func_76224_d()) {
brace goes on new line

2017-06-27 03:48 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockLiquid.java.patch
> ++            if (state.func_177230_c() instanceof BlockLiquid) {
brace goes on new line

2017-06-27 03:48 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockLiquid.java.patch
> ++            if (viewport.field_72448_b > (double)f1) {
brace goes on new line

2017-06-27 03:48 UTC, mezz commented on patches/minecraft/net/minecraft/client/renderer/EntityRenderer.java.patch
> ++        else {
brace goes on new line

2017-06-27 03:48 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FogColorInsideMaterialTest.java
> +    public static void registerBlocks(RegistryEvent.Register<Block> event) {
brace goes on new line

2017-06-27 03:48 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FogColorInsideMaterialTest.java
> +        Block fluid = new BlockFluidClassic(FluidRegistry.WATER, Material.WATER) {
brace goes on new line

2017-06-27 03:48 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FogColorInsideMaterialTest.java
> +    public static void registerItems(RegistryEvent.Register<Item> event) {
brace goes on new line

2017-06-27 03:48 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FogColorInsideMaterialTest.java
> +    public static void registerModels(ModelRegistryEvent event) {
brace goes on new line

2017-06-27 03:48 UTC, mezz commented on src/test/java/net/minecraftforge/debug/FogColorInsideMaterialTest.java
> +        ModelLoader.setCustomStateMapper(FLUID_BLOCK, new StateMapperBase() {
brace goes on new line

2017-06-27 08:32 UTC, covers1624 commented
Thanks! Formatting addressed, and some minor logic errors inside BlockLiquid's override, As for before and after. 

Before:
![](http://ss.covers1624.net/7196g7z.png)
After:
![](http://ss.covers1624.net/ukn3iaf.png)
The default behavior from vanilla dictates that "hey you are a material water, so, water fog color" but the test mod overrides such fog color to achieve the same color as lava.

2017-06-27 21:00 UTC, bs2609 commented
For the `EntityRenderer` patch, it'd probably be cleaner to have the new code in an `else if (true)` block, rather than deleting the existing code.

2017-06-28 05:53 UTC, HenryLoenwind commented
I haven't been following the state of all these PRs, so what about the overlay texture and its color? Is that already in?

2017-06-28 05:55 UTC, mezz approved these changes

2017-06-28 22:23 UTC, merged

2017-06-29 08:02 UTC, covers1624 commented
@HenryLoenwind Currently TF uses an event to handle that. https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/proxy/ProxyClient.java#L141-L181