Add a World argument to WorldtypeEvent
MinecraftForge/MinecraftForge pull request #4092
Opened 2017-06-26 22:27 UTC by maruohon

This adds a World argument to WorldTypeEvent.BiomeSize and WorldTypeEvent.InitBiomeGens, so that those events can be targeted to specific dimensions by mods.

The argument is optional (Nullable), because the BiomeProvider is sometimes created without access to a World, such as from the AnvilSaveConverter when converting pre-Anvil worlds to Anvil format.

Offtopic:
The patch still looks a bit funky because the constructor/method bodies changed to different methods. How should these be handled? Should those params be named to their srg names to keep the patches smaller?

2017-06-27 03:44 UTC, mezz commented
I think you can fix up the patches by adding your new methods to the `forge.exc` file.

2017-06-27 08:09 UTC, maruohon commented
I now added the lines to `forge.exc` and the extra patch noise went away.

2017-07-31 03:54 UTC, mezz requested changes
Looks pretty good but needs to avoid breaking changes.

2017-07-31 03:54 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeProvider.java.patch
> ++    public GenLayer[] getModdedBiomeGenerators(@javax.annotation.Nullable net.minecraft.world.World world, WorldType worldType, long seed, GenLayer[] original)
Public methods like this can't be changed directly, they need to be deprecated and replaced with new methods.

2017-07-31 03:54 UTC, mezz commented on patches/minecraft/net/minecraft/world/gen/layer/GenLayer.java.patch
> ++    public static int getModdedBiomeSize(@javax.annotation.Nullable net.minecraft.world.World world, WorldType worldType, int original)
Public methods like this can't be changed directly, they need to be deprecated and replaced with new methods.

2017-07-31 03:54 UTC, mezz commented on src/main/java/net/minecraftforge/event/terraingen/WorldTypeEvent.java
> +    public WorldTypeEvent(@Nullable World world, WorldType worldType)
Public methods like this can't be changed directly, they need to be deprecated and replaced with new methods.

2017-07-31 03:54 UTC, mezz commented on src/main/java/net/minecraftforge/event/terraingen/WorldTypeEvent.java
> +        public BiomeSize(@Nullable World world, WorldType worldType, int original)
Public methods like this can't be changed directly, they need to be deprecated and replaced with new methods.

2017-07-31 03:54 UTC, mezz commented on src/main/java/net/minecraftforge/event/terraingen/WorldTypeEvent.java
> +        public InitBiomeGens(@Nullable World world, WorldType worldType, long seed, GenLayer[] original)
Public methods like this can't be changed directly, they need to be deprecated and replaced with new methods.

2017-10-11 07:31 UTC, closed without merging