Replace ASMEventHandler with an equivalent based on lambdas
MinecraftForge/MinecraftForge pull request #4118
Opened 2017-07-02 10:54 UTC by Mysteryem

I don't know if this is something that would be wanted, but I realised that how Java 8 creates lambdas using LambdaMetaFactory is very similar to how the current ASMEventHandler works. So, mostly as a proof of concept, I replaced the ASM with LambdaMetaFactory usage.

As LambdaMetaFactory was introduced in Java 8, this obviously can't be backported to older versions where Java 8 was not a requirement.

I made a diff for comparing ASMEventHandler and LambdaEventHandler since they are considered completely separate files in the commit https://gist.github.com/Mysteryem/54bd72c0c9d00c65b3119f7ebadc516e

I gave it a quick test with the All The Mods 3 modpack, specifically testing the OpenBlock Elevators mod which listens to net.minecraftforge.fml.common.gameevent.InputEvent and it seemed fine.

The generated classes are just normal lambda classes that you would get from using lambda expressions. The main technical differences between these classes and the previously generated classes are:
1. These classes are anonymous
1. They have private access to LambdaEventHandler
1. Their unique names are controlled by LambdaMetaFactory
1. They are loaded with LambdaEventHandler's ClassLoader

-------------------

I thought it would be too much of a hacky feature to include in this PR, but with some reflection to either construct MethodHandles.Lookup instances with access to specific classes or to get the 'TRUSTED' MethodHandles.Lookup instance, it's possible to further modify this code so that the generated classes have private access to classes that are subscribing to events, allowing for event subscribed methods to have any access modifier.

2017-07-02 12:58 UTC, shadowfacts commented
The whole point of the ASMEventHandler based system is that is very, very performant with barely any overhead on firing events. Before this PR has even the slightest chance of being merged, there needs to be enough data to actually compare the performance of the ASM based one with the lambda based one. With many events being fired every tick and more every frame, the slightest bit of performance can't be lost.

2017-07-02 13:09 UTC, diesieben07 commented
Currently the lambda metafactory basically does the same thing: generate an anonymous class using ASM.

2017-07-02 16:10 UTC, Mysteryem commented
@shadowfacts I don't really know what I'm doing with JMH, but I attempted to do some benchmarks:

https://gist.github.com/Mysteryem/c739011e769f4f06321346c2fa392a2a

2017-07-02 16:37 UTC, shadowfacts commented
Might wanna do more measurement iterations, but that looks like a good benchmarking setup.

2017-07-03 13:22 UTC, Champerson commented
But the lambda metafactory also uses asm https://github.com/JetBrains/jdk8u_jdk/blob/master/src/share/classes/java/lang/invoke/InnerClassLambdaMetafactory.java

2017-07-03 13:55 UTC, diesieben07 commented
But in the future they might improve their implementation and then Forge will get it for free.

2017-07-03 17:05 UTC, mezz requested changes
Looks interesting.

2017-07-03 17:05 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/eventhandler/ASMEventHandler.java
> -public class ASMEventHandler implements IEventListener
This is `public`, it needs to be kept around and deprecated in case a mod is using it.

2017-07-03 17:05 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/eventhandler/EventBus.java
> +        catch (Throwable e)
Catching `Throwable` is generally bad practice, is there a reason to change this?

2017-07-04 11:36 UTC, Mysteryem commented on src/main/java/net/minecraftforge/fml/common/eventhandler/EventBus.java
> +        catch (Throwable e)
MethodHandle#invoke, which throws Throwable, is used to construct the lambda class instances. The call to [getHandler](https://github.com/MinecraftForge/MinecraftForge/pull/4118/files#diff-10e669c4a744e9a7418290e95a383028R59) could be surrounded with a try-catch and any non-Exceptions wrapped in an Exception subclass and then thrown?

2017-07-04 12:01 UTC, Mysteryem commented
I dumped and disassembled static and instance versions of both the asm and lambda generated classes so their bytecode could be compared: https://gist.github.com/Mysteryem/0467e45aa86d0cd0df469a80bf4acf8b

The short of it is:
1. In instance method `IEventListener`s, the [type of the field storing the instance](https://gist.github.com/Mysteryem/0467e45aa86d0cd0df469a80bf4acf8b#file-3_instance_lambda-txt-L43) matches the type of the instance rather than being [`Object`](https://gist.github.com/Mysteryem/0467e45aa86d0cd0df469a80bf4acf8b#file-2_instance_asm-txt-L40). This removes a [single `checkcast`](https://gist.github.com/Mysteryem/0467e45aa86d0cd0df469a80bf4acf8b#file-2_instance_asm-txt-L62) instruction from the [`invoke` method](https://gist.github.com/Mysteryem/0467e45aa86d0cd0df469a80bf4acf8b#file-3_instance_lambda-txt-L76).
1. Static asm `IEventListener`s have an [erroneous `aload_0` instruction](https://gist.github.com/Mysteryem/0467e45aa86d0cd0df469a80bf4acf8b#file-5_static_asm-txt-L48) at the start of their `invoke` method
1. [The field in instance lambdas is final](https://gist.github.com/Mysteryem/0467e45aa86d0cd0df469a80bf4acf8b#file-3_instance_lambda-txt-L42)
1. In lambdas, the `invoke` method's stack frame is hidden from stacktraces (I think)
1. Lambdas use more restrictive access modifiers
1. The MethodHandle used to construct instance method `IEventHandler` lambdas is actually a MethodHandle of a static method in the generated class rather than the class' constructor

2017-07-05 05:40 UTC, mezz commented on src/main/java/net/minecraftforge/fml/common/eventhandler/EventBus.java
> +        catch (Throwable e)
I have never seen something with `throws Throwable` before. I guess this is fine then.

2017-07-05 05:45 UTC, mezz commented
Looks good.
You should be able to test the stack trace pretty easily, right? Just throw an exception from an event and it should log the stack trace. Hiding the invocation from the stack trace would be nice, they currently take up a few lines.

2017-07-05 05:45 UTC, mezz approved these changes

2017-07-20 21:51 UTC, LexManos commented
1) We have a unit test section now, add the profiler test to it so it can be easily verified in-repo.
2) @Mysteryem may be right about the static handlers having a few extra ops, they are really just a hack on top of the instance based version so i may of missed removing a few things. PRs to fix that is fine, and should probably be included in this. This goes for things like the field type, final flags, etc.. 
3) I would MUCH rather have both systems available and have a single 'factory' that is easily switched. Possibly including a system property of something to select what strategy to use.

2017-07-20 22:33 UTC, PaleoCrafter commented
The main benefit of the lambda approach is that we get potential optimisations the JVM gets later on for free. Given that the backend for lambdas is basically the same as the ASM event handler generation, the similar performance is obvious. If the Java team finds a more efficient approach, though, we'd manually have to adapt to that with our current system.

2017-07-20 23:46 UTC, LexManos commented
Ya i'd prefer to manually have to adopt. This may be a personal thing. But I am not a fan of 'magically' getting things performance related. Hence why I suggested keeping both and allowing a flag to specify which to use.

2017-08-10 14:30 UTC, bs2609 commented
If we're keeping both, it might make sense to refactor common code into an abstract superclass to reduce duplication.

2017-10-11 07:31 UTC, closed without merging