[1.12] Add amount and contextual data to DecorateBiomeEvent.Decorate
MinecraftForge/MinecraftForge pull request #4134
Opened 2017-07-04 18:50 UTC by Ivorforce

Originally from https://github.com/MinecraftForge/MinecraftForge/pull/3318 - the PR didn't want to update anymore.

This PR adds amount and contextual data to the decoration events.

Examples:

With this PR, a decoration / world generation mod can now 
- Cancel only parts of a decoration aspect (e.g. replace only 5 out of 10 trees, effectively providing an opportunity to inject weighted decorations (e.g. different tree types while honouring default ones)) 
- Distinguish between more different decoration types using contextual information (e.g. cancel only red mushrooms, but not brown ones)
- Modify the amount of a decoration aspect (e.g. change plains to generate 10 instead of 4 trees per biome). This is different from overriding the value the amount is ready or generated from because many biome mods don't even use the BiomeDecorator and have their own algorithm to generate amounts.

With the current event implementation, you can only cancel any whole decoration aspect of the biome. Since in various places (e.g. roofed forests) it is not guaranteed for an event to be fired just once per biome, you cannot act on these events and use them to decorate the biome yourself. 

This also greatly helps decoration mods and biome mods to interact, as many biome mods do not use the default decorator, and can now pass the actual calculated amount and context through the event.

Note that it keeps backwards compatibility by continuing to provide the old event constructor, fire method, and cancellation capability.

2017-07-04 18:53 UTC, Ivorforce commented
@mezz You argued that the event shouldn't carry over the original decoration's position.

That isn't the case. The position included in the event is, as unchanged from the current implementation, the chunk's origin block position. The event doesn't contain a specific position (and can't if the amount is > 1, obviously).

2017-07-31 04:29 UTC, mezz requested changes
Looks good aside from some patch formatting issues.
Please remove lines from patches, do not comment them out.

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int i = 0; i < this.sandPatchesPerChunk; ++i)
Please don't comment out lines in patches, just remove them.

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int i1 = 0; i1 < this.clayPerChunk; ++i1)
Please don't comment out lines in patches, just remove them.

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int j1 = 0; j1 < this.gravelPatchesPerChunk; ++j1)
Please don't comment out lines in patches, just remove them.

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int k2 = 0; k2 < this.bigMushroomsPerChunk; ++k2)
Please don't comment out lines in patches, just remove them.

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int l2 = 0; l2 < this.flowersPerChunk; ++l2)
Please don't comment out lines in patches, just remove them.

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int i3 = 0; i3 < this.grassPerChunk; ++i3)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int j3 = 0; j3 < this.deadBushPerChunk; ++j3)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int k3 = 0; k3 < this.waterlilyPerChunk; ++k3)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int l3 = 0; l3 < this.mushroomsPerChunk; ++l3)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//            if (random.nextInt(4) == 0)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//            if (random.nextInt(8) == 0)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        if (random.nextInt(4) == 0)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        if (random.nextInt(8) == 0)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int k4 = 0; k4 < this.reedsPerChunk; ++k4)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int l4 = 0; l4 < 10; ++l4)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        if (random.nextInt(32) == 0)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//        for (int j5 = 0; j5 < this.cactiPerChunk; ++j5)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//            for (int k5 = 0; k5 < 50; ++k5)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDecorator.java.patch
> ++//            for (int l5 = 0; l5 < 20; ++l5)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDesert.java.patch
> ++//        if (rand.nextInt(1000) == 0)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeDesert.java.patch
> ++//        if (rand.nextInt(64) == 0)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeJungle.java.patch
> ++//        for (int j1 = 0; j1 < 50; ++j1)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomePlains.java.patch
> ++//            for (int i = 0; i < 7; ++i)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomePlains.java.patch
> ++//            for (int i1 = 0; i1 < 10; ++i1)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeSavanna.java.patch
> ++//        for (int i = 0; i < 7; ++i)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeSnow.java.patch
> ++//            for (int i = 0; i < 3; ++i)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeSnow.java.patch
> ++//            for (int l = 0; l < 2; ++l)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeSwamp.java.patch
> ++//        if (rand.nextInt(64) == 0)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/biome/BiomeTaiga.java.patch
> ++//        for (int i1 = 0; i1 < 7; ++i1)
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/gen/ChunkGeneratorHell.java.patch
> ++//        if (this.rand.nextBoolean())
comment in patch

2017-07-31 04:29 UTC, mezz commented on patches/minecraft/net/minecraft/world/gen/ChunkGeneratorHell.java.patch
> ++//        if (this.rand.nextBoolean())
comment in patch

2017-07-31 04:30 UTC, mezz commented
I think having the original position where a tree was generating (for example) is fine. However we _need_ the original chunk position for decoration, or else we do not know the bounds we can generate in before overflowing into ungenerated chunks.

2017-07-31 04:33 UTC, mezz commented
One example of a place where we do not have the chunk pos is `BiomeForest#addMushrooms`, it calls `TerrainGen.decorate` using the position of the mushroom or tree and not the chunk pos.

2017-07-31 16:08 UTC, Ivorforce commented
> One example of a place where we do not have the chunk pos is BiomeForest#addMushrooms, it calls TerrainGen.decorate using the position of the mushroom or tree and not the chunk pos.

Aha, true. That's not the intended parameter, just a bug. I will commit a fix.

2017-10-04 06:53 UTC, mezz commented
Please resolve the merge conflict in `ChunkGeneratorHell.java.patch`

2017-10-04 06:53 UTC, mezz approved these changes

2017-11-04 05:02 UTC, liach commented
@Ivorforce Would you redo the patches?

2017-11-04 05:53 UTC, mezz commented
If this ends up getting closed for lack of activity, I can update it and resubmit. 
I'll wait for Ivorforce for now though.

2017-11-04 16:27 UTC, Ivorforce commented
My Forge instance kept fucking up but I hope I fixed it now. Should be mergable again.

2017-11-05 22:23 UTC, mezz commented
Tested (worldgen is the same, doesn't crash) and looks good to me.

2017-11-09 22:44 UTC, LexManos commented on patches/minecraft/net/minecraft/world/biome/BiomeForest.java.patch
>                   {
This is wrong.

2017-11-09 22:48 UTC, LexManos commented on patches/minecraft/net/minecraft/world/biome/BiomeForest.java.patch
> ++                for (int f_i_o = net.minecraftforge.event.terraingen.TerrainGen.decorate(p_185379_1_, p_185379_2_, p_185379_3_, net.minecraftforge.event.terraingen.DecorateBiomeEvent.Decorate.EventT
The layout makes the logic for this very annyoing to read. Cleanup should be done. It also doesn't actually mimic the real logic. You probably want something like shroom = decorate(shroom, rand(20) == 0 ? 1 : 0; if (shroom > 0) else tree

2017-11-09 23:20 UTC, Ivorforce commented
@mezz Lex says to pull it for the 1.13 update but not in 1.12 as it has breaking changes

2017-11-10 05:04 UTC, mezz commented
Ok, that makes sense to me. There are a lot of changes here and probably a couple that could be considered breaking because they change the context of the event slightly.

Would you mind making a separate 1.12 PR to fix events that get the wrong blockpos passed to them? If you are not interested, I might work on it when I get a chance.

2017-11-21 15:16 UTC, Ivorforce commented
Done with the import changes. 

@mezz Not sure what you mean by 'wrong blockpos'?

2017-11-22 05:20 UTC, mezz commented
From earlier conversation (above),
> One example of a place where we do not have the chunk pos is BiomeForest#addMushrooms, it calls TerrainGen.decorate using the position of the mushroom or tree and not the chunk pos.

2017-12-03 15:39 UTC, Ivorforce commented
I can't use the events until the change anyway so that's not really interesting to me.

2019-08-29 01:42 UTC, closed without merging