Added a cloud renderer that uploads geometry to the GPU.
MinecraftForge/MinecraftForge pull request #4143
Opened 2017-07-06 19:34 UTC by Zaggy1024

#3578 updated to 1.12.x.

There are multiple commits on that previous pull request to see the changes over time to the cloud renderer.

2017-07-07 03:43 UTC, p455w0rd commented
shouldn't en_US.lang be en_us.lang in 1.12? or does that only apply to mods?

2017-07-07 03:47 UTC, liach commented
@p455w0rd It seems this is an existing bug in forge.

2017-07-07 03:56 UTC, Zaggy1024 commented
Don't look at me, all I did was edit the file. :P

2017-07-12 04:27 UTC, mezz commented
Tested.

Before:
![2017-07-11_21 23 30](https://user-images.githubusercontent.com/916092/28101749-69880332-667f-11e7-9332-5c5b606253ce.png)

After:
![2017-07-11_21 25 34](https://user-images.githubusercontent.com/916092/28101774-844e8b64-667f-11e7-8cbd-42c5da668890.png)

I noticed the vanilla clouds and fastclouds do not line up when you switch modes, is that intentional or is there an issue?

2017-07-12 04:36 UTC, mezz commented
I also see this in the log, it should be resolved somehow:
```
[21:34:31] [main/ERROR] [FML]: Unable to determine registrant mod for net.minecraftforge.client.CloudRenderer@78029cf3. This is a critical error and should be impossible
java.lang.Throwable: null
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:74) [EventBus.class:?]
	at net.minecraftforge.client.CloudRenderer.<init>(CloudRenderer.java:84) [CloudRenderer.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:463) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:552) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:377) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [Forge_main/:?]
	at GradleStart.main(GradleStart.java:26) [Forge_main/:?]
```

2017-07-12 04:37 UTC, mezz commented
I also see this in the log, it should be resolved somehow:
```
[21:34:31] [main/ERROR] [FML]: Unable to determine registrant mod for net.minecraftforge.client.CloudRenderer@78029cf3. This is a critical error and should be impossible
java.lang.Throwable: null
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:74) [EventBus.class:?]
	at net.minecraftforge.client.CloudRenderer.<init>(CloudRenderer.java:84) [CloudRenderer.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:463) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:552) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:377) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [Forge_main/:?]
	at GradleStart.main(GradleStart.java:26) [Forge_main/:?]
```

2017-07-30 06:45 UTC, mezz commented
@Zaggy1024 any update?

2017-07-30 17:29 UTC, Zaggy1024 commented
I'm not seeing either of those issues in my development environment... The clouds appear to be identical if I make it switch them off and on every half second.

The only errors I'm seeing are for model loading that's unrelated to the cloud renderer.

2017-07-30 23:17 UTC, mezz requested changes
Tested again with a fresh workspace and the clouds line up fine but there is still a console error.

2017-07-30 23:17 UTC, mezz commented on src/main/java/net/minecraftforge/client/CloudRenderer.java
> +        MinecraftForge.EVENT_BUS.register(this);
I tried again with a new workspace but this line still causes an error log.
There is no active mod container when this is called.

```
[main/ERROR] [FML]: Unable to determine registrant mod for net.minecraftforge.client.CloudRenderer@72f05bd9. This is a critical error and should be impossible
java.lang.Throwable: null
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:74) [EventBus.class:?]
	at net.minecraftforge.client.CloudRenderer.<init>(CloudRenderer.java:84) [CloudRenderer.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.onInitializationComplete(FMLClientHandler.java:463) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:552) [Minecraft.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:377) [Minecraft.class:?]
	at net.minecraft.client.main.Main.main(Main.java:118) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97) [Forge_main/:?]
	at GradleStart.main(GradleStart.java:26) [Forge_main/:?]
```

I think it has to be called from somewhere when FML is the active mod container.
Make sure you are testing with your branch merged into the latest for the 1.12.x branch.

2017-09-23 19:00 UTC, bs2609 commented
Any update on this?

2017-09-26 18:19 UTC, Zaggy1024 commented
I was never able to reproduce the issue... I'm going to try rebasing one more time and see if it happens this time, but if not, I don't know what I can do about it, except trial and error having someone else test it.

2017-09-26 22:31 UTC, Zaggy1024 commented
Actually, it looks like what's happening on your end shouldn't even be possible, since it's stepping through the stack checking for packages owned by a mod, and it's not made to ignore the class that's finding the package owners, so it should *always* find the owner as FML, if fml.common is part of the FML mod container. I'm not sure how this code was meant to work, but it seems to me it needs to be made to ignore a certain number of classes off the top of the stack trace...

Either way, I'm not sure why it would fail on your end, it might be worth debugging in your IDE to see what it's doing. The relevant code is https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/java/net/minecraftforge/fml/common/LoadController.java#L388.

2017-09-29 00:04 UTC, Zaggy1024 commented
Actually, I'm wondering if it would be best to register it in FMLContainer. Is that bad practice or would that work? Another option I guess would be to set the active mod container in FMLClientHandler, but I'm not sure of the best way to get the instance of FMLContainer to set it to.

2017-09-29 02:57 UTC, LexManos commented
ForgeInternalHandler

2017-09-29 16:28 UTC, bs2609 commented on src/main/java/net/minecraftforge/client/CloudRenderer.java
> +            vbo = new net.minecraft.client.renderer.vertex.VertexBuffer(FORMAT);
You don't need the fully-qualified name here now that this is targeting 1.12 - might as well take advantage of the name change.

2017-10-11 17:52 UTC, bs2609 commented
@mezz, mind looking at this again now it's been updated?

2017-10-15 01:53 UTC, mezz commented
Tested and looks good to me.

2017-10-15 01:53 UTC, mezz approved these changes

2017-10-31 18:45 UTC, merged

2017-11-02 06:14 UTC, mezz commented
🎉