Log a big warning if a mod violates against the new coremod rules
MinecraftForge/MinecraftForge pull request #4146
Opened 2017-07-07 18:48 UTC by ichttt

This will (hopefully) force the modders to adapt to the new coremod rules as pointed out [here](http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/).

2017-07-07 19:41 UTC, williewillus commented on src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java
> +                }
"should be to be"?

2017-07-07 19:48 UTC, ichttt commented on src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java
> +                }
woops, should read "should be signed"

2017-07-07 20:26 UTC, liach commented on src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java
> +                    FMLLog.bigWarning("The coremod {} ({}) is not signed! Coremods should be signed, and this will required in 1.13", coreModName, coreModClass);
"will be required"

2017-07-08 04:25 UTC, mezz commented
Those are coremod best practices, not rules. If someone wants to ignore them that's their decision.
Warnings and info are fine but we have no intention of crashing the game if coremods do not comply with best practices.

2017-07-08 16:49 UTC, killjoy1221 commented
Is it known if mods inside coremods will still be supported at a future date? If not, it would be a good idea to mention it.

2017-07-08 19:18 UTC, LexManos commented
No, the plan is to remove that in the re-write and move to the jar-in-jar system.

2017-07-09 06:08 UTC, mezz requested changes

2017-07-09 06:08 UTC, mezz commented on src/main/java/net/minecraftforge/fml/relauncher/CoreModManager.java
> +                    FMLLog.log.warn("Found FMLCorePluginContainsFMLMod marker in {}. This is not recommended, mods should be in an other jar as the coremod.",
The text might be better this way:
`This is not recommended, @Mods should be in a separate jar from the coremod.`

2017-07-13 05:27 UTC, mezz approved these changes

2017-07-20 21:32 UTC, merged