Support oredicted dyes for shulkerbox recipes
MinecraftForge/MinecraftForge pull request #4223
Opened 2017-07-22 20:23 UTC by Landmaster

This fixes #4222 by slightly modifying the shulkerbox recipe so that it converts an ore-dicted dye itemstack to a metadata value, which is then converted to a dye color; the code for detecting the validity of a dye for the shulkerbox recipe was updated as well.

Tested with Actually Additions dyes.

2017-07-22 20:56 UTC, kashike requested changes

2017-07-22 20:56 UTC, kashike commented on src/main/java/net/minecraftforge/oredict/DyeUtils.java
> +package net.minecraftforge.oredict;
Missing license header.

2017-07-22 21:02 UTC, JamiesWhiteShirt commented
You should consider similarly patching RecipesArmorDyes, the recipe used for coloring leather armor.

RecipesArmorDyes would benefit from DyeUtils returning an EnumDyeColor instead of metadata. I have a recipe very much like that which would also benefit from it.

2017-07-22 21:20 UTC, KnightMiner commented
The banner recipe as well could have it's patch reduced by this util.  If we are converting dye recipes to a new system might as well do that

2017-07-22 21:22 UTC, Landmaster commented on src/main/java/net/minecraftforge/oredict/DyeUtils.java
> +package net.minecraftforge.oredict;
@kashike 62efbc9f1e82350366fe8a3120bdd3a3244f354b

2017-07-22 22:10 UTC, Landmaster commented
@JamiesWhiteShirt Added `DyeUtils` hooks for…pretty much every dye recipe except for the banner one. I'll patch the banner one shortly.

2017-07-22 22:21 UTC, JamiesWhiteShirt reviewed
Maybe add a method `DyeUtils.isDye` to simplify the other stuff.

2017-07-22 22:21 UTC, JamiesWhiteShirt commented on patches/minecraft/net/minecraft/item/crafting/ShulkerBoxRecipes.java.patch
> ++                ItemStack itemstack3 = BlockShulkerBox.func_190953_b(EnumDyeColor.func_176764_b(net.minecraftforge.oredict.DyeUtils.metaFromStack(itemstack1).getAsInt()));
Might as well use `DyeUtil.colorFromStack` here.

2017-07-22 22:21 UTC, JamiesWhiteShirt commented on patches/minecraft/net/minecraft/item/crafting/RecipesArmorDyes.java.patch
> ++                    float[] afloat = EnumDyeColor.func_176764_b(net.minecraftforge.oredict.DyeUtils.metaFromStack(itemstack1).getAsInt()).func_193349_f();
Might as well use `DyeUtil.colorFromStack` here.

2017-07-23 01:09 UTC, howtonotwin commented
`.DS_Store` should not be in `.gitignore`. `.gitignore` is for files generated by the project itself. For Forge, this includes build files and generated IDE configurations. Ignores that are not part of the project should go in other places. For a Mac, `core.excludesfile` should be set to globally ignore `.DS_Store`s in all git repositories, and if you have a repo specific file you want ignored, it goes in `.git/info/excludes`.

Otherwise stated:

- System-wide ignores (`.DS_Store`, MyHomebrewIDE's configuration, etc.) go in `core.excludesfile`
- Project-wide ignores (build files, test output, etc.) go in `.gitignore`
- Repo-wide ignores (a `.vimrc` tailored for just you and just this project, or something) go in `.git/info/excludes`

2017-07-30 06:20 UTC, mezz requested changes

2017-07-30 06:20 UTC, mezz commented on patches/minecraft/net/minecraft/item/crafting/RecipesBanners.java.patch
> ++                        final java.util.OptionalInt color = net.minecraftforge.oredict.DyeUtils.dyeDamageFromStack(itemstack2);
To simplify the patch, you should keep their convention of using `-1` instead of introducing `OptionalInt` here.

2017-07-31 00:34 UTC, Landmaster commented on patches/minecraft/net/minecraft/item/crafting/RecipesBanners.java.patch
> ++                        final java.util.OptionalInt color = net.minecraftforge.oredict.DyeUtils.dyeDamageFromStack(itemstack2);
@mezz Should the `DyeUtils#colorFromStack` method, which currently returns an `Optional<EnumDyeColor>`, also be changed to return just an `EnumDyeColor` with a sentinel (`null`) for a non-dye?

2017-07-31 00:36 UTC, mezz commented on patches/minecraft/net/minecraft/item/crafting/RecipesBanners.java.patch
> ++                        final java.util.OptionalInt color = net.minecraftforge.oredict.DyeUtils.dyeDamageFromStack(itemstack2);
You can do whatever you want for those, you just need to make an extra method that follows the vanilla convention here so the patch is small.

2017-07-31 05:29 UTC, mezz approved these changes

2017-07-31 05:45 UTC, mezz commented
Tested and looks good to me.

2017-08-01 18:00 UTC, LexManos commented
Wow minecraft is really shitty about how it deals with dyes.. they need to stick to one design/access scheme and not screw with things 4 different ways... oh well guess this works for now.

2017-08-01 18:03 UTC, merged