Add ReloadEvent. Resolves #4217
MinecraftForge/MinecraftForge pull request #4234
Opened 2017-07-25 16:01 UTC by rguy96

This actually adds two events, ReloadEvent.Pre, which is called before advancements, loot tables, functions, and ~~[recipes](https://github.com/MinecraftForge/MinecraftForge/pull/4229)~~ anything else is reloaded, and ReloadEvent.Post, which is called after everything has been reloaded.

2017-07-25 16:07 UTC, Choonster commented
It looks like you forgot to include the patches.

2017-07-25 16:18 UTC, kashike requested changes

2017-07-25 16:18 UTC, kashike commented on src/main/java/net/minecraftforge/event/ReloadEvent.java
> +package net.minecraftforge.event;
Missing license header.

2017-07-26 00:16 UTC, williewillus commented on src/main/java/net/minecraftforge/event/ReloadEvent.java
> +public class ReloadEvent extends Event
needs documentation saying under what circumstances this is fired, mentioning at some point that it guards the assets reloaded by the vanilla `/reload` command

2017-07-26 19:23 UTC, killjoy1221 commented on src/main/java/net/minecraftforge/event/ReloadEvent.java
> +public class ReloadEvent extends Event
Agreed. If you don't document it, someone might think it's for reloading the mod like in bukkit.

2017-07-26 19:27 UTC, killjoy1221 commented
In all likeliness, Mojang is probably going to be making a better resource system on the server side rather than just having a bunch of folders. With it, we can probably use the existing resource reload listener.

This still has use in 1.12, but I won't expect to still have it in 1.13

2017-10-11 07:31 UTC, closed without merging