Added AdvancementEvent
MinecraftForge/MinecraftForge pull request #4257
Opened 2017-07-30 00:31 UTC by Chikachi

This adds two events related to Advancements.

AdvancementEvent.Pre which triggers when a player has completed an advancement, but before the player receives the rewards. This is cancelable.
AdvancementEvent.Post which triggers after the player has received the rewards for completing an advancement.

2017-07-30 17:26 UTC, liach commented
Rename it to GrantAdvancementEvent is better.

2017-07-30 20:17 UTC, Madsthunder requested changes
The pr looks good, but it looks like some unnecessary patches were accidentally added.

2017-07-30 20:17 UTC, Madsthunder commented on patches/minecraft/net/minecraft/advancements/PlayerAdvancements.java.patch
> + import org.apache.logging.log4j.LogManager;
Try getting rid of these imports...

2017-07-30 20:17 UTC, Madsthunder commented on patches/minecraft/net/minecraft/advancements/PlayerAdvancements.java.patch
> ++                if (MinecraftForge.EVENT_BUS.post(new AdvancementEvent.Pre(this.field_192762_j, p_192750_1_))) {
...change this line to `net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(new net.minecraftforge.event.entity.player.AdvancementEvent.Pre(this.field_192762_j, p_192750_1_))) {`, ...

2017-07-30 20:17 UTC, Madsthunder commented on patches/minecraft/net/minecraft/advancements/PlayerAdvancements.java.patch
> ++                MinecraftForge.EVENT_BUS.post(new AdvancementEvent.Post(this.field_192762_j, p_192750_1_));
...And change this line to `net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(new net.minecraftforge.event.entity.player.AdvancementEvent.Post(this.field_192762_j, p_192750_1_));`

2017-07-30 21:49 UTC, MiraWaNeko commented
@liach I agree, I will commit the namechange in a moment
@Madsthunder It seems like you're suggesting changes that exist in the second commit. Can you check?

2017-07-30 21:57 UTC, Chikachi commented
@liach Upon further thinking, would `AdvancementGrantEvent` maybe be better?
This would make it more in line with other events where they starts with what the event overall is about and then the action, such as `LivingDeathEvent` and `LivingDropsEvent`.

2017-07-30 22:09 UTC, Madsthunder commented
@Chikachi You're right, I had a slight derp...

2017-08-02 15:54 UTC, howtonotwin requested changes

2017-08-02 15:54 UTC, howtonotwin commented on src/main/java/net/minecraftforge/event/entity/player/AdvancementGrantEvent.java
> +    public static class Pre extends AdvancementGrantEvent
There should be a Javadoc on this that explicitly states that this event is cancelable and what happens when this event is canceled.

2017-08-13 21:24 UTC, TechnicianLP commented
- 1.13 will probably cause problems with this pr as advancements a mod expects can be missing/renamed via datapacks - nevertheless the `Post`-Event is usefull for other datapack-defined systems depending on advancements
- Why exactly is the Pre one neccessary? if you dont want the player to get the advancement yet  you should add an additional criterion to it instead

2017-08-21 16:03 UTC, Chikachi commented
The `Pre` isn't neccessary, I added it simply because there might be a use case that I hadn't thought about.

2017-09-15 04:23 UTC, BillyGalbreath commented
Any word on this? I'm eager to use this API

2017-10-15 06:20 UTC, liach commented
This patch needs to get fixed.

2017-10-24 03:44 UTC, mezz commented
Superseded by #4467

2017-10-24 03:44 UTC, closed without merging