Reduce the number of quads generated by ItemLayerModel
MinecraftForge/MinecraftForge pull request #4332
Opened 2017-08-22 08:45 UTC by bs2609

As seen in #3246, item models are something that can potentially consume a lot of memory.

As well as moving from unpacked to packed quads, we can also just reduce the number of quads in total, which is what this PR sets out to achieve.

Rather than generating quads immediately, the original code now just marks which side faces will be visible. Then a second pass is made, using the collected data to combine adjacent faces into a single quad before building. The existing quad building logic is mostly unchanged, just tweaked to allow for quads of larger sizes.

Here's a [gist](https://gist.github.com/bs2609/8894e832012f7674e4c6fade9177ac01) of the reduction in generated quads for vanilla's item models. (~40% reduction across all item models)

Should also resolve #3460 for good measure.

2017-08-22 09:16 UTC, kashike requested changes

2017-08-22 09:16 UTC, kashike commented on src/main/java/net/minecraftforge/client/model/ItemLayerModel.java
> +        for (EnumFacing facing : Arrays.asList(EnumFacing.UP, EnumFacing.DOWN))
You should cache this (as well as the one below) as fields.
```java
private static final EnumFacing[] HORIZONTALS = new EnumFacing[]{EnumFacing.UP, EnumFacing.DOWN};
private static final EnumFacing[] VERTICALS = new EnumFacing[]{EnumFacing.WEST, EnumFacing.EAST};
```

2017-08-22 09:17 UTC, kashike commented on src/main/java/net/minecraftforge/client/model/ItemLayerModel.java
> +            return v*vMax + u;
missing spaces around `*`

2017-08-31 03:54 UTC, mezz commented
Tested and wasn't able to spot any issues.

2017-09-06 21:05 UTC, LexManos commented
What are the memory savings?
What is the speed cost?
Give some number, profile it, SOMETHING to justify this.

2017-09-10 22:01 UTC, bs2609 commented
Looking at some heap dumps taken from vanilla+forge runs, here's the relevant memory usage numbers.

For 768 `BakedItemModel` instances, the corresponding `UnpackedBakedQuad` numbers were:
* Forge 2475: 25,542 instances, 32.08 MB heap used
* This PR: 15,476 instances, 19.45 MB heap used

The total heap usage of `BakedItemModel` falls from 33.01 MB to 20.30 MB, a 12.71 MB saving (38.5%).

Model baking took ~0.5s in both cases, and given the variability, it seems hard to ascertain any exact impact from these changes.

2017-10-02 23:43 UTC, merged

2017-10-04 22:51 UTC, bs2609 commented
Followup testing with a modpack now that this was merged:

22,484 `BakedItemModel` instances in both cases.

Heap `UnpackedBakedQuad` numbers were:
* Forge 2497: 805,216 instances, 1012.3MB heap used
* Forge 2498: 521,964 instances, 656.3MB heap used

The total heap usage of `BakedItemModel` fell from 875MB to 554.9MB, a saving of 320.1MB (36.6%).

2017-10-05 03:58 UTC, williewillus commented
that's awesome savings, how big was the pack?
I wonder how much more you save with something like foamfix's deduplication.

2017-10-05 04:04 UTC, mezz commented
Agreed, that is very nice!

2017-10-05 04:04 UTC, bs2609 commented
Pack's basically All The Mods 3, minus FoamFix and with it's own Forge versions.