PotionAppliedEvent and PotionRemovedEvent
MinecraftForge/MinecraftForge pull request #4385
Opened 2017-09-09 08:52 UTC by IceMetalPunk

Just a simple hook into the methods for adding and removing potion effects from entities. The PotionRemovedEvent comes with a boolean for whether it was cured or not (i.e. removed or simply ran out of time). And the PotionAppliedEvent can have its potion effect set with the setter to replace the effect entirely. If the PotionAppliedEvent is canceled, the potion is not applied. The PotionRemovedEvent can also be canceled, but it only has an effect if it's trying to be cured (in which case, if canceled, the effect won't be cured). It wouldn't make much sense to prevent the removal of an effect that's just run up its duration, so in that case, canceling it does nothing.

2017-09-09 08:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=4385) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=4385) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=4385) it.</sub>

2017-09-09 09:57 UTC, JamiesWhiteShirt requested changes
Your patches are very broken. You need to check your formatting settings and make sure you are not adding any import statements.

All the events need proper javadocs like all other events. I would also suggest creating separate event classes for potion effect expiration and potion effect curing to make the cancellation behavior static.

Perhaps use inner classes for the events that extend `PotionEvent`.

2017-09-09 09:57 UTC, JamiesWhiteShirt commented on src/main/java/net/minecraftforge/event/entity/living/potions/PotionAppliedEvent.java
> +package net.minecraftforge.event.entity.living.potions;
Missing license header

2017-09-09 09:57 UTC, JamiesWhiteShirt commented on src/main/java/net/minecraftforge/event/entity/living/potions/PotionEvent.java
> +package net.minecraftforge.event.entity.living.potions;
Missing license header

2017-09-09 09:57 UTC, JamiesWhiteShirt commented on src/main/java/net/minecraftforge/event/entity/living/potions/PotionRemovedEvent.java
> +package net.minecraftforge.event.entity.living.potions;
Missing license header

2017-09-09 09:57 UTC, JamiesWhiteShirt commented on src/main/java/net/minecraftforge/event/entity/living/potions/PotionEvent.java
> +public class PotionEvent extends LivingEvent {
I would suggest calling this `PotionEffectEvent`. `PotionEffect` and `Potion` are different classes, and if events for `Potion` were added, there would be a name conflict.

2017-09-11 16:33 UTC, liach requested changes
My browser gets slow immediately when I view your changes... Redo it.

2017-09-13 11:35 UTC, loordgek commented
> PotionRemovedEvent can also be canceled, but it only has an effect if it's trying to be cured (in which case, if canceled, the effect won't be cured). It wouldn't make much sense to prevent the removal of an effect that's just run up its duration, so in that case, canceling it does nothing.

that looks bad just use a potioncured event so you can get the itemstack that was used to cure with

2017-09-23 06:13 UTC, mezz commented
It looks like your editor has auto-formatting enabled, so the patch files have many changes to imports and spacing.
The patch changes must be minimal and can't have new imports, please re-implement this change with that in mind.

2017-10-30 07:32 UTC, closed without merging