[1.12.x] Added block model flag to allow exceeding of the default JSON model size limits.
MinecraftForge/MinecraftForge pull request #4420
Opened 2017-09-24 06:05 UTC by elucent

By default, the JSON block model format restricts models to a 3x3x3 blockspace. This patch modifies the deserializer classes in both ModelBlock and BlockPart to introduce a new JSON boolean flag "limitsize" that can allow these restrictions to be bypassed for certain models.

Similar to controlling ambient occlusion on a model, "limitsize" defaults to true, and will result default vanilla behavior when true. When false, ModelBlock.limitSize is appropriately assigned within the deserializer's getModelElements call. This field is checked in BlockPart, and if false, each point being checked will bypass the normal size restrictions. After getModelElements, ModelBlock.limitSize is reset to the default value and will uphold vanilla size restrictions.

Since large block models have several caveats, particularly regarding lighting, and _especially_ regarding ambient occlusion, if the "ambientocclusion" flag is true and the "limitsize" flag is false in a block model, the block model will throw an appropriate exception and fail to load.

For a specific use case for this functionality, the ability to use larger JSON models should allow for their much more effective use in multiblock structures. Mods like Immersive Engineering or Magneticraft have become hugely popular for their use of multiblocks but make use of OBJ models. With this size restriction out of the way, JSON models should become a viable way to accomplish similar visuals, in a much more modding-adjacent and accessible format.

Screenshot of a large JSON model making use of the code in this PR:

![image](https://user-images.githubusercontent.com/9532786/30779933-beb6c7d0-a0cc-11e7-9d6f-1fe0a312b8dd.png)

2017-09-24 17:12 UTC, bs2609 commented on patches/minecraft/net/minecraft/client/renderer/block/model/ModelBlock.java.patch
> ++            	limitSize = getSizeLimited(p_178325_2_);
Indentation's gone a bit wonky here

2017-09-24 17:19 UTC, kashike requested changes

2017-09-24 17:19 UTC, kashike commented on patches/minecraft/net/minecraft/client/renderer/block/model/ModelBlock.java.patch
> ++            protected boolean getSizeLimited(JsonObject object)
`isSizeLimited`

2017-09-27 03:54 UTC, mezz requested changes
Looks good, please fix the issues pointed out by kashike and bs2609.

2017-11-03 06:42 UTC, closed without merging