Patch BlockDynamicLiquid#isBlocked to use state sensitive material check
MinecraftForge/MinecraftForge pull request #4474
Opened 2017-10-20 23:38 UTC by InsomniaKitten

This pull request resolves #4473

2017-10-20 23:46 UTC, InsomniaKitten commented
Should the state be declared once in its own field for this? I'm not sure how much it would affect performance declaring it twice for `material` and `block` individually.

2017-10-20 23:53 UTC, covers1624 commented
Is this really needed no-one should have custom impl's of BlockDynamicLiquid as forge has it's own fluid block base class.

2017-10-20 23:55 UTC, InsomniaKitten commented
It causes issues when a mod provides different block materials based on state values. Vanilla's fluid block is currently only respecting the material passed in the super of the Block constructor, which I personally am not relying on for some of my blocks, that use a PropertyEnum for variants, all of which pass their own material to the state sensitive method in Block.

2017-10-20 23:57 UTC, InsomniaKitten commented
For example passing `Material.STONE` to the constructor and then having a state variant that passes `Material.CIRCUITS` to `Block#getMaterial(IBlockState)`, will be treated as `Material.STONE` by the `BlockDynamicLiquid#isBlocked`

2017-10-21 00:19 UTC, covers1624 commented
Right, but why use BlockDynamicLiquid over forges implementation?

2017-10-21 00:21 UTC, InsomniaKitten commented
I am not. But vanilla uses it for water and lava. This method not being state sensitive with its material check causes problems between modded blocks and vanilla fluids.

2017-10-21 00:24 UTC, covers1624 commented
Ohhhh, was confused as to what the method actually did, don't have code infront of me.. in that case patch looks good to me.

2017-10-21 05:36 UTC, mezz requested changes
Makes sense, just needs a minor change to the patch to make it smaller and simpler to update.

2017-10-21 05:36 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockDynamicLiquid.java.patch
> ++        Material material = p_176372_1_.func_180495_p(p_176372_2_).func_185904_a();
Please move this line down so the two patched lines are right next to each other

2017-10-21 18:05 UTC, mezz approved these changes

2017-10-31 17:40 UTC, closed without merging