Add event to allow for mods to cancel the loading of advancements.
MinecraftForge/MinecraftForge pull request #4541
Opened 2017-11-22 04:13 UTC by Blargerist

Adds a basic event, fired during the three loops which load advancement Json files and use them to build Advancement$Builder objects, immediately after the ResourceLocation is created. If canceled, the loop is continued, causing the advancement to not be loaded/built.

This is useful for removing advancements before they are even loaded, bypassing extreme log spam from advancement parsing errors, as seen in #4500.

Do note, the test mod has an enable boolean, which is currently set to off. If you're going to test it, please be sure to turn it on first.

2017-11-23 02:08 UTC, williewillus commented
if we're going to add an event, why not develop into a full event and allow editing of the loaded advancement?

2017-11-23 06:25 UTC, Blargerist commented
Assuming you mean "allow editing of the advancement being loaded": Why? What's a case where that would be required?

2017-11-23 07:25 UTC, williewillus commented
My point is "what's the point of a singular event like that just lets you do *one* thing?". If we're going to go through the effort of patching something into this process might as well spend extra time and do it right. See `LootTableLoadEvent` and friends. Same use cases are applicable, dynamic scanning or generation.

2017-11-23 15:26 UTC, Blargerist commented
I can see how that might be useful. The event could be moved between the file being read and the Advancement$Builder being constructed, giving access to a JsonObject for the advancement, which could be read/modified as needed. If the powers that be would prefer that, I can make the necessary changes.

2017-12-26 21:12 UTC, josephcsible commented
Not stale, just awaiting review

2017-12-26 23:04 UTC, mezz requested changes
Looks good, just needs a copyright header.

2017-12-26 23:04 UTC, mezz commented on src/main/java/net/minecraftforge/event/advancement/AdvancementAboutToLoadEvent.java
> +package net.minecraftforge.event.advancement;
Please copy the header comment from another file and put it at the top of this file.

2017-12-27 01:24 UTC, mezz commented
Discussed with Lex and we think it's probably better to solve this issue (#4541) another way.
In 1.13 with data packs, there will be some other way of handling this because recipes can be added and removed by adding and removing their JSON.
So for now, just log the syntax errors less noisily.

Something like this: 

```
[14:00:28] [Server thread/ERROR]: Parsing error loading built-in advancement minecraft:recipes/transportation/spruce_boat: com.google.gson.JsonSyntaxException: Unknown recipe 'minecraft:spruce_boat'
```

That will cut your [example error log](https://gist.github.com/Blargerist/f43b34a6b29829a8bc5b4dd7a7acb614#file-gistfile1-txt-L4702) down from 4702 lines to 193 lines.

Alternatively you can collate them so that only the first few errors from each domain (i.e. 'minecraft') are logged together after all the advancements are loaded.

2017-12-31 19:14 UTC, Blargerist commented
Alright, I'll close this then, thanks for the response. I'll throw up a new PR for the quieter logging when I have time.

2017-12-31 19:14 UTC, closed without merging