Added a TileEntity parameter to Block.getDrops(). Closes #4674
MinecraftForge/MinecraftForge pull request #4717
Opened 2018-01-30 20:22 UTC by canitzp

This pr does add a TileEntity parameter to the Block.getDrops method. The old methods are still there to not break mods. It also adds a TileEntity variable to the HarvestBlock Event.
This is is important, cause like already tolded in #4674 , the trying to get the TileEntity with world.getTileEntity is null everytime. This is caused by Minecraft, who does remove the TileEntity before getDrops is called. This can be changed with some trickery, without this pr, but this would cause more or less a mess in all mods, since most mods wants to drop some things, depending on the TileEntity.

2018-01-30 20:38 UTC, williewillus commented
I think there's a cleaner way to do this (I'll give it a shot tonight)

2018-01-30 20:42 UTC, canitzp commented
It looks like a lot, but it isn't that much. Most of the things I've done to not break compatability with Minecraft (which I could change all) and Mods

2018-01-30 21:11 UTC, LexManos commented
First off, you randomly pick to put the new argument at the second argument... No new arguments to functions go to the end... Just makes the upgrading process for both us and Modders much easier.
Secondly, https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/patches/minecraft/net/minecraft/block/BlockFlowerPot.java.patch#L40-L53 seems simple enough to do on the blocks end, why does it need to be this complex?

2018-01-31 07:53 UTC, raoulvdberge commented
The BlockFlowerPot way of doing things is even more complex and confusing.

2018-01-31 16:20 UTC, williewillus commented
@canitzp consider using a threadlocal set in harvestBlock (like the `harvesters` variable) so you don't have to patch dropBlockAsItem, just have the old getDrops read from the threadlocal then pass it to the new getDrops.

2018-01-31 18:33 UTC, canitzp commented
This is worth a look and I also thinked about it, but I decided against it since I'm not exactly sure how ThreadLocal works, but I should be able to find it and its benifits out

2018-01-31 20:19 UTC, canitzp commented
I now made the TileEntity a ThreadLocal variable to use two less methods, but I keep the new getDrops for easier use (and added EntityPlayer as parameter too) and also the Harvest Event has the TileEntity parameter now

2018-02-01 18:16 UTC, canitzp commented
@williewillus is this now like you meant it?

2018-02-03 05:24 UTC, mezz commented
You can see Forestry's nasty ThreadLocal hack for this with Leaves here:
https://github.com/ForestryMC/ForestryMC/blob/bb52acc67c38be508492aba8b0ba48298b14ebf8/src/main/java/forestry/arboriculture/blocks/BlockAbstractLeaves.java#L159-L205

It might still need the hack even with this PR because it needs access to the `Player` when figuring out the drops.

2018-02-03 08:37 UTC, canitzp commented
@mezz My new getDrops method does provide the tileentity and the player. Both variables are stored as ThreadLocal and I use them in the getDrops call, but you should also be able to use the player at your leafes since it is already a protected ThreadLocal variable inside the Block class

2018-02-04 03:50 UTC, mezz requested changes

2018-02-04 03:50 UTC, mezz commented on patches/minecraft/net/minecraft/block/Block.java.patch
> +-import com.google.common.collect.Sets;
Patches must not change any imports, please make sure to leave these as they were.

2018-02-04 03:51 UTC, mezz commented
Sounds good. Please update this to fix the imports and resolve merge conflicts.

2018-02-04 13:20 UTC, canitzp commented
My initial fork got fucked up completly and I couldn't repair it, so I rewrote this pr in #4727

2018-02-04 13:20 UTC, closed without merging