[1.12] Expose EntityRenderer.thirdPersonDistance
MinecraftForge/MinecraftForge pull request #4731
Opened 2018-02-07 14:24 UTC by alexander0153

Use-case:
Mods that add large ridable entities can increase the third-person camera distance. This could keep the camera from clipping into the entity.

2018-02-07 14:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=4731) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=4731) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=4731) it.</sub>

2018-02-07 14:32 UTC, PhiProven requested changes

2018-02-07 14:32 UTC, PhiPro95 commented on patches/minecraft/net/minecraft/client/renderer/EntityRenderer.java.patch
> ++    public float field_78490_B = 4.0F;
I think you should use `forge_at.cfg` for this.

2018-02-07 20:07 UTC, alexander0153 commented
I moved the access modifier changes into the `forge_at.cfg` file.

2018-02-08 06:15 UTC, mezz commented
Looks good to me.
Please create a small test mod which sets the `thirdPersonDistance` to show that it works as expected.
You can find the other test mods in `net.minecraftforge.debug`.
Your test mod should be disabled by default, see `AdvancementEventTest` as an example.

2018-02-08 09:46 UTC, alexander0153 commented
Cool! I also added a test mod now.

2018-02-10 19:12 UTC, gegy1000 commented
A common problem I've noticed with changing third person distance is mods can override each other easily. Would there be any way this could be more friendly to this kind of situation? Maybe a multiplier system instead of directly setting it, or possibly priority for which distance should be selected?
You could probably assume that the largest distance would be desired.

2018-02-10 20:36 UTC, alexander0153 commented
@gegy1000 I was originally thinking of an event, similar to `FOVUpdateEvent`, with which you could set a distance multiplier. However, I am not sure about performance implications of firing an event every frame, especially for a feature that only a few mods would use.

2018-02-11 07:11 UTC, gegy1000 commented
@alexander0153 Understandable. I don't think it needs to be fired every frame though -- it could be done each tick (interpolation is already done).

2018-02-11 08:48 UTC, alexander0153 commented
I added a new event: `CameraDistanceUpdateEvent`.

If a mod wants to increase the distance between camera and entity, it can call the `multiplyDistance(float multiplier)` method of that event (see the test mod).

As @gegy1000 suggested, this would allow multiple mods to change the distance without overwriting each other's changes.

2018-02-16 05:20 UTC, mezz commented
Having this event fired every tick seems a bit much compared to the old version.

I think the case of two mods competing on the camera distance needs to be considered more carefully.
If one mod wants to zoom out 2x and another mod wants the same thing, you end up with 4x and nobody really gets what they wanted.
If one mod wants 4x and another just always sets it to 2x then it will depend on whoever went last.

We should try to find a good way for mods to work together on this event, and if that doesn't work I think we should prefer just setting the field.

2018-02-16 05:50 UTC, williewillus commented
Anytime you have stacking modifiers on a single numeric value, attributes are a great system to use. Although, in this case the number is client side only which complicates things a bit.

2018-03-10 17:21 UTC, alexander0153 commented
I have reverted my changes for the new event. However, I don't know how to improve on this. I have not worked with attributes yet, but from what I see they are mainly used for entities. This is my first contribution to Minecraft Forge, so I am not sure what the best way to implement this is.

To me, setting the field directly seems like the simplest solution, especially if only very few mods would use this feature.

2018-04-16 18:19 UTC, closed without merging