Add functionality for harvesting more crops
MinecraftForge/MinecraftForge pull request #4745
Opened 2018-02-14 16:20 UTC by temp1011

Same as https://github.com/MinecraftForge/MinecraftForge/pull/4744 but with a branch that works.

2018-03-16 17:15 UTC, temp1011 commented
I still think this a useful feature for forge.

2018-03-21 04:40 UTC, mezz commented
Wont this cause issues with existing `EnumPlantType.CROP` vanilla plants?
What do villagers do when they encounter a melon or pumpkin stem?

2018-03-21 04:44 UTC, mezz requested changes

2018-03-21 04:44 UTC, mezz commented on patches/minecraft/net/minecraft/entity/ai/EntityAIHarvestFarmland.java.patch
> ++                        	world.func_180501_a(blockpos, ((net.minecraftforge.common.IPlantable)itemstack.func_77973_b()).getPlant(world, blockpos), 3); flag = true; }
This should probably be 3 lines, putting the closing brace at the end of a statement makes this section hard to understand.

2018-03-23 21:50 UTC, temp1011 commented
The villagers already automatically harvest anything that is an instance of `BlockCrops` and is fully grown. This PR just makes sure they also have the ability to replant the seeds of the crops that they do break. So I don't think melons and pumpkins will cause any problems since villagers don't break them anyway.

I've made the patch more readable. Hopefully it's not too large now.

2018-04-12 18:58 UTC, mezz commented
Tested and looks good to me.

2018-04-12 18:58 UTC, mezz approved these changes

2018-05-17 05:54 UTC, merged

2019-07-25 03:51 UTC, Snownee commented
Since villager naturally can only pick up vanilla item, so are these codes really reachable?

2019-07-25 10:07 UTC, temp1011 commented
This does seem problematic. I'll look into an updated and improved version of this once the planting interfaces are resolved.