Fix some IResources being leaked
MinecraftForge/MinecraftForge pull request #4806
Opened 2018-03-18 14:47 UTC by ichttt

This can be observed when setting the logger to DEBUG level in the log4j xml config, as minecraft replaces the inputstream with a leak tracking input stream when their logger has debug enabled.

2018-03-19 01:56 UTC, mezz requested changes
Looks good, I saw this too when messing with the logs.
Please update these to use try-with-resources.

2018-03-19 01:56 UTC, mezz commented on src/main/java/net/minecraftforge/client/model/ModelDynBucket.java
> +                empty = getResource(new ResourceLocation("textures/items/bucket_empty.png"));
Please use try-with-resources for these instead, it looks like this:
```java
try (
    IResource empty = getResource(new ResourceLocation("textures/items/bucket_empty.png"));
    IResource mask = getResource(new ResourceLocation(ForgeVersion.MOD_ID, "textures/items/vanilla_bucket_cover_mask.png"))
) {
    // do stuff
}
catch (IOException e)
{
    FMLLog.log.error("Failed to close resource. {}", e);
}
```

2018-03-19 09:40 UTC, ichttt commented
@mezz I switched everything but the B3D and OBJ over to try-with-resources, because B3D and OBJ try to search in alternative places if the first resource lookup fails

2018-03-20 05:48 UTC, mezz commented
Cool, looks good to me.

2018-03-20 05:48 UTC, mezz approved these changes

2018-03-20 05:58 UTC, merged