Add support for fluid colour handlers
MinecraftForge/MinecraftForge pull request #4952
Opened 2018-05-26 10:58 UTC by bs2609

Should fix #4948 in a way that doesn't break existing implementations. See the [comment](https://github.com/MinecraftForge/MinecraftForge/issues/4948#issuecomment-392252825) there for a description of the problem.

Firstly, the Forge bucket model is updated to provide a tint index to all quads, via updated `ItemTextureQuadConverter` methods.

Secondly, the bucket item now has an `IItemColor` implementation registered for it, which can apply colouring based on the `FluidStack` contents.

To do this in a way which doesn't cause issues for existing fluid/fluid container implementations, fluids are required to opt-in to this additional colouring.

This is done via an `IFluidColor` interface, which allows colouring based on `FluidStack`s, similar to the existing `IItemColor` interface. Fluids can register an implementation to the `FluidRegistry`, and the universal bucket will delegate to it in its `IItemColor` handler.

This way, existing fluids will be coloured via the existing model code, and any fluids which need special treatment can effectively 'opt-out' of this and instead opt-in to being handled by the `IItemColor` handler.

The `IItemColor` implementation used for the Forge bucket is made available for other mods, as well as a default `IFluidColor` implementation.

An existing test mod has been updated to demonstrate.

2018-05-26 11:06 UTC, asiekierka commented
I slightly dislike this solution. Specifically, because we now have two ways of colouring a Fluid: the IFluidColor, and the Fluid. I feel they're partially redundant.

I believe the better solution is to put the opt-in on the bucket model itself, which is probably a lot less confusing than putting it on the fluid. Alternately, we could move to IFluidColor entirely and deprecate the Fluid's existing getColor() mechanisms, but is this really a way to go?

2018-05-26 14:10 UTC, asiekierka commented
Looks good to me!

2018-05-26 18:57 UTC, mezz requested changes

2018-05-26 18:57 UTC, mezz commented on src/main/java/net/minecraftforge/client/model/ModelDynBucket.java
> +            builder.addAll(ItemTextureQuadConverter.convertTexture(format, transform, liquid, fluidSprite, NORTH_Z_FLUID, EnumFacing.NORTH, tint ? fluid.getColor() : ~0, 1));
I think I'd prefer  `0xffffffff` over `~0`.

2018-05-26 23:17 UTC, mezz approved these changes

2018-05-26 23:17 UTC, mezz commented
The code looks good to me. Can you post a before and after picture?

2018-05-27 13:40 UTC, bs2609 commented
Here's an example using a `Fluid` implementation with these overrides:
```java
@Override
public int getColor()
{
    return Color.MAGENTA.getRGB();
}

@Override
public int getColor(FluidStack stack)
{
    return Color.CYAN.getRGB();
}
```

![2018-05-27_14 36 02](https://user-images.githubusercontent.com/1447117/40586563-a39ec1ae-61bb-11e8-913b-d6b48bd30bd1.png)

The universal bucket has the "new" behaviour and the Forestry can behaves the same as the existing bucket would.

2018-05-27 23:10 UTC, mezz commented
You made this opt-in, what kind of issues do you think might come up if it was active by default?

2018-05-27 23:15 UTC, bs2609 commented
From my comment on #4948:
>This is because you want to use an IItemColor handler to have the appropriate context. Adding this to the general bucket requires removing the colour tint from the model, otherwise it'll be applied twice. However removing the tint from the model requires the other items using the model to have their own IItemColor handlers, or else the colour tint won't be applied at all.

2018-05-28 03:38 UTC, asiekierka commented
To tl;dr: Some other mods use ModelDynBucket on their own items and expect the tint to be applied in-model, not with an IItemColor.

It's opt-in as to not break them, and should stop being opt-in in 1.13.

2018-05-29 11:24 UTC, jabelar commented
I guess I missed it: what is the actual method for opting in to change the behavior? And the opt-in is applied to the bucket, but that setting is per-mod? Or per fluid? Like one mod can opt in and another one not opt in and both will work?

2018-05-29 17:17 UTC, asiekierka commented
>what is the actual method for opting in to change the behavior? 

After the changes? There's a new boolean in the ModelDynBucket.

> And the opt-in is applied to the bucket, but that setting is per-mod? Or per fluid?

Per-bucket-model-kind.

2018-05-29 19:08 UTC, KnightMiner commented
Specifically, it seems the opt in is in [this file](https://github.com/bs2609/MinecraftForge/blob/ba8f7245005677abd173b953e6d66d01f3eae548/src/main/resources/assets/forge/blockstates/dynbucket.json). This allows mods such as [my mod](https://github.com/KnightMiner/Ceramics/blob/1.12/src/main/resources/assets/ceramics/blockstates/clay_bucket.json) which use the bucket model to still work without needing updates (they will not have the NBT sensitive tints, but will still have what they had before this PR).

When I have time this evening I will verify my mod that uses the bucket model still works with this patch.

2018-06-28 12:06 UTC, asiekierka commented
@KnightMiner Have you verified it?

2018-07-06 03:04 UTC, KnightMiner commented
Sorry, completely forgot about this.

![image](https://user-images.githubusercontent.com/12155288/42357708-d521a618-809e-11e8-8a74-2dfcd0e62b29.png)

I just tested and everything works as expected. As seen in the image above on the right, both the Forge bucket and my custom bucket tint liquids property (one of the Tinkers Construct molten fluids).

For my test, I also made the test mod colored fluid return green in `getFluid(FluidStack)`. As was expected, my bucket returned the default pink from `getColor()` while the Forge one used the stack sensitive green color.

2018-07-10 04:43 UTC, mezz commented
Please run `gradle updateLicenses` to fix the license headers on your PRs that add new files.

2018-07-14 21:52 UTC, merged