Clean up and improve ICapabilityProvider javadocs
MinecraftForge/MinecraftForge pull request #4978
Opened 2018-06-13 00:19 UTC by tterrag1098

This PR aims to improve the contract definitions of the ICapabilityProvider interface. Previously there were some uncertainties when it came to how the two methods, `hasCapability` and `getCapability`, were related. Hopefully with these additions it is clearer to all. Due to the formatting changes and addition of HTML tags, here is the post-formatting before/after of the javadocs:

### `hasCapability` before:

<div class="block">Determines if this object has support for the capability in question on the specific side.
 The return value of this MIGHT change during runtime if this object gains or looses support
 for a capability.

 Example:
   A Pipe getting a cover placed on one side causing it loose the Inventory attachment function for that side.

 This is a light weight version of getCapability, intended for metadata uses.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>capability</code> - The capability to check</dd>
<dd><code>facing</code> - The Side to check from:
   CAN BE NULL. Null is defined to represent 'internal' or 'self'</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>True if this object supports the capability.</dd>
</dl>

___

### `hasCapability` after:

<div class="block">Determines if this object has support for the capability in question on the specific side.
 The return value of this MIGHT change during runtime if this object gains or loses support
 for a capability. It is not required to call this function before calling 
 <a href="#"><code>getCapability(Capability, EnumFacing)</code></a>.

 <p>
 <em>Example:</em>
   A Pipe getting a cover placed on one side causing it lose the Inventory attachment function for that side.
 </p><p>
 This is a light weight version of getCapability, intended for metadata uses.
 </p></div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>capability</code> - The capability to check</dd>
<dd><code>facing</code> - The Side to check from:
   CAN BE NULL. Null is defined to represent 'internal' or 'self'</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>True if this object supports the capability. If true, then <a href="#"><code>getCapability(Capability, EnumFacing)</code></a> 
 must not return null.</dd>
</dl>

___

### `getCapability` before:

<div class="block">Retrieves the handler for the capability requested on the specific side.
 The return value CAN be null if the object does not support the capability.
 The return value CAN be the same for multiple faces.</div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>capability</code> - The capability to check</dd>
<dd><code>facing</code> - The Side to check from:
   CAN BE NULL. Null is defined to represent 'internal' or 'self'</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>The requested capability. Returns null when <a href="#"><code>hasCapability(Capability, EnumFacing)</code></a> would return false.</dd>
</dl>

___

### `getCapability` after:

<div class="block">Retrieves the handler for the capability requested on the specific side.
 <ul>
 <li>The return value <strong>CAN</strong> be null if the object does not support the capability.</il>
 <li>The return value <strong>CAN</strong> be the same for multiple faces.</li>
 </ul></div>
<dl>
<dt><span class="paramLabel">Parameters:</span></dt>
<dd><code>capability</code> - The capability to check</dd>
<dd><code>facing</code> - The Side to check from, 
   <strong>CAN BE NULL</strong>. Null is defined to represent 'internal' or 'self'</dd>
<dt><span class="returnLabel">Returns:</span></dt>
<dd>The requested capability. Must <strong>NOT</strong> be null when <a href="#"><code>hasCapability(Capability, EnumFacing)</code></a> 
 would return true.</dd>
</dl>

___

2018-06-13 00:22 UTC, tterrag1098 commented
I am open to suggestions on wording and syntax, but the defined rules are not being changed here. This is simply clarifying the rules that have always existed. This PR was created after extensive conversation with Lex, and is accurate to his vision for the capability system.

Please do not comment/argue about the rules themselves here. Whether or not the capability rules should be changed is a separate issue.

2018-06-13 00:24 UTC, HenryLoenwind commented
I would amend `Determines if this object has support for the capability in question on the specific side.` with `<em>and</em> can supply a handler for that capability at this time.`

And another idea, open for discussion:

```
 * Note: Remember that getCapability() and hasCapability() will have to run the same logic
 * to determine if the capability is available (e.g. side checks, capability type comparison,
 * machine state checks, multiple super calls etc.). So by calling both, you're doubling the
 * workload for the CPU. By only calling one or the other, depending on whether you need
 * the handler or only want to know if it is supported, you're helping the players' tps.
```

2018-06-13 04:30 UTC, mezz requested changes
Please make a comparison to `Map#containsKey` and `Map#get` in the docs. Map is a simple thing that people already understand very well. You can elaborate on every edge case in modding but at the core of it people will understand better if they have a familiar model for it to follow.

2018-07-14 13:25 UTC, raoulvdberge commented
Can we mention something about caching / creating new instances of the capability?

2018-07-14 21:08 UTC, merged