Use registry names in crash reports
MinecraftForge/MinecraftForge pull request #5011
Opened 2018-07-03 07:14 UTC by Shadows-of-Fire

2018-07-03 07:16 UTC, liach commented
What if those registry entries are not yet in the registry so that they have null for their registry names? I would favor a static method handling such situation.

2018-07-03 07:19 UTC, Shadows-of-Fire commented
All but one of the changed entries (the one in RenderItem is the exception) have numerical IDs at the time of writing the crash report.  That would imply that they have already been registered to get to that point.

2018-07-03 07:59 UTC, liach commented
If a serial crash happens, as long as we can still spot what the broken item is, it will be fine.

2018-07-03 08:14 UTC, kashike commented
You're more than likely going to be breaking Hopper, and other crash report reading tools, by changing this - they won't be expecting a string.

2018-07-03 09:07 UTC, Shadows-of-Fire commented
I may be misunderstanding, but isn't hopper only for vanilla crashes?  It doesn't exactly come up as a concern.  
The changes made by this PR are for readability, any tool shouldn't be relying on the int ids for anything, as they change per-world in modded.

2018-07-03 14:47 UTC, liach commented
guess hopper just ignores crashes with is modded:definitely

2018-07-04 05:03 UTC, mezz commented
I think it would make sense to have this in addition to what vanilla adds, rather than replace vanilla's.

2018-07-04 06:11 UTC, Shadows-of-Fire commented
Perhaps, It could be argued that the unlocalized name is of some use for something (albeit not as useful as registry name), but the numerical ID and certainly the Item#toString versions should be replaced entirely, as they are basically worthless when reading a crash report.

2018-07-05 04:52 UTC, Shadows-of-Fire commented
The changes have been updated to be additions to vanilla.  I have also created [a gist](https://gist.github.com/Shadows-of-Fire/70b805ebdec822e2faf72468fd41ea9b) to showcase the changes.

2018-07-06 02:13 UTC, kashike requested changes

2018-07-06 02:13 UTC, kashike commented on patches/minecraft/net/minecraft/tileentity/TileEntity.java.patch
> ++                    	return String.format("ID #%d (%s // %s // %s)", i, Block.func_149729_e(i).func_149739_a(), Block.func_149729_e(i).getClass().getName(), Block.func_149729_e(i).getRegistryName())
Indentation change.

2018-07-14 21:30 UTC, LexManos commented on patches/minecraft/net/minecraft/client/renderer/RenderItem.java.patch
> ++                crashreportcategory.func_189529_a("Registry Name", () -> p_184391_2_.func_77973_b().getRegistryName().toString());
NPE

2018-07-14 21:32 UTC, LexManos commented on patches/minecraft/net/minecraft/entity/player/InventoryPlayer.java.patch
> +                 crashreportcategory.func_189529_a("Item name", new ICrashReportDetail<String>()
More NPEs

2018-07-14 21:35 UTC, LexManos commented on patches/minecraft/net/minecraft/world/World.java.patch
> ++                                return String.format("ID #%d (%s // %s // %s)", Block.func_149682_b(p_190529_2_), p_190529_2_.func_149739_a(), p_190529_2_.getClass().getName(), p_190529_2_.getRegist
This one is fine because if getRegistryName returns null it'll just output "null" and not crash.

2018-07-14 21:38 UTC, liach commented
`Objects.toString()` should be able to handle those cases since all npes are caused by `toString()` calls

2018-07-15 01:01 UTC, Shadows-of-Fire commented
`Objects.toString()` just calls `String.valueOf()`, so I've used that.  That should fix all concerns.

2018-07-29 00:39 UTC, merged