Add function to lookup model location for an ItemStack
MinecraftForge/MinecraftForge pull request #5017
Opened 2018-07-05 20:02 UTC by bs2609

Aims to provide a 'proper' way to lookup the `ModelResourceLocation` for an `ItemStack`, which can be used to get the associated `IModel`. At the moment, mods have taken to reflecting into internal Forge classes, causing issues such as https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63, which is obviously not ideal.

2018-07-07 06:11 UTC, liach approved these changes
Should we reduce patch or add a patch to prevent an extra cast in `Minecraft.getMinecraft().getRenderItem().getItemModelMesher()` call?

2018-07-16 06:26 UTC, mezz requested changes

2018-07-16 06:26 UTC, mezz commented on src/main/java/net/minecraftforge/client/ItemModelMesherForge.java
> +        ModelResourceLocation location = null;
Can you just use `return` instead of storing the `location` to a variable?
I'm not sure if this is a stylistic choice or just the result of some code reworks, but it seems a bit odd to me.

2018-07-16 07:10 UTC, liach commented on src/main/java/net/minecraftforge/client/ItemModelMesherForge.java
> +        ModelResourceLocation location = null;
The `map.get` can definitely return null; however, I don't know if the mesh definition can return null. We can only return at the mesh definition getmodellocation if it guarantees to return non-null.

2018-07-16 10:15 UTC, bs2609 commented on src/main/java/net/minecraftforge/client/ItemModelMesherForge.java
> +        ModelResourceLocation location = null;
It's written to resemble `ItemModelMesher.getItemModel(ItemStack)`, but I can change it if you prefer. The returns would need to be null checked, however, as mentioned.

2018-07-17 04:29 UTC, mezz commented on src/main/java/net/minecraftforge/client/ItemModelMesherForge.java
> +        ModelResourceLocation location = null;
Ok I see. The way it's written now seems pretty resilient to errors so I guess it'll be fine.

2018-07-17 04:30 UTC, mezz approved these changes

2018-07-29 01:55 UTC, merged