Re-Add probably stripped Methods to NBT-Classes
MinecraftForge/MinecraftForge pull request #5080
Opened 2018-08-04 23:57 UTC by TechnicianLP

Specificall readds:
`getLongArray()` to `NBTTagLongArray` (to actually make it usable without reflection)
missing `long[]` getters and setters to `NBTTagComound`
missing getters to `NBTTagList` (didnt add `set()` or `append()` here as vanilla doesnt have any overloads here by default - tell me if those should be added as well)

2018-10-04 19:10 UTC, TechnicianLP commented
Yes or No?

2018-10-05 15:46 UTC, kashike requested changes

2018-10-05 15:46 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagCompound.java.patch
> ++    public void setLongArray(String key, long[] value)
Should be `putLongArray`.

2018-10-05 15:46 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++    public byte getByteAt(int i)
Should be `getByte`.

2018-10-05 15:46 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++    public short getShortAt(int i)
Should be `getShort`.

2018-10-05 15:46 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++    public boolean getBooleanAt(int i)
Should be `getBoolean`.

2018-10-05 15:46 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++    public long getLongAt(int i)
Should be `getLong`.

2018-10-05 15:46 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++    public byte[] getByteArrayAt(int i)
Should be `getByteArray`.

2018-10-05 15:46 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++    public long[] getLongArrayAt(int i)
Should be `getLongArray`.

2018-10-05 15:46 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++    public NBTTagList getListTagAt(int i, int type)
Should be `getList`.

2018-12-06 15:36 UTC, MajorTuvok commented
Waiting for changes...
Not stale...

2018-12-06 22:30 UTC, kashike commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++    public boolean getBooleanAt(int i)
^

2019-01-02 22:35 UTC, tterrag1098 requested changes

2019-01-02 22:35 UTC, tterrag1098 commented on patches/minecraft/net/minecraft/nbt/NBTTagList.java.patch
> ++            if (nbtbase.func_74732_a() == 1)
No need to hardcode these constants in our own code, use `Constants.NBT` instead

2019-03-17 20:52 UTC, TechnicianLP commented
I will be able to take a look at this again in a few days

2019-05-12 21:04 UTC, mezz requested changes

2019-05-12 21:04 UTC, mezz commented on patches/minecraft/net/minecraft/nbt/NBTTagCompound.java.patch
> ++            if (this.func_150297_b(key, 12))
use `net.minecraftforge.common.util.Constants.NBT#TAG_LONG_ARRAY`

2019-05-12 21:04 UTC, mezz commented on patches/minecraft/net/minecraft/nbt/NBTTagCompound.java.patch
> ++            throw new ReportedException(this.func_82581_a(key, 12, classcastexception));
use `net.minecraftforge.common.util.Constants.NBT#TAG_LONG_ARRAY`

2019-05-12 22:27 UTC, mezz approved these changes

2019-08-29 01:59 UTC, closed without merging