Added getter for children of CompoundIngredient
MinecraftForge/MinecraftForge pull request #5082
Opened 2018-08-05 15:01 UTC by mcenderdragon

This PR adds a getter to CompoundIngredient to access the collection of sub ingredients. I am not sure if we should make this collection readonly or not. But in general this collection shoiuld not get edited since it will break cashing.

2018-08-05 16:14 UTC, Wyn-Price commented
`getChilds` should be `getChildren`, as children is the proper plural for child. Having it as a Collection is fine, the children list should be unmodified anyway

2018-08-05 16:17 UTC, mcenderdragon commented
@Wyn-Price doen. I kind of though about JS were it was named childs.

2018-08-05 18:09 UTC, mezz requested changes

2018-08-05 18:09 UTC, mezz commented on src/main/java/net/minecraftforge/common/crafting/CompoundIngredient.java
> +        return this.children;
use `return Collections.unmodifiableCollection(this.children);`

2018-08-05 20:33 UTC, mcenderdragon commented
ok @mezz done.

2018-08-05 20:47 UTC, mezz commented
Looks good. What do you need this for?

2018-08-05 20:47 UTC, mezz approved these changes

2018-08-05 23:10 UTC, mcenderdragon commented
I am building a small mod for recipe improvment, so it will log all recipe were items have an oredict but the oredict version is not used. But unfortunetly it is not possible to say if a recipe uses oredict ore not if the compound ingredient is used. THe goal is to make a config so for example large modpacks can just list some recipes and I will replace them so they are oredict compatible for a better experience. (Nothing is worse then broken OreDict mod support)

2018-08-16 20:19 UTC, merged

2018-08-16 20:20 UTC, LexManos commented
I dont think this is needed, as it breaks the Ingredient api, but whatever if I dont do this people'll just reflect and break crap anyways.