Improve context provided by potion icon rendering hooks
MinecraftForge/MinecraftForge pull request #5111
Opened 2018-08-21 06:43 UTC by bs2609

Small update of the hooks provided by #1194 and #2798 to provide some additional context - the GUI instance and the z-level used for rendering. The new methods currently forward to the existing ones, which are deprecated and marked for removal.

The aim here is to make it easier to render at the correct z-level, either by using an applicable `Gui` instance method, or by specifying the value manually. Currently this information isn't readily available, and using a level of 0 doesn't give correct results (as can be seen in https://github.com/TeamTwilight/twilightforest/issues/602 and also the current test code).

The existing test mod is updated to use the new methods, and is also cleaned up to remove some old, no longer applicable, code.

2018-11-15 04:35 UTC, tterrag1098 approved these changes

2018-11-24 00:23 UTC, mezz requested changes
The test mod doesn't use the `Gui` parameter, what is it needed for?

2018-11-24 00:34 UTC, bs2609 commented
The test mod could just use something like this to draw the sprite:
```java
gui.drawTexturedModalRect(x, y, sprite, width, height);
```

The existing test code does serve better as an example of how to draw a non-atlased texure, however.

2018-11-24 00:36 UTC, mezz approved these changes

2018-11-24 00:36 UTC, merged