Modified EntityLIving.depawnEntity()
MinecraftForge/MinecraftForge pull request #5154
Opened 2018-09-19 21:49 UTC by MrChoke72

This is the 2nd solution to fix issues #5148 and #4485.  It is better than the 1st in that it ensures that the forge LivingEvent.AllowDespawn() event handler is not called more often than every 32 ticks.

As explained in the previous solution, the current implementation in Forge does not allow full depawn override capability for the modder.  Many parts of the default behavior like distance checks will still execute and despawn entities regardless of what the modder wants.  That is because 31 out of every 32 ticks, the default behavior is called.

This solution will only call the AllowDespawn event handler once every 32 ticks.  Below is the behavior to the handler's result:
DENY:  The event handler AND the default behavior are both not executed for 32 ticks.
ALLOW:  The entity is despawned.
DEFAULT:  The default behavior is called for 32 ticks without calling the event handler

The last solution had a performance concern with the even the handler being called every tick.  As you can see, this design addresses that concern.

2018-09-19 22:39 UTC, liach commented
be careful, no imports in patches

2018-09-19 22:41 UTC, MrChoke72 commented
> be careful, no imports in patches


> be careful, no imports in patches

Oh yeah, that was from me debugging..  Oops.  I will remove it.  Thanks.

2018-09-20 03:45 UTC, MajorTuvok commented on patches/minecraft/net/minecraft/entity/EntityLiving.java.patch
> ++    protected int despawnHndlrWaitTime;
Typo... (Handler)

2018-09-20 14:04 UTC, diesieben07 commented on patches/minecraft/net/minecraft/entity/EntityLiving.java.patch
> ++    protected boolean forceNodespawn;
Should be spelled `forceNoDespawn`, otherwise it reads "node" + "spawn".

2018-09-20 21:18 UTC, MrChoke72 commented
Ok.  The two variable naming suggestions have been applied.  Thanks.

2018-09-21 13:35 UTC, Alpvax approved these changes

2018-10-10 22:19 UTC, MrChoke72 commented
Guys, I just pushed a change to reset forceNoDespawn back to false if the event handler comes back DEFAULT.  I swear I had that in there before but oh well.  It's there now.

2018-10-11 02:39 UTC, tterrag1098 requested changes
Lots of extra unnecessary changes in this commit

2018-12-11 03:20 UTC, MrChoke72 commented
I am replying to stop this PR from being "stale".  I applied all pending review changes.  I think it's a good change for 1.12.

2019-02-23 04:35 UTC, closed without merging