Spelling/grammar check, link fix.
MinecraftForge/MinecraftForge pull request #5155
Opened 2018-09-20 19:28 UTC by CatRabbit499

- Spelling corrections
- Grammar corrections
- Change FML Source link to 1.13-pre from 1.12.x
- Update MCP link
- Changed Maven link to HTTPS

2018-09-20 19:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=5155) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=5155) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=5155) it.</sub>

2018-09-20 19:36 UTC, liach commented
the branch, i am sure, will change once a runnable 1.13 is out.

2018-09-21 00:01 UTC, SkyHawkB commented
you have an extra capital on Line 19, just saying

2018-09-21 02:32 UTC, liach requested changes
I do not think this is worthy enough to create a pull request, and I believe this pull request has a very slight chance to be merged as it is trivial. Moreover, this pull request has a few issues; it even introduces more grammatical errors.

2018-09-21 02:32 UTC, liach commented on CREDITS.txt
> +several years now, so now I would like to take this time thank a few people who have
No need for `now`

2018-09-21 02:32 UTC, liach commented on CREDITS.txt
> +First, thanks to the people who originally created the Forge projects way back in
No need for `to` before the names of people because you are enumerating `a few people`.

2018-09-21 02:32 UTC, liach commented on CREDITS.txt
>      * Minecraft Coder Pack (MCP) *
You should rename this to `Mod Coder Pack` since its name has changed.

2018-09-21 02:32 UTC, liach commented on CREDITS.txt
> +It also contains a partial repackaging of the javaxdelta library from SourceForge with credit to it's authors.
`it's` -> `its`. Your grammar failed!

2018-09-21 02:32 UTC, liach commented on CREDITS.txt
> +Forge Mod Loader downloads components from the Minecraft Coder Pack with kind permission from the MCP team.
`Mod Coder Pack`, too.

2019-02-19 17:14 UTC, closed without merging