Speed up runtime deobfuscation
MinecraftForge/MinecraftForge pull request #5243
Opened 2018-11-19 10:35 UTC by ichttt

This PR aims to improve startup time, esp on large modpacks. This is done by changing the deobf transformer to not expand frames, which, as the javadoc says, is slow. This works for a simple renaming transformer as well, but we need to change it to a ´ClassRemapper´ instead of a ´RemappingClassAdapter´, as the ´RemappingClassAdapter´ class requires ´EXPAND_FRAMES´.
See https://gitlab.ow2.org/asm/asm/issues/317576 for some background information.

2018-11-19 11:05 UTC, reece2d requested changes

2018-11-19 11:05 UTC, reece2d commented on src/main/java/net/minecraftforge/fml/common/asm/transformers/DeobfuscationTransformer.java
> +import com.google.common.base.Stopwatch;
Remember to remove unnecessary dependancies

2018-11-19 15:52 UTC, tterrag1098 approved these changes
This looks okay to me, but I'll leave it to @LexManos to give the final review since he knows more about this system.

2018-11-19 23:39 UTC, ichttt commented
I also added check to the SideTransformer, so classes that didn't changed don't have their class bytes recalculated. The same check is already present in all other transformers.

2018-11-23 05:05 UTC, mezz approved these changes
I was curious why `ClassReader.EXPAND_FRAMES` was needed before but didn't find much information on it.
There are some [pretty old bugs](https://jira.terracotta.org/jira/si/jira.issueviews:issue-html/CDV-286/CDV-286.html) about it being required for some specific `classReader.accept` implementations but I haven't seen anything recent so I think your analysis is the right one.

If anyone else is curious, the original `DeobfuscationTransformer` was written here: https://github.com/MinecraftForge/FML/commit/b5d5c95b3364075e111afe79395f23198426645c#diff-bb8c8be01d90f6d6dde226c050f76b44

2018-11-23 11:20 UTC, ichttt commented
You are right about these old bugs. This is because The RemappingMethodAdapter is a subclass of LocalVariablesSorter, which requires EXPAND_FRAMES to sort. However, variable sorting is not needed for a simple renaming transformer (see the linked issue in my original explenation), so the ASM authors added a new MethodRemapper, which doesn't subclass LocalVariableSorter. In theory this is a breaking change, but as the asm transformer has no use outside of asm context and coremods might break on any change, this shouldn't be a problem.

2018-11-24 00:49 UTC, darkhax commented
I think this is a good change but it would be nice to have some benchmarks that go along with it, even if it's just a simple one.

2018-11-24 02:07 UTC, ichttt commented
I did some testing with obfuscated minecraft with a modpack consisting of 171 mods and got the following results with [my profiler](https://gist.github.com/ichttt/88b650ead95b5415c7ee3972cfa123d9):
1.12.x with profiler patches:
SideTransformer: Total 1182 invocations 28400 mean 0.04163472
DeobfTransformer: Total 11174 invocations 28200 mean 0.39627618
My branch with profiler patches:
SideTransformer: Total 19 invocations 28400 mean 6.8838027E-4
DeobfTransformer: Total 10060 invocations 28200 mean 0.3567684

As the SideTransformer has close to no work on the client, the difference is most visible here, and the difference in the time needed for deobf is also visible.
I tested each version twice and got more or less the same results

2018-11-24 02:19 UTC, darkhax commented
Thanks, you may want to show the actual decimal value for the second run so it's easier to compare. (0.00068838027)

2019-01-03 04:35 UTC, tterrag1098 commented
This is a far-reaching change with very little actual improvement. I'm not sure it's worth risking the many edge cases.

2019-01-03 04:38 UTC, closed without merging

2019-01-03 08:16 UTC, ichttt commented
Fair enough