Ensure slave maps are cleaned up when handling registry overrides
MinecraftForge/MinecraftForge pull request #5250
Opened 2018-11-24 06:13 UTC by bs2609

As per title, adds code to the various `onAdd` callbacks to remove any entries in slave maps relating to the old value, prior to adding the new value.

This is to ensure the maps don't end up with "orphan" entries that waste space and may cause issues if they show up in queries.

2018-11-26 02:32 UTC, mezz requested changes
mostly looks good, just some style nitpicks

2018-11-26 02:32 UTC, mezz commented on src/main/java/net/minecraftforge/registries/GameData.java
> +            if (prev != null) this.objectList.set(prev, null);
please keep the body of an `if` on its own line

2018-11-26 02:32 UTC, mezz commented on src/main/java/net/minecraftforge/registries/GameData.java
> +                for (IBlockState state : oldBlock.getBlockState().getValidStates())
I'd really prefer braces on `for` loops, most of them in the forge codebase have braces

2018-12-02 01:02 UTC, mezz approved these changes

2018-12-02 01:25 UTC, tterrag1098 approved these changes

2019-01-04 01:36 UTC, merged