Add ModelRotationEvent
MinecraftForge/MinecraftForge pull request #5299
Opened 2018-12-24 18:29 UTC by Flemmli97

Adds an event in RenderLivingBase.doRender just before the actual model is rendered. This allows to modify the models rotation etc. (including the players).

2018-12-24 18:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=5299) <br/>All committers have signed the CLA.

2018-12-24 20:55 UTC, Landmaster requested changes
@Flemmli97 Can you add a simple test mod to make sure that the event works? Also:

2018-12-24 20:55 UTC, Landmaster commented on src/main/java/net/minecraftforge/client/event/ModelRotationEvent.java
> +public class ModelRotationEvent extends Event{
Braces should be on their own line as per Forge convention.

2018-12-25 13:48 UTC, Flemmli97 commented
This now partially works. All of the models of vanilla minecraft are calling ModelBase.setRotationAngles in ModelBase.doRender again (for some reasons) and thus changes to the model made with this event wont get applied (i dont understand why they are calling that method twice). You can however disable the rendering of certain parts of the model which i did in the example mod (and then render the hidden parts yourself). Though this wasnt actually the purpose of this event.

2018-12-26 14:31 UTC, Landmaster requested changes
Please replace the tabs in `ModelRotationEvent` and `ModelRotationEventTest` with 4 spaces as per Forge convention.

2018-12-28 17:34 UTC, darkhax commented
What is the use of this PR? It seems like it would add a lot of overhead to rendering models.

2018-12-28 17:36 UTC, Suffril commented
I think they indeed to allow the manipulation limbs for the use of custom animations to pre-existing mobs and players

2019-01-02 22:01 UTC, tterrag1098 commented
Again, this is a high-volume event with no justification. Please provide at least a use case for this event.

2019-01-04 15:07 UTC, Flemmli97 commented
the purpose was to modify the model before rendering it but since vanilla sets the rotations in ModelBase.doRender again it wont work anymore. i left it open thinking since it can work for modded entity models it might be useful but seems not like it. ill close this one

2019-01-04 15:07 UTC, closed without merging