Adding long support to configuration
MinecraftForge/MinecraftForge pull request #5327
Opened 2019-01-07 20:11 UTC by Elec0

I was writing a mod and I tried to save longs into the config, but it told me that longs weren't a primitive, which is obviously incorrect.

I saw 
```
public enum Type
    {
        STRING,
        INTEGER,
        BOOLEAN,
        DOUBLE,
        COLOR,
        MOD_ID;
```

I thought at first it was because `com.google.common.primitives.Longs` didn't exist, but it does, so I added the code to handle longs.

I wrote a test to make sure it saved and loaded properly. I didn't really need to actually write much original code, since there are so many other types already in there, I just copied the existing functionality and changed the names and types.

2019-01-07 20:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=5327) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=5327) before we can accept your contribution.<br/><hr/>**Aaron Steele** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=5327) it.</sub>

2019-01-10 11:13 UTC, tterrag1098 requested changes
What is your usecase? I can't think of a case where I would need to configure such large values.

2019-01-10 11:13 UTC, tterrag1098 commented on src/main/java/net/minecraftforge/common/config/ConfigElement.java
> +            prop.getType() == Property.Type.INTEGER ? ConfigGuiType.INTEGER :  prop.getType() == Property.Type.COLOR ? ConfigGuiType.COLOR :
Unnecessary whitespace change

2019-01-10 18:26 UTC, Elec0 commented on src/main/java/net/minecraftforge/common/config/ConfigElement.java
> +            prop.getType() == Property.Type.INTEGER ? ConfigGuiType.INTEGER :  prop.getType() == Property.Type.COLOR ? ConfigGuiType.COLOR :
Agreed.

2019-01-10 18:29 UTC, Elec0 commented
My usecase is this: https://github.com/Elec0/Megastructures/wiki/Material-Requirements-Calculations
Specifically my calculations say that reasonable values that I'm looking at are in the 10^18 to 10^20 range. 
Also because the error that said long wasn't a primitive confused me.

2019-01-10 21:15 UTC, LexManos commented
Your usecase is something that can be calculated on the fly. Or better ux would be to have a global 'scale' config to reduce or inflate the calculates value by a fixed percentage. And honestly with the fact that 1.13 is flat out deleting this class. I'm reluctant to hack anything else onto it.

2019-01-10 21:15 UTC, closed without merging