Modified BlockBubbleColumn so mod-added blocks can create bubble columns
MinecraftForge/MinecraftForge pull request #5458
Opened 2019-02-10 15:51 UTC by Laton95

Vanilla BlockBubbleColumn destroys itself when it is not placed on either soul sand or magma blocks. I've added two methods in IForgeBlock and IForgeBlockState to replace those hardcoded blocks, similar to how beacons were modified, so mod-added blocks can create bubble columns on top of them.

Example mod here:
https://pastebin.com/PZ1d7myy

2019-02-10 15:54 UTC, bs2609 commented
This seems like something that can potentially be better implemented by defining a tag for it.

2019-02-10 16:01 UTC, Laton95 commented
> This seems like something that can potentially be better implemented by defining a tag for it.

If tags are the new way to go, sure. I was just working off the precedent of isBeaconBase, but maybe that should change in the future too

2019-02-10 22:33 UTC, liach commented
you should add another tag for columns that push, and make the overall tag reference the 2 subtags instead of individual blocks.

2019-02-11 00:49 UTC, Laton95 commented
> you should add another tag for columns that push, and make the overall tag reference the 2 subtags instead of individual blocks.

Good idea, and done.

I want to make it clear though that these tags will not cause any block to create bubbles by themselves. It would be up to the modder to place the bubble column block, these changes just allow changes to what blocks bubble columns think are valid to be placed on.

2019-02-11 01:26 UTC, liach approved these changes

2019-04-25 09:00 UTC, liach commented
looks good, why no merge?

2019-06-05 05:19 UTC, mezz requested changes

2019-06-05 05:19 UTC, mezz commented on patches/minecraft/net/minecraft/block/BlockBubbleColumn.java.patch
> ++         return p_203157_0_.func_180495_p(p_203157_1_.func_177977_b()).func_203425_a(net.minecraftforge.common.Tags.Blocks.BUBBLE_SOURCES_WITH_DRAG);
I don't think this is equivalent. The original `block` comes from `iblockstate` which is at position `p_203157_1_`.
Why are you checking the block state below `p_203157_1_` here?

2019-08-25 10:17 UTC, closed without merging