[1.13.x] fire KeyInputEvent
MinecraftForge/MinecraftForge pull request #5533
Opened 2019-02-19 18:36 UTC by 0uti

fixes #5481

2019-02-19 23:14 UTC, blay09 commented
Since we don't have `Keyboard.getEventKey()` etc. anymore, the event data passed into the patched method (key, scanCode, action, modifiers) should also be added to the `KeyInputEvent` similar to how the GUI key events have them.

2019-02-19 23:20 UTC, 3TUSK commented
While we are on this - it might be a good idea to move those events out of `net.minecraftforge.fml.common.gameevent` package and put them into `net.minecraftforge.event`.

2019-02-20 17:48 UTC, 0uti commented
PR is updated. Please take a look.

2019-02-26 22:06 UTC, 0uti commented
Updated. Conflicts resolved.

2019-03-03 22:06 UTC, mezz approved these changes

2019-03-05 19:18 UTC, Pfuenzle approved these changes

2019-03-05 19:52 UTC, EwyBoy approved these changes

2019-03-12 05:20 UTC, tterrag1098 requested changes

2019-03-12 05:20 UTC, tterrag1098 commented on src/main/java/net/minecraftforge/client/event/InputEvent.java
> +public class InputEvent extends Event {
Formatting is all over the place here.

2019-03-12 08:34 UTC, 0uti commented on src/main/java/net/minecraftforge/client/event/InputEvent.java
> +public class InputEvent extends Event {
Formatting fixed.

2019-03-19 12:38 UTC, Waterpicker commented
So how long until this is ready. I have a mod that needs these events.

2019-03-23 18:12 UTC, 0uti commented on src/main/java/net/minecraftforge/client/event/InputEvent.java
> +public class InputEvent extends Event {
Please see if it fits.

2019-04-02 18:56 UTC, alucas commented
Hi,

I'm trying to update a mod that bind chat commands to keys.
It has its own GUIs for the user to add his commands and select the keys.

It's currently using that old event to intercept the keys and run the commands. So I can't finish my port without this PR for now. Or I can use the existing keybinding system but I'm not sure if this is a good choice.

2019-04-16 01:50 UTC, merged