Add GuiContainerEvent.DrawBackground event.
MinecraftForge/MinecraftForge pull request #5595
Opened 2019-03-06 03:56 UTC by Larsg310

This allows modders to draw custom background elements on GuiContainers.

I want to use this to draw an overlay on top of the item slots to highlight items in an inventory. Currently, I am using DrawForeground to render it however that causes rendering issues:
![image](https://user-images.githubusercontent.com/5021026/53854950-dbcbfa80-3fcb-11e9-8ea4-c98fce211fd4.png)

I tried rendering this using my own GuiContainer in the drawGuiContainerBackgroundLayer, and it works there:
![image](https://user-images.githubusercontent.com/5021026/53854977-fbfbb980-3fcb-11e9-9c35-51c76e6a145b.png)

This event would allow me to render the overlay properly on the background.

2019-03-12 05:09 UTC, tterrag1098 approved these changes

2019-03-26 04:57 UTC, mezz requested changes
This looks good but I think it could use a better name. Right now the name looks very similar to `GuiScreenEvent.BackgroundDrawnEvent`

2019-03-26 13:12 UTC, Larsg310 commented
What do you suggest?

I agree they look very similar in name, though I think it makes sense to name it `DrawBackground`

2019-03-27 04:35 UTC, mezz commented
Hmm based on MCP names we should probably rename the other event to `WorldBackgroundDrawnEvent`.
Even then I think the names are pretty bad... I guess there isn't much to be done here in this PR.
I'm ok to go ahead with this.

2019-03-27 04:36 UTC, mezz approved these changes

2019-04-16 01:56 UTC, merged