[1.13.2] Uncommenting lines to re-add Custom Entities for Items
MinecraftForge/MinecraftForge pull request #5600
Opened 2019-03-08 21:22 UTC by Suffril

Uncommented lines in ForgeInternalHandler to re-add support for Items that have custom entities, for them to actually use the custom entity instead of the items EntityItem. 

It was apparently commented out early on in Forge 1.13 Dev by Cpw because it made the server fail to start due to missing patches. This is no longer the case and this now works as expected.

2019-03-09 01:11 UTC, SkyHawkB commented
Why did you close this?

2019-03-12 05:08 UTC, tterrag1098 requested changes

2019-03-12 05:08 UTC, tterrag1098 commented on src/main/java/net/minecraftforge/common/ForgeInternalHandler.java
> +
Don't change whitespace

2019-03-18 13:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=5600) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=5600) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: Suffril<br/>:x: Fril<br/><hr/>**Fril** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=5600) it.</sub>

2019-03-18 14:05 UTC, Suffril commented
I will fix the CLA later today, accidentally committed with the wrong email

2019-03-18 14:16 UTC, tterrag1098 approved these changes

2019-06-05 05:37 UTC, mezz commented
@Suffril please sign the Contributor License Agreement

2019-07-09 02:43 UTC, LexManos commented
```
/var/jenkins_home/workspace/forge_forge_PR-5600/src/main/java/net/minecraftforge/common/ForgeInternalHandler.java:56: error: cannot find symbol
                    event.getWorld().spawnEntity(newEntity);
```

2019-07-09 13:42 UTC, closed without merging