[1.13.2] Add getter method for MouseHelper.middleDown
MinecraftForge/MinecraftForge pull request #5610
Opened 2019-03-15 00:45 UTC by Geforce132

The current MouseHelper class has getters for leftDown and rightDown, which are booleans that return true if the player is holding down their left or right mouse buttons respectively. However, for some reason, MouseHelper doesn't have a getter method for middleDown, which is a boolean that checks whether or not the player's middle mouse button is being held down. This could be a useful method for mods that want to utilize middle-mouse to perform some function (including one of mine). 

An AccessTransformer or Reflection could also allow us access to this private value, but that's fairly impractical to have to set up an AT or deal with the performance issues of Reflection (if you're referencing this boolean a lot) when there's already getters for the other two mouse buttons. This commit simply adds a return method for middleDown into MouseHelper.

2019-03-15 00:49 UTC, williewillus commented
Is there any other private data in this class we want to expose too? So we can get em all at once

2019-03-15 04:12 UTC, Geforce132 commented
I don't believe so? The only other private variables that I think would ever be used by any type of mod in MouseHelper is x/yVelocity, but I don't know how that would be used.

2019-03-23 15:17 UTC, Cadiboo commented
> The only other private variables that I think would ever be used by any type of mod in MouseHelper is x/yVelocity, but I don't know why that would be needed.

I can think of mods would render something facing a direction and have it moveable with click & drag, which will probably use velocity

2019-05-22 17:15 UTC, bl4ckscor3 commented
Merging this would be very helpful for ease of accessibility.

2019-06-05 05:40 UTC, mezz requested changes

2019-06-05 05:40 UTC, mezz commented on patches/minecraft/net/minecraft/client/MouseHelper.java.patch
> ++   public boolean isMiddleDown() {
Please put new methods at the bottom of the file, after a comment like this:
` /* ======================================== FORGE START =====================================*/`

2019-06-06 05:48 UTC, closed without merging

2019-06-06 18:34 UTC, mezz commented
Superseded by https://github.com/MinecraftForge/MinecraftForge/pull/5776