Improve performance of smooth vertex lighting
MinecraftForge/MinecraftForge pull request #5763
Opened 2019-05-28 23:31 UTC by bs2609

Changes `VertexLighterSmoothAo.calcLightmap` to compute block/sky light values together, instead of in separate passes. This avoids duplicating the calculations which do not depend on the light values provided.

As a test, this can be seen to reduce frame times in artificially render-bound scenarios, and will deliver a general small improvement in performance wrt. chunk rebuild times where smooth lighting is used.

Before:
![2019-05-28_21 58 24](https://user-images.githubusercontent.com/1447117/58518790-86f1e780-81a8-11e9-82dd-e414b0320576.png)

![lighting-pre](https://user-images.githubusercontent.com/1447117/58518859-c6b8cf00-81a8-11e9-9a21-4b61b5d283a5.PNG)

After:
![2019-05-28_21 54 32](https://user-images.githubusercontent.com/1447117/58518813-9c671180-81a8-11e9-8245-b7f56f19fb72.png)

![lighting-post](https://user-images.githubusercontent.com/1447117/58518861-c8829280-81a8-11e9-8668-be9e9bd7532e.png)

Note that this is a minor breaking change, due to changing the signature of the protected `calcLightmap` method. As this is only defined in `VertexLighterSmoothAo` itself, this is unlikely to be used elsewhere, but it is worth noting. Unfortunately due to the original implementation, I couldn't see an easy way to keep compatibility here without duplicating the original code, although if anyone else can think of a 'clean' way of keeping compat, it can be added.

Thanks to @jellysquid3 for the suggestion.

2019-06-04 16:07 UTC, ichttt approved these changes

2019-06-04 18:00 UTC, ichttt commented
Please note that this is a breaking change in 1.12, as custom implemations could call the original method.

2019-06-04 18:02 UTC, bs2609 commented
> Note that this is a minor breaking change, due to changing the signature of the protected `calcLightmap` method. As this is only defined in `VertexLighterSmoothAo` itself, this is unlikely to be used elsewhere, but it is worth noting. Unfortunately due to the original implementation, I couldn't see an easy way to keep compatibility here without duplicating the original code, although if anyone else can think of a 'clean' way of keeping compat, it can be added.

Mentioned in the original post.

2019-06-06 18:48 UTC, mezz requested changes
Looks good. Out of paranoia, can you keep the old method there and deprecate it? We should try to be as safe as possible, diagnosing a crash when a Forge method disappears can be a real headache for mod devs.

2019-08-02 21:14 UTC, merged

2019-08-02 21:15 UTC, LexManos commented
Nobody digs this deep into the lighting code, so screw it.