Fix various unclosed I/O resources
MinecraftForge/MinecraftForge pull request #5766
Opened 2019-05-31 01:53 UTC by bs2609

Fixes various places found in vanilla/Forge code where I/O resources are not closed correctly.

For the vanilla issues, only `LanguageMap` still appears to be an issue as of 1.14.2, and has been reported as [MC-153470](https://bugs.mojang.com/browse/MC-153470).

2019-06-01 02:30 UTC, killjoy1221 commented on src/main/java/net/minecraftforge/common/ForgeModContainer.java
> +import org.apache.commons.io.IOUtils;
No imports.

2019-06-01 03:01 UTC, liach commented
you can do try with resources in patches. it doesn't make patches explode as i see and can make code cleaner (just make parentheses on new lines)

2019-06-12 06:09 UTC, tterrag1098 requested changes
Fixes in vanilla code need a comment and (if available) a vanilla bug ID.

And I agree, most of these changes would be better served by using try-with-resources.

2019-06-12 07:35 UTC, bs2609 commented
Do bear in mind that try-with-resources needs handling of `IOException`s which could occur.

2019-06-12 07:36 UTC, liach approved these changes

2019-08-02 20:28 UTC, LexManos commented on patches/minecraft/net/minecraft/client/resources/ResourcePackRepository.java.patch
> +-            String s = DigestUtils.sha1Hex((InputStream)(new FileInputStream(p_190113_2_)));
You use try-with in all the code we control where size doesn't matter.. but you don't feel like doing it in the patches where size does?

2019-08-02 20:32 UTC, merged