Added entity nameplate rendering event hook
MinecraftForge/MinecraftForge pull request #6412
Opened 2020-01-05 14:50 UTC by ScottehBoeh

2020-01-05 14:52 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6412) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6412) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=6412) it.</sub>

2020-01-05 21:03 UTC, diesieben07 requested changes
Do we really want yet another event that fires _every frame_ for _every entity_?

2020-01-05 21:03 UTC, diesieben07 commented on patches/minecraft/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
> ++import net.minecraftforge.eventbus.api.Event;
No imports in patch files.

2020-01-05 21:03 UTC, diesieben07 commented on patches/minecraft/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
> ++      if(net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(renderNameplateEvent)) return;
Formatting (missing whitespace)

2020-01-05 21:03 UTC, diesieben07 commented on patches/minecraft/net/minecraft/client/renderer/entity/EntityRenderer.java.patch
> ++      if (!renderNameplateEvent.getResult().equals(Event.Result.DENY) && (renderNameplateEvent.getResult().equals(Event.Result.ALLOW) || this.func_177070_b(p_225623_1_))) {
Why is this event both cancelable _and_ has a result? `Result.DENY` already covers the "cancel it" case. Your event class is also missing `@HasResult` if you want a result.
Why `equals` for enums?

2020-01-06 21:59 UTC, ScottehBoeh commented
Creating a new mended PR

2020-01-06 21:59 UTC, closed without merging

2020-01-07 17:48 UTC, diesieben07 commented
> Creating a new mended PR

NO! Just update your local branch. You can even change the target branch for this PR.