Add an AT entry to make it easier to add vanilla-like brewing recipes
MinecraftForge/MinecraftForge pull request #6490
Opened 2020-02-01 09:38 UTC by Yaossg

I noticed that in 1.13+ Forge no longer publish methods in net.minecraft.potion.PotionBrewing (once called PotionHelper in 1.12.2) to allow modder to add vanilla-like brewing recipes easier. But I also noticed there is a patch on it to make its subclass MixPredictae follow Forge's principles. So I think its missing is due to cleanup and forgetting to re-add.
Old version at link: [https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/resources/forge_at.cfg#L297](url)

2020-02-01 09:39 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6490) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6490) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=6490) it.</sub>

2020-02-02 12:41 UTC, diesieben07 requested changes
Blanket "make everything public" ATs are a bad idea. Make public exactly what you need and provide justification for why. ""it's convenient" is not justification, show some code.

2020-02-02 14:59 UTC, Yaossg commented
> Blanket "make everything public" ATs are a bad idea. Make public exactly what you need and provide justification for why. ""it's convenient" is not justification, show some code.

## Adding a vanilla-like brewing recipes for a potion
By this:
`PotionBrewing.addMix(Potions.AWKWARD, Items.KELP, myPotion);`
By Forge's Hooks:
```
BrewingRecipeRegistry.addRecipe(
   /* Ingredient that only accepts specific potion*/
   Ingredient.fromItems(Items.KELP),
   /* ItemStack of the potion with myPotion*/
);
```

## Adding a vanilla-like potion container
By this:
`PotionBrewing.addContainer(...)`
`PotionBrewing.addContainerRecipe(...)`
By Forge's Hooks:
**ALMOST IMPOSSIBLE**

## Adding my own brewing stand
By this:
Just do as what vanilla does!
By Forge's Hooks
Forge's Hooks' comment told me vanilla brews potion by shifting bits! (net.minecraftforge.common.brewing.VanillaBrewingRecipe#getOutput's Javadoc)
_Did I miss 1.7?_

## Why I decided to make everything public?
Becasue each and every of its non-public method should be public for convenience (examples above)
Almost public could be all public just like `DamageSource`.

## Justification
I said above, and now I say again:
> I noticed that in 1.13+ Forge no longer publish methods in net.minecraft.potion.PotionBrewing (once called PotionHelper in 1.12.2) **to allow modder to add vanilla-like brewing recipes easier.** But I also noticed there is a patch on it to make its subclass MixPredicate follow Forge's principles. **So I think its missing is due to cleanup and forgetting to re-add.**

This was the way how almost all modders added their brewing recipes in 1.12.2
This should be the way how modders add their brewing now and in the future
Forge's Hooks only prepared for generic cases, making brewing stand a crafting table
However, What vanilla util do is to make a brewing stand could **brew**

2020-02-02 18:17 UTC, diesieben07 commented
All this is handled via the brewing recipe registry...

2020-02-03 02:26 UTC, Yaossg commented
> All this is handled via the brewing recipe registry...

which is too generic to add a real brewing recipes.
As I had compred above, Each and every modders may suffer 20 more times lines of code to get a maybe-incorrect-and-incompatible result aganist vanilla mechanism, but more than 95% mods added a vanilla-like brewing recipes. That's why with BrewingRecipeRegistry available, old version also publish BrewingPotion(once called PotionHelper): It's to serve modders as vanilla

2020-02-03 03:47 UTC, Yaossg commented
With the help of my friend, I prepared an full example
<details>
 
```
import net.minecraft.block.Blocks;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.potion.Potion;
import net.minecraft.potion.PotionBrewing;
import net.minecraft.potion.PotionUtils;
import net.minecraft.potion.Potions;
import net.minecraftforge.common.brewing.BrewingRecipeRegistry;
import net.minecraftforge.common.brewing.IBrewingRecipe;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;

import javax.annotation.Nullable;
import java.util.stream.Stream;

@Mod("examplemod")
public class ExampleMod {

	public ExampleMod() {
		// Register the setup method for modloading
		FMLJavaModLoadingContext.get().getModEventBus().addListener(this::setup);
	}

	public static Item steelPotionBottle, steelSplashPotionBottle, steelLingeringPotionBottle;

	public static Potion myPotion;

	private void setup(final FMLCommonSetupEvent event) {
		// Add my own brewing recipes by forge hooks 
		BrewingRecipeRegistry.addRecipe(new Ingredient(Stream.empty()) {
			@Override public boolean test(@Nullable ItemStack item) {
				return item != null && item.getItem() == Items.POTION && PotionUtils.getPotionFromItem(item) == Potions.AWKWARD;
			}
		}, Ingredient.fromItems(Blocks.BEDROCK), PotionUtils.addPotionToItemStack(new ItemStack(Items.POTION), myPotion));
		BrewingRecipeRegistry.addRecipe(new Ingredient(Stream.empty()) {
			@Override public boolean test(@Nullable ItemStack item) {
				return item != null && item.getItem() == Items.SPLASH_POTION && PotionUtils.getPotionFromItem(item) == Potions.AWKWARD;
			}
		}, Ingredient.fromItems(Blocks.BEDROCK), PotionUtils.addPotionToItemStack(new ItemStack(Items.SPLASH_POTION), myPotion));
		BrewingRecipeRegistry.addRecipe(new Ingredient(Stream.empty()) {
			@Override public boolean test(@Nullable ItemStack item) {
				return item != null && item.getItem() == Items.LINGERING_POTION && PotionUtils.getPotionFromItem(item) == Potions.AWKWARD;
			}
		}, Ingredient.fromItems(Blocks.BEDROCK), PotionUtils.addPotionToItemStack(new ItemStack(Items.LINGERING_POTION), myPotion));
		
		// Oops, How can I know others' mods' containers and their items?
		
		// maybe use can use vanilla util:
//		PotionBrewing.addMix(Potions.AWKWARD, Blocks.BEDROCK.asItem(), myPotion);
		
		
		// Add my own potion container: steel bottle
		BrewingRecipeRegistry.addRecipe(new IBrewingRecipe() {

			private boolean isSteelBottle(ItemStack item) {
				return item.getItem() == steelPotionBottle || item.getItem() == steelSplashPotionBottle || item.getItem() == steelLingeringPotionBottle;
			}

			private ItemStack translate(ItemStack item) {
				ItemStack result;
				if (item.getItem() == Items.POTION) {
					result = new ItemStack(steelPotionBottle, item.getCount());
				} else if (item.getItem() == Items.SPLASH_POTION) {
					result = new ItemStack(steelSplashPotionBottle, item.getCount());
				} else if (item.getItem() == Items.LINGERING_POTION) {
					result = new ItemStack(steelLingeringPotionBottle, item.getCount());
				} else {
					// Oops, How can I know others' mods' containers and their items?
					return item;
				}
				result.setTag(item.getTag());
				return result;
			}

			@Override
			public boolean isInput(ItemStack input) { return isSteelBottle(input); }

			@Override
			public boolean isIngredient(ItemStack ingredient) { return ingredient.getItem() == Items.IRON_INGOT; }

			@Override
			public ItemStack getOutput(ItemStack input, ItemStack ingredient) {
				if (!input.isEmpty() && !ingredient.isEmpty() && isIngredient(ingredient)) {
					ItemStack result = PotionBrewing.doReaction(ingredient, input);
					if (result != input) {
						if (!isSteelBottle(result)) {
							result = translate(result);
						}
						return result;
					}
					return ItemStack.EMPTY;
				}
				return ItemStack.EMPTY;
			}
		});
		// maybe use can use vanilla util:
//		PotionBrewing.addContainer(steelPotionBottle);
//		PotionBrewing.addContainer(steelSplashPotionBottle);
//		PotionBrewing.addContainer(steelLingeringPotionBottle);
//		PotionBrewing.addContainerRecipe(Items.POTION, Items.IRON_INGOT, steelPotionBottle);
//		PotionBrewing.addContainerRecipe(Items.SPLASH_POTION, Items.IRON_INGOT, steelSplashPotionBottle);
//		PotionBrewing.addContainerRecipe(Items.LINGERING_POTION, Items.IRON_INGOT, steelLingeringPotionBottle);
		
		BrewingRecipeRegistry.addRecipe(new IBrewingRecipe() {
			@Override
			public boolean isInput(ItemStack input) {
				return input.getItem() == steelPotionBottle;
			}

			@Override
			public boolean isIngredient(ItemStack ingredient) {
				return ingredient.getItem() == Items.GUNPOWDER;
			}

			@Override
			public ItemStack getOutput(ItemStack input, ItemStack ingredient) {
				return PotionUtils.addPotionToItemStack(new ItemStack(steelSplashPotionBottle), PotionUtils.getPotionFromItem(input));
			}
		});
		
		BrewingRecipeRegistry.addRecipe(new IBrewingRecipe() {
			@Override
			public boolean isInput(ItemStack input) {
				return input.getItem() == steelSplashPotionBottle;
			}

			@Override
			public boolean isIngredient(ItemStack ingredient) {
				return ingredient.getItem() == Items.DRAGON_BREATH;
			}

			@Override
			public ItemStack getOutput(ItemStack input, ItemStack ingredient) {
				return PotionUtils.addPotionToItemStack(new ItemStack(steelLingeringPotionBottle), PotionUtils.getPotionFromItem(input));
			}
		});
		// maybe use can use vanilla util:
//		PotionBrewing.addContainerRecipe(steelPotionBottle, Items.GUNPOWDER, steelSplashPotionBottle);
//		PotionBrewing.addContainerRecipe(steelSplashPotionBottle, Items.DRAGON_BREATH, steelLingeringPotionBottle);
		
		
	}
}
```
</details>

2020-02-03 04:44 UTC, LexManos commented
1) You can use the standard mechanism that the vanilla code does, using java's instanceof operator.
2) As Dies stated, the main issue is that we do not accept 'MAKE ALL THE THINGS PUBLIC' ATs. You JUST want the addContainer/addContainerRecipe {which I am still not convinced that people need} so you should add those two lines directly, not a wildcard.
So, as it sits it seems you need to talk to someone and figure out exactly what you're trying to do.

2020-02-03 05:16 UTC, Yaossg commented
> 1. You can use the standard mechanism that the vanilla code does, using java's instanceof operator.
> 2. As Dies stated, the main issue is that we do not accept 'MAKE ALL THE THINGS PUBLIC' ATs. You JUST want the addContainer/addContainerRecipe {which I am still not convinced that people need} so you should add those two lines directly, not a wildcard.
>    So, as it sits it seems you need to talk to someone and figure out exactly what you're trying to do.

1. Please view example I provided above first, It's not just an easy 'instanceof' who can solve problems
2. A wildcard is after considering. 3 private methods matters (addMix, addContainer, addContainerRecipes). 4 protected methods are helpers (Why mojang make them protected as they're static methods inside a final class？). What's more, there exists MAKE ALL PUBLIC AT already.
3. See [here](https://github.com/MinecraftForge/MinecraftForge/issues/5814) and [here](https://github.com/Vazkii/Quark/blob/master/src/main/java/vazkii/quark/base/reflect/PotionReflection.java). I have talked to someone who once had the same view as you and dies. Now he got understood why. (example code above provided by my friend).
two links mentioned: @yrsegal @Vazkii

2020-02-15 07:38 UTC, Minecraftschurli commented
From what I can see it would be enough to expose addContainerRecipe and addContainer because everything else can be done by using the methods in BrewingRecipeRegistry

2020-02-24 00:30 UTC, Yaossg commented
> From what I can see it would be enough to expose addContainerRecipe and addContainer because everything else can be done by using the methods in BrewingRecipeRegistry

Even if mods which added potions never use that because of complexity.

Shall we remove crafting shapless and shaped because we had a more generic way to implement?
There exist 2 special furnaces in the game because they can smelt special itmes faster without mistabke(other things cannot be smelted there)
There exists special hooks in vanilla because they can register faster without mistake

I think maybe few of you ever tried to add potion as a modder. I listed people who did but you ignore those who always reflect or ATs to access addMix instead of Forge's generic hooks

2020-03-13 02:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6490) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6490) before we can accept your contribution.<br/><hr/>**Yaossg** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=6490) it.</sub>

2020-05-15 17:27 UTC, closed without merging