[1.15] allow different item attribute modifier based on the applied entity
MinecraftForge/MinecraftForge pull request #6567
Opened 2020-03-14 16:27 UTC by Cheaterpaul

this allows for an custom item to override IForgeItem#getAttributeModifiers to return different attribute modifier based on the entity the modifier should be applied to.

2020-03-22 14:37 UTC, diesieben07 requested changes
These changes are not binary compatible.

2020-03-23 11:19 UTC, Cheaterpaul commented
hope this is binary compatible.

not sure about the IForgeItem, maybe inline that for 1.16

2020-03-24 19:33 UTC, williewillus commented on src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
>          return getItem().getAttributeModifiers(slot);
Can you mark this old method as deprecated for removal in 1.16?

2020-03-24 19:34 UTC, williewillus commented on src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
>          return getItem().getAttributeModifiers(slot);
(not this line, but the method it's in)

2020-05-12 22:18 UTC, LexManos commented
Yes.. but why?
Also you need an exec file to minimize your patch as you've got hunks that are just name changes.

2020-07-09 18:31 UTC, closed without merging