1.15 Create a JigsawPiece event
MinecraftForge/MinecraftForge pull request #6732
Opened 2020-05-29 02:32 UTC by Cyborgmas

Add an event which fires when a Jigsaw Block is looking for all possible jigsaw connections from a pool.

This means that when generating plain villages (which are the biggest) there is about 500 to 600 event fired.

The event contains the list of jigsawpieces which can be modified in any way. 
It also contains 3 fields to be able to pinpoint which jigsaw pieces to replace.

There is also a test mod which replace the iron golem spawn with a wither one. This is only in plains biome, so to test use buffet generation. 

This however does not allow for putting custom JigsawPatterns in the village pools.
However, it is (should be... did not check) still possible to use custom pools by using a JigsawPiece containing a jigsaw block containing a custom pool. that pool having been registered to the JigsawPatternRegistry in the JigsawManager

2020-05-29 02:32 UTC, Cyborgmas commented
i was told this PR exists also https://github.com/MinecraftForge/MinecraftForge/pull/6378 
But i was already in too deep, and hopefully this solution is a bit better

2020-05-29 17:57 UTC, GotoLink commented
I don't speak for the Forge team here, but i think the javadoc goes into "code guide" territory.
I would stick to the facts:
-when the event is fired (and possibly a simple use-case)
-what the fields mean (and possibly where to use them).
From a coding-style point of view, i dislike the enum here, you just use it as string array..so why no string array ?

2020-05-29 23:36 UTC, Cyborgmas commented
Yeah you are right, went a little overboard with the javadocs I will admit that. 
What I propose is to leave them as is for now so that anyone reviewing this PR has access to that information. When it comes time to PR ill make it more concise and submit everything to the Forge Docs.

I like enums because they are flashy and serve as a code reference. You can see all the types just by typing its name instead of the array list which you have to check the inside the event and the strings.
Still see why it is pretty useless to make it as an enum, so I made it an immutable list. 

Also corrected some things. for instance some jigsaw patterns can be empty, so added that.
JigsawPatterns can also be invalid, however that is checked before the event so can never happen.

2020-06-24 23:04 UTC, Cyborgmas commented
Removed the javadoc and added a PR to the documentation, ofc for now the link in the javadocs is broken.

2020-06-28 15:14 UTC, filips123 commented
I have a use-case for such event (but with some modifications) for my custom structure for my mod. I posted more details to [forums](https://forums.minecraftforge.net/topic/87580-1161-partly-changing-jigsawmanagers-functionality/).

2020-06-28 16:03 UTC, Cheaterpaul requested changes
At whole this seem like a good approach. But this does not work for non village & pillage structures.

Not sure if that are to much events for only one village at world gen, because the result for throwing the event for the same patternlocation is always the same (except `currentDepth`, but i dont know how it should help).

2020-06-28 16:03 UTC, Cheaterpaul commented on src/main/java/net/minecraftforge/event/world/JigsawPieceEvent.java
> +      this.specificType = pool.replace("zombie/", "");;
With a custom jigsawbased structure that adds a patternlocation that contain `village` or `zombie`. `specificType` will be filled with a useless string. (additionally modid is missing)

2020-06-28 16:03 UTC, Cheaterpaul commented on src/main/java/net/minecraftforge/event/world/JigsawPieceEvent.java
> +   public final int currentDepth;
There should be a field that holds the whole patternLocation. And then `generalType` and `specificType` are not really needed.

2020-07-07 21:10 UTC, filips123 commented
I tried to port this PR to 1.16, make it more friendly for modded structures and implement some of the things I mentioned in my forum topic. I think it works but I still need to modify and test it a bit. Is it ok if I open a PR for that in a few days?

2020-07-07 21:44 UTC, Cyborgmas commented
Ah dang, dont know how i missed the updates from cheaterpaul - will address them when i have the time (not this week prob). you can if you want but i was going to port this eventually fyi

2020-07-10 12:32 UTC, Cyborgmas commented
#6939 should be backported instead, no sense making 2 separate PRS

2020-07-10 12:32 UTC, closed without merging