Add function to add items with the same behavior as the pumpkin for enderman
MinecraftForge/MinecraftForge pull request #6890
Opened 2020-06-30 20:47 UTC by Mysterious-Dev

This RP adds an function to create an item like carved pumpkin for enderman

This PR is a recréation of an [old ](https://github.com/MinecraftForge/MinecraftForge/pull/6759)one which was closed for Forge 1.15.x

2020-07-01 07:41 UTC, diesieben07 requested changes

2020-07-01 07:41 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
> +    default boolean isEnderMask(PlayerEntity player, EndermanEntity endermanEntity) {
Formatting (braces on newlines)

2020-07-01 07:42 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
> +    default boolean isEnderMask(ItemStack stack, PlayerEntity player, EndermanEntity endermanEntity) {
Formatting (braces on newlines)

2020-07-01 08:40 UTC, Mysterious-Dev commented on src/main/java/net/minecraftforge/common/extensions/IForgeItem.java
> +    default boolean isEnderMask(ItemStack stack, PlayerEntity player, EndermanEntity endermanEntity) {
It's change

2020-07-01 08:40 UTC, Mysterious-Dev commented on src/main/java/net/minecraftforge/common/extensions/IForgeItemStack.java
> +    default boolean isEnderMask(PlayerEntity player, EndermanEntity endermanEntity) {
It's change

2020-07-01 08:46 UTC, diesieben07 approved these changes

2020-07-04 20:26 UTC, Mysterious-Dev commented
Now what can i do?

2020-07-06 20:34 UTC, merged