Add support for custom Nether Portal Blocks
MinecraftForge/MinecraftForge pull request #6896
Opened 2020-07-01 22:47 UTC by artman41

- Modify accessibility so that `NetherPortalBlock$Size` can be extended, allowing for custom `NetherPortalBlock`s
- Allow `NetherPortalBlock$Size` to be instantiated with a given `portalBlock`

2020-07-01 22:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6896) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6896) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=6896) it.</sub>

2020-07-01 22:50 UTC, pupnewfster commented
Isn't this already possible via `IForgeBlock#isPortalFrame`? https://github.com/MinecraftForge/MinecraftForge/blob/1.16.x/src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java#L582

2020-07-01 22:51 UTC, artman41 commented
@pupnewfster if I'm not mistaken, that's referring to the Obsidian outer frame correct?

2020-07-01 22:52 UTC, pupnewfster commented
That is correct, is this PR for the actual portal itself?

2020-07-01 22:52 UTC, artman41 commented
It is

2020-07-02 09:23 UTC, diesieben07 requested changes
Your patch file is completely broken, did you edit it by hand?

2020-07-02 09:23 UTC, diesieben07 commented on patches/minecraft/net/minecraft/block/NetherPortalBlock.java.patch
> ++      protected int portalBlockCount;
Please use an AT

2020-07-02 09:23 UTC, diesieben07 commented on patches/minecraft/net/minecraft/block/NetherPortalBlock.java.patch
> ++      protected int width;
Please use an AT

2020-07-02 09:23 UTC, diesieben07 commented on patches/minecraft/net/minecraft/block/NetherPortalBlock.java.patch
> ++         this.portalBlock = portalBlock;
Move this assignment up (first thing in the constructor) to get a consecutive patch.

2020-07-02 09:55 UTC, artman41 commented on patches/minecraft/net/minecraft/block/NetherPortalBlock.java.patch
> ++      protected int portalBlockCount;
@diesieben07 could I get a definition on `at`?

2020-07-02 09:57 UTC, TheSilkMiner commented on patches/minecraft/net/minecraft/block/NetherPortalBlock.java.patch
> ++      protected int portalBlockCount;
Access Transformer

2020-09-14 11:45 UTC, closed without merging