Implement GUI Stacking feature.
MinecraftForge/MinecraftForge pull request #6927
Opened 2020-07-06 20:22 UTC by gigaherz

You can now use `mc.pushGuiLayer` and `mc.popGuiLayer` to manage the layers.
mc.displayGuiScreen behaves such that if called with a non-null screen it replaces the entire stack, and if called with null it closes the entire stack.

![stack showcase](https://cdn.discordapp.com/attachments/679070190721433659/729784664700616835/unknown.png)

Supersedes #6867

2020-07-13 16:41 UTC, Nightenom commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +            drawScreenInternal(layer, mStack, -1, -1, partialTicks);
Why don't you pass in mouse XY?

2020-07-13 16:43 UTC, Nightenom approved these changes
Seems ok

2020-07-13 16:45 UTC, Mysterious-Dev approved these changes
This look good

2021-04-30 02:28 UTC, TheCurle commented
Please rebase this PR when you get the time, and still would like this PR to be implemented.

This is another surprisingly often requested feature, and it would be nice for those mods that deal with GUIs in this way, such as those that have layered configuration interfaces.

2021-09-30 23:59 UTC, sciwhiz12 requested changes
Some minor indentation quibbles, then this looks as fine as the 1.17 PR to me.

2021-09-30 23:59 UTC, sciwhiz12 commented on src/test/resources/META-INF/mods.toml
> +	modId="containertypetest"
Please revert this indentation change of a tab character.

2021-09-30 23:59 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +    }
Please fix this unneeded indentation change.

2021-10-02 07:29 UTC, sciwhiz12 approved these changes

2021-10-06 01:02 UTC, ChampionAsh5357 approved these changes

2021-11-04 07:09 UTC, merged