[1.16.x] Added event for when a particle is spawned in the world
MinecraftForge/MinecraftForge pull request #6943
Opened 2020-07-09 08:35 UTC by ChristianANoeddeboe

Adds a new event, which is used when a particle is spawned in the world.

This allows players to temporarily replace or change a spawned vanilla particle.

An example scenario is increasing the damage the player does. So far a high damage hit on an entity will display many damage particles, and this will help modders reduce these to a reasonable amount.

Testmod has been added as ParticleWorldHandleEventTest.java.

2020-07-16 19:48 UTC, diesieben07 requested changes

2020-07-16 19:48 UTC, diesieben07 commented on patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch
> ++      if(event == null) return 0;
Formatting (missing space after `if`)

2020-07-16 19:48 UTC, diesieben07 commented on patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch
> ++      if(event == null) return false;
Formatting (missing space after `if`)

2020-07-17 10:25 UTC, diesieben07 approved these changes

2020-07-17 17:19 UTC, ichttt commented
Is this event really needed? Is there no other way to cancel whatever spawen the particles? As this is an event that would fire quite often, we have to evalute if it is really worth the performance hit.

2020-07-17 18:43 UTC, ChristianANoeddeboe commented
> 
> 
> Is this event really needed? Is there no other way to cancel whatever spawen the particles? As this is an event that would fire quite often, we have to evalute if it is really worth the performance hit.

For now it seems the only way to cancel or change vanilla particle spawns would be modifying the original code. In my use case a lot of damage particles are spawned when applying a high amount of damage, no matter how much health the mob has. This would allow me to cancel most of these, such if I only do 10% damage on a mob, it will not spam damage particles out.

2020-07-28 09:07 UTC, ichttt commented
Sorry but I don't think this PR can be accepted in this way. This has a major performance penalty. We understand its a farily good place to hook in due to it being the central location. But it'd be better if the particles just wouldn't be spawned.

2020-07-28 09:25 UTC, ChristianANoeddeboe commented
> 
> 
> Sorry but I don't think this PR can be accepted in this way. This has a major performance penalty. We understand its a farily good place to hook in due to it being the central location. But it'd be better if the particles just wouldn't be spawned.

Any alternative way you might see I can disable the particles spawning? I realize this will often be fired, but atm. I am not sure how I might affect particle spawning without modifying base classes. But I'm completely open to alternatives to this.

2021-06-25 23:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6943) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=6943) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: ChristianANoeddeboe<br/>:x: Christian<br/><hr/>**Christian** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=6943) it.</sub>

2021-12-24 21:14 UTC, sciwhiz12 commented
Hello! @ChristianANoeddeboe, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). If we do not hear back from you after some time, this PR will be closed for inactivity.
Additionally, if you do continue this PR, please rewrite your commits so the authors are properly in place for the CLA assistant to properly detect this PR's full compliance with the CLA.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2021-12-28 14:55 UTC, can-vaerks commented
@sciwhiz12 
I don't mod minecraft anymore, and as it seems this didn't have a lot of interest, you can go ahead and close this one.

2021-12-28 14:58 UTC, ChristianANoeddeboe commented
@sciwhiz12 
I don't mod minecraft anymore, and as it seems this didn't have a lot of interest, you can go ahead and close it.

2021-12-28 15:12 UTC, closed without merging