Forge gui rendering utils was not using matrixstack
MinecraftForge/MinecraftForge pull request #7127
Opened 2020-07-24 13:30 UTC by Cyborgmas

Added matrix stack to all of its functions and use it in the IVertexBuilder.

2020-07-24 13:42 UTC, Nightenom approved these changes
Looks good, few formatting mistakes

2020-07-24 13:42 UTC, Nightenom commented on src/main/java/net/minecraftforge/fml/client/gui/GuiUtils.java
> +        drawTexturedModalRect(matrixStack,x + leftBorder + canvasWidth, y, u + leftBorder + fillerWidth, v, rightBorder, topBorder, zLevel);
Missing spaces after commas, also few times below

2020-07-24 13:54 UTC, desht commented on src/main/java/net/minecraftforge/fml/client/gui/widget/ExtendedButton.java
> +        super(xPos, yPos, width, height, displayString, handler,tooltip);
Missing comma between handler & tooltip

2020-07-24 13:57 UTC, desht commented
You beat me to it (was just preparing a PR), but this looks pretty much exactly like what I've done locally

I've also confirmed this fixes my problem in PneumaticCraft: Repressurized, where GUI buttons weren't rendering.  I did create a tiny test mod to create a trivial GUI with a single ExtendedButton in the centre of the screen, but that doesn't demonstrate the problem, presumably because the default transform is OK for something so trivial.

2020-07-24 15:04 UTC, Cyborgmas commented on src/main/java/net/minecraftforge/fml/client/gui/widget/ExtendedButton.java
> +        super(xPos, yPos, width, height, displayString, handler,tooltip);
gonna guess you meant space

2020-07-24 15:05 UTC, Cyborgmas commented
Sorry for stealing the PR hah, sometimes i jump on stuff pretty randomly.

2020-07-25 12:02 UTC, marchermans approved these changes

2020-09-15 14:21 UTC, gigaherz requested changes
Hey Cyborg, Sorry for not looking at this sooner.
I'd like to merge this, but it's a bit late in the process now to have those breaking changes, I think.
Since you have to rebase anyhow, could you take the chance to duplicate the methods and keep the original ones `@Deprecated`?

2020-09-15 18:36 UTC, OrionDevelopment commented
Yeah sorry i missed that one too during the review.
Need to get used to requiring matrixstack everywhere where rendering is involved.

/me makes note.....

2020-09-15 19:45 UTC, gigaherz approved these changes
Thanks :)

2020-09-15 19:46 UTC, merged