[1.15] Re-added PlayerEvent.NameFormat
MinecraftForge/MinecraftForge pull request #7173
Opened 2020-07-25 19:01 UTC by Tschipp

1.15 Backport of #6992 
Since it seems that `PlayerEvent.NameFormat` wasn't ported to more recent versions of Forge, I have reimplemented it here.
The behavior is identical to how it used to work:
- The `PlayerEvent.NameFormat` is fired properly and can change the display name of a player.
- This affects the name tag in the world and in the chat.
- This does not affect the name in the player list (tab). This is intended and how it used to work.
- `EntityPlayer#refreshDisplayName()` needs to be called to re-fire the `PlayerEvent.NameFormat` event.

Changes:
- Didn't readd `EntityPlayer#getDisplayNameString()`. Instead, the `displayname` field is now set in `EntityPlayer#getDisplayName()`

- This PR also contains a test mod

This PR should be non-breaking, for all those that used `PlayerEvent.NameFormat` in their mods (but didn't notice that it is never fired).

2020-07-26 11:08 UTC, diesieben07 requested changes
I think you should expose the original `ITextComponent` in the event as well and allow setting it as well. This will require some deprecation of the methods that use `String`.

2020-07-26 12:33 UTC, Tschipp commented
I thought about it, but decided against it, simply for the reason that I would have to make different names for the `ITextComponent` methods, and those names wouldn't be used in the 1.16 version anymore (at least how my PR stands right now). Thus when updating from 1.15 to 1.16 the modders have to either rename the method (So from `getDisplaynameComponent` to `getDisplayName`) Or they just account for the return type of those methods no longer being a `String` but a `ITextComponent`. What do you think is the better approach?

2020-07-26 12:35 UTC, diesieben07 commented
Yes, but this prevents people from doing proper formatting.

2020-07-26 12:37 UTC, Tschipp commented
That is true. Though they could always use `ChatFormatting` for color codes and styles I guess. What other things could be customized? Click events don't really make sense in this context.

2020-07-26 12:43 UTC, diesieben07 commented
Raw use of text formatting codes is ugly and deprecated.
`ITextComponent` would also allow using for example `TranslationTextComponent`.

2020-07-26 12:44 UTC, Tschipp commented
Yeah, that makes sense. Alright I'll make an augment of this PR and include methods for `ITextComponent`s

2020-07-28 08:16 UTC, Tschipp commented
Alright, changed it

2020-07-28 08:42 UTC, diesieben07 approved these changes

2020-08-03 23:35 UTC, merged