Add ConcretePowderConversionEvent
MinecraftForge/MinecraftForge pull request #7188
Opened 2020-07-28 22:39 UTC by mrp-v2

Adds an event for when concrete powder is about to convert to concrete. Allows the conversion to be cancelled.
Includes a test mod.

2020-07-28 22:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=7188) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=7188) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=7188) it.</sub>

2020-07-29 08:26 UTC, diesieben07 requested changes
As it is implemented currently this event is very limited, as it only allows prevention of the conversion.
The event should instead provide a setter for the resulting block state and not just be cancellable but have a `Result`:
- `Result.DENY`: Do not convert.
- `Result.ALLOW`: Convert to block state given in event (which by default is the solidified state), regardless of vanilla checks.
- `Result.DEFAULT`: Apply vanilla logic.

It's also questionable if this should be an event at all. Is it not enough to ask the block which (potentially) causes the conversion? i.e. add a method to `IForgeBlockState` and `IForgeBlock`, called for example `convertConcretePowder`.

2020-07-29 08:26 UTC, diesieben07 commented on src/test/java/net/minecraftforge/debug/block/ConcretePowderConversionEventTest.java
> +public class ConcretePowderConversionEventTest {
Formatting (braces on new lines)

2020-07-29 08:26 UTC, diesieben07 commented on src/test/java/net/minecraftforge/debug/block/ConcretePowderConversionEventTest.java
> +    public static void concretePowderConversion(final BlockEvent.ConcretePowderConversionEvent event){
Formatting (braces on new lines)

2020-07-29 08:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/world/BlockEvent.java
> +    /* Fired when a concrete powder block is about to be converted to a concrete block from
This is not proper Javadoc formatting

2020-07-29 08:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +
Unnecessary whitespace change

2020-07-29 08:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
> +        return MinecraftForge.EVENT_BUS.post(new BlockEvent.ConcretePowderConversionEvent(world, pos, world.getBlockState(pos)));
Why call `getBlockState` here instead of passing in the state being converted?

2020-07-29 13:38 UTC, mrp-v2 commented
I have now modified the event to have a result instead of being `cancelable`.

> It's also questionable if this should be an event at all. Is it not enough to ask the block which (potentially) causes the conversion? i.e. add a method to `IForgeBlockState` and `IForgeBlock`, called for example `convertConcretePowder`.

I'm don't think I understand. Are you saying a method should be added to `IForgeBlock` and `IForgeBlockState` that `ConcretePowderBlock` then calls to see if it should convert?

2020-07-29 14:21 UTC, diesieben07 commented
Yes, that way a custom fluid could for example decide to turn concrete powder into something else.
What else is your use-case for this being an event?

2020-07-29 15:04 UTC, mrp-v2 commented
I have a mod in which I wanted to give players the option of disabling the vanilla concrete conversion mechanic.

2020-07-29 17:55 UTC, diesieben07 requested changes
Now you have some sort of strange hybrid between the two suggested approaches. And you didn't implement the blockstate replacement.
And you still have unnecessary whitespace changes.

2020-07-29 19:04 UTC, mrp-v2 commented
I fixed my IDE settings so the whitespace changes will stop happening. Also I think I may have reached a decent combination of the `IForge...` methods and the conversion event.

2020-07-30 08:49 UTC, diesieben07 requested changes
My point was not to make the event _and_ method in IForgeBlock... Either one or the other. Both together just confuses things.

2020-07-30 08:49 UTC, diesieben07 commented on patches/minecraft/net/minecraft/block/ConcretePowderBlock.java.patch
> ++            if (causesSolidify(blockstate, direction.func_176734_d(), p_196441_0_, blockpos$mutable)) {
Why does suddenly only check the method? And not the event? You have to be consistent.

2020-07-30 14:20 UTC, mrp-v2 commented
It is now only the `IForge...` methods, which should still allow canceling vanilla behavior by replacing vanilla's water block.

2020-10-25 16:12 UTC, TheCurle commented
Please rebase to clean up that commit log and fix the conflicts.

2020-10-25 18:05 UTC, mrp-v2 commented
Done. Also cleaned up leftover code from the event.

2021-12-24 20:49 UTC, sciwhiz12 commented
Hello! @mrp-v2, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2022-03-05 10:38 UTC, sciwhiz12 commented
Hello! Since the application of the Stale label, there has been no recent activity on this PR. As said in our previous comment, this PR will now be closed for inactivity.

If you wish to continue this PR, please open a new PR against the Latest supported version (to be conformant with our version support and contributions policy). 

Thank you for your contributions. 👋

2022-03-05 10:38 UTC, closed without merging