Add DataProviders for WorldGen
MinecraftForge/MinecraftForge pull request #7257
Opened 2020-08-16 20:33 UTC by Cyborgmas

Added dataproviders for all of the possible registries, formatting is still incorrect for now, I'll be fixing it a bit later.

Codecs are the key feature her and I explain a lot of it in the javadocs. 

An issue I encountered is that most world gen objects will inline any other worldgen object that is not present in the registry and not reference them using a resourcelocation. To prevent that, RegistryKeyCodec must be used and parsed using WorldSettingsImport.
Furthemore, some providers depend on the output of other providers, it would be a pain to have to gen the first batch of files, put them in the mod resources, then gen the second batch (and then a third batch even!).
To help with that, each new provider will cause the ExistingFileHelper to reload the ResourceManager. Since it has no listeners it is pretty efficient and only serves to discover the newly created files. This is then used by the WorldSettingsImport$IResourceAccess (its anonymous class, which bases itself off of a ResourceManager).

There was also some issues with how enums are decoded because of IEnumExtensible, added some debug information for that.

Questions welcome and if some extra helper could be added, do tell.

2020-08-18 18:18 UTC, Cyborgmas commented
Okay, so made it much easier now to reference other objects through RegistryOpsHelper.

2020-08-26 15:46 UTC, Redstoneguy129 approved these changes

2020-09-23 11:59 UTC, Cyborgmas commented
This PR contains some minor breaking changes, only related to internal stuff however. (DataModLoader and GatherDataEvent).
However, the main thing is that it allows for properly encoding object references instead of the whole objects, something that is needed to make datagen for #7287

2020-12-27 19:58 UTC, Cyborgmas commented
The latest commit also removed the breaking in change in GatherDataEvent

2021-09-27 00:07 UTC, ChampionAsh5357 requested changes
So I have one major concern that's not really specified. This forces an order of registration meaning that Carvers must be registered before Biomes and so on. This order is not made clear for any consumer trying to use these events.

In other news, please update this PR to 1.17 as well.

2021-09-27 00:07 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/entity/EntityClassification.java.patch
>  +   }
Is this a misapplied patch since it seems to be unrelated to this PR?

2021-09-27 00:07 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/data/worldgen/CodecBackedProvider.java
> +        this(codec, regOps, new GsonBuilder().setPrettyPrinting().registerTypeAdapter(ResourceLocation.class, new ResourceLocation.Serializer()).create());
Why create a new GSON instance for every provider?

2021-09-27 00:07 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/data/worldgen/RegistryBackedProvider.java
> +            ((IForgeRegistryEntry<?>) instance).setRegistryName(name);
I don't believe this is necessary as the codec field itself is optional. Adding this field wouldn't do anything anyways as it seems Forge replaces it with the current registry name regardless.

2021-09-27 00:07 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/data/worldgen/BiomeDataProvider.java
> +public abstract class BiomeDataProvider extends RegistryBackedProvider<Biome>
Most of this class could be abstracted into `RegistryBackedProvider`.

- `#map` and `#generator` can be stored within the registry backed provider
- `#act` and `#put` could also be implemented back there as the location is stored within the registry key path
- `#modid` is only used for `#getName`, it probably doesn't need to be a field here.
- The entire class needs to be javadoced more clearly since you have to observe the code to be able to figure out how to get it working.

2021-09-27 00:07 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/data/worldgen/ConfiguredCarverProvider.java
> +        //TODO This codec is dispatched for the vanilla CARVER registry, and won't affect any mod added carvers.
Is this comment out of date along with the rest? `RegistryOpsHelper` registers to the vanilla registry along with any other mod carvers. This event executes after `FMLCommonSetupEvent` which by then all mods have registered to the builtin registries. The only one this isn't true for is the `#DIMENSION_TYPE_REGISTRY` iirc, but those seem to be added from the `RegistryOpsHelper`.

2021-12-25 02:26 UTC, sciwhiz12 commented
Hello! @Cyborgmas, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2021-12-26 20:46 UTC, Cyborgmas commented
Will try to update, but not sure. Will close for now, and open a new PR in the case I do update

2021-12-26 20:46 UTC, closed without merging