Implement LivingConversionEvent event
MinecraftForge/MinecraftForge pull request #7386
Opened 2020-10-02 10:28 UTC by poopoodice

This is an event can help the users to handle mob conversion.
If pre is cancelled the mob conversion will be also cancelled.
Post provides the original entity (likely to be removed right after the event), and the new entity.

2020-10-02 12:20 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/living/LivingConversionEvent.java
> +@Cancelable
The base event should not be cancelable. Only make the needed events cancelable.

2020-10-02 12:20 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/living/LivingConversionEvent.java
> +        }
None of these seem to do anything.

2020-10-02 12:20 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/living/LivingConversionEvent.java
> +        }
These also seem pointless.

2020-10-02 12:20 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/living/LivingConversionEvent.java
> +package net.minecraftforge.event.entity.living;
Add Forge license for header.

2020-10-02 12:20 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/entity/living/LivingConversionEventTest.java
> +package net.minecraftforge.debug.entity.living;
Add Forge license for header.

2020-10-05 23:12 UTC, Alpvax commented
Do we want to expand this to include creeper -> charged creeper?
Or is it only for when the EntityType changes?

2020-10-05 23:18 UTC, cech12 commented
A mooshroom can be transformed by a lightning. The EntityType does not change but the color (brown).
Maybe the Sheep can also be part of it when it is colored?

2020-10-05 23:56 UTC, poopoodice commented
I feel like the things you've mentioned (change in data) should probably handle in another new event as if we add those changes in this event, it will make things a bit messed up unless we create a list of conditions to decide clearly if a data change can be count as a conversion.

2020-10-07 07:05 UTC, OrionDevelopment approved these changes
Good addition.

Personally I think we should not trigger this event for raw data changes.
We could add additional events for this, but a single event, like EntityStateChanged could also suffice.

That said, this PR works, code looks good and well formatted.

2020-10-07 07:06 UTC, OrionDevelopment requested changes
Code okey, javadoc missing.

2020-10-07 07:06 UTC, OrionDevelopment commented on src/main/java/net/minecraftforge/event/entity/living/LivingConversionEvent.java
> +        public EntityType<? extends LivingEntity> getOutcome()
Please add javadoc to this entry.

2020-10-07 07:06 UTC, OrionDevelopment commented on src/main/java/net/minecraftforge/event/entity/living/LivingConversionEvent.java
> +        public LivingEntity getOutcome()
Please add javadoc to this entry.

2020-11-10 20:04 UTC, LexManos commented
Needs rebasing, but pullable after that.

2020-11-10 22:14 UTC, poopoodice commented
Haven't play Minecraft for a while, there may be some leftovers.

Entities conversion types we currently have in this pr:
Villager --> Witch
Zombie --> Drowned
Villager <-> ZombieVIllager
Piglin    -->  Zombified Piglin
Pig        -->  Zombified Piglin

2020-11-10 22:17 UTC, bl4ckscor3 commented
Hoglin --> Zoglin is one that is missing.

2020-11-10 22:17 UTC, sciwhiz12 commented
There is also conversion of red mooshrooms into brown mooshrooms and vice-versa by being struck by lightning.

2020-11-10 22:29 UTC, poopoodice commented
> Hoglin --> Zoglin is one that is missing.

Thank you.

> There is also conversion of red mooshrooms into brown mooshrooms and vice-versa by being struck by lightning.

LivingConversionEvent is currently looking for conversions that have changing in EntityType, but mooshrooms are pretty special that they have their own type, there's a discussion on this in previous comments.

I'm also thinking should we reset the timer when the event is cancelled, for example:
- Reset drownedConversionTime to 0 if the event is cancelled.
- Reset field_234358_by_ to 0 if the event is cancelled.

Otherwise the event can be triggered every tick even if the event was cancelled last tick, an alternative way is I can create another boolean to let the users decide whether the timer should be reset. What do you think?

2020-11-11 19:48 UTC, Alpvax commented
It might be worth making the timer available in the event so modders can delay the transformation by a set number of ticks. For transformations without a timer it could be set to -1 and ignored

2020-11-11 19:53 UTC, LexManos commented
That was my initial thought myself, but not all conversions are based on timer. So it'd be better to access accessors to the entities themselves, and let the mods call whatever logic they want to delay.

2020-11-12 23:07 UTC, poopoodice commented
Maybe something like this will work?

`
private boolean reset;
public void resetTimerIfApplicable()
{
    reset = true;
}`

`
if (shouldConvert())
{
    LivingConversionEvent event = ........;
    if (!event.isCancelled())
        convert();
    else if (event.shouldRestTimer())
        timer = 0;
}
else
    timer = 0;`

2020-11-12 23:51 UTC, Alpvax commented
> Maybe something like this will work?
> 
> https://pastebin.com/UqQr5Dky

Except that will not reset the cooldown when the event is cancelled. You need to remove the else from the else if.

2020-11-13 08:28 UTC, poopoodice commented
> Except that will not reset the cooldown when the event is cancelled. You need to remove the else from the else if.

Are you sure about that, I may be wrong but isn't if the event is cancelled, boolean cancelled = true, then !cancelled = false, therefore else if will execute which resets the timer if needed?

2020-11-13 09:08 UTC, Alpvax commented
My mistake, if it is not cancelled, the timer will not reset. But of course in that instance the transformation will continue, so the timer will be irrelevant. I had not thought through all the side effects.

2020-11-13 09:23 UTC, poopoodice commented
> My mistake, if it is not cancelled, the timer will not reset. But of course in that instance the transformation will continue, so the timer will be irrelevant. I had not thought through all the side effects.
Yeah, the reason I did not reset if the event is not cancelled is that the entity itself is likely going to be removed right after that.

2020-11-20 18:55 UTC, LexManos commented
Perhaps pass in a Consumer<Integer> to the hook to reset the timer to a numeric value?
So we dont have to add accessors. And so that the patches can be tiny `delay -> this.convertDelay = delay` as an argument to the hook.

Also, its a difference between 'reset the time' and 'set the timer to a value'
The second part is more flexible so you should go that route.

2020-12-05 19:47 UTC, LexManos requested changes
Sorry for the delay, moving houses is a pain. Anyways, seems there are some obf issues with your latest commit. @MinecraftForge/issuemanager Can someone keep an eye on this and poke it when it's resolved. All my other concerns have been addressed.

2020-12-05 19:47 UTC, LexManos commented on patches/minecraft/net/minecraft/entity/monster/ZombieEntity.java.patch
> ++            if (this.field_204708_bE < 0 && net.minecraftforge.event.ForgeEventFactory.canLivingConvert(this, EntityType.field_200725_aD, (timer) -> this.drownedConversionTime = timer)) {
Something is broken here.. did you edit this file by hand? The field should of been mapped to the srg name. I mean.. it's fixed in the first part of the line, but the lamba is broken...

2020-12-05 19:47 UTC, LexManos commented on patches/minecraft/net/minecraft/entity/monster/ZombieVillagerEntity.java.patch
> ++         if (this.field_82234_d <= 0 && net.minecraftforge.event.ForgeEventFactory.canLivingConvert(this, EntityType.field_200756_av, (timer) -> this.conversionTime = timer)) {
Same here...

2020-12-05 19:47 UTC, LexManos commented on patches/minecraft/net/minecraft/entity/monster/piglin/AbstractPiglinEntity.java.patch
>            this.func_241848_eP();
This one obfed correctly

2020-12-21 10:00 UTC, poopoodice commented
It seems like I did not run genPatches correctly, sorry for wasting your time.

2020-12-28 20:02 UTC, LexManos approved these changes

2020-12-28 20:03 UTC, merged