[1.16.5] Add support for custom WoodTypes
MinecraftForge/MinecraftForge pull request #7623
Opened 2021-01-25 20:34 UTC by kaydogz

This is a newer version of #7304, due to my fork breaking. As per the original description:

`WoodType`'s are needed to make sign blocks, and currently, they are bound to the Minecraft namespace (see `Atlases#getSignMaterial`). The only way around this is an AT-filled hack that requires several classes and event subscribers to override GUIs and rendering. This PR will allow namespaced `WoodType`'s, as well as a proper system for creating a modded one, using `WoodType#create`. I also created a test that adds a simple sign using the new method of doing so.

2021-02-15 19:05 UTC, LexManos commented
Since this hasn't been relayed yet.
I'm having trouble seeing why any of this is necessary at all.
The map is public, you can insert your own values whenever you want.
The getName() function is only called in getSignMaterial, which is just a helper function to build the initial map.
So we don't need to introduce a big set of changes. People can just add their own WoodType/RenderMaterial to that map at the appropriate time with the existing code.

2021-02-15 20:38 UTC, kaydogz commented
getSignMaterial is called at line 93 of SignTileEntityRenderer, so I guess all that should be done is to return the map's value?

2021-02-15 20:43 UTC, LexManos commented
Humm, I missed that in my reference search. But yes, if the map has a value it should probably return that value.
You could also have a 2 line change to getSignMaterial that turns the name into a RL and splits it out.
The point is to make the changes as small as possible.

2021-02-16 22:47 UTC, kaydogz commented
Ok, should be good now. The additional line in ForgeHooksClient is needed to render the sign.

2021-02-17 07:05 UTC, covers1624 requested changes
Minor style changes

2021-02-17 07:05 UTC, covers1624 commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +import java.util.*;
Don't collapse imports to *'s

2021-02-17 07:16 UTC, kaydogz commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +import java.util.*;
Done.

2021-02-17 07:21 UTC, covers1624 approved these changes

2021-03-15 19:28 UTC, merged