Add (cancelable) ToastAddEvent for use in ToastGui.add
MinecraftForge/MinecraftForge pull request #7821
Opened 2021-06-16 17:05 UTC by Roundaround

Gives modders the ability to hook into the ToastGui's toast queue. To prevent the toast from being added, cancel the event. To change the toast, modify it directly or replace it with event.setToast(IToast).

2021-06-16 17:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=7821) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=7821) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=7821) it.</sub>

2021-06-16 17:23 UTC, ChampionAsh5357 reviewed
Bunch of things that would probably need to be addressed.
- There is no test case. How do we know this works rather than just some assumption that it does.
- There is no documentation. How do I use this event? What does it do?
- This will break existing Minecraft behavior because it doesn't replace all cases of the toast. e.g. `Tutorial#addTimedToast`. This will break all tutorial steps if replaced.

2021-06-16 17:23 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/event/ToastAddEvent.java
> +package net.minecraftforge.client.event;
Missing license header.

2021-06-16 17:23 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/event/ToastAddEvent.java
> +public class ToastAddEvent extends Event {
Incorrect formatting, forge uses new line braces.

2021-06-16 17:23 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/event/ToastAddEvent.java
> +    public ToastAddEvent(IToast toast) {
New line braces.

2021-06-16 17:23 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/event/ToastAddEvent.java
> +    private IToast toast;
Separate fields from constructor with empty line.

2021-06-16 17:23 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/event/ToastAddEvent.java
> +    public IToast getToast() {
New line braces.

2021-06-16 17:23 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/event/ToastAddEvent.java
> +    public void setToast(IToast toast) {
New line braces.

2021-06-16 17:24 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/client/gui/toasts/ToastGui.java.patch
> +       this.field_191792_h.add(p_192988_1_);
Just added another line, revert to what you previously had.

2021-06-16 18:39 UTC, Roundaround commented
I've formatted the files as requested, added JavaDoc comments to the event, and written a text/example mod demonstrating the event usage.

As for your third point about situations like `Tutorial#addTimedToast`, I've removed the ability to set the toast in the event (and therefore made it final), so that references to the passed toast remain valid.

2021-06-17 15:54 UTC, Roundaround commented
Sorry, accidentally closed when I attempted to rename the branch. Apparently you can rename the target branch and PRs will update, but the same cannot be said for the source branch.

2021-06-17 23:34 UTC, Roundaround reviewed
Responded to feedback. Updating

2021-07-14 20:30 UTC, TheCurle requested changes
Seems good, and if you can fix the issue quickly we can merge this with the next batch of PRs.

2021-07-14 20:30 UTC, TheCurle commented on src/test/java/net/minecraftforge/debug/client/ToastAddTest.java
> +    @OnlyIn(Dist.CLIENT)
This is poor practice, and in actuality won't help prevent any issues.. this should be removed from the test mod.

2021-12-25 02:17 UTC, sciwhiz12 commented
Hello! @Roundaround, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2021-12-25 19:08 UTC, closed without merging