[1.16.x] Add support to forge's "remove" list to tag datagenerators
MinecraftForge/MinecraftForge pull request #7870
Opened 2021-07-17 03:43 UTC by Commoble

## Background

Forge expands the tag format to support a "remove" list, allowing tags to specify IDs of individual elements or IDs of tags to remove from that tag rather than adding to it. However, the current tag generators do not support this; tag generators cannot currently generate tag jsons that use the "remove" list. This PR expands the tag datagenerators to support this.

For clarification, there are two kinds of "tag builders" that this PR touches:
* Firstly is the ITag.Builder (sometimes called the "internal" or "raw" builder, which is used for both parsing tag jsons when data is loaded, and for writing tag jsons during datagen. This builder only works with the IDs of things and doesn't care about what the tags actually represent.
* The other one is the TagsProvider.Builder, which is exclusively used for datagenerating tags of registry objects. TagsProviders provide TagsProviders.Builders to callers; these are wrappers around ITag.Builders but with methods for making tags of registry objects.

## What's this PR do?
We patch ITag.Builder in the following ways:
* We implement a new IForgeRawTagBuilder forge extension interface to minimize the size of the patch
* We add a list field to ITag.Builder that items to add to the "remove" list in the json can be added to
* Where the builder serializes its data to a json, we add a line to serialize our extra removal data

IForgeRawTagBuilder has methods for adding to the removal list in a similar manner to the way ITag.Builder adds values to the value list.

We also add extra methods to IForgeTagBuilder (the extension interface of TagsProvider.Builder) to assist with adding registry objects and tags to the removal list in the same way it can add things to the standard values list.

The reason for adding these methods to both builders is that A) data generation of tags of registry objects should use TagsProviders and their builders rather than working with ITag.Builders directly, while B) tags of things that aren't registry objects can easily exist (see: function tags) and would necessarily need their own data providers (not TagsProviders) backed by ITag.Builders in a similar way.

2021-11-12 04:56 UTC, ChampionAsh5357 commented
As the 1.17 version of the PR has been merged, the changes should be backported to this version. Apologies for not getting around to reviewing this until now.

2021-11-28 15:59 UTC, ChampionAsh5357 requested changes
Mainly just missing functionalities and consistent namings between the two PRs.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/tags/ITag.java.patch
> ++      public List<ITag.Proxy> getRemoveEntries() { return this.removeEntries; } // forge -- track additions to the "remove" list during datageneration
This should be a read-only view, see [this](https://github.com/MinecraftForge/MinecraftForge/pull/7911/files#diff-f8049b7220c9c3128f74e20f2128209a7a56cc09f4306035144cb8ed4dfbfdb7R9-R15).

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeRawTagBuilder.java
> +    default ITag.Builder removeProxy(final ITag.Proxy proxy)
See [Lex's comment](https://github.com/MinecraftForge/MinecraftForge/pull/7911/files#r684373367) on this.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeRawTagBuilder.java
> +    default ITag.Builder removeTagEntry(final ITag.ITagEntry tagEntry, final String source)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeRawTagBuilder.java
> +    default ITag.Builder removeElementByID(final ResourceLocation elementID, final String source)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeRawTagBuilder.java
> +    default ITag.Builder removeTagByID(final ResourceLocation tagID, final String source)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeTagBuilder.java
> +    default TagsProvider.Builder<T> removeRegistryEntry(final IForgeRegistryEntry<T> entry)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeTagBuilder.java
> +    default TagsProvider.Builder<T> removeRegistryEntries(final IForgeRegistryEntry<T>...entries)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeTagBuilder.java
> +    default TagsProvider.Builder<T> removeElementByID(final ResourceLocation location)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeTagBuilder.java
> +    default TagsProvider.Builder<T> removeElementsByID(final ResourceLocation... locations)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeTagBuilder.java
> +    default TagsProvider.Builder<T> removeTag(ITag.INamedTag<T> tag)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-11-28 15:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeTagBuilder.java
> +    default TagsProvider.Builder<T> removeTags(ITag.INamedTag<T>...tags)
Use same naming scheme as in 1.17 to reduce upgrading or downgrading complexity.

2021-12-25 03:21 UTC, sciwhiz12 commented
Hello! @Commoble, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2021-12-25 17:03 UTC, Commoble commented
This was merged into 1.18 in #7911; I have no further interest in backporting this at this time, but anyone else who needs this in 1.16 is welcome to

2021-12-25 17:03 UTC, closed without merging