[1.17.x] Redstone dust now defers to the blockstate for determining connectivity
MinecraftForge/MinecraftForge pull request #7927
Opened 2021-07-25 15:20 UTC by Da-Technomancer

Implements #7915 

Makes redstone dust defer to a new method in IForgeBlockstate (which calls a new method in IForgeBlock) to determine whether it should connect to a block on a side. 
The new method in IForgeBlock defaults to the original vanilla logic, so this has no gameplay impact on vanilla features without mods.

2021-07-26 06:52 UTC, OrionDevelopment requested changes
Please add a test mod showing this feature in action.

2021-07-26 07:04 UTC, OrionDevelopment requested changes
I would choose a different name for the new method.

2021-07-26 07:04 UTC, OrionDevelopment commented on patches/minecraft/net/minecraft/world/level/block/RedStoneWireBlock.java.patch
> ++         return p_55595_.canConnectRedstone(p_55596_);
A better name would be `canRedstoneConnectTo`

2021-07-28 17:24 UTC, Da-Technomancer commented
I've applied the suggested changes.

2021-08-11 23:30 UTC, Da-Technomancer commented
Did a quick commit to fix the merge conflict on mods.toml. 
This PR should be merge-ready at this point.

2021-08-17 16:41 UTC, rikka0w0 commented
Is it possible to make this hook be aware of world and blockpos (The old `boolean canConnectRedstone(BlockState state, IBlockReader world, BlockPos pos, @Nullable Direction side)`)? A lot of mod rely on this feature to access the data stored in BlockEntity.

https://github.com/RoyalAliceAcademyOfSciences/SimElectricity/blob/34eb82f68ac2b7c19b45922307cc5e6cac60feae/src/main/java/simelectricity/essential/cable/BlockCable.java#L562

Thanks!

2021-08-17 16:55 UTC, KnightMiner commented
I would be concerned that making it world sensitive would cause some people to allow redstone to connect but not trigger the proper events to ensure redstone updates. If world/pos access is granted I would add a statement to the javadoc saying the modder is responsible for triggering block updates if the redstone connectivity changes due to something other than the block state properties

That said, I do see little reason not to include redstone connectivity in your blockstate as you probably want to render it in the model as well. The TE can always change the block state as needed, it will persist as long as the block stays the same.

2021-08-17 18:08 UTC, rikka0w0 commented
> I would be concerned that making it world sensitive would cause some people to allow redstone to connect but not trigger the proper events to ensure redstone updates. If world/pos access is granted I would add a statement to the javadoc saying the modder is responsible for triggering block updates if the redstone connectivity changes due to something other than the block state properties
> 
> That said, I do see little reason not to include redstone connectivity in your blockstate as you probably want to render it in the model as well. The TE can always change the block state as needed, it will persist as long as the block stays the same.

Imagine this scenario, there is a cable block which may have addon panels installed on any sides, there are two catogories of addon panels, one may emit redstone signal, the other does not. Using blockstate, there will be 2^6 combinations for each cable...

Looking at the old `canConnectRedstone`, it provides the world and pos in addition to blockstate and direction. In most case, blockstate should be good enough. But for those really dynamic stuff (like the cable block example I mentioned above), world and blockpos access is still necessary. I would agree that it is the modder's responsiblity to trigger block updates in the latter case.

2021-08-18 14:48 UTC, Da-Technomancer commented
I agree with the changes by @rikka0w0 in PR #8014, which is based off this PR. 
As a matter of recordkeeping, should I close this PR to avoid having two competing PRs?

2021-09-27 23:15 UTC, ChampionAsh5357 commented
To address your question, yes it should if you believe the other implementation is better. However, since that has been merged now, I'll close the PR.

2021-09-27 23:15 UTC, closed without merging