Added a BlockPos field to CheckSpawn and SpecialSpawn events.
MinecraftForge/MinecraftForge pull request #7941
Opened 2021-07-27 18:48 UTC by strikerrocker

In 1.16, Spawner's block entity can be obtained via getting the block pos from BaseSpawner/AbstractSpawner but in 1.17 there is no way to get the block pos of the spawner block(SpawnerEntity can be obtained tho). This PR adds BlockPos field to CheckSpawn and SpecialSpawn event.

2021-07-27 19:00 UTC, SuperMartijn642 commented on src/main/java/net/minecraftforge/event/entity/living/LivingSpawnEvent.java
> +        public CheckSpawn(Mob entity, LevelAccessor world, double x, double y, double z, @Nullable BaseSpawner spawner, MobSpawnType spawnReason,BlockPos spawnerPos)
The `spawnerPos` argument is missing the `Nullable` annotation

2021-07-27 19:03 UTC, SuperMartijn642 commented on src/main/java/net/minecraftforge/event/entity/living/LivingSpawnEvent.java
> +        public BlockPos getSpawnerPos(){return spawnerPos;}
This is not formatted like Forge's coding style

2021-07-27 19:04 UTC, SuperMartijn642 commented on src/main/java/net/minecraftforge/event/entity/living/LivingSpawnEvent.java
> +            this.spawnerPos=spawnerPos;
You seem to be missing spaces between things

2021-07-27 19:26 UTC, strikerrocker commented
Fixed all the styling issues.

2021-07-28 07:16 UTC, OrionDevelopment commented
I understand why you would want this. But have you considered making the anonymous inner class, not anonymous and pass in the spawner instance there?

That way you can get away with a two line patch, and don't need to hassle with the blockposes which could be null.
In the end a simple instanceof against the base spawner, cast and for example a field retrieval would do the job, and would likely be much cleaner and easier to maintain.

2021-08-03 06:47 UTC, OrionDevelopment requested changes
I like this change, but can you do the same thing for the MinecartSpawner that you did for the SpawnerBlockEntity?

2021-08-07 06:05 UTC, strikerrocker commented
> 
> 
> I like this change, but can you do the same thing for the MinecartSpawner that you did for the SpawnerBlockEntity?

You can already get the MinecartSpawner entity using BaseSpawner.getSpawnerEntity() so no need to modify MinecartSpawner Spawner instance. Test mod now also now blocks minecart spawner spawns

2021-08-18 09:10 UTC, OrionDevelopment approved these changes

2021-08-18 09:15 UTC, merged