Fixed wrong SRG name in ForgeHooks used with ObfuscationReflectionHelper
MinecraftForge/MinecraftForge pull request #7961
Opened 2021-07-30 09:27 UTC by noeppi-noeppi

Currently this throws an `ObfuscationReflectionHelper$UnableToFindFieldException` as the used SRG name existed in 1.16.5 but is no longer exists in 1.17.1.

2021-07-31 04:13 UTC, coolsimulations requested changes

2021-07-31 04:13 UTC, coolsimulations commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +                RegistryAccess regs = ObfuscationReflectionHelper.getPrivateValue(RegistryReadOps.class, ops, "f_179860_");
I would recommend you follow the established convention used throughout Forge for `ObfuscationReflectionHelper` which would mean `"f_179860_"` becomes `"f_17986" + "0_"`.

2021-08-03 21:19 UTC, coolsimulations approved these changes

2021-08-10 20:10 UTC, closed without merging

2021-08-10 20:11 UTC, LexManos commented
I just switched it to an AT considering the field is final.
I also added a timebomb to throw an error if we use this code in future MC versions as this only fixes a bug that was present for a small window of 1.16.5. So it shouldn't be nessasary any more.