Fix ScrollPanel render calls and usage
MinecraftForge/MinecraftForge pull request #8012
Opened 2021-08-16 15:42 UTC by iTitus

The scrollbar was rendered with a texture shader and scrolling didn't work.
I fixed both issues.

2021-08-16 15:43 UTC, iTitus commented
There is still an issue with the "Done" button not being clickable when not fully scrolled down.

2021-08-16 17:00 UTC, iTitus commented
Should be working now

2021-08-24 15:39 UTC, OrionDevelopment approved these changes
Good catch with the mod list scrollbar.

Thanks for the fix.

2021-08-24 15:45 UTC, gigaherz requested changes
Minor issue but for consistency.

2021-08-24 15:45 UTC, gigaherz commented on src/main/java/net/minecraftforge/client/gui/ScrollPanel.java
> +            worldr.begin(VertexFormat.Mode.QUADS, DefaultVertexFormat.POSITION_COLOR);
You changed these to POS_COLOR but the vertices are still calling .uv()

2021-08-31 14:56 UTC, gigaherz approved these changes

2021-08-31 14:57 UTC, merged