1.18 Allow mod menus to have their own recipebook
MinecraftForge/MinecraftForge pull request #8028
Opened 2021-08-26 01:11 UTC by Cyborgmas

This PR allows for mod menus to add a recipebook with their own tabs.

This PR does not adress adding to existing recipebook tabs as their were discussions about how to handle excess tabs that were not resolved (afaik)

I have tested this with my own mod as well.

2021-10-10 01:44 UTC, ChampionAsh5357 commented
Would you mind adding a test mod for this? It would allow us to better review the work and make it easier to maintain when updating between versions.

2021-12-25 02:31 UTC, sciwhiz12 commented
Hello! @Cyborgmas, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2021-12-26 20:43 UTC, Cyborgmas commented
yeah, will try to update soon

2022-01-06 18:50 UTC, Cyborgmas commented
Updated to 1.18. Haven't yet gotten around to adding the test mod though

2022-01-09 19:52 UTC, Cyborgmas commented
Added a test mod, right click on a grass block to open the crafting menu, there is no GUI but the slots can be seen to do the crafts.

2022-02-05 22:16 UTC, ChampionAsh5357 requested changes
First few things is licensing on top of files and Forge formatting (braces on new lines) for the forge files.

Second thing of note is how the recipes are displayed in the recipe book since they still use the 3x3 sprite grid. It's an easy enough implementation though that it doesn't really matter whether its here or not, just for something to take note of.

Finally would be to add an advancement such that it unlocks the recipe. Just want a case to make sure that you can see the recipe in the book before crafting.

Other than that, I don't see any issues since most of this is just standard container/screen code for testing.

2022-02-05 22:16 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookExtensionTest.java
> +        MinecraftForge.EVENT_BUS.addListener(this::onRightClick);
Testing interfaces should now have an `ENABLE` boolean for enabling or disabling the test mod.

2022-02-06 00:06 UTC, Cyborgmas commented
As proposed by gigaherz on discord, I moved out the patches of RecipeBookCategories into RecipeBookRegistry.

Also yeah for the 3x3 grid, it's rendering done in RecipeBookComponent, any mod can copy and modify it (albeit substantially iirc) to change it.

2022-02-16 16:55 UTC, ChampionAsh5357 requested changes

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookExtensionTest.java
> +        event.enqueueWork(() -> {
New line braces.

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookExtensionTest.java
> +        public RecipeBookTestContainer() {
New line braces.

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/advancements/recipes/recipe_book_extension_advancment.json
> +{
Since the mod can be enabled/disabled, this should be using the conditional advancement system.

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_1.json
> +{
Since the mod can be enabled/disabled, this should be using the conditional recipe system.

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_2.json
> +{
Since the mod can be enabled/disabled, this should be using the conditional recipe system.

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_3.json
> +{
Since the mod can be enabled/disabled, this should be using the conditional recipe system.

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_4.json
> +{
Since the mod can be enabled/disabled, this should be using the conditional recipe system.

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_5.json
> +{
Since the mod can be enabled/disabled, this should be using the conditional recipe system.

2022-02-16 16:55 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/RecipeBookRegistry.java
> +    public static final Map<RecipeBookType, List<RecipeBookCategories>> TYPE_TO_CATEGORIES_VIEW = Collections.unmodifiableMap(TYPE_TO_CATEGORIES);
If the views are supposed to be immutable, wouldn't the lists also need to be immutable as well?

2022-03-12 14:09 UTC, Cyborgmas commented
Merged to 1.18.2, disabled the recipes & advancements and made sure the nested lists were immutable

2022-03-12 21:00 UTC, ChampionAsh5357 requested changes

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/RecipeBookRegistry.java
> + */
Update license.

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookExtensionClientHelper.java
> + */
Update license.

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/recipe/recipebook/RecipeBookExtensionTest.java
> + */
Update license.

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/advancements/recipes/recipe_book_extension_advancment.json
> +      "type" : "forge:false"
Should be `ModLoadedCondition` instead as otherwise the recipes are not testable.

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_1.json
> +      "type" : "forge:false"
Should be `ModLoadedCondition` instead as otherwise the recipes are not testable.

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_2.json
> +      "type" : "forge:false"
Should be `ModLoadedCondition` instead as otherwise the recipes are not testable.

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_3.json
> +      "type" : "forge:false"
Should be `ModLoadedCondition` instead as otherwise the recipes are not testable.

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_4.json
> +      "type" : "forge:false"
Should be `ModLoadedCondition` instead as otherwise the recipes are not testable.

2022-03-12 21:00 UTC, ChampionAsh5357 commented on src/test/resources/data/recipe_book_extension_test/recipes/recipe_book_extension_recipe_5.json
> +      "type" : "forge:false"
Should be `ModLoadedCondition` instead as otherwise the recipes are not testable.

2022-03-13 02:32 UTC, ChampionAsh5357 approved these changes

2022-03-24 22:07 UTC, TheCurle commented
A very common request!

The previous solution to this was "Add JEI compat!"
One-To-One recipe visualisations can be derived from Furnace recipes, which saves a lot of time in the implementation.

I hope to see decent uptake on this change, because it has a lot of potential.

2022-03-24 22:08 UTC, merged