New raid related events
MinecraftForge/MinecraftForge pull request #8084
Opened 2021-09-17 12:59 UTC by PellucidDice

This pr adds a total of 4 events.

1. RaidEvent.GetOrCreate is triggered when a raid is requested in the given position, users are allowed to assign custom ones.

2. RaidEvent.Load is triggered when Raids trying to load, users are able to retrieve custom raids here

3. RaidEvent.SpawnGroup is triggered when a raid is trying to spawn a new wave. Users are allowed to change the spawn position and force spawn a bonus group. This event is Cancelable.

4. RaidEvent.Stop is triggered when the raid attempts to end. Users are allowed to prevent the raid for being cancelled. This event is Cancelable.

Also added [two getters](https://github.com/MinecraftForge/MinecraftForge/compare/1.17.x...PellucidDice:1.17.x#diff-2248f92eb2620ef4d5165f810f50671e16747c6a04aa95c4d2d5977adc9cfa61R98-R106) in Raid.java that allows users to access more about raids, for example players and raiders groups.

[Test Mod](https://github.com/MinecraftForge/MinecraftForge/compare/1.17.x...PellucidDice:1.17.x#diff-537d2852e3d01f22f103763bc5831df0f9dec7b665691ee6414ce618bd86ca46):
RaidEventTest ("raid_event_test")

Players receive slowness effect during raid:
![image](https://user-images.githubusercontent.com/48399898/133785001-23e46206-b848-466f-b9c6-22711a2ddfce.png)

When remaining raider count less than 2, they glows and are poisoned:
![image](https://user-images.githubusercontent.com/48399898/133785042-604923f9-bb3c-4aea-985c-67a3917b008f.png)
![image](https://user-images.githubusercontent.com/48399898/133785149-bfd1a2ee-539c-4d13-9f3d-04d66fb3f849.png)

Player receives message when raid is ended:
![image](https://user-images.githubusercontent.com/48399898/133786415-97596b99-701e-4225-aaca-3770bc73e824.png)

2021-09-23 10:51 UTC, dpeter99 requested changes
This looks quite promissing. I added a few smaller notes on the code.
The main concern I have is the fact that this leaves the detection of the raid type to the modder. This could cause mods colliding, as different modders might decide to save the type differently. (One modder might call it ``type`` and other might call it ``raidType``) Also the current solution separates the loading and saving code. I would suggest introducing a registry for a class that handles saving and loading. And move the detection into forge.

2021-09-23 10:51 UTC, dpeter99 commented on patches/minecraft/net/minecraft/world/entity/raid/Raid.java.patch
> ++                  }
This is a lot of changes. Either don't indent, or better try to do an early return.

2021-09-23 10:51 UTC, dpeter99 commented on patches/minecraft/net/minecraft/world/entity/raid/Raids.java.patch
> ++      return event.getCustomRaid() != null ? event.getCustomRaid().apply(m_37977_()) : event.getRaid() != null ? event.getRaid() : new Raid(m_37977_(), p_37961_, p_37962_);
This is a really complex few lines. It could be a single line between the two vanilla lines if you make the ``getOrCreateRaid`` return the current one if no new one was created.

2021-09-23 10:51 UTC, dpeter99 commented on patches/minecraft/net/minecraft/world/entity/raid/Raid.java.patch
> ++      {
This shoud also be on the same line.

2021-09-23 10:51 UTC, dpeter99 commented on src/main/java/net/minecraftforge/event/world/RaidEvent.java
> +    public static class Stop extends RaidEvent
A better name for this would be ``Ending`` as it would be more obvious what is happening and what canceling it causes.

2021-09-23 10:51 UTC, dpeter99 commented on src/test/java/net/minecraftforge/debug/world/RaidEventTest.java
> +            event.setCustomRaid((id) -> new TestModRaid(id, event.getLevel(), event.getPos()));
For a test mod it is not a really good idea to make the effect change based. You coud be unlucky and not see anything for quite a few raids.

2021-09-23 10:51 UTC, dpeter99 commented on src/test/java/net/minecraftforge/debug/world/RaidEventTest.java
> +public class RaidEventTest
If you look in other test mods there is ususally a ``private static final boolean ENABLE = false;`` this is so that they can be disabled more easily.

2021-09-23 10:51 UTC, dpeter99 commented on src/test/java/net/minecraftforge/debug/world/RaidEventTest.java
> +                    });
You could just use a normal for loop for this.

2021-11-24 00:50 UTC, Thelnfamous1 commented
Can you include an event to detect and even modify specific raiders that are to be spawned as a part of the raid?

Example use case: I want all pillagers that spawn with the raid at the final wave to spawn with multishot piercing crossbows

Another example use case: I want to all evokers in the raid to spawn riding a Ravager

2021-12-25 02:54 UTC, sciwhiz12 commented
Hello! @PellucidDice, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 if applicable. If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2021-12-25 03:33 UTC, PellucidDice commented
Hi, sorry I've been a bit bust in the past month.
I'll redo all the stuff on 1.18.

2022-01-08 21:29 UTC, PellucidDice commented
Will make another PR for modern versions of changes, thanks for the feedback and comments.

2022-01-08 21:29 UTC, closed without merging