Prevent call to Item#initializeClient when in datagen
MinecraftForge/MinecraftForge pull request #8097
Opened 2021-09-19 21:35 UTC by sciwhiz12

When running under data-generation, the `Minecraft` singleton is unavailable even though the operating env is under the `CLIENT` dist. Along with the fact that most uses of IItemRenderProperties (usually to provide a custom BEWLR) make use of the `Minecraft` singleton, this means that developers unaware of `Minecraft`'s unavailability will encounter a null pointer exception when they try to access its singleton.

This PR adds a check to prevent the `Item#initializeClient` method from being called during data-generation, to prevent the situation described before from causing an NPE. As `IItemRenderProperties` has nothing which might be used by datageneration, this is safe to do.

This PR is inspired by a [Discord conversation][discord] on The Forge Project discord server wherein @gigaherz expressed that this method shouldn't be called in datagen but this check was forgotten, and that it should be PR-ed.

[discord]: https://discord.com/channels/313125603924639766/867851603468615740/888932184122069036

2021-09-20 10:00 UTC, OrionDevelopment approved these changes

2021-09-20 10:10 UTC, gigaherz requested changes
There's 3 initializeClient methods in total (Item, Block, and MobEffect). Would be nice to get the same fix done to the other 2.

2021-09-20 13:33 UTC, OrionDevelopment commented
> initializeClient

I noticed them, but I am not sure they are related to issues in Datagen.
How are these other two involved?

2021-09-20 17:41 UTC, gigaherz commented
> How are these other two involved?

They are all equally involved. When datagen runs, forge runs its initialization logic, during which it registers all the things (items, blocks, and mobeffects included).
Since the initializeClient calls are done in the constructor of their respective object, it means all 3 will be called during datagen, and all 3 will run into the same issue.

2021-09-20 18:27 UTC, sciwhiz12 commented
Updated to also prevent `Block#initializeClient` and `Item#initializeClient` from being called during datagen.

2021-09-20 21:19 UTC, gigaherz approved these changes

2021-09-24 19:22 UTC, OrionDevelopment approved these changes

2021-09-24 21:05 UTC, gigaherz commented
Oops I forgot about this. Meant to merge sometime I wasn't busy.... and I guess I'm not busy now.

2021-09-24 21:10 UTC, merged