Re-add hook for LivingExperienceDropEvent, fixes #7900
MinecraftForge/MinecraftForge pull request #8115
Opened 2021-09-22 18:43 UTC by AterAnimAvis

Re-adds the hook that got missed during the 1.17 port.

Testing:
----- 
- Enable Test Mod
- Join World
- Spawn a `pig` and kill it
- Verify the logged message
- Verify via `/xp query points` that the received xp was double the reported original.

2021-09-22 21:11 UTC, sciwhiz12 requested changes
Looks good to me, except for a missing license header.

2021-09-22 21:11 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/entity/living/LivingExperienceDropEventTest.java
> +package net.minecraftforge.debug.entity.living;
Missing license header.

2021-09-22 21:20 UTC, AterAnimAvis commented on src/test/java/net/minecraftforge/debug/entity/living/LivingExperienceDropEventTest.java
> +package net.minecraftforge.debug.entity.living;
Whoops

2021-09-22 21:30 UTC, sciwhiz12 approved these changes

2021-09-27 20:06 UTC, LexManos commented
Dragons

2021-11-25 18:17 UTC, AterAnimAvis commented
Closing this for the moment with the aim to retarget to 1.18, EnderDragons are more complex to account for (The attacking player may be null at the point of time the event fires)

2021-11-25 18:17 UTC, closed without merging