[RFC] Cap Rework
MinecraftForge/MinecraftForge pull request #8116
Opened 2021-09-22 19:48 UTC by LexManos

There has been a request too move away from reflection {which makes  sense because of J16} and synthetic final fields that can be null.

So here is is. The current system of @CapabilityInject in deprecated for removal in 1.18.
It still works as before, only being injected when the capability is registered. 

You now always get a non-null Capability. Using CapabiltyToken to specify the type.

```
public static Capability<IDataHolder> DATA_HOLDER_CAPABILITY = CapabilityManager.get(new CapabilityToken<>(){});
```
Note the fact that it's a anon class. This forces the compiler to include the generic information we need.
We are not going to pass in a Class object because we need to keep the soft dependency system.

The general concept is Capability now has a 'isRegistered()' function instead of testing != null.
It also has a addListener(Consumer<Capability<T>>) function, which is analogous too the old @CapabilityInject on a method.

Re: https://github.com/MinecraftForge/MinecraftForge/pull/8104

2021-09-23 07:43 UTC, diesieben07 requested changes
Overall I approve, just some small oversights

2021-09-23 07:43 UTC, diesieben07 commented on fmlloader/src/main/java/net/minecraftforge/common/asm/CapabilityTokenSubclass.java
> + */
This is still the old javadoc from the definalize transformer

2021-09-23 07:43 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/capabilities/CapabilityManager.java
> +        get(Type.getType(type).toString(), true);
I don't think this line is correct. `Type#toString` says it returns the descriptor, which would be `Lfoo/bar/Baz;`.
It should be
```suggestion
        get(type.getName(), true);
```
like in `RegisterCapabilitiesEvent`

2021-09-23 07:43 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/capabilities/CapabilityManager.java
> +        return INSTANCE.get(type.getType(), false);
`CapabilityToken#getType` returns the internal name (using slashes), all other callers of `get(String, boolean)` pass the binary name (using dots) though.

2021-09-23 07:43 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/capabilities/CapabilityManager.java
> +            }
```suggestion
            cap = (Capability<T>)providers.computeIfAbsent(realName, Capability::new);
```

2021-09-23 07:43 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/capabilities/CapabilityManager.java
> +            if (cap.isRegistered() && registering)
This call to `isRegistered` can technically fail, because it's not guarded by a `synchronized` on the `Capability`.

2021-09-23 19:44 UTC, diesieben07 approved these changes
lgtm!

2021-09-24 15:08 UTC, Sm0keySa1m0n commented on fmlloader/src/main/java/net/minecraftforge/common/asm/CapabilityTokenSubclass.java
> + * Implements getType() in CapabilityTokeen subclasses.
Typo on CapabilityToken

2021-10-01 05:53 UTC, LexManos commented
A week of no bad comments, and nothing but good on here and discord. It should be fully bin compat. So no downside, and gives prep for future.

2021-10-01 05:54 UTC, merged