[1.17] change the AdvancementProvider to make it possabible for mods to hook into it
MinecraftForge/MinecraftForge pull request #8120
Opened 2021-09-26 14:37 UTC by Unbekannt1998

This is a PR  which ports the Changes from PR #7488  to 1.17

2021-09-27 22:14 UTC, ChampionAsh5357 reviewed
These are in addition to the changes on the 1.16 PR since you work on them synchronously.

2021-09-27 22:14 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/advancements/Advancement.java.patch
> ++
Extra line.

2021-09-27 22:14 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/data/advancements/AdvancementProvider.java.patch
> ++
Extra line

2021-09-27 22:23 UTC, ChampionAsh5357 commented
Test mod is missing `forge:dummy_parent` preventing last test from executing.

2021-10-01 17:47 UTC, Unbekannt1998 commented
Sorry for the delay we had a Internet outage for a week so could not update should now be updated on both Requests

2021-10-02 03:02 UTC, ChampionAsh5357 reviewed
Just minor formats. Test mod works fine now.

2021-10-02 03:02 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/data/advancements/AdvancementProvider.java.patch
> ++   public AdvancementProvider (DataGenerator generatorIn, net.minecraftforge.common.data.ExistingFileHelper fileHelperIn) {
Remove space between parameter list and constructor name.

2021-10-02 03:02 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/data/advancements/AdvancementProvider.java.patch
> ++   protected void registerAdvancements (Consumer<Advancement> consumer, net.minecraftforge.common.data.ExistingFileHelper fileHelper) {
Remove space between parameter list and constructor name.

2021-10-02 18:15 UTC, ChampionAsh5357 approved these changes

2021-10-04 21:58 UTC, LexManos commented on patches/minecraft/net/minecraft/advancements/Advancement.java.patch
> ++      public Advancement save(Consumer<Advancement> consumer, ResourceLocation id, net.minecraftforge.common.data.ExistingFileHelper fileHelper) {
Use an extension interface. Instead of exposing a patch and class as public API.

2021-10-05 19:15 UTC, ChampionAsh5357 requested changes
Extension interface formatting comments.

2021-10-05 19:15 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/data/AdvancementBuilderHelper.java
> +public interface AdvancementBuilderHelper
Extension interfaces have a specific naming schema and location.

Naming schema: `IForge*`
Location: `net.minecraftforge.common.extensions`

2021-10-05 19:15 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/data/AdvancementBuilderHelper.java
> +    default Advancement save(ResourceLocation id, Consumer<Advancement> consumer, ExistingFileHelper fileHelper, Advancement.Builder builder)
The builder is obtained using a `#self` method. See any current extension interface.

2021-10-06 21:02 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeAdvancementBuilder.java
> +    default Advancement save(Consumer<Advancement> consumer ,ResourceLocation id, ExistingFileHelper fileHelper)
Needs documentation. Otherwise looks good.

2021-10-07 00:35 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeAdvancementBuilder.java
> +     * @throws IllegalStateException when an Advancement is build with an invalid parent
Going to be extremely nitpicky here since I do think that proper javadocs are good for everyone.

- Descriptions are proper sentences, references to classes should be done via `@link`. (e.g. `Constructs an {@link Advancement} for generation.`)
- Parameter descriptions are informative on what they are, (e.g. `@param consumer a {@link Consumer} which the built advancement is passed to`)

 Another thing for the English language is that when prefixing a noun with a verb, we use the past participle to make it act like an adjective (e.g. `the built {@link Advancement}`).

2021-10-09 17:11 UTC, ChampionAsh5357 approved these changes

2021-10-15 03:00 UTC, merged

2021-10-28 08:18 UTC, rehwinkel commented
This PR adds the `obtain_dirt` advancement using a data generator, however, the generated JSON is not tracked by git at the moment, leading it to appear in my "Unversioned Files". Same goes for these files:

- `src/generated_test/resources/data/minecraft/advancements/story/root.json`
- `src/generated_test/resources/data/minecraft/advancements/good_parent.json`
- `src/generated_test/resources/data/minecraft/advancements/obtain_diamond_block.json`
- `src/generated_test/resources/data/data_gen_test/advancements/obtain_dirt.json`