Added back the attacking entity to LivingKnockBackEvent
MinecraftForge/MinecraftForge pull request #8126
Opened 2021-09-28 20:45 UTC by Sarinsa

Added back the attacking entity to LivingKnockBackEvent and added nulllable entity parameter for attacking entity to LivingEntity#knockback

2021-09-28 20:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=8126) it.</sub>

2021-10-14 20:58 UTC, ChampionAsh5357 requested changes
Since 1.16 is now LTS, PRs should be made to 1.17 first if applicable and then backported when merged in.

2021-10-14 20:58 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/entity/LivingEntity.java.patch
> +-   public void func_233627_a_(float p_233627_1_, double p_233627_2_, double p_233627_4_) {
We do not remove methods, we deprecate them and defer the call.

2021-10-14 20:58 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/entity/LivingEntity.java.patch
> ++      net.minecraftforge.event.entity.living.LivingKnockBackEvent event = net.minecraftforge.common.ForgeHooks.onLivingKnockBack(attacker,this, p_233627_1_, p_233627_2_, p_233627_4_);
Space between `attacker` and `this`.

2021-10-14 20:58 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/entity/LivingEntity.java.patch
> ++      p_213371_1_.knockback(this,0.5F, p_213371_1_.func_226277_ct_() - this.func_226277_ct_(), p_213371_1_.func_226281_cx_() - this.func_226281_cx_());
Space between `this` and `0.5F`

2021-10-14 20:58 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/entity/MobEntity.java.patch
> ++            ((LivingEntity)p_70652_1_).knockback(this,f1 * 0.5F, (double)MathHelper.func_76126_a(this.field_70177_z * ((float)Math.PI / 180F)), (double)(-MathHelper.func_76134_b(this.field_70177_z *
Space between `this` and `f1 * 0.5F`

2021-10-14 20:58 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch
> ++                        ((LivingEntity)p_71059_1_).knockback(this,(float)i * 0.5F, (double)MathHelper.func_76126_a(this.field_70177_z * ((float)Math.PI / 180F)), (double)(-MathHelper.func_76134_b(th
Space after `this` comma.

2021-10-14 20:58 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/entity/player/PlayerEntity.java.patch
> ++                           livingentity.knockback(this,0.4F, (double)MathHelper.func_76126_a(this.field_70177_z * ((float)Math.PI / 180F)), (double)(-MathHelper.func_76134_b(this.field_70177_z * ((f
Space after `this` comma.

2021-10-14 20:58 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +    public static LivingKnockBackEvent onLivingKnockBack(@Nullable Entity attacker, LivingEntity target, float strength, double ratioX, double ratioZ)
Breaking change, should have another method which is deprecated which delegates to this one.

2021-10-14 20:58 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/living/LivingKnockBackEvent.java
> - * {@link EntityPlayer#attackTargetEntityWithCurrentItem(Entity)} <br>
Why? They are still being called at these places.

2021-10-14 20:58 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/living/LivingKnockBackEvent.java
> +    public LivingKnockBackEvent(@Nullable Entity attacker, LivingEntity target, float strength, double ratioX, double ratioZ)
Breaking change, deprecate old constructor for removal and create new one. Old constructor delegates to new one.

2021-10-14 22:17 UTC, Sarinsa commented on src/main/java/net/minecraftforge/event/entity/living/LivingKnockBackEvent.java
> +    public LivingKnockBackEvent(@Nullable Entity attacker, LivingEntity target, float strength, double ratioX, double ratioZ)
Yeah, I see I have been way too hasty with this

2021-12-25 02:44 UTC, sciwhiz12 commented
Hello! @Sarinsa, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 (or leave an explanation why this PR's changes are not applicable to 1.18). If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2022-03-05 10:43 UTC, sciwhiz12 commented
Hello! Since the application of the Stale label, there has been no recent activity on this PR. As said in our previous comment, this PR will now be closed for inactivity.

If you wish to continue this PR, please open a new PR against the Latest supported version (to be conformant with our version support and contributions policy). 

Thank you for your contributions. 👋

2022-03-05 10:43 UTC, closed without merging