1.17.x client chat received on client
MinecraftForge/MinecraftForge pull request #8135
Opened 2021-10-03 00:42 UTC by coehlrich

Adds an event for messages that were either received from the server or from messages that are put in chat from client-side mods or debug messages while also allowing the change the id of the message so that if a message with the same id as another id get's received then the older message get's removed.

The vanilla method that accept's the message id is currently private.

I feel like there would be a better name for the event than `ClientChatReceivedBothSidesEvent` but `ClientChatReceivedEvent` is already used which is the event that fires only for messages from the server.

2021-10-03 10:56 UTC, diesieben07 commented
What is the use case for this?

2021-10-03 11:00 UTC, diesieben07 requested changes
I am really not sure what the use-case for this event would be. Please elaborate.

2021-10-03 11:00 UTC, diesieben07 commented on src/main/java/net/minecraftforge/client/event/ClientChatReceivedBothSidesEvent.java
> +public class ClientChatReceivedBothSidesEvent extends Event
The javadoc as well as the name of this event do not at all accurately describe what it does.

2021-10-03 11:00 UTC, diesieben07 commented on src/main/java/net/minecraftforge/client/event/ClientChatReceivedBothSidesEvent.java
> +    public void setId(int id)
What is the use-case for setting the ID on a message via this event?

2021-10-03 11:00 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/ForgeEventFactory.java
>  public class ForgeEventFactory
Do not reorganize the imports in this file.

2021-10-03 22:41 UTC, coehlrich commented on src/main/java/net/minecraftforge/client/event/ClientChatReceivedBothSidesEvent.java
> +public class ClientChatReceivedBothSidesEvent extends Event
I was trying to think of a better name for the event (which would probably also help with the javadoc) but couldn't think of anything other than `ClientChatReceived` which is already used for the event that only receives messages from the server.

2021-10-03 22:53 UTC, coehlrich commented
For the use-case I was thinking it would be useful for chat message modification's that would fit for both message's coming from the server, debug keys, and other client-side mods like adding timestamps to the start of chat messages.

About the message id the use-case I had in mind was where it could be used for if a message from a server would better fit replacing the previous message of it's kind which since server's can't use the message id system it can't do that itself.

2021-12-25 02:53 UTC, sciwhiz12 commented
Hello! @coehlrich, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 if applicable. If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2022-03-05 10:43 UTC, sciwhiz12 commented
Hello! Since the application of the Stale label, there has been no recent activity on this PR. As said in our previous comment, this PR will now be closed for inactivity.

If you wish to continue this PR, please open a new PR against the Latest supported version (to be conformant with our version support and contributions policy). 

Thank you for your contributions. 👋

2022-03-05 10:43 UTC, closed without merging