Add `BiomeDictionary#hasType(String)`
MinecraftForge/MinecraftForge pull request #8157
Opened 2021-10-16 20:44 UTC by alcatrazEscapee

Add a way of checking if a type exists by name. This is useful in terms of error reporting when provided by biome dictionary names from untrusted sources (e.g. a config or codec). As an example, currently all that's possible is the following code:

```java
Codec<BiomeDictionary.Type> CODEC = Codec.STRING.xmap(
    BiomeDictionary.Type::getType,
    BiomeDictionary.Type::getName
);
```

Whereas, adding `hasType` allows us to report errors and typos in the user's configuration:

```java
Codec<BiomeDictionary.Type> CODEC = Codec.STRING.comapFlatMap(
    t -> BiomeDictionary.Type.hasType(t) ?
        DataResult.success(BiomeDictionary.Type.getType(t)) :
        DataResult.error("No biome dictionary type with name: " + t),
    BiomeDictionary.Type::getName
);
```

2021-10-16 21:57 UTC, Harleyoc1 commented on src/main/java/net/minecraftforge/common/BiomeDictionary.java
> +         * @see #getType(String, Type...) for type naming conventions.
I suggest adding `#getType` after the `#getType(String, Type...)` link or the Javadoc shows up as `See Also:
for type naming conventions.` when rendered.

2021-10-16 22:07 UTC, Harleyoc1 approved these changes

2021-10-17 00:12 UTC, ChampionAsh5357 commented
I understand the use of this method when it comes from a config and codec. Though why not also just supply a codec for the `BiomeDictionary$Type` as well? It seems like a common enough use case and it would make it such that modders do not need to write the same codec multiple times.

2021-10-17 00:33 UTC, alcatrazEscapee commented
Mostly in the interest of making a PR small and targeted, and broadly useful. Would you like me to add a codec as part of this PR? I could also add a `getTypeIfPresent` or any other number of "probably also useful" things but I went with the simplest viable solution here.

2021-10-17 00:59 UTC, ChampionAsh5357 requested changes
As part of this PR, probably not since it seems out of scope. But I would definitely say in another a common codec would probably be nice, though it would require a bit more extensive testing on our part.

2021-10-17 00:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/BiomeDictionary.java
> +            return byName.containsKey(name.toUpperCase());
Should use `Locale#ROOT` in upper case to avoid any casing issues in other languages.

2021-10-17 01:25 UTC, alcatrazEscapee commented on src/main/java/net/minecraftforge/common/BiomeDictionary.java
> +            return byName.containsKey(name.toUpperCase());
If I do this I'd also need to change the existing `BiomeDictionary.Type#getType` as otherwise they'd have inconsistent results in said languages with casing issues (since I mirrored that functionality here). Which, again, in theme, was something I decided not to change in the initial draft, would you like me to change that one as well?

2021-10-17 01:44 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/BiomeDictionary.java
> +            return byName.containsKey(name.toUpperCase());
Hmm...after taking a closer look at the code, it seems to be unnecessary. Since `BiomeDictionary$Type#getType` is always used to generate the data, the comparisons will be the same regardless. For this case, I have no issues otherwise.

2021-10-17 01:45 UTC, ChampionAsh5357 approved these changes

2021-10-20 19:10 UTC, merged