[1.17.x] Made several vanilla registries forge registries, added missing ObjectHolder annotations
MinecraftForge/MinecraftForge pull request #8159
Opened 2021-10-17 14:16 UTC by rehwinkel

Adds TrunkPlacerTypes as a forge registry.

2021-10-17 14:33 UTC, pupnewfster commented
A couple things:
1. I believe you also need create the registry in [GameData](https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/src/main/java/net/minecraftforge/registries/GameData.java#L129)
2. It might be wise to broaden this PR slightly to capture other new vanilla registries that can easily be captured as well. I know there is at least GameEvent, and I wouldn't be surprised if there were others as well. (Special note on game events the registry should also be added [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/src/main/java/net/minecraftforge/common/data/ForgeRegistryTagsProvider.java#L39-L46))

2021-10-18 01:47 UTC, thedarkcolour commented
The other ones that I see are `FEATURE_SIZE_TYPES`, `BIOME_SOURCE`, `CHUNK_GENERATOR`, `STRUCTURE_PROCESSOR`, and `STRUCTURE_POOL_ELEMENT` from Registry

2021-10-18 13:04 UTC, alcatrazEscapee commented
Biome source and chunk generators cannot be made into a Forge registry as their elements have the same generic type, and notably are of a `Codec<?>`, which would be a huge breaking change, along with a big pile o patches if you were to change those to a forge registry type. See #7969

2021-10-18 15:23 UTC, ChampionAsh5357 commented
Structure processors and structure pool elements are also a no go since those are also functional interfaces around a codec similar to how `RecipeType`s are constructed anonymously.

2021-10-18 16:49 UTC, rehwinkel commented
I added the missing lines to make the registry actually work like @pupnewfster mentioned in #1. Adding the registry for FeatureSizeType would make sense here too.

2021-10-18 17:40 UTC, ChampionAsh5357 commented
There are many more types as pup said including `GameEvent`, any of the loot types, and `PositionSourceType`. Also, it would probably be good to AT any constructors to be public as the two you have implemented are currently inaccessible to modders due to their private constructors.

2021-10-19 14:08 UTC, ChampionAsh5357 commented
Since this is already a registry addition, wondering if it would also be appropriate to deal with #7574 as well since all those would need is `ObjectHolder` annotations on most vanilla registry object classes (excluding `Biome` and `RecipeSerializer` currently).

2021-10-20 11:15 UTC, rehwinkel commented
@ChampionAsh5357 How about classes like RecipeType, who's members aren't `public static final`?

2021-10-20 12:55 UTC, ChampionAsh5357 commented
So, for registries you are still missing the loot types and `PositionSourceType`. I'm not sure whether the builtin registries should be forge registries currently so I'm omitting them from this explanation for now.

As for the annotation, you seemed to have put them on every class regardless of if it was a forge wrapped registry or not. So you need to remove those that aren't.

> How about interfaces like RecipeType ~~or RecipeSerializer~~?

I've already mentioned not to add the annotation to `RecipeSerializer` (or any interfaces for that matter). What the definalizer does violates the contract of fields in interfaces and throws an exception (see [JVMS 4.5](https://docs.oracle.com/javase/specs/jvms/se16/html/jvms-4.html#jvms-4.5)). As for `RecipeType`, it's not a forge wrapped registry.

2021-10-20 13:41 UTC, pupnewfster commented on src/main/java/net/minecraftforge/registries/GameData.java
> +        makeRegistry(GAME_EVENT, c(GameEvent.class)).disableSaving().disableSync().create();
I am not sure if these are the correct flags for Game Events, in terms of disable saving and sync... Given the fact vanilla has game event tags they definitely should sync and honestly they probably should save as well? Also Can you address this TODO: https://github.com/MinecraftForge/MinecraftForge/blob/1.17.x/src/main/java/net/minecraftforge/common/data/ForgeRegistryTagsProvider.java#L39-L46 and add the reference to the forge game event registry and tag folder there?

2021-10-21 11:30 UTC, rehwinkel commented on src/main/java/net/minecraftforge/registries/GameData.java
> +        makeRegistry(GAME_EVENT, c(GameEvent.class)).disableSaving().disableSync().create();
I'll admit I wasn't at all sure what to put there, but I figured since the Registry would remain static after the game has started, syncing wouldn't be required. Am I right in thinking that "sync" in this context refers to the server giving the client(s) the contents of the registry? And "saving" meaning the registry is saved on a per-world basis?

2021-10-21 11:42 UTC, rehwinkel commented
I've fixed the ObjectHolder annotations to only apply to classes that hold forge registry objects.

> So, for registries you are still missing the loot types and `PositionSourceType`.

What is the standard/preferred way for making classes like `LootPoolEntryType` a `ForgeRegistryEntry`? Do I just implement `IForgeRegistryEntry`? Do I do that in the base class? I'd naively just implement it in the `LootPoolEntryType` type directly, but if there is a better way to do that, let me know.

2021-10-21 12:17 UTC, ChampionAsh5357 commented
> What is the standard/preferred way for making classes like `LootPoolEntryType` a `ForgeRegistryEntry`?

See `RecipeSerializer` and its subtypes. That tells you exactly how to do it.

2021-10-21 12:45 UTC, rehwinkel commented
`RecipeSerializer` is an interface, `SerializerType` is not. I'll just implement the `IForgeRegistryEntry` interface manually.

2021-10-21 12:48 UTC, ChampionAsh5357 commented
Apologies, misread because of the quote. Just implement ForgeRegistryEntry on the class type. Do not implement anything on SerializerType.

2021-10-21 13:25 UTC, pupnewfster commented on src/main/java/net/minecraftforge/registries/GameData.java
> +        makeRegistry(GAME_EVENT, c(GameEvent.class)).disableSaving().disableSync().create();
I believe that is correct, at least the syncing making sure the client and server have the same entries (which given vanilla has tags for game events is important).

2021-10-22 12:45 UTC, rehwinkel commented on src/main/java/net/minecraftforge/registries/GameData.java
> +        makeRegistry(GAME_EVENT, c(GameEvent.class)).disableSaving().disableSync().create();
Yeah! In my most recent commits I enabled saving and sync again.

2021-11-03 13:47 UTC, pupnewfster commented on patches/minecraft/net/minecraft/world/level/storage/loot/entries/LootPoolEntryType.java.patch
> ++   net.minecraft.resources.ResourceLocation checkRegistryName(String name) { return net.minecraftforge.registries.GameData.checkPrefix(name, true); }
I am not sure if this (and the other loot types can be properly taken over by forge, I haven't looked at it yet), but as a lot of them extend `SerializerType` and are adding these massive copy paste blocks that `ForgeRegistryEntry` is used to reduce the stuff that needs patching... I feel like creating a `ForgeSerializerTypeRegistryEntry` intermediary class would be less messy and certainly reduce the size of a bunch of these patches

2021-11-24 02:26 UTC, ChampionAsh5357 requested changes
I think just a few formatting and javadoc concerns left.

2021-11-24 02:26 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/registries/ForgeSerializerTypeRegistryEntry.java
> +package net.minecraftforge.registries;
Missing license.

2021-11-24 02:26 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/registries/ForgeSerializerTypeRegistryEntry.java
> +public class ForgeSerializerTypeRegistryEntry<V extends IForgeRegistryEntry<V>, T> extends SerializerType<T> implements IForgeRegistryEntry<V>
Needs javadoc on what this is for.

2021-11-24 02:26 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/registries/ForgeSerializerTypeRegistryEntry.java
> +    public ForgeSerializerTypeRegistryEntry(Serializer<? extends T> p_79330_)
Name the parameter.

2021-11-25 18:21 UTC, ChampionAsh5357 approved these changes
Update the PR name so Lex and others know what this is for without having to guess. For small context in case you don't before anyone can look at it, this PR just adds in the missing forge wrapped registries and adds object holders to those that already exist.

2021-12-02 10:27 UTC, sciwhiz12 commented
@rehwinkel: Please retarget this PR to 1.18 and check for any additional vanilla registries which may need to have new Forge registry counterparts.

2021-12-25 03:26 UTC, sciwhiz12 commented
Hello! @rehwinkel, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 if applicable. If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2022-01-09 06:29 UTC, closed without merging