[1.17.x] Added a hook to activate spyglass-style scoping
MinecraftForge/MinecraftForge pull request #8171
Opened 2021-10-25 18:47 UTC by Da-Technomancer

Added a hook to trigger the 'scoping' effect the spyglass uses (zoom in, visual overlay, adjusted movement).

Mods can register a predicate which will be tested on the client side to see whether the scoping effect is being externally triggered. If any registered predicate returns true, scoping will be active. 

Also wrote a test mod.

2021-10-25 19:23 UTC, diesieben07 requested changes

2021-10-25 19:23 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +import java.util.*;
Don't use * imports

2021-10-25 19:23 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +     * Only one registered predicate needs to be true for scoping to occur
Missing periods at the ends of the sentences.

2021-10-25 19:23 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +        SPYGLASS_PREDICATES.add(spyglassCondition);
This method should be made threadsafe, to enable use from `FMLCommonSetupEvent`.

2021-10-25 19:23 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +    public static boolean isPlayerScoping(Player player){
Formatting (braces on new lines).

2021-10-25 19:23 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +        return SPYGLASS_PREDICATES.stream().anyMatch(pred -> pred.test(player));
Considering this is called frequently, you should use a normal foreach loop for performance reasons.

2021-10-25 19:23 UTC, diesieben07 commented on src/test/java/net/minecraftforge/debug/entity/player/PlayerSpyglassScopeTest.java
> +        if(ENABLE){
Formatting (whitespace and braces on newlines)

2021-10-26 07:02 UTC, diesieben07 requested changes

2021-10-26 07:02 UTC, diesieben07 commented on src/test/java/net/minecraftforge/debug/entity/player/PlayerSpyglassScopeTest.java
> +        if(ENABLE)
Missing space after if

2021-10-26 07:02 UTC, diesieben07 commented on src/main/java/net/minecraftforge/common/SpyglassHooks.java
> +            if(spyglassPredicate.test(player))
Missing space after if and for

2021-10-26 07:25 UTC, sciwhiz12 requested changes

2021-10-26 07:25 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/SpyglassHooks.java
> +package net.minecraftforge.common;
Missing license header, please run the `updateLicenses`/`licenseFormat` task.

2021-10-26 07:25 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/entity/player/PlayerSpyglassScopeTest.java
> +    static final boolean ENABLE = false;
The convention is for the field controlling the activation status of a test mod to be named `ENABLED`.

2021-10-26 07:25 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/SpyglassHooks.java
> +     * @param spyglassCondition A predicate which will be checked on the client side. Might be tested very frequently.
The comment regarding the given predicate being likely to be called very frequently (how frequently? every tick?) should be moved to the javadoc body proper and **marked in bold** (placed between `<strong>` and `</strong>`).

Also, the phrase _"on the client"_ suggests that this predicate is called only on the client-side. Is this true, or is it also called on the server-side (as the existence of the check method on the `Player` class would likely indicate)?

2021-10-26 13:57 UTC, Da-Technomancer commented on src/main/java/net/minecraftforge/common/SpyglassHooks.java
> +package net.minecraftforge.common;
Done in the latest commit. Note that the task also added a header to an unrelated class.

2021-10-26 13:58 UTC, Da-Technomancer commented on src/main/java/net/minecraftforge/common/SpyglassHooks.java
> +     * @param spyglassCondition A predicate which will be checked on the client side. Might be tested very frequently.
"Also, the phrase "on the client" suggests that this predicate is called only on the client-side. Is this true, or is it also called on the server-side (as the existence of the check method on the Player class would likely indicate)?"
The method in Player is only ever called on the client side in vanilla usage.

2021-10-26 14:21 UTC, Da-Technomancer commented
I would like to note that running the `updateLicenses` task as suggested also added a license header to an unrelated class- which was presumably missing a header before.
I've included that change in the commit. 

Edit: Reverted that change in a later commit.

2021-10-27 09:17 UTC, rehwinkel reviewed
The intended changes look good, I added a little suggestion for your consideration though.

2021-10-27 09:17 UTC, rehwinkel commented on patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
> ++      return this.m_6117_() && this.m_21211_().m_150930_(Items.f_151059_) || net.minecraftforge.common.SpyglassHooks.isPlayerScoping(this);
Could it be desirable to override the default spyglass behavior, like disabling vanilla spyglasses from working to add custom behavior? With this current method, default spyglasses would always "work". Just a some food for thought.

2021-10-27 09:17 UTC, rehwinkel commented on src/main/java/net/minecraftforge/common/SpyglassHooks.java
> +        for (Predicate<Player> spyglassPredicate : SPYGLASS_PREDICATES)
This code looks fine, however I think having an opposite check would be useful too. Like "if this condition matches, DO NOT show the scoping effect". Something like a paralysis potion effect, or blindness might wish to disable scoping, just an idea though.

2021-10-27 09:17 UTC, rehwinkel commented on src/test/java/net/minecraftforge/debug/block/FullPotsAccessorDemo.java
> +
Does this belong in this PR? On a related note, I've also seen that some datagen-assets are missing in git, maybe making an extra-PR for adding this license header and the mentioned assets would be better.

2021-11-02 17:55 UTC, Da-Technomancer commented on patches/minecraft/net/minecraft/world/entity/player/Player.java.patch
> ++      return this.m_6117_() && this.m_21211_().m_150930_(Items.f_151059_) || net.minecraftforge.common.SpyglassHooks.isPlayerScoping(this);
There are existing ways for mods to disable the vanilla spyglass behavior (by changing the item or preventing it being set to active).

2021-11-03 04:45 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/SpyglassHooks.java
> +        for (Predicate<Player> spyglassPredicate : SPYGLASS_PREDICATES)
That would either mean holding another list of predicates which deny the scoping behavior and run before the allowing predicates, or something akin to a `Function<Player, Result>` where the result encodes some status like 'defer', 'allow (if not blocked)', or 'block'; am I correct?

2021-12-25 03:17 UTC, sciwhiz12 commented
Hello! @Da-Technomancer, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 if applicable. If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2021-12-25 14:45 UTC, Da-Technomancer commented
I've now rebased this PR onto 1.18, in a separate PR (here: https://github.com/MinecraftForge/MinecraftForge/pull/8325).
Closing this PR, as it is stale and for an outdated version.

2021-12-25 14:45 UTC, closed without merging