New events for Minecarts to handle things like making trains
MinecraftForge/MinecraftForge pull request #8172
Opened 2021-10-26 14:08 UTC by rehwinkel

This PR provides 4 events to the `AbstractMinecart` entity:
* `MinecartEvent.Steered` for when a player moves in a minecart
* `MinecartEvent.Pushed` for when a minecart is pushed by another entity
* `MinecartEvent.PreMove` called before the code for moving along the track is executed, cancellable
* `MinecartEvent.PostMove` to adjust movements after the fact

Theses events aim to replace the old Minecart events (such as `MinecartUpdateEvent`). I've also written a little test mod that makes linking minecarts together possible, just like RailCraft does it.

2021-10-26 17:34 UTC, ChampionAsh5357 requested changes
I'm not sure how I feel about this particular event set since its called three events on almost every tick for any minecart present. Though, I currently cannot think of another way to do so.

2021-10-26 17:34 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/world/entity/vehicle/AbstractMinecart.java.patch
> ++            this.m_20256_(this.m_20184_().m_82520_(event.getX(), 0.0D, event.getX()));
Gets the same coordinate for both directions instead of one for each.

2021-10-26 17:34 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/world/entity/vehicle/AbstractMinecart.java.patch
> ++      net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(postMoveEvent);
Can be condensed to one line.

2021-10-26 17:34 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +import net.minecraftforge.event.entity.*;
No wildcard imports.

2021-10-26 17:34 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/MinecartEvent.java
> +public class MinecartEvent extends Event {
License header missing, brackets on new lines, documentation.

2021-10-26 17:34 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/MinecartEvent.java
> +    @net.minecraftforge.eventbus.api.Cancelable
Just import, this is a forge class.

2021-10-26 17:34 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/entity/MinecartLinkTest.java
> +public class MinecartLinkTest {
Missing license header, brackets on new lines, and remove wildcard imports.

2021-10-26 17:50 UTC, rehwinkel commented on src/main/java/net/minecraftforge/event/entity/MinecartEvent.java
> +    @net.minecraftforge.eventbus.api.Cancelable
I did it that way because I saw other forge events do it that way, e.g.:
```java
@net.minecraftforge.eventbus.api.Cancelable
public class EntityJoinWorldEvent extends EntityEvent { ... }
```

2021-10-26 20:59 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/MinecartEvent.java
> +    @net.minecraftforge.eventbus.api.Cancelable
I don't really know why other Forge events did it that way, but in any case you should just import it.

2021-10-26 21:29 UTC, ChampionAsh5357 requested changes
I'll give this a proper testing when I can, but currently just fixing up formatting and clarity.

2021-10-26 21:29 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/MinecartEvent.java
> +    @net.minecraftforge.eventbus.api.Cancelable
Import.

2021-10-26 21:29 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/entity/MinecartLinkTest.java
> +            if (dist > 8F) {
Opening brace on new line.

2021-10-29 17:27 UTC, Shadows-of-Fire commented
We had hooks like these previously, and they were removed due to their limited usage and high cost.  I'm not sure readding them in any form is a good idea.

2021-10-30 10:10 UTC, rehwinkel commented
The main use for this would be minecart linking the way railcraft does it, which was my primary motivation for making this PR. I agree, the use cases are quite limited, however I am not sure how one would best achieve functionality like that without an event like this (without replacing vanilla minecarts entirely, which is very bad for compatbility).

2021-12-25 03:17 UTC, sciwhiz12 commented
Hello! @rehwinkel, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.18 if applicable. If we do not hear back from you after some time, this PR will be closed for inactivity.
If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference. 
Thank you for your contributions. 👋

2022-01-09 11:29 UTC, closed without merging