Fix PartEntity id shifting
MinecraftForge/MinecraftForge pull request #8189
Opened 2021-11-04 13:28 UTC by XenonDB

https://github.com/MinecraftForge/MinecraftForge/issues/8188

2021-11-04 13:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8189) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8189) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=8189) it.</sub>

2021-11-04 13:31 UTC, ChampionAsh5357 requested changes
As this issue exists in both 1.16 and 1.17. This should be ported to 1.17 and then once merged handled back in 1.16.

2021-11-04 13:31 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/client/network/play/ClientPlayNetHandler.java.patch
> +                aenderdragonpartentity[i].func_145769_d((i + 1) + p_147281_1_.func_149024_d());
Should have comment linking to the mc issue this fixes (E.g. ` //Forge: Fixes MC-123456`).

2021-11-04 13:42 UTC, XenonDB commented
I should find where this code is in 1.17..

2021-11-04 13:57 UTC, ChampionAsh5357 commented
Within `EnderDragon` as packet data is now handled directly on the entity.

2021-11-04 14:00 UTC, XenonDB commented
> Within `EnderDragon` as packet data is now handled directly on the entity.

Ok, I found that.

2021-11-04 14:11 UTC, ChampionAsh5357 commented
As someone pointed out to me, this is a manual edit instead of an actual patch. Please properly generate the patch using the `genPatches` task after you setup your Forge project in your IDE of choice.

2021-11-05 19:29 UTC, XenonDB commented
hmm...since I delete my fork relative to this. I will close this PR and make a new one.
Is there any way to make a private patched version for testing?

2021-11-05 19:29 UTC, closed without merging

2021-11-05 19:43 UTC, ChampionAsh5357 commented
> hmm...since I delete my fork relative to this. I will close this PR and make a new one. Is there any way to make a private patched version for testing?

Just run the test client in the dev environment. As long as it is not the clean one, it should have your changes.