[1.18.x] Allow blocks to hide faces on a neighboring block
MinecraftForge/MinecraftForge pull request #8300
Opened 2021-12-14 17:40 UTC by XFactHD

This PR adds a hook that allows a block to hide a neighboring block's face that touches it. This is really useful for blocks like glass slabs which should behave identically to a glass block when placed on another glass block.

The level and position context is intended for blocks which need dynamic data from their `BlockEntity` to decide whether they would hide a neighboring block's face*. I have thought about the feasibility of using the `IModelData` system to allow modders to pass dynamic context to this method but this approach runs into multiple roadblocks:

- `Block#shouldRenderFace()` gets a `BlockGetter` while `ModelDataManager#getModelData()` requires a `Level`
- The `BlockGetter` given to `Block#shouldRenderFace()` is very unlikely to be the current client `Level` because the chunk rendering uses additional data structures that act similar to a `Level` but aren't actually one
- This would not work for blocks that use `BakedModel#getModelData()` to create the data object instead of using the `ModelDataManager`

*My usecase is a block which can be camouflaged as almost any full size block. Registering a dedicated variant for every camo block is not possible because some of those blocks come from a tag since it is completely impossible to determine if a block's model actually fills the whole cube for blocks which are not considered solid.

One thing I am not sure about and would love to get feedback on is the addition of `IForgeBlockGetter#getExistingBlockEntity()` and the reference to it from the javadoc on `IForgeBlock#hidesNeighborFace()`.
The intention behind it is to allow modders to access their BEs while making sure that someone passing an actual `Level` to `Block#shouldRenderFace()` doesn't accidentally cause the BE retrieval to create a BE that doesn't exist yet which would cause a CME when this happens in a render worker thread, for example while the world is still loading. The reason for this behavior is that `Level#getBlockEntity()` calls `LevelChunk#getBlockEntity()` with `LevelChunk.EntityCreationType.IMMEDIATE` to immediately create a `BlockEntity` for the given position if it has not been added yet.
The other option would be to document this even more thoroughly on `IForgeBlock#hidesNeighborFace()` and let the modder handle this differentiation themselves, though this feels very prone to error on the modder's side.

2021-12-21 00:15 UTC, ChampionAsh5357 requested changes
Besides the fact that it should be treated as a more sensitive method, it looks useful to me. The addition of `#getExistingBlockEntity` also seems like a valid idea to try and mitigate people having to check a specific case each time.

I am concerned on whether or not `LevelChunk#getBlockEntity` is thread safe at all though. It can remove BEs or promote BEs that are being loaded, making it not thread safe.

2021-12-21 00:15 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/world/level/block/Block.java.patch
> ++         return false;
In my opinion, this is a level and position sensitive `#skipRendering` implementation. So, it would probably be better to replace that call, rename, and default to the vanilla method.

2021-12-21 00:15 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeBlockGetter.java
> +package net.minecraftforge.common.extensions;
Missing license header

2021-12-21 00:15 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/block/HideNeighborFaceTest.java
> +package net.minecraftforge.debug.block;
Missing license header.

2021-12-21 00:15 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
> +     * WARNING: This method is likely to be called from a worker thread! If you want to retrieve a
The warning should also include information regarding to CMEs for any kind of write operation.

2021-12-29 15:20 UTC, ChampionAsh5357 approved these changes
Another triage member (sciwhiz) has confirmed the safety of the statement. As such, I will approve this now

2022-03-05 23:50 UTC, sciwhiz12 requested changes
Please update the license headers in the following files:

- `src/main/java/net/minecraftforge/common/extensions/IForgeBlockGetter.java`
- `src/test/java/net/minecraftforge/debug/block/HideNeighborFaceTest.java`

2022-03-06 17:04 UTC, sciwhiz12 approved these changes

2022-03-07 09:01 UTC, OrionDevelopment commented
We talked about this internally some more.

By default, we don't really like having APIs in forge which allow the modification of behavior of other mods. This would mean that normally this PR would be out of scope for forge, however we also agree with the fact that camouflage is a concept that we should support up to a certain degree.

The discussion ended up with a compromise:
- We would like to shrink the scope of this functionality way down. As it states right now the scope is way to large, and there is no way for mods to opt out of this functionality at all.
- We realized that for solid blocks this behavior is completely unwanted.
- We want an override on the neighbor block (the one whose sides this PR would hide) to completely opt out and fallback to the current behavior.

This al caused us to come up with the following compromise:
1) Add a method to IForgeBlock that functions as an override. Something like `supportsExternalFaceHiding` this method returns a `boolean` which indicates if a neighbor can hide a face or not. Use the DistExecutor to check for the rendering type that the block uses, if it is solid return `false`, if not return `true`. This should result in the required override behaviour.
2) Add a check for this method, before executing your hiding logic, if it is false default to the current behavior.

Would that work for you?

2022-03-07 10:50 UTC, XFactHD commented
That's a fair compromise, I can work with that.

2022-03-07 11:52 UTC, OrionDevelopment approved these changes

2022-03-13 21:59 UTC, merged

2022-03-13 22:17 UTC, sciwhiz12 commented
:shipit: Published as **1.18.2-40.0.15**.