1.16.x
MinecraftForge/MinecraftForge pull request #8334
Opened 2021-12-30 21:45 UTC by NoOneCanCode

Expose `World` and x/y/z coordinates in `PlaySoundAtEntityEvent`. This is necessary because the player entity attached to the event is often null and thus the location and world corresponding to the event cannot always be determined. These changes expose those values as separate fields so that they can be accessed by mods that subscribe to the event. This is useful, for instance, if a mod wants to hook into sound events to provide a sense of hearing to a mob (as I was trying to do before writing this PR).

An example mod is provided in `PlaySoundAtEntityEventTest.java`. Set the `ENABLED` flag to `true` to enable the event subscription. When the mod is enabled, there should be lots of log spam showing the coordinates and dimension name of each sound event. An easy way to confirm the coordinates are correct is to tp to an entity making sound.

2021-12-30 21:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8334) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8334) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=8334) it.</sub>

2021-12-30 21:48 UTC, diesieben07 commented
PRs should first target the current latest version (1.18.1). Once they are merged there they can be backported to LTS.

2021-12-30 21:52 UTC, XFactHD commented
This change looks completely pointless to me: The event already gives you the entity that fired the event, which means you already have access to the entity's world and coordinates via `EntityEvent#getEntity().getLevel()` and `EntityEvent#getEntity().getX/Y/Z()`.

2021-12-30 21:52 UTC, diesieben07 commented
The entity is often null, the event name is very misleading.

2021-12-30 21:55 UTC, XFactHD commented
In those cases the proposed changes would lead to a `NullPointerException` anyway because the `Entity` passed into the methods that fire this event is accessed without null-checks

2021-12-30 22:52 UTC, NoOneCanCode commented
> In those cases the proposed changes would lead to a `NullPointerException` anyway because the `Entity` passed into the methods that fire this event is accessed without null-checks

Could you point me to where this is dereferenced? It looks like the parameter is tagged `@Nullable` and there are many places where null is passed into `ServerWorld#playSound` for instance:
![image](https://user-images.githubusercontent.com/96887642/147792876-357ca19b-ef9a-4906-af0b-21bec6c3dd9d.png)
And I'm not seeing anywhere in the event factory that the entity gets dereferenced. Could you clarify?

2021-12-30 22:56 UTC, NoOneCanCode commented
> The entity is often null, the event name is very misleading.

Might it separately be worth changing some of the nomenclature around the event? I'm new to forge so I'm not familiar with naming convention but the javadoc around the class and the class/field names themselves seem to suggest that the entity attached to the event is the entity that generates the event. In fact, the entity is always a player entity if it is not null. The player entity appears to correspond to the player that creates the sound event, but since most sound events aren't player created it is usually null. Also, because the event extends `EntityEvent` it inherits an entity field with a generic entity. This could be misleading because the entity will always be a player when present.

2021-12-30 23:28 UTC, sciwhiz12 requested changes
As said by @diesieben07, PRs (features, enhancements, bugfixes) must be made for the active version (1.18.x) before they are accepted for the LTS version (1.16.x), or it must be proved that the PR's contents are not applicable to the active version.

In addition, please title your PR properly.

2021-12-30 23:31 UTC, NoOneCanCode commented
> As said by @diesieben07, PRs (features, enhancements, bugfixes) must be made for the active version (1.18.x) before they are accepted for the LTS version (1.16.x), or it must be proved that the PR's contents are not applicable to the active version.
> 
> In addition, please title your PR properly.

Just fixed the title. I can submit a PR with similar functionality to 1.18 tonight or tomorrow afternoon but maybe there should be some more discussion about what the actual fix should be, and whether or not the event should include the entity that generates it and not just the player it comes from.

2021-12-31 01:12 UTC, XFactHD commented
> The player entity appears to correspond to the player that creates the sound event, but since most sound events aren't player created it is usually null.

This is incorrect in most cases.

There are five places where the event hook is called:

- Two in `ClientWorld`
- One in `ClientPlayerEntity`
- Two in `ServerWorld`

#### `ClientWorld` and `ServerWorld`
The call-sites in `ClientWorld` and `ServerWorld` are very similar with one important distinction: The player that is passed into the method is handled differently.
On the client side, the player passed into the method must match `Minecraft#player` and only then the sound will be played.
On the server side, a packet will be sent to all players except the one passed in.
The reason for this is that it allows an interaction (like switching a lever for example) to play a sound without a side check and therefore avoid unnecessary network packets and lag between player interaction and sound playback on the client of the player that performed the interaction.
The player passed to these methods is in most cases not the sound source.

#### `ClientPlayerEntity`
`Entity#playSound()` seems to be used when the `Entity` is actually the source of the sound. This method is overriden in `ClientPlayerEntity` and fires the event seperately.
The implementations of `playSound()` in `PlayerEntity` and `Entity` both call one of the `World#playSound()` methods.

---

The problem with all this is that most sounds, even when created by an entity, don't go through the `World#playSound()` method with an additional entity argument because that overload is only used for sounds that move with the entity.

If this event were to be reworked, it should be changed to not be an `EntityEvent` because there is no guarantee that an `Entity` that fits is available, it should be renamed to something like `PlaySoundAtPositionEvent` and provide the `World` and coordinates like you are proposing here. Obviously this would be a breaking change and could only happen in a phase where those are accepted. This is of course only my personal opinion.
After this deepdive into the sound code, your proposed changes would be a decent bandaid-fix for this event IMO.

In light of that I have to apologize for my initial reaction, I completely misinterpreted this whole thing.

---

Further discussion on this might be easier on the Forge Discord in the #github-discussions channel.

2022-07-17 14:22 UTC, closed without merging