Fix for #8223: "TileFluidHandler is a poor reference due to doing a few things incorrectly"
MinecraftForge/MinecraftForge pull request #8345
Opened 2022-01-03 01:06 UTC by OneLemonyBoi

Corrects TileFluidHandler by replacing ```BlockEntity#save``` with ```BlockEntity#saveAdditional``` and invalidating the LazyOptional.

2022-01-03 01:11 UTC, KnightMiner commented on src/main/java/net/minecraftforge/fluids/capability/TileFluidHandler.java
>          super.save(tag);
You missed part of the update here

2022-01-03 03:22 UTC, pupnewfster commented
See some of forge's implementations of `reviveCaps` as you should likely override that as well.

2022-01-19 21:02 UTC, 3TUSK commented
Side note, #8235 partially overlaps with this PR (namely the `BlockEntity#saveAdditional` part) which has been merged recently. Merge conflict may happen.

Also the title is wrong: the correct issue ticket is #8332 as indicated by the source branch name.

2022-02-06 01:45 UTC, sciwhiz12 requested changes
Please fix the merge conflicts, which include the removal of this PR's change to `TileFluidHandler#saveAdditional` (as it has since been corrected by #8235).

2022-08-27 18:42 UTC, sciwhiz12 commented
Hello! @OneLemonyBoi, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.19.2 (or leave an explanation why this PR's changes are not applicable to 1.19.2). If we do not hear back from you after some time, this PR will be closed for inactivity.

If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference.
Thank you for your contributions. 👋

2022-10-12 09:32 UTC, sciwhiz12 commented
Hello! As per my previous comment, we will be closing this PR for inactivity. If you or another contributor wishes to continue the work of this PR, please create a new PR with a link to this PR for reference.
Thank you for your contributions. 👋

2022-10-12 09:32 UTC, closed without merging