Fix and improve Ingredient invalidation
MinecraftForge/MinecraftForge pull request #8361
Opened 2022-01-06 19:25 UTC by diesieben07

As it turns out Ingredient.invalidateAll has not been called at all since 1.13. It was supposed to be fixed by #7953, but that did not fix it.
This PR actually re-adds the call to Ingredient.invalidateAll.

Additionally the invalidation tracking is greatly improved. Instead of keeping a set of all existing Ingredient instances in memory (which has its own problems, see #8359), a global counter is used to enable the ingredient itself to check whether invalidation has to happen. To do this, `checkInvalidation` must be called by the ingredient before it accesses any invalidation-sensitive data. It will call `invalidate` if necessary. Then `markValid` must be called once the invalidation-sensitive data has been computed.

A test mod is included that checks that ingredients that survive across world loads are invalidated.

Fixes #8359

2022-01-06 19:56 UTC, alcatrazEscapee approved these changes

2022-01-10 13:34 UTC, sciwhiz12 requested changes
The changes seem solid to me; most of my concerns are with the included test mod.

2022-01-10 13:34 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/world/item/IngredientInvalidationTest.java
> +    private static class ForgeEventListener
Why does this use a full class for a simple event listener, rather than adding a method reference as an event listener?

2022-01-10 13:34 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/world/item/IngredientInvalidationTest.java
> +@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, modid = IngredientInvalidationTest.MOD_ID)
Why does this class need an `@Mod.EventBusSubscriber` annotation? The event listener is in an inner class (which I also question in another comment), and there are no other `static` methods annotated with `@SubscribeEvent` in this class.

2022-01-10 13:34 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/world/item/IngredientInvalidationTest.java
> +    private static final RegistryObject<Item> TEST_ITEM = ITEMS.register("test_item", () -> new Item(new Item.Properties()));
These two fields seem to be unused: the item is unused by anything, and the deferred register is not registered to the mod-specific event bus which renders it and the item useless.

2022-01-10 13:34 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/world/item/IngredientInvalidationTest.java
> +public class IngredientInvalidationTest
For the sake of documentation, please add a javadoc to this class explaining what this test is checking for and how to confirm the behavior it is checking works as expected.

2022-01-10 13:34 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeMod.java
> +        MinecraftForge.EVENT_BUS.addListener(this::mappingChanged);
Should the license header of this file also be updated with the new year, given that you have modified it?

2022-01-10 13:43 UTC, diesieben07 commented
I have addressed the concerns, the test mod issues were a result of me doing a lazy copypasta job.

2022-01-10 14:11 UTC, sciwhiz12 approved these changes

2022-01-14 15:05 UTC, TheCurle commented
This is causing a very hard to debug hard-crash during worldloading, so I'm going to accelerate this. Thanks for the fix, diesieben.

2022-01-14 15:05 UTC, merged