Allow adding to Weathering and Waxing maps
MinecraftForge/MinecraftForge pull request #8363
Opened 2022-01-08 17:10 UTC by bageldotjpg

Currently, it is impossible to add to WeatheringCopper's `NEXT_BY_BLOCK` map, which makes it quite hard to add new copper blocks that can oxidize. Making a HashBiMap instead makes it a lot easier as modders can just add to the map directly by getting the value in the supplier. While it is possible to make stuff oxidize without adding to this map, it would require a lot more work to get all the quirks functional especially stuff such as lightning reversing, when it can be made easier just by being able to add to this map.

The same kind of map is used in HoneycombItem's `WAXABLES` to determine what copper blocks can be waxed and scraped off, making this a HashBiMap also makes it simpler to modify. 

A test mod is included, registering new copper blocks, that can be observed to be oxidizing over time (though, you may want to turn up the tick speed). You can also confirm that lightning reverses the custom copper's oxidation, and axes can scrape off the oxidation. There is also a test that shows the HoneycombItem's `WAXABLES` map is updated, using dirt and sand. Axe scraping works here as well.

2022-01-08 17:35 UTC, diesieben07 commented
This can be done without any patches and instead using an AT and then setting the field. Forge should do that and then provide methods to add to them in the MInecraftForge class instead of this huge patch.

2022-01-08 17:39 UTC, bageldotjpg commented
Oops, you are right about `WAXABLES` but I am pretty sure `NEXT_BY_BLOCK` can not be AT'd.

2022-01-08 17:44 UTC, diesieben07 commented
Why not?

2022-01-08 18:09 UTC, bageldotjpg commented
Not sure, just did some testing and `WAXABLES` updates and runs just fine when I AT it but `NEXT_BY_BLOCK` does not. It no longer has the red line under it in IntelliJ but running says I cannot assign a value to it because its final, unlike `WAXABLES`.

2022-01-10 22:44 UTC, thelegitdolt commented
wow

2022-01-11 01:25 UTC, bageldotjpg commented
This has been updated as last discussed in github-discussions, not sure if any other changing needs being done

2022-05-13 07:52 UTC, sciwhiz12 requested changes
The current implementation looks fine to me.

However, this raises the design question of whether giving modders almost full control over the contents of the map is intended, and whether the use of the `BiMap<Block, Block>` is suitable for Forge which prefers data structures store the delegate to a registry object (like a block).

As a possible alternative, we could store two `BiMap<IRegistryDelegate<Block>, IRegistryDelegate<Block>>`s in `ForgeHooks`, and patch `HoneycombItem` and `WeatheringCopper` to add static, synchronized methods which register new blocks to the map and to modify the existing query methods to query the new `BiMap`s in `ForgeHooks` (the ordering would be dependent on whether we wish to allow mods to override regular vanilla behavior).

2022-05-13 07:52 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/block/CustomCopperTest.java
> + */
Outdated license header, please update your PR to the latest commit of the base branch and run the `updateLicenses`/`licenseFormat` task.

2022-05-13 07:52 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/block/CustomCopperTest.java
> +public class CustomCopperTest
Please provide a javadoc for this class which explains what feature this tests, how to test it, and what the expected results are from said test.

2022-05-13 07:52 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/block/CustomCopperTest.java
> +            MinecraftForge.EVENT_BUS.register(this);
As there are no listeners for events fired on the main Forge event bus, this line is unneeded.

2022-05-13 11:59 UTC, ChampionAsh5357 commented
As a quick question, is there a reason why this injects into the map instead of adding an extension method in `IForgeBlock`? This seems like a similar usecase of how Forge handled flammability by the `FireBlock` or burn time for furnaces.

2022-05-13 14:58 UTC, Random832 commented
I think waxing is better done by adding a ToolAction.

For weathering, it may make more sense to have custom blocks override getNext, and add a defaulted getFirst method that can likewise be called from lightning.

2022-08-27 18:39 UTC, sciwhiz12 commented
Hello! @bageldotjpg, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.19.2 (or leave an explanation why this PR's changes are not applicable to 1.19.2). If we do not hear back from you after some time, this PR will be closed for inactivity.

If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference.
Thank you for your contributions. 👋

2022-10-12 09:32 UTC, sciwhiz12 commented
Hello! As per my previous comment, we will be closing this PR for inactivity. If you or another contributor wishes to continue the work of this PR, please create a new PR with a link to this PR for reference.
Thank you for your contributions. 👋

2022-10-12 09:32 UTC, closed without merging