Implement full support for IPv6 - both for dual-stack dedicated servers and Open to LAN worlds
MinecraftForge/MinecraftForge pull request #8376
Opened 2022-01-09 16:46 UTC by PaintNinja

Successor of https://github.com/ForgeForce/MinecraftForge/pull/13

This PR intends to fix and enhance the small existing IPv6 patches in Forge, including:
- IPv6 support for Open to LAN and local server discovery
- Dual-stack resolution support for hostnames
- Compressed representation of IPv6 addresses

Marked as a draft while I do some more comprehensive testing.

2022-02-04 09:23 UTC, PaintNinja commented
I've already thoroughly tested this but to help speed up approval by a Triager, here's some instructions on how to test this PR yourself if needed. How thoroughly you test it is up to you - at a certain point it's more about combatting paranoia by covering every edge-case. Note that you do *not* need a native IPv6 Internet connection to fully test this, although having it does make it easier.

# How to test
First, clone the PR and set up forgedev environment as usual

## Open to LAN features

### Forgedev
1. Create a copy of the forge client run configuration and change the username arg from `Dev` to `Dev###`
    - We'll call the original run config "client 1" and the copy "client 2" from now on for simplicity's sake
2. Run both client 1 and client 2
3. Make a new flat world on client 1 and Open to LAN or `/publish`
4. Click the Multiplayer screen on client 2

If it works, client 1 should be discovered by client 2 and show up at the bottom of the list with a compressed IPv6 address and client 2 should be able to join client 1's world.

Repeat the process after toggling the new `compressLanIPv6Addresses` config option in `projects\forge\run\config\forge-client.toml` to test the LAN IPv6 address compression feature.

Repeat the process after disabling IPv4 on your network adapter to confirm that legacy connections still work. Don't forget to re-enable IPv6 support on your network adapter afterwards!

### Userdev
1. Make an MDK and `publishToMavenLocal`
2. Add `mavenLocal()` to repositories in the MDK's build.gradle
3. Now follow the forgedev instructions

### Production clients
1. Build Forge
2. Run installer and install client
3. Start client twice
4. Now follow forgedev instructions 3 and 4

### Interaction between forgedev <-> userdev <-> production clients
For completeness, you may want to test each combination of client types such as forgedev client opening to lan and production client discovering and joining the world.

## Dual-stack resolution feature
If you do not have a native IPv6 Internet connection, you can use a tunnel broker or setup local DNS entries. These steps assume you have already tested the Open To LAN features.

### Forgedev
1. Start the forge server run configuration
2. Determine your computer's public IPv4 and v6 addresses with `ipconfig` or use https://ipv4.icanhazip.com and https://ipv6.icanhazip.com respectively. Press Ctrl + F5 a couple of times if the wrong IP address version is returned by the site.
3. Setup an `A` DNS record that points to your computer's public IPv4 address and an `AAAA` record for your IPv6 one
4. Verify that you can connect over both IP versions with your OS' ping command (e.g. `ping -6 -p 25565 ipv6patch-test.example.com.invalid` for IPv6 and `ping -4 -p 25565 ipv6patch-test.example.com.invalid for IPv4`)
4.1 If you cannot connect over IPv4, temporarily enable DMZ for your test system or setup port forwarding or port triggering
5. Start the client 1 run configuration
6. Click the Multiplayer screen on client 2 and add the server hostname created in step 3

If it works, client 1 should be able to ping and connect to the server. The server console should show a connection over IPv6 if your operating system returned the AAAA record with higher priority (due to OS preference, lower ping or no connection over IPv4)

7. Disable IPv6 connectivity for the server but keep the AAAA record

If it works, client 1 should still be able to ping and connect to the server and the server console should show a connection over IPv4.

8. Disable DMZ or port forwarding/triggering over IPv4 and re-enable IPv6 connectivity for the server, but keep the A record

If it works, client 1 should still be able to ping and connect to the server. The server console should show a connection over IPv6. 

Without this PR, the client will fail to connect as it will always resolve to the IPv4 A record in all circumstances if one is available - regardless of connectivity or OS logic. With this patch, your operating system should return the AAAA record if it knows there's no connectivity over IPv4 but is able to connect over IPv6.

### Userdev
Same as Forgedev, but you can skip steps 2 and 3 as they only need to be performed once

### Production server and client
1. Build Forge
2. Run installer and install the server and client.
3. Follow forgedev instructions 4-8. Production client in this case would be "client 1"

### Interaction between forgedev <-> userdev <-> production servers and clients
For completeness, you may want to test each combination of client and server types such as forgedev client joining a production server, production client joining userdev server and so on.

### Interaction between different Internet connections
If you want to be as thorough as I was, you can run these tests...
- ...on a known IPv4-only Internet connection
- ...on a known IPv6-only Internet connection
- ...on on a known dual-stack (IPv4 and IPv6) Internet connection
- ...and different combinations of each, such as running the server on a known IPv6-only Internet connection and trying to connect to it as a client on a known dual-stack one.

### Interaction between different operating systems
While of course different OSes have different implementations of IPv6 and their own quirks, support has existed for a long time in major operating systems (Windows XP supported IPv6, Windows Vista enabled it by default. Linux supported it without experimental status around version 2.6.12) so it is safe to reasonably assume that interaction between the different major operating systems is sufficiently mature and stable.

It should be noted that with this PR, clients may still use IPv4 if their OS determines that IPv6 connectivity is poor or unavailable. The 

### Finishing up
1. Remove the DNS entries to your computer's public IP addresses created in forgedev instructions step 3 if desired
2. Re-enable IPv6 on your network adapters if you disabled it during testing

2022-02-26 14:17 UTC, sciwhiz12 requested changes
My testing shows that this works, though I haven't followed the testing guidelines you gave fully (partly because of the DNS part). Anyone, please also try out this PR yourselves and comment here on your results so we can avoid any potential breaks that might not be caught by our testing.

---

Please update the license headers in the following files by changing the year from `2021` to `2022`:
- `src/main/java/net/minecraftforge/common/ForgeConfig.java`

2022-02-26 14:17 UTC, sciwhiz12 commented on patches/minecraft/net/minecraft/client/server/LanServerDetection.java.patch
> ++            this.f_120087_ = InetAddress.getByName("FF75:230::60");
This should probably reference the patched constant field in `LanServerPinger`, as I presume the address string was inlined by the compiler from there anyway.

2022-02-26 14:17 UTC, sciwhiz12 commented on patches/minecraft/net/minecraft/client/server/LanServerDetection.java.patch
> ++            }
You can avoid the removal of the line by not indenting it.

2022-02-26 14:17 UTC, sciwhiz12 commented on patches/minecraft/net/minecraft/client/server/LanServerDetection.java.patch
> ++         }
You can avoid the removal of the line by not indenting it.

2022-02-26 14:17 UTC, sciwhiz12 commented on patches/minecraft/net/minecraft/client/server/LanServerPinger.java.patch
> ++           net.minecraftforge.network.DualStackUtils.isIPv6(net.minecraftforge.network.DualStackUtils.getLocalAddress()) ? "FF75:230::60" : "224.0.2.60";
Could you please explain here (and if possible, in a comment in all similar spaces) how this IPv6 address was chosen? Also, we'll want to keep this on one line instead, and perhaps extract the condition to a special helper method in `DualStackUtils`.

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +    public static boolean isIPv6(final InetAddress inetAddress) {
The method's name (and its overload) should be modified to better reflect that this method has side-effects, such as perhaps `checkIPv6`. Also, formatting: braces on newlines.
```suggestion
    public static boolean isIPv6(final InetAddress inetAddress)
    {
```

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +     * @author Paint_Ninja
I don't think we accept the use of the `@author` tag in javadocs. @ChampionAsh5357 and @TheCurle, your thoughts?

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +public class DualStackUtils {
Formatting: braces on newlines.
```suggestion
public class DualStackUtils
{
```

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +    public static boolean isIPv6(final String hostAddress) {
Formatting: braces on newlines.
```suggestion
    public static boolean isIPv6(final String hostAddress)
    {
```

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +    public static InetAddress getLocalAddress() {
Formatting: braces on newlines.
```suggestion
    public static InetAddress getLocalAddress()
    {
```

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +        }
Formatting: braces on newlines.
```suggestion
        try
        {
            return InetAddress.getByName("localhost");
        } catch (final UnknownHostException e)
        {
            return null;
        }
```

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +     * accordingly (it doesn't understand the java.net.preferIPv6Addresses=system property)
Some stylistic javadoc changes:
```suggestion
     * Resolve the address and see if Java and the OS return an IPv6 or IPv4 one, then let Netty know
     * accordingly (as it doesn't understand the {@code java.net.preferIPv6Addresses=system} property).
```

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +     * Checks if an address is an IPv6 one or an IPv4 one, then lets netty know accordingly and returns the result
Some stylistic javadoc changes:
```suggestion
     * Checks if an address is an IPv6 one or an IPv4 one, lets Netty know accordingly and returns the result.
```

2022-02-26 14:17 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +     * @return the client's local IP address or null if unable
Some stylistic javadoc changes:
```suggestion
     * @return the client's local IP address or {@code null} if unable to determine it
```

2022-02-26 14:33 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> +     * @author Paint_Ninja
I concur. It's a bit pointless if we have the git logs to track contributions.

2022-06-05 15:02 UTC, TheCurle commented on src/main/java/net/minecraftforge/network/DualStackUtils.java
> + */
Old style license, please update to SPDX header

2022-07-17 14:26 UTC, merged