Add network filter for ID-limited vanilla MobEffect packets
MinecraftForge/MinecraftForge pull request #8380
Opened 2022-01-10 10:50 UTC by diesieben07

`ClientboundUpdateMobEffectPacket` and `ClientboundRemoveMobEffectPacket` use `writeByte` for the MobEffect ID and are thus limiting the ID range to 0-255. This adds a network filter to use a custom network channel instead which does not limit the ID range.
A test mod is included which registers 255 MobEffects that can be used to test the effectiveness of this filter. Without the filter, effects with an ID above 255 do not get sent to the client correctly.

2022-02-16 03:38 UTC, ChampionAsh5357 requested changes
Although this removes the limit for packet sending, it will still need to be patched in all other entities and usecases as otherwise the data stored will still be defaulted to the original 255.

However, that's just something for the next PR, this looks fine besides from a few text changes.

2022-02-16 03:38 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/ManyMobEffectsTest.java
> +                public void applyEffectTick(LivingEntity p_19467_, int p_19468_)
Parameters should be given names instead of left as srg.

2022-02-16 03:38 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/ManyMobEffectsTest.java
> +                public boolean isDurationEffectTick(int p_19455_, int p_19456_)
Parameters should be given names instead of left as srg.

2022-02-16 03:38 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/ManyMobEffectsTest.java
> +            MOB_EFFECTS.register("effect_" + i, () -> new MobEffect(MobEffectCategory.NEUTRAL, 0)
I would choose a different color mainly just to show particle effects on other mobs for an easy way that the effect was applied successfully.

2022-02-26 22:01 UTC, diesieben07 commented
I've updated the PR to add patches for the places that store the byte-ID in NBT as well.

2022-03-05 14:51 UTC, ChampionAsh5357 approved these changes

2022-03-05 19:32 UTC, diesieben07 commented
Updated to 1.18.2, removed custom packet because vanilla packet now transmits VarInt.

2022-03-06 00:01 UTC, sciwhiz12 requested changes
Please update the license headers in the following file(s):
- `src/test/java/net/minecraftforge/debug/ManyMobEffectsTest.java`

2022-03-06 13:49 UTC, ChampionAsh5357 approved these changes

2022-03-06 14:11 UTC, sciwhiz12 approved these changes

2022-03-22 06:10 UTC, merged