Introduce an attribute for step height
MinecraftForge/MinecraftForge pull request #8389
Opened 2022-01-13 05:47 UTC by williewillus

Very similar to the reach distance attribute. Basically this is a primitive field modders like to tweak a lot, and it's tricky to make sure you apply/remove things at the right time lest you get into a bad state. Perfect use for attributes, something Mojang chronically forgets exists.

Adds the new attribute, and new method that queries the combined old field + attribute value. Writes to the old field are kept while all reads of the old field are redirected to the new method.

Test: https://gfycat.com/compassionatehonoredlhasaapso
I show what happens with three helmets, with +1, +2, and +5 step height. Note that the default player step height is 0.6, so with the +1 helmet I can step up 1.6 blocks and clear the grass + slab.

2022-01-14 00:47 UTC, Random832 commented
If multiple mods use this with the design intent of an item that grants "step assist" [+0.4 or perhaps +0.5], will these interact in a way that lets you use more than one and cause the player to be able to step up multiple blocks? Is there a way for modders to determine whether their modifier applies if another one is already in effect [maybe some sort of extension to attribute modifiers, and possibly determine what order the modifiers are applied in since any such logic will be sensitive to this]

2022-01-14 01:42 UTC, williewillus commented
> will these interact in a way that lets you use more than one and cause the player to be able to step up multiple blocks

yes, that's the point of using the attribute system over the old way, where mods just clobber each other writing to the same field

> Is there a way for modders to determine whether their modifier applies if another one is already in effect [maybe some sort of extension to attribute modifiers, and possibly determine what order the modifiers are applied in since any such logic will be sensitive to this]

Outside of what methods vanilla makes available, no, but as you noted this is more a general feature request for the attribute system than a specific thing this diff needs to address

2022-01-17 14:31 UTC, diesieben07 commented
A possible suggestion:
- Introduce `IForgeLivingEntity#onAttributeModified` and call it from `AttributeMap#onAttributeModified` (patch `AttributeMap` to store the `LivingEntity` optionally)
- From `onAttributeModified` set `maxUpStep` according to the attribute value. Then all the patches could be saved.

Not sure if this is really viable, but it sounds like a better solution in my head.

2022-01-17 17:52 UTC, williewillus commented
I'm not sure what you mean -- all the patches in this PR are for vanilla code to read the attribute instead of the old field. I don't see a way to avoid them since redirecting reads of that field is the purpose of the PR. Writing to the old field by vanilla code is still fine (but discouraged).

2022-01-17 22:20 UTC, diesieben07 commented
If you keep the field in sync with the attribute then you don't need to patch the reads.

2022-01-26 03:24 UTC, williewillus commented
Then you need to patch all the writes, of which there's many as well.

2022-03-27 02:40 UTC, sciwhiz12 requested changes
Locally updating the PR and testing shows that it works as expected. 

However, I do have a concern with how the attribute is expressed right now: because the attribute is merely added to the default step height (`maxUpStep`) of the entity, the base value of the attribute is 0 rather than the intuitive value of whatever the entity's `maxUpStep` is.

We should find a solution so the attribute's base value is correctly synchronized with the entity's `maxUpStep` (such that, for example, checking the player's base attribute value correctly reports `0.5`). An alternative is to rename the attribute to something like `step_height_addition` to correctly reflect that it merely adds to the existing step height rather than representing what it actually is.

2022-03-27 02:40 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
> +    }
Formatting: braces on newlines.
```suggestion
    default float getStepHeight()
    {
        var vanillaStep = self().maxUpStep;
        if (self() instanceof LivingEntity living)
        {
            return (float) (vanillaStep + living.getAttributeValue(ForgeMod.STEP_HEIGHT.get()));
        } else
        {
            return vanillaStep;
        }
    }
```

2022-03-27 02:40 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/extensions/IForgeEntity.java
> +     *  (if this Entity is a {@link LivingEntity}).
Suggestion for improving the javadocs:
```suggestion
     * {@return the height in blocks that the Entity can step up without needing to jump} This is the sum of 
     * the entity's {@link Entity#maxUpStep} and the value of the of the 
     * {@link net.minecraftforge.common.ForgeMod#STEP_HEIGHT} attribute (if this is a {@link LivingEntity}).
```

2022-03-29 03:59 UTC, williewillus commented
Sure, I can rename it to have `addition` in the name. I think trying to shoehorn vanilla's defaults in to the attribute base value isn't worth the trouble.

2022-03-29 13:43 UTC, Alpvax commented
I personally would prefer to have it as the entire step height, rather than an addition. Otherwise there is no way to easily double the height, you have to check what the base value is and add it into any calculations you perform.
I haven't looked into the source though, so maybe that is not reasonable to maintain.

2022-05-03 17:01 UTC, TheCurle approved these changes
Seems like this is a relatively easy to maintain addition that will save on a lot of unnecessary adjustments to the same field, 

Concerns about requiring calculations to be performed on the addition value rather than absolute are reciprocated, but in the absence of collaboration, i think we can pull this now.

Thanks for the contribution, williewillus.

2022-05-03 17:01 UTC, merged