Fix long keybinds making shorter ones unreadable
MinecraftForge/MinecraftForge pull request #8437
Opened 2022-01-29 20:48 UTC by sekwah41

In mods such as JEI at the default scaling value sometimes their translation strings can be too long making the text unreadable for other mods.
![image](https://user-images.githubusercontent.com/3209834/151677047-376dcfd9-420a-4810-983d-4351102cb9ba.png)

![image](https://user-images.githubusercontent.com/3209834/151676930-4c792988-3aa4-4ef6-af5d-66391888b5a4.png)

Fix
![image](https://user-images.githubusercontent.com/3209834/151676967-a63c682a-396b-4548-802b-c30e6018dbe5.png)

Just adding a max limit to how far they can offset so only mods with long names are affected.

I was considering making it change the text to ... but that would cause issues where you are right at the border and want another symbol, so decided this was probably better.

2022-02-13 12:11 UTC, sciwhiz12 requested changes
This works fine, though I wonder how complicated it would be to implement other solutions. 

For example, splitting the keybind name across multiple lines (whether in `KeyBindsList` automatically or by the mod manually in its language file or something similar), or adding a tooltip when hovering over a keybind's name to show the full name if it is clipped (the text width exceeding the 175px limit).

2022-02-13 12:11 UTC, sciwhiz12 commented on patches/minecraft/net/minecraft/client/gui/screens/controls/KeyBindsList.java.patch
> ++         }
Please include a Forge comment marker (`// FORGE: ...`) explaining why this change is in place, for future maintainability.

Also, this is better placed after the `for`-loop, to check and set the field's value once after all keybinds have been processed rather than checking each time.

2022-02-13 16:34 UTC, Shadows-of-Fire commented
Good catch, we don't want to have longer names breaking the whole gui.  Though we probably want to make that full name visible somehow...

A solution adding a hovered tooltip or a scrollable name when hovered should both be viable, though the former is much easier to do.

2022-02-13 17:10 UTC, sekwah41 commented on patches/minecraft/net/minecraft/client/gui/screens/controls/KeyBindsList.java.patch
> ++         }
Fair point I'll add that when I get a moment in the next few days.

2022-02-13 17:12 UTC, sekwah41 commented
@Shadows-of-Fire I can take a look at multi lining or a hover UI when I'm back as I'm on a break. multi lining would probably make most sense otherwise you have hover then multi line.

2022-08-27 18:35 UTC, sciwhiz12 commented
Hello! @sekwah41, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.19.2 (or leave an explanation why this PR's changes are not applicable to 1.19.2). If we do not hear back from you after some time, this PR will be closed for inactivity.

If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference.
Thank you for your contributions. 👋

2022-08-30 10:25 UTC, sekwah41 commented
Ah sorry I've been quite busy. I'll add it to the list to get to sometime this or next week hopefully. It shouldn't take much changing.

2022-09-10 17:14 UTC, sekwah41 commented
Ill make a new pr with these changes for 1.19 but backport it to this too.

2022-09-10 17:39 UTC, sekwah41 commented
![image](https://user-images.githubusercontent.com/3209834/189495319-0db15c4f-1462-419e-b231-1ec6c1258666.png)

2022-09-10 17:41 UTC, sekwah41 commented
Switched over to forcefully shorten the string rather than shot it behind the button. Can revert it if that is preferred to just spill behind the button if its too long.

I was planning to possibly make it so it shows a tooltip when you hover.

2022-09-10 17:47 UTC, sekwah41 commented
Ill push the changes and other parts to fix it now

2022-09-10 18:06 UTC, sekwah41 commented
ignore the fact my branch says 1.18, I've force pushed 1.19 to it on my end so its actually the right one

2023-06-23 03:00 UTC, sekwah41 commented
Not sure if this is still an issue or not though I am going to leave this or someone else to handle as I've updated it a few times.

I know none of the mods I have atm at least cause this issue.

2023-07-17 23:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8437) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=8437) it.</sub>

2023-07-19 22:55 UTC, closed without merging