Load Modded Dimensions on Dedicated Server Start (#8552)
MinecraftForge/MinecraftForge pull request #8555
Opened 2022-04-06 08:13 UTC by Wyn-Price

As fair as I can tell, `Dimension` and `DimensionType` use only the vanilla entries when starting a world on a dedicated server. This makes sense from a vanilla standpoint, as the datapack folder is inside the world folder, so if there is no world, there is no datapacks to load. However this excludes all modded dimension types/dimensions which are loaded in "datapacks" outside the world/datapacks folder.  
 - DimensionTypes can be registered immediately
 - Dimensions need to be registered later, as they are registered to a local variable registry before the main registry. 

If the loading of a modded dimensions/dimension type fails, I've logged a warning to the console.

Note that this code should only run on dedicated servers. The checks for `registryAccess.get() == null` or `registryResouceAccess.get() == null` do this, as they're only ever set on dedicated servers.

I've tested with the `server_world_creation_test` mod, which has a custom dimension, dimension type, and noise settings (noise settings is to confirm that the other registries load datapacks)

2022-04-14 17:41 UTC, sciwhiz12 requested changes
I've not tested this PR yet (and my investigation through the code is stalled a bit since I have little knowledge of the world loading system). 

However, testing the code from the dropped patch (which I mentioned in the linked issue) shows that it works as expected. Is there a reason why that patch was not simply re-added by this PR?

If not, then please port over the patch instead as a simpler test. You may choose to keep or discard the test mod, but note that the issue can also be replicated with the `dimension_seed_test`'s dimensions.

<details>
<summary>Mapped code of the dropped patch, for convenience</summary>

<p>

```java
// Forge: Deserialize the WorldGenSettings to ensure modded dims are loaded on first server load. Vanilla behaviour only loads from the server.properties and deserializes only after the 2nd server load.
worldgensettings = WorldGenSettings.CODEC.encodeStart(RegistryOps.create(NbtOps.INSTANCE, registryaccess$writable), worldgensettings).flatMap(nbt -> WorldGenSettings.CODEC.parse(dynamicops, nbt)).getOrThrow(false, errorMsg -> {});
```

</p>

</details>

---

Please remove the issue number from your title and amend your description to include the phrase `fixes #8552` or `closes #8552`, so the issue is closed when this PR is merged.

If you move to porting the patch over instead of your PR's additions, please mark the relevant review comments as resolved.

2022-04-14 17:41 UTC, sciwhiz12 commented on src/test/resources/META-INF/mods.toml
> -
Please keep this blank line above the comment.

2022-04-14 17:41 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/world/ServerWorldCreationTest.java
> +    public ServerWorldCreationTest(){
Formatting: braces on newlines.
```suggestion
    public ServerWorldCreationTest(
    {
```

2022-04-14 17:41 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/world/ServerWorldCreationTest.java
> +public class ServerWorldCreationTest {
Please provide a javadoc for this class which explains what feature this tests, how to test it, and what the expected results are from said test.

Also, formatting: braces on newlines.
```suggestion
public class ServerWorldCreationTest
{
```

2022-04-14 17:41 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/world/ServerWorldCreationTest.java
> +    private static final Logger LOGGER = LogManager.getLogger(MODID);
As this logger is unused, please remove it and any unused imports.

2022-04-14 17:41 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/world/ServerWorldCreationTest.java
> + * Minecraft Forge - Forge Development LLC
Outdated license header, please update to the latest commit of your base branch and run the `updateLicenses`/`licenseFormat` task.

2022-04-14 17:41 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +import net.minecraft.resources.*;
Please avoid the use of wildcard imports.

2022-04-14 17:41 UTC, sciwhiz12 commented on src/main/resources/META-INF/accesstransformer.cfg
> +public net.minecraft.resources.RegistryLoader <init>(Lnet/minecraft/resources/RegistryResourceAccess;)V # <init>
Please run the `checkATs` task to correct the comment of this entry and remove the trailing newline.

2022-04-14 17:41 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +    private static final ThreadLocal<RegistryResourceAccess> registryResouceAccess = new ThreadLocal<>();
Typo in field name; missing a `r` in `Resource`.
```suggestion
    private static final ThreadLocal<RegistryResourceAccess> registryResourceAccess = new ThreadLocal<>();
```

2022-04-14 17:41 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +    public static RegistryAccess.Writable createAndCacheWritable(ResourceManager manager) {
Formatting: braces on newlines.
```suggestion
    public static RegistryAccess.Writable createAndCacheWritable(ResourceManager manager)
    {
```

2022-04-14 17:41 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +    public static void registerDefaultDimensions(WritableRegistry<LevelStem> writableregistry) {
Formatting: braces on newlines.
```suggestion
    public static void registerDefaultDimensions(WritableRegistry<LevelStem> writableregistry)
    {
```

2022-04-14 17:41 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +        if(registryAccess.get() == null || registryResouceAccess.get() == null) {
Formatting: space before an `if`-expression's opening parenthesis, and braces on newlines.
```suggestion
        if (registryAccess.get() == null || registryResouceAccess.get() == null)
        {
```

2022-04-16 03:36 UTC, Wyn-Price commented
The original intent was to "inject" modded dimensions into the world gen settings. If the writing/parsing way works and is preferred, I can modify this PR to do that, or somebody can create a new PR. I admit, it is a much cleaner looking solution. 

The point of the test mod was to ensure that dim types, dims, and everything else (tested with noise settings) is also loaded correctly.

2022-04-16 13:51 UTC, sciwhiz12 approved these changes

2022-04-17 21:41 UTC, merged