Deprecate alwaysSetupTerrainOffThread option
MinecraftForge/MinecraftForge pull request #8565
Opened 2022-04-12 05:31 UTC by williewillus

It is wholly superseded by vanilla's option. The config field is kept in case anyone is reading it.

2022-04-12 06:04 UTC, sciwhiz12 requested changes
Should we modify the config comment to reflect its obsolescence by the vanilla config setting and removal in a future version? 
What about keeping the config setting working for now (modifying the patch as needed) so it still works as users/modpack developers expect it should, and removing it completely in a future version?

2022-04-12 06:04 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeConfig.java
> +        @Deprecated(forRemoval = true) // Superseded by vanilla option
Please specify the version through `since`:
```suggestion
        @Deprecated(forRemoval = true, since = "1.18.2") // Superseded by vanilla option
```

2022-04-12 06:24 UTC, williewillus commented
> What about keeping the config setting working for now (modifying the patch as needed) so it still works as users/modpack developers expect it should

if we wanted that, we'd just leave the current patch in place

2022-05-03 17:41 UTC, TheCurle commented
I concur. This option suddenly breaking with no explanation (from an end-user's perspective) is an unacceptable change.

This change has been put on the changelist for 1.19, and i'm going to close this PR.

2022-05-03 17:41 UTC, closed without merging