[1.18] Add callback after a BlockState was changed
MinecraftForge/MinecraftForge pull request #8617
Opened 2022-05-08 20:16 UTC by XFactHD

This PR adds a callback after a blocks `BlockState` is changed in the world. The method is very similar to `BlockBehaviour#onPlace()` (which is called on the new `BlockState`) with two significant differences:

1. The new method is also called on the client side, while `BlockBehaviour#onPlace()` is only called on the server side
2. The new method is called after neighboring blocks are also updated, which allows taking changes to neighboring blocks into account

`BlockBehaviour#onRemove()` is not entirely comparable to the new method because `BlockBehaviour#onRemove()` is called on the old `BlockState`. Apart from that, both of the above restrictions also apply to that method.

The added method intentionally takes a `LevelReader` instead of a `Level` because it is intended to be used for read-only accesses, mainly because it doesn't include any guards against infinite recursion.

My usecase for this is to update a client-only occlusion cache when blockstates change. This works fine for most blocks when a neighbor changes (handled through `Block#updateShape()`), but with that approach some blocks need to have the re-calculation of that cache deferred to the end of the current tick because the new `BlockState` is placed into the world after `Block#updateShape()` returns (this is the case for any blocks that use said method for it's intended purpose, like walls and fences) and for some blocks this approach doesn't work at all because there is no way to catch a block update on the client side (this is the case for "self-modifying" blocks like doors and trapdoors).

2022-05-28 02:08 UTC, sciwhiz12 requested changes
This looks solid and the test works fine (after some mishaps with pistons and the `PistonEventTest`); I just have a few formatting notes.

2022-05-28 02:08 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/block/BlockStateChangeTest.java
> +import net.minecraft.world.item.*;
Please avoid the use of wildcard imports. (There's another one down the list.)

2022-05-28 02:08 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/block/BlockStateChangeTest.java
> +public class BlockStateChangeTest
Please provide a javadoc for this class which explains what feature this tests, how to test it, and what the expected results are from said test.

2022-05-28 02:08 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
> +
The blank space can be omitted.
```suggestion
```

2022-05-28 22:12 UTC, sciwhiz12 approved these changes

2022-05-31 18:17 UTC, LexManos commented
Discussed on discord, this hook is not needed as the existing Block.updateIndirectNeighbourShapes should suffice.

2022-06-27 03:29 UTC, sciwhiz12 commented
Reopening upon request of PR author, see #8686.

2022-07-03 00:28 UTC, sciwhiz12 approved these changes
1.19 PR has been merged.

2022-07-09 09:19 UTC, merged