Add ItemStack context to Enchantment#getDamageBonus
MinecraftForge/MinecraftForge pull request #8635
Opened 2022-05-28 14:38 UTC by diesieben07

This came up as a request on Discord and the patch is fairly small.

2022-05-28 23:09 UTC, sciwhiz12 requested changes
Looks fine to me, just needs some tiny formatting fixes.

2022-05-28 23:09 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/extensions/IForgeEnchantment.java
> +
Formatting: the empty line should be removed.

2022-05-28 23:09 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/extensions/IForgeEnchantment.java
> +
Formatting: the empty line should be removed.

2022-05-29 18:07 UTC, sciwhiz12 approved these changes

2022-05-30 20:07 UTC, Shadows-of-Fire commented
May want to patch an `@Deprecated` onto the non-contextual method.

2022-05-31 17:53 UTC, LexManos commented
Simple enough, once the deprecation marker is added feel free  to pull.

2022-06-01 07:20 UTC, diesieben07 commented
Added the deprecation notice

2022-06-01 16:19 UTC, merged