Improve TagsUpdatedEvent
MinecraftForge/MinecraftForge pull request #8636
Opened 2022-05-28 15:41 UTC by diesieben07

- Add UpdateCause information. This tells the user what caused the event.
- Add hint for when static (shared in SP) data should be refreshed. This is now used in Forge to update the burn time map, which previously would refresh twice in SP.

2022-05-28 23:04 UTC, sciwhiz12 requested changes

2022-05-28 23:04 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/event/TagsUpdatedEvent.java
> +
Formatting: empty lines should be removed.

2022-05-28 23:04 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/event/TagsUpdatedEvent.java
>       }
Since you're already modifying the constructor, could you please correct the indentation from 5 spaces to 4 spaces?

2022-05-29 18:07 UTC, sciwhiz12 approved these changes

2022-05-29 21:17 UTC, Technici4n approved these changes

2022-05-31 18:03 UTC, merged