Add SweepHitBoxEvent to allow modification to the hit box of sweeping sword items
MinecraftForge/MinecraftForge pull request #8669
Opened 2022-06-06 23:23 UTC by lcy0x1

This is not yet tested

2022-06-06 23:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8669) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8669) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=8669) it.</sub>

2022-06-07 07:26 UTC, diesieben07 requested changes

2022-06-07 07:26 UTC, diesieben07 commented on patches/minecraft/net/minecraft/world/item/ItemStack.java.patch
> ++
Why is this in a patch and not in the `IForgeItemStack` method?

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/PlayerItemStackEvent.java
> +package net.minecraftforge.event.item;
Missing license header.

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/PlayerItemStackEvent.java
> +	public ItemStack getStack(){
Formatting: braces on new lines, missing space before brace.

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/PlayerItemStackEvent.java
> +public class PlayerItemStackEvent extends PlayerEvent {
This class should be abstract.

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/SweepHitBoxEvent.java
> +package net.minecraftforge.event.item;
Missing license header

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/SweepHitBoxEvent.java
> +public class SweepHitBoxEvent extends PlayerItemStackEvent {
Formatting in this whole class: Braces on new lines.

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/SweepHitBoxEvent.java
> +	 * get the attacked entity
Use `@return` instead.
```suggestion
	 * @return the entity being attacked
```

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/SweepHitBoxEvent.java
> +	 * get the original hit box provided by the Item
Use `@return` instead.
```suggestion
	 * @return the original hitbox as given by the item
```

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/SweepHitBoxEvent.java
> +	 * get modified hit box
Use `@return` instead.

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/SweepHitBoxEvent.java
> +	 * modify the hit box
This Javadoc is bad.
```suggestion
	 * Set the hitbox.
```

2022-06-07 07:26 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/SweepHitBoxEvent.java
> +	 * inflate the hit box
This Javadoc is bad.
```suggestion
	 * Inflates the hitbox by the specified amount.
	 * @see AABB#inflate
```

2022-06-07 07:58 UTC, diesieben07 requested changes

2022-06-07 07:58 UTC, diesieben07 commented on src/main/java/net/minecraftforge/event/item/SweepHitBoxEvent.java
> +	 * @return get modified hit box
`@return` describes what is returned, not what happens. So it would be `@return the modified hitbox`

2022-06-07 08:11 UTC, diesieben07 approved these changes

2022-08-07 23:42 UTC, Shadows-of-Fire commented
Would this be better implemented as a `SweepHitEvent` (similar to `CriticalHitEvent`) that allowed you to force, cancel, or modify the entire sweep attack, rather than just the hitbox as proposed?

2022-10-07 14:05 UTC, Matyrobbrt commented
Hello! @lcy0x1, please leave a comment whether you wish to continue this PR and update it to the latest active version of 1.19.2 (or leave an explanation why this PR's changes are not applicable to 1.19.2). If we do not hear back from you after some time, this PR will be closed for inactivity.

If anyone else wishes to continue the work of this PR, please create a PR with a link to this PR for reference.
Thank you for your contributions. 👋

2022-10-07 17:46 UTC, lcy0x1 commented
I would still love to see this change, but I’m busy recently, so It’s fine to close it and I will reopen it when I have time to continue this work.

2022-10-12 09:31 UTC, sciwhiz12 commented
Please close this PR yourself so you can reopen it yourself when you are ready to continue this. (If a maintainer such as myself closes a PR, the PR author cannot reopen it; only the maintainer can reopen such a PR.) 

If we do not hear back in a while, we will close this PR and you can create a new PR in the future for 1.19 once you are ready to do so.

2022-10-12 18:39 UTC, closed without merging