Update door datagen
MinecraftForge/MinecraftForge pull request #8687
Opened 2022-06-08 18:55 UTC by ferriarnus

Updated door data generators to 1.19 (since someone mentioned them in forgecord). 

I also checked the wall. The check does fail, but this seems to be because the checker can not handle that the parameter order is different. I did not touch that part, since it seems to not be my place to change.

P.S. : I also have "fixed" the mods.toml for dev, should I push it?

2022-06-09 08:55 UTC, Minecraftschurli approved these changes

2022-06-17 19:32 UTC, AnonymousHacker1279 approved these changes

2022-06-17 19:38 UTC, SizableShrimp requested changes

2022-06-17 19:38 UTC, SizableShrimp commented on src/main/java/net/minecraftforge/client/model/generators/BlockStateProvider.java
> +            return ConfiguredModel.builder().modelFile(state.getValue(DoorBlock.HALF) == DoubleBlockHalf.LOWER ? (right ? ( open ? bottomRightOpen : bottomRight ) : ( open ? bottomLeftOpen : bottomLe
This line is way too complex. It should instead be nested ifs that store to a variable or something.

2022-06-17 19:38 UTC, SizableShrimp commented on src/main/java/net/minecraftforge/client/model/generators/BlockStateProvider.java
> +    public void doorBlock(DoorBlock block, ModelFile bottomLeft, ModelFile bottomLeftOpen , ModelFile bottomRight, ModelFile bottomRightOpen, ModelFile topLeft, ModelFile topLeftOpen, ModelFile topRi
Extra space here before a comma that shouldn't be

2022-06-17 19:38 UTC, SizableShrimp commented on src/test/java/net/minecraftforge/debug/DataGeneratorTest.java
> +            // TODO 1.19: fix fenceBlock, wall and co -SS
it's still wallBlock so shouldn't be changed from the method name in the comment.
Additionally, would it be possible for you to look into these other cases and fix them at the same time? Would be a lot nicer all in one PR

2022-06-29 11:31 UTC, ferriarnus commented
Unfortunately, due to both messing up a rebase and my time running out, I won't be able to finish this for now. The door part works, however, the wall verification fails during the datagen test, while it is correct. I did not see a clean way to solve this, which is why it isn't done yet. I will close the PR for now, so someone else can pick it up instead of waiting for me. If it is not yet done by the time I'm back, I will pick it up again.

2022-06-29 11:31 UTC, closed without merging