Closes #8689
MinecraftForge/MinecraftForge pull request #8699
Opened 2022-06-09 04:28 UTC by Shadows-of-Fire

In 1.19 mojang added `ServerGamePacketListenerImpl.MAX_INTERACTION_DISTANCE` and added checks against it that need to be removed to support extended reach/range.  This PR removes the checks and deprecates the field.

2022-06-09 10:52 UTC, sciwhiz12 requested changes
Tested that it fixes the issue. Just need a small change to the added deprecation.

---

Please rename this PR to have a title fitting its contents, and please add `fixes #8689` to the PR description so GitHub links this PR to the issue.

2022-06-09 10:52 UTC, sciwhiz12 commented on patches/minecraft/net/minecraft/server/network/ServerGamePacketListenerImpl.java.patch
> ++   @Deprecated // Forge: See Reach Distance / Attack Range attributes.
This should be a javadoc comment with (fully-qualified) references to the attributes in `ForgeMod`.

2022-06-09 19:04 UTC, Shadows-of-Fire commented
PR and comment updated.

2022-06-13 04:15 UTC, sciwhiz12 approved these changes

2022-06-13 16:33 UTC, merged