[1.19.x] Add CommandBuildContext to Register Command Events
MinecraftForge/MinecraftForge pull request #8716
Opened 2022-06-10 15:15 UTC by ChampionAsh5357

This expands `RegisterCommandsEvent` and `RegisterClientCommandsEvent` to accept a `CommandBuildContext` for holder lookups.

2022-06-11 15:04 UTC, sciwhiz12 requested changes

2022-06-11 15:04 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/event/RegisterClientCommandsEvent.java
> +     * @return the context to build the commands for
This should use an inline `{@return}` tag:
```suggestion
     * {@return the context to build the commands for}
```

2022-06-11 15:04 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/event/RegisterClientCommandsEvent.java
> +    public CommandBuildContext getContext()
Could it be `getBuildContext()` instead?

2022-06-11 15:04 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/event/RegisterCommandsEvent.java
> +    public CommandBuildContext getContext()
Could it be `getBuildContext()` instead? Also, could copy over the javadocs from the client commands event into here as well.

2022-06-12 21:34 UTC, pupnewfster approved these changes

2022-06-12 22:36 UTC, merged