[1.19.x] [Breaking] Return correct BiomeSpecialEffectsBuilder type in BiomeInfo$Builder
MinecraftForge/MinecraftForge pull request #8781
Opened 2022-06-21 22:44 UTC by Commoble

One of the intentions of the BiomeModifier api was to provide read access to the current and modified state of a biome to a BiomeModifier, so that the BiomeModifier can read the state to determine whether to make further modifications.

To facilitate this, forge extensions of vanilla's builders for climate and client special effects were used, to provide read access to the builders' fields (the vanilla builders have setters but no getters), in a similar manner to the generation and mob spawn builder extensions originally created for the BiomeLoadingEvent.

However, due to a clerical error, the getter for the special effects builder provides the vanilla builder type, not the forge extension. The actual implementation is still the forge extension, but mods have to cast to the forge builder to use its getters. This PR fixes the API to return the correct builder type.

This is technically a binary-breaking change, but since the forge effects builder extends the vanilla builder, the break would only affect mods that extended BiomeInfo$Builder themselves and overrode getEffects(), which isn't expected to be a large population.

2022-06-22 01:38 UTC, pupnewfster commented on src/main/java/net/minecraftforge/common/world/ModifiableBiomeInfo.java
> +            @Deprecated(forRemoval=true)
This should have a since 1.19 in the annotation

2022-06-26 01:56 UTC, sciwhiz12 requested changes

2022-06-26 01:56 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/world/ModifiableBiomeInfo.java
> +            	return effects;
Formatting: 4 spaces for indentation, not tabs
```suggestion
                return effects;
```

2022-06-26 16:57 UTC, sciwhiz12 approved these changes

2022-06-28 04:01 UTC, merged