Add API for tab list header/footer
MinecraftForge/MinecraftForge pull request #8803
Opened 2022-06-28 02:13 UTC by zml2008

![image](https://user-images.githubusercontent.com/629092/176076267-e69689b8-98f0-4e60-a5e0-b64c73ecd352.png)

With the existing state of affairs, any single mod could update both tab list header and footer at the same time, just by sending the existing vanilla packet. However, if one mod wants to set a header, and another mod wants to set a footer, they would need some shared way of tracking that state.

This PR adds such a way of tracking state, with wrapper API on ServerPlayer to hold the last sent header and footer.

I don't do anything to step anyone from constructing a tab list packet directly -- is that worth doing, by deprecating the constructor or something?

## testing steps

I did up a quick command to test this API:

```java
    @SubscribeEvent
    public void registerCommands(final RegisterCommandsEvent event) {
      event.getDispatcher().register(literal("tablist")
        .then(literal("header").then(argument("value", ComponentArgument.textComponent()).executes(ctx -> {
          ctx.getSource().getPlayerOrException().setTabListHeader(ComponentArgument.getComponent(ctx, "value"));
          return Command.SINGLE_SUCCESS;
        })))
        .then(literal("footer").then(argument("value", ComponentArgument.textComponent()).executes(ctx -> {
          ctx.getSource().getPlayerOrException().setTabListFooter(ComponentArgument.getComponent(ctx, "value"));
          return Command.SINGLE_SUCCESS;
        })))
      );
    }
```

This was tested with dev client, connected to dev dedicated server (since the tab list doesn't show up in SP)

Then, I confirmed that:

1. header was maintained while setting footer
2. footer was maintained while setting header
3. After executing `/kill`, that executing either command wouldn't clear the other's value on the tab list

2022-07-11 05:34 UTC, OrionDevelopment approved these changes
Reading into this, is it not better to make this an event instead of a single field where last comes, last wins rules the game?
This way the event could potentially make this automatically multi-line with an explicit clear option that people can use?

2022-07-11 05:34 UTC, OrionDevelopment requested changes
Sorry previous comment was supposed to be a request changes.
Not an approve.

2022-07-14 03:50 UTC, zml2008 commented
I'm not clear what exactly an event would be triggered by? There's nothing in the game that changes the header and footer here -- it's only there for use by mods. The fields seem like the least confusing variant of this API for me.

2022-07-17 14:02 UTC, TheCurle commented
Yeah, events are reactionary, and there's nothing to react to here.
This implementation looks perfectly fine to me.

2022-07-17 14:16 UTC, OrionDevelopment commented
> Yeah, events are reactionary, and there's nothing to react to here. This implementation looks perfectly fine to me.

The problem that I see with this, and which is generally a problem which we really try to avoid, is that this is a last comes last serves kind of a deal, where only a single mod can show something and all others be damned?

I would rather see an event here which combined the inputs of all mods together.

2022-07-17 14:18 UTC, sciwhiz12 commented
How would such an event be fired? Whenever a mod attempts to modify the tab list header/footer, fire an event and let all other mods (including the mod itself, potentially) take a stab at the value?

2022-07-17 14:18 UTC, TheCurle commented
COMBINING all the messages is a terrible terrible idea.
It *should* be all or nothing. Otherwise you have long, mismatched, disparate messages being chained one after the other in a visual soup of distracting nothingness.

2022-07-17 16:22 UTC, OrionDevelopment commented
Then this should be configurable by the end user.

I am aware that an event is far from ideal. But also a system where the last mod wins. We have several examples how we deal with these kinds of scenarios, the permission handler is an example.

So I would like to see this configurable by the end user / server owner at least to prevent weirdness from occuring.

2022-07-20 18:06 UTC, LexManos commented
This isn't bad, I just need some justification for it that isn't skeezy microtransactions, which is literally the only thing i've ever seen this feature used for.

2022-07-22 03:51 UTC, zml2008 commented
These fields can be used for server branding (used especially effectively with custom fonts in Vanilla resource packs), and short status information, such as:

- current time
- active world information
- extra information about player count (current/max, # of users truncated from the player list)
- information about current server events

A relatively tasteful example from a server that seems popular (unfortunately overlayed on some spam in the boss bar position):

![image](https://user-images.githubusercontent.com/629092/180358644-8a3b9203-000c-460d-91da-d5e0a4424fc5.png)

2022-07-22 04:01 UTC, merged