[1.19.X] Allow LazyOptional listeners to be weakly registered
MinecraftForge/MinecraftForge pull request #8805
Opened 2022-06-28 18:58 UTC by amadornes

In the current LazyOptional implementation, if BlockEntity A registers a listener on BlockEntity B's LazyOptional, even if BlockEntity A is removed from the world, it won't be evicted from memory, as it's still being referenced by the listener callback held by BlockEntity B. Moreover, even if BlockEntity B's LazyOptional is invalidated, the listeners are still retained in memory and won't be considered for GC until the LazyOptional itself has no references.

This PR addresses both of those issues by adding a new method to `LazyOptional` which allows listeners to be registered via a `WeakReference`, as well as clearing the list of listeners after they have been notified of the LazyOptional's invalidation.

An example usage would look like: `myLazyOptional.addListener(myObject, MyObjectType::callback)` as opposed to the current `myLazyOptional.addListener(myObject::callback)`.

2022-06-29 02:08 UTC, covers1624 commented
This is still quite fragile as if anyone pulls reference to `myObject` into the lambda they supply (probably `this` in most cases), then the weak reference is serving no purpose, as the original method.
```
.addListener(this, (e, l) -> this.clearSomeRandomCache(l))
```

This should be clarified in the docs that you MUST use the instance variable passed back into the lambda instead of grabbing your own. The current docs example with the use of a MethodRef does not cover the semantics of this exact common issue.

```
.addListener(this, (e, l) -> e.clearSomeRandomCache(l))
```

2022-06-29 04:19 UTC, Shadows-of-Fire commented
as discussed on discord, the old method may want to be either deprecated or removed, as otherwise it is unlikely that mod code is updated to use this method

2022-07-11 05:32 UTC, OrionDevelopment requested changes
This needs better documentation.
I agree with @covers1624 That the implementation is weak, pun intended. It is easy to screw up and only provides safe guards.

Is there no other way to clean up the listener lists here? Like clearing them entirely out when getting invalidated?

2023-07-17 23:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8805) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8805) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=8805) it.</sub>

2023-07-22 06:46 UTC, closed without merging