Pass renderType to IForgeBakedModel.useAmbientOcclusion
MinecraftForge/MinecraftForge pull request #8834
Opened 2022-07-08 10:35 UTC by bdew

It would be nice to have RenderType passed to IForgeBakedModel.useAmbientOcclusion so that a model that renders in multiple RenderTypes can have AO in some but not other.

Before the recent rendering rework I had checks for MinecraftForgeClient.getRenderType in useAmbientOcclusion but that's not possible anymore.

2022-07-08 10:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8834) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=8834) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=8834) it.</sub>

2022-07-08 11:15 UTC, OrionDevelopment commented
Please run the check command, especially checkExcs is needed. Since you addede an override to a vanilla method.

2022-07-08 11:56 UTC, bdew commented
I did run checkExcs and it didn't show anything. I don't see a "check" task... anything else i need to check?

2022-07-08 16:15 UTC, marchermans commented
Asked internally no new excs is needed it was a misunderstanding.
Assigning.

2022-07-08 16:16 UTC, OrionDevelopment approved these changes

2022-07-08 16:19 UTC, OrionDevelopment requested changes
Either keep the state only methods, or remove said method and only leave the one with the state and the rendertype.

2022-07-08 16:19 UTC, marchermans commented on patches/minecraft/net/minecraft/client/resources/model/MultiPartBakedModel.java.patch
>  +   }
Leave this method in place. Add the override manually in case this is called already. Preserves compatibility.

2022-07-08 16:19 UTC, marchermans commented on patches/minecraft/net/minecraft/client/resources/model/WeightedBakedModel.java.patch
> -+      return this.f_119542_.useAmbientOcclusion(state);
Leave this method in place. Add the override manually in case this is called already. Preserves compatibility.

2022-07-08 16:19 UTC, marchermans commented on src/main/java/net/minecraftforge/client/model/BakedModelWrapper.java
> -        return originalModel.useAmbientOcclusion(state);
Leave this method in place. Add the override manually in case this is called already. Preserves compatibility.

2022-07-08 21:14 UTC, bdew commented
Changed the patch to leave the original methods in place, is that ok now?

2022-07-09 09:24 UTC, OrionDevelopment approved these changes

2022-07-09 15:20 UTC, merged