Fix packet handling on play messages.
MinecraftForge/MinecraftForge pull request #8875
Opened 2022-07-15 19:31 UTC by OrionDevelopment

This fixes forges own play messages trying to read data from a FriendlyByteBuf in an enqueueWork section after the code-flow execution of the network thread (which owns and frees said FriendlyByteBuf) has already been completed.

Fixes: #8873

2022-07-16 04:01 UTC, sciwhiz12 requested changes

2022-07-16 04:01 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/PlayMessages.java
> +                ((IEntityAdditionalSpawnData) msg.entity).writeSpawnData(spawnDataBuffer);
Since we're already modifying this code, this should be using pattern-matching instanceof.

2022-07-16 04:01 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/PlayMessages.java
> +            else {
Formatting: braces on newlines.
```suggestion
            else
            {
```

2022-07-16 04:01 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/PlayMessages.java
> +            if (count > 0) {
Formatting: braces on newlines.
```suggestion
        private static FriendlyByteBuf readSpawnDataPacket(FriendlyByteBuf buf)
        {
            final int count = buf.readVarInt();
            if (count > 0)
            {
```

2022-07-16 04:01 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/PlayMessages.java
> +                    msg.buf.release();
Perhaps a `try`-`finally` would be better here to ensure the buffer's release, instead of inserting multiple release calls?

2022-07-16 04:01 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/PlayMessages.java
>                      ((IEntityAdditionalSpawnData) e).readSpawnData(msg.buf);
Please also convert this into using pattern-matching `instanceof`.

2022-07-16 04:01 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/network/PlayMessages.java
> +                                 msg.getAdditionalData().release();
This is also a candidate for using a `try`-`finally` to ensure the buffer is released.

2022-07-17 13:54 UTC, TheCurle commented on src/main/java/net/minecraftforge/network/PlayMessages.java
> +            ctx.get().enqueueWork(() ->
I beg you to make this function easier to read.

I legitimately cannot parse the control flow or order of parameters being used here.

Please make things one giant line if it benefits, this ridiculous line splitting is horrendous for the rest of us.

2022-07-17 13:54 UTC, TheCurle commented on src/main/java/net/minecraftforge/network/PlayMessages.java
> +                    if (type == null)
This is a useless check, type cannot be null.

2022-07-22 13:43 UTC, sciwhiz12 approved these changes

2022-07-22 19:08 UTC, merged