Allow registering custom `ColorResolver`s
MinecraftForge/MinecraftForge pull request #8880
Opened 2022-07-16 12:15 UTC by diesieben07

`ColorResolver` is used to create biome-based block coloring. The `BlockAndTintGetter`  given to `BlockColor` cannot directly be used to obtain the biome, it must be done through `ColorResolver`, which will allow the game to implement caching and also apply the selected biome blend. Any ColorResolver instance must be registered for this cache though. This PR adds an event to allow mods to register their own.

2022-07-16 19:18 UTC, OrionDevelopment requested changes

2022-07-16 19:18 UTC, OrionDevelopment commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +    private static ImmutableList<ColorResolver> colorResolvers;
Please move this into its own management class.

2022-07-17 15:52 UTC, OrionDevelopment approved these changes

2022-08-04 08:05 UTC, sciwhiz12 requested changes

2022-08-04 08:05 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/ColorResolverManager.java
> +    public static void registerBlockTintCaches(ClientLevel level, Map<ColorResolver, BlockTintCache> target)
Should this be marked as `@ApiStatus.Internal`? Is there a reason for a mod to call this method?

2022-08-04 08:05 UTC, sciwhiz12 commented on src/test/java/net/minecraftforge/debug/client/CustomColorResolverTest.java
> +public class CustomColorResolverTest
Please provide a javadoc for this class which explains what feature this tests, how to test it, and what the expected results are from said test.

This should also be added to the test sourceset's `mods.toml` for now.

2022-08-04 08:58 UTC, diesieben07 commented on src/main/java/net/minecraftforge/client/ColorResolverManager.java
> +    public static void registerBlockTintCaches(ClientLevel level, Map<ColorResolver, BlockTintCache> target)
My reason for not marking it as internal was for mods that do custom rendering (maybe even something like Optifine) needing to call it.

2022-08-04 09:17 UTC, diesieben07 commented
Test mod without biome blend
![2022-08-04_11 15 50](https://user-images.githubusercontent.com/1915984/182811088-4174dcbd-5cf4-4176-ac7e-027913f64a2c.png)
And with biome blend
![2022-08-04_11 16 06](https://user-images.githubusercontent.com/1915984/182811105-8da7f86a-68a5-4c51-9f09-c1f9b6c3e3dc.png)

2022-08-04 09:41 UTC, sciwhiz12 approved these changes

2022-08-09 09:07 UTC, diesieben07 commented
Updated to 1.19.2

2022-08-09 09:15 UTC, sciwhiz12 approved these changes

2022-08-17 20:51 UTC, merged