[1.19.x] Custom Holderset Types
MinecraftForge/MinecraftForge pull request #8928
Opened 2022-07-31 21:19 UTC by Commoble

This PR adds a serializer registry for custom holderset types that can be used in worldgen jsons and implements several builtin holderset types that mods and datapacks can use.

## What's a Holderset?

An interface that represents collection of registry elements and acts as both a set and an indexable list. Holdersets are how mojang implements the "element, list, or tag" format by which elements can be represented in worldgen jsons:

```json
{
  "a_biome": "desert",
  "some_biomes": ["desert", "swamp", "forest"],
  "biome_tag": "#is_overworld"
}
```

HolderSets use registry codecs and can only be deserialized in contexts that have access to a RegistryAccess/RegistryOps for deserializing with registry context.

The tag holdersets are deceptively tricky to work with; they are mutable and have their contents rebound when tags reload (the other two vanilla holderset types are immutable). The mutability of tag holdersets in conjunction with the need to cache an indexable list of holders makes implementing custom composite holdersets slightly convoluted.

This PR expands the existing holderset codecs to allow a fourth format, a type-dispatched holderset object:

```json
{
   "custom_holderset_type":
  {
    "type": "modid:typename",
    // additional context as needed
  }
}
```

## APIs
* IForgeHolderSet<T>
  * Extension interface patched onto HolderSet, the sole current purpose of which is to allow tag holdersets to invalidate any composite holdersets that "own" them by invalidating IForgeHolderSet's addInvalidationListener method. Custom holderset types composed of other holdersets should also override this method so that they can be notified of tags rebinding.
* ICustomHolderSet<T> extends HolderSet<T>
  * An interface which all custom holderset types must implement. This provides a HolderSetType getter, which is necessary for implementing the type dispatcher and ensures holdersets are serializable when datagenerating datapack registry elements that have holderset fields (such as biome modifiers).
* HolderSetType
  * A registrable holderset serializer type. Mods that implement custom holderset types should register one of these via DeferredRegister for each ICustomHolderSet-implementing class (We can't simply register a holderset codec because the way that vanilla creates their own holderset codec convolutes this slightly).

## Builtin HolderSet Types
In addition to the three vanilla holderset types (singleton, list, and tag), this PR adds five additional holderset types to forge:

### forge:any
This immutable holderset type represents all holders in a given registry. Its holderset interfaces are implemented by delegating to the registry itself as much as possible and does not create any list/set caches. Json format:
```json
{
  "type": "forge:any"
}
```

### forge:and
This mutable composite holderset type represents an intersection of other holdersets. It lazily caches a list and set of its holders as needed and invalidates these caches when tags reload. Json format:
```json
{
  "type": "forge:and",
  "values": [ list of holderset strings, lists, or objects ]
}
```

### forge:or
This mutable composite holderset type represents a union of other holdersets. It lazily caches a list and set of its holders and invalidates these caches when tags reload. Json format:
```json
{
  "type": "forge:or",
  "values": [ list of holderset strings, lists, or objects ]
}
```

### forge:exclusion
This mutable composite holderset type represents all holders present in one holderset but not another holderset. It lazily caches a list and set of its holders and invalidates these caches when tags reload. Json format:
```json
{
  "type": "forge:exclusion",
  "include": holderset string, list, or object
  "exclude": holderset string, list, or object
}
```

### forge:not
This mutable composite holderset type represents all holders not present in another holderset. It lazily caches a list (but not a set) of its holders and invalidates this list when tags reload. Using `exclusion(x,y)` is generally preferable to `and(x, not(y))` as exclusion is able to make smaller caches. Json format:
```json
{
  "type": "forge:not",
  "value": holderset string, list, or object
}
```

## Patches
* HolderSetCodec#create has a forge hook patched into it to wrap the vanilla codec in an Either(dispatch, vanilla) codec. This results in all existing holderset codecs first attempting to read holderset json elements as type-dispatchable objects, then falling back to the vanilla formats if this fails. This uses the ExtraCodecs's Either codec (rather than DFU's Either codec) as ExtraCodecs-Either reports both parse errors if both subcodecs fail (DFU Either only reports the second codec's parse error).
* HolderSet is patched to implement IForgeHolderSet
* HolderSet$Named is patched to override IForgeHolderSet#addInvalidationListener
* HolderSet$Named#bind is patched to invalidate "owning" holdersets when tags rebind

## Test Datapack / Example Usage
The attached datapack provides a biome modifier that uses all eight vanilla/forge holderset formats to add a placed feature to all non-sandy biomes except swamps, cold mountains, and stony peaks:

[custom_holdersets_test.zip](https://github.com/MinecraftForge/MinecraftForge/files/9229714/custom_holdersets_test.zip)

```json
{
	"type": "forge:add_features",
	"features": "forge:red_wool",
	"step": "underground_ores",
	"biomes":
	{
		"type": "forge:exclusion",
		"include":
		{
			"type": "forge:and",
			"values":
			[
				{
					"type": "forge:any"
				},
				{
					"type": "forge:not",
					"value": "#forge:is_sandy"
				}
			]
		},
		"exclude":
		{
			"type": "forge:or",
			"values":
			[
				["swamp", "mangrove_swamp"],
				"stony_peaks",
				{
					"type": "forge:and",
					"values":
					[
						"#is_mountain",
						"#forge:is_cold"
					]
				}
			]
		}
	}
}
```

2022-08-01 00:12 UTC, sciwhiz12 requested changes
Works fine according to the tests. (Also, may be good to use `json5` as the language for the codeblocks in your PR description so the comments don't appear in alarming red.)

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/extensions/IForgeHolderSet.java
> +    default public HolderSet<T> self()
The `self()` method in extension interfaces should be `private`.
```suggestion
    private HolderSet<T> self()
```

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/extensions/IForgeHolderSet.java
> +     * Composite holdersets should use this to add callbacks to each of their component holdersets when constructed.</p>
If this is all a single paragraph, the paragraph tags can be omitted. 

```suggestion
     * Adds a callback to run when this holderset's contents invalidate (i.e. because tags were rebound).
     * The intended usage and use case is with composite holdersets that need to cache sets/list based on other
     * holdersets, which may be mutable (because they are tag-based or themselves composite holdersets).
     * Composite holdersets should use this to add callbacks to each of their component holdersets when constructed.
```

However, if you decide to split the second and third sentences into their own paragraph (which would probably improve readability a bit), then the opening paragraph tag should be moved to the beginning of the second sentence, and a blank space added to improve source readability.

```suggestion
     * Adds a callback to run when this holderset's contents invalidate (i.e. because tags were rebound).
     *
     * <p>The intended usage and use case is with composite holdersets that need to cache sets/list based on other
     * holdersets, which may be mutable (because they are tag-based or themselves composite holdersets).
     * Composite holdersets should use this to add callbacks to each of their component holdersets when constructed.</p>
```

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/HolderSetType.java
> +public interface HolderSetType
The builtin Forge implementations of this interface seem to use this as a functional interface. Would there be a case where this interface would not be implemented as such (i.e. as a lambda or method reference)? If not, might be good to mark this as a `@FunctionalInterface`. If yes, then it should be documented that it can be implemented as a method reference.

Also, Forge naming convention calls for all interfaces to be prefixed with `I`.

```suggestion
@FunctionalInterface
public interface IHolderSetType
```

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/HolderSetType.java
> +    public abstract <T> Codec<? extends ICustomHolderSet<T>> makeCodec(ResourceKey<? extends Registry<T>> registryKey, Codec<Holder<T>> holderCodec, boolean forceList);
Non-private interface member methods do not need to be marked as `public abstract`.
```suggestion
    <T> Codec<? extends ICustomHolderSet<T>> makeCodec(ResourceKey<? extends Registry<T>> registryKey, Codec<Holder<T>> holderCodec, boolean forceList); 
```

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/ICustomHolderSet.java
> +    public abstract HolderSetType type();
Non-private interface member methods do not need to be marked as `public abstract`.
```suggestion
    HolderSetType type();
```

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeMod.java
> +     * Stock holder set type that represents any/all values in a registry. Can be used in a holderset object with { "type": "forge:any" }
The JSON code should be wrapped in a `{@code}` tag. (Same comment for each of the below javadocs.)

```suggestion
     * Stock holder set type that represents any/all values in a registry. Can be used in a holderset object with {@code { "type": "forge:any" }}.
```

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeMod.java
> +     * Stock holder set type that represents an intersection of other holdersets. Can be used in a holderset object with { "type": "forge:or", "values": [list of holdersets] }
This is not an intersection but a union of other holdersets.
```suggestion
     * Stock holder set type that represents a union of other holdersets. Can be used in a holderset object with {@code { "type": "forge:or", "values": [list of holdersets] }}
```

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/ForgeMod.java
> +     * Stock holder set type that represents all values in a registry except those in another given set. Can be used in a holderset object with { "type": "forge:not", "value": holderset }
The javadocs should echo your PR description's recommendation to use the `exclusion` holderset type instead of `and(x, not(y))`.

2022-08-01 00:12 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/ForgeHolderSets.java
> +    private ForgeHolderSets() {} // Organizational class
Should we consider moving these inner classes to a new subpackage as full (outer) classes?

2022-08-02 02:30 UTC, sciwhiz12 requested changes

2022-08-02 02:30 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/holdersets/AndHolderSet.java
> +package net.minecraftforge.registries.holdersets;
Missing license header, please run the `updateLicenses`/`licenseFormat` task.

2022-08-02 02:30 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/holdersets/AnyHolderSet.java
> +package net.minecraftforge.registries.holdersets;
Missing license header, please run the `updateLicenses`/`licenseFormat` task.

2022-08-02 02:30 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/holdersets/CompositeHolderSet.java
> +package net.minecraftforge.registries.holdersets;
Missing license header, please run the `updateLicenses`/`licenseFormat` task.

2022-08-02 02:30 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/holdersets/ExclusionHolderSet.java
> +package net.minecraftforge.registries.holdersets;
Missing license header, please run the `updateLicenses`/`licenseFormat` task.

2022-08-02 02:30 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/holdersets/NotHolderSet.java
> +package net.minecraftforge.registries.holdersets;
Missing license header, please run the `updateLicenses`/`licenseFormat` task.

2022-08-02 02:30 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/registries/holdersets/OrHolderSet.java
> +package net.minecraftforge.registries.holdersets;
Missing license header, please run the `updateLicenses`/`licenseFormat` task.

2022-08-02 03:17 UTC, sciwhiz12 approved these changes

2022-08-05 19:30 UTC, LexManos requested changes
Aa couple small notes. And do we have verification that this is never sent over the network/doesn't break vanilla  networking? I dont think HolderSets are sent over the network. The only thing I can think of is recipes, but I think that's resolved into an ItemStack array.

2022-08-05 19:30 UTC, LexManos commented on src/main/java/net/minecraftforge/common/extensions/IForgeHolderSet.java
> +    private HolderSet<T> self()
Self is only needed if the extension interface's default implementation itself needs to cast itself.

2022-08-05 19:30 UTC, LexManos commented on src/main/java/net/minecraftforge/common/ForgeMod.java
> +    public static final RegistryObject<HolderSetType> EXCLUSION_HOLDER_SET = HOLDER_SET_TYPES.register("exclusion", () -> ExclusionHolderSet::codec);
Remove this, as it is just a `and(A, not(B))` would rather not have this as API.

2022-08-06 02:00 UTC, Commoble commented
Removed forge:exclusion, datapack in original post has been amended to not have this.

Re; network serialization: Vanilla never syncs holdersets, they're not used in any datapack registry network codecs or any reload listeners. For datapack registries in particular, synced datapack registries are serialized without registry context, which would cause any holderset to be serialized as a list of values and decoded as a list of unregistered values, which would probably cause problems in most contexts, however I have refactored the HolderSetCodec patch so that this behavior is used for custom holderset types in addition to vanilla holdersets, for consistency.

2022-08-09 19:24 UTC, LexManos commented
This  all look fine to  me, I couldn't find anywhere in vanilla code where they are serialized over the network so I am pretty sure that this doesn't break anything. Lets give it a try.

2022-08-09 19:25 UTC, merged