Fix Enchantment#doPostHurt and Enchantment#doPostAttack being called twice for players
MinecraftForge/MinecraftForge pull request #8948
Opened 2022-08-08 02:21 UTC by Shadows-of-Fire

Title.  Fixes vanilla bug MC-248272

2022-08-08 13:32 UTC, sciwhiz12 requested changes

2022-08-08 13:32 UTC, sciwhiz12 commented on patches/minecraft/net/minecraft/world/item/enchantment/EnchantmentHelper.java.patch
> ++      if (false && p_44825_ instanceof Player) { // Forge: Fix MC-248272
A simpler patch would be to insert `if (false)` directly above the existing `if` statement. (Same suggestion for the other hunk in the patch.)
```suggestion
+      if (false) // FORGE: Fix MC-248272
       if (p_44825_ instanceof Player) {
```

2022-08-13 20:40 UTC, Shadows-of-Fire commented
@sciwhiz12 patches simplified, probably ready for assignment

2022-08-13 20:49 UTC, sciwhiz12 approved these changes

2022-08-16 20:40 UTC, merged