Add cancellable event firing when Toasts are added (1.19)
MinecraftForge/MinecraftForge pull request #8952
Opened 2022-08-10 02:26 UTC by eerussianguy

This is a 1.19 port of #7821

Cancelling this event just causes nothing to happen, it's a safe operation. In relation to the concerns raised by addTimedToast, that provides extra functionality with relation to auto-hiding, it's not a full-fledged second toast handler that we have to handle separately.

2022-08-10 08:03 UTC, OrionDevelopment requested changes

2022-08-10 08:03 UTC, OrionDevelopment commented on patches/minecraft/net/minecraft/client/gui/components/toasts/ToastComponent.java.patch
> ++      if (net.minecraftforge.common.MinecraftForge.EVENT_BUS.post(event)) return;
Since the event does not have a result, make an event factory in the relevant hooks class which like all the others.

2022-08-10 12:26 UTC, marchermans requested changes

2022-08-10 12:26 UTC, OrionDevelopment commented on patches/minecraft/net/minecraft/client/gui/components/toasts/ToastComponent.java.patch
> ++      this.f_94916_.add(event.getToast());
You are understanding me wrong.
The fired event can not change the toast you passed in.
So it suffices to return a boolean from the hook method, and turn this 4 line patch into a single line patch above the add method.

2022-08-15 00:33 UTC, Shadows-of-Fire approved these changes

2022-08-16 20:48 UTC, merged