[1.19.x] add methods with more context to tree growers
MinecraftForge/MinecraftForge pull request #8956
Opened 2022-08-10 17:58 UTC by Minecraftschurli

This PR adds a method in `AbstractTreeGrower` and `AbstractMegaTreeGrower` that allows for more control and the usage of RegistryAccess in the grower.
This PR is not intending to fix `MC-251744`

2022-08-11 15:17 UTC, eerussianguy commented
Typically forge added methods appear below the rest of the class, and have a `/*** FORGE START ***/` label, but in this case it may not be such a big deal.

2022-08-11 15:37 UTC, Minecraftschurli commented
@eerussianguy it is intentionally placed there so the patch is only one block and one line and not scattered throughout the file

2022-08-29 11:55 UTC, ChampionAsh5357 commented
Clarifying question, why would having the granularity control in the grower be better than using the granular control the block already provides when calling the grower?

2022-08-29 12:30 UTC, Minecraftschurli commented
@ChampionAsh5357 as stated in the PR description it allows access to the registry access which is necessary if you dont register the feature in the built-in registry but instead datagen it (vanilla uses the hardcoded references to the default values)

2022-08-29 13:17 UTC, ChampionAsh5357 requested changes
After talking it over with other triages, there should be markers on the newly added method to indicate why it was added.
Other than that, the PR looks fine.

2022-08-29 13:17 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/world/level/block/grower/AbstractMegaTreeGrower.java.patch
> ++      return m_213566_(random);
Should have `// Forge: ` markers to indicate it is Forge-added.

2022-08-29 13:17 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/world/level/block/grower/AbstractTreeGrower.java.patch
> ++      return m_213888_(random, hasFlowers);
Should have `// Forge: ` markers to indicate it is Forge-added.

2022-09-03 19:20 UTC, ChampionAsh5357 approved these changes

2022-09-03 19:24 UTC, merged