Allow mods to specify shader import namespace
MinecraftForge/MinecraftForge pull request #9021
Opened 2022-09-06 20:52 UTC by FiniteReality

Previously any included shaders would be hardcoded to search using the `minecraft` namespace, limiting options for organisation options for modders. This change allows modders to specify which namespace that their shader imports should be loaded from, by prefixing their import with the desired mod namespace.

To be completely honest, I am not a huge fan of this approach, but it appears to be the least invasive, and also avoids a double-lookup where we attempt to search the mod's namespace before falling back to the `minecraft` namespace.

2022-09-06 20:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9021) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9021) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=9021) it.</sub>

2022-09-07 14:14 UTC, ChampionAsh5357 requested changes

2022-09-07 14:14 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/client/renderer/ShaderInstance.java.patch
> ++                     FileUtil.m_179924_((p_173374_ ? s1 : "shaders/include/") + resourcelocation.m_135815_()));
This could be made into a Forge client hook to reduce the patch size.

2022-09-07 14:14 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/client/rendering/ShaderResourcesTest.java
> +    private static final boolean ENABLED = false;
I believe the convention Forge uses is `ENABLE`.

2022-09-07 14:14 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/client/rendering/ShaderResourcesTest.java
> +        if (!ENABLED)
Test mod will fail on the server. Please fix sideness.

2022-09-07 14:20 UTC, FiniteReality commented on src/test/java/net/minecraftforge/debug/client/rendering/ShaderResourcesTest.java
> +        if (!ENABLED)
Oh right, I didn't check this on the server side -  originally I was using the subscribe annotations but those weren't working so I changed it to manually adding the listeners, and forgot to add the client-side check. My bad!

2022-09-08 11:05 UTC, OrionDevelopment approved these changes

2022-09-08 11:06 UTC, OrionDevelopment commented
@ChampionAsh5357 This is good to go form my end. Anything to add?

2022-09-08 11:45 UTC, ChampionAsh5357 requested changes
Two quick fixes on formatting, but otherwise looks and works fine.

2022-09-08 11:45 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/client/renderer/ShaderInstance.java.patch
> +-
Unnecessary removal

2022-09-08 11:45 UTC, ChampionAsh5357 commented on src/test/resources/assets/shader_resources_test/shaders/include/cubemap_includes.glsl
> +out vec4 fragColor;
New line at end of file.

2022-09-08 14:12 UTC, FiniteReality commented on patches/minecraft/net/minecraft/client/renderer/ShaderInstance.java.patch
> +-
I've added back the empty line - more Eclipse default workspace setting woes that I missed. The removal of the ResourceLocation is still necessary as it's computed earlier for duplicate import checks.

2022-09-08 14:55 UTC, ChampionAsh5357 approved these changes

2022-09-08 15:10 UTC, merged