Add simple block appearance API
MinecraftForge/MinecraftForge pull request #9066
Opened 2022-10-02 16:05 UTC by amadornes

The proposed API allows blocks to report looking like a different block on a given face. This allows blocks with connected textures to seamlessly connect to other blocks that mimic them, such as the covers and facades often used to hide cables, without adding any extra dependencies and special-casing for each mod that adds such blocks.

An API of this style has been requested several times over the years, and has been previously denied due to the impracticality of their implementation and performance implications. However, Forge and Java have both matured plenty since then, making this a trivial addition with a negligible performance impact in the few cases it's used.

*This PR was made on request from Soaryn and the AE2 team.*

2022-10-02 18:41 UTC, OrionDevelopment approved these changes

2022-10-02 21:00 UTC, sciwhiz12 requested changes

2022-10-02 21:00 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/extensions/IForgeBlockState.java
> +    default BlockState getAppearance(BlockGetter level, BlockPos pos, Direction side)
This should have a `@see` tag directing to the `IForgeBlock`-equivalent method.

2022-10-02 23:40 UTC, eerussianguy commented
It may be worth noting in the javadoc that the method itself doesn't actually *do* anything, this is just a place to specify a common implementation for others to consume.

2022-10-15 09:45 UTC, Technici4n commented on src/main/java/net/minecraftforge/common/extensions/IForgeBlock.java
> +    default BlockState getAppearance(BlockState state, BlockGetter level, BlockPos pos, Direction side)
Why not `BlockAndTintGetter` ?

2022-11-09 16:46 UTC, Technici4n approved these changes
Looks great, hope this can be merged soon. :shipit:

2022-11-12 15:42 UTC, marchermans approved these changes

2022-11-21 19:48 UTC, merged