[1.18.x] Add Forge "bosses" tag
MinecraftForge/MinecraftForge pull request #9081
Opened 2022-10-12 12:39 UTC by MagnusHJensen

This is an LTS backport of #9017, which was an extension of the abandoned PR #8464.

2022-10-12 13:27 UTC, marchermans approved these changes

2022-12-20 11:08 UTC, covers1624 requested changes

2022-12-20 11:08 UTC, covers1624 commented on src/main/java/net/minecraftforge/common/ForgeMod.java
> +import net.minecraftforge.common.data.*;
We do not use * imports. Please revert this and add your new import.

2023-05-29 22:36 UTC, Matyrobbrt commented
This PR was superseded by #9513. Thank you for your contribution!

2023-05-29 22:36 UTC, closed without merging