Add a method to LootContext.Builder that allows changing the queried loot table id
MinecraftForge/MinecraftForge pull request #9084
Opened 2022-10-12 16:47 UTC by noeppi-noeppi

Forge adds a `queriedLootTableId` property to `LootContext``that holds the currently queried loot table id. This is for example used by the [LootTableIdCondition](https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/main/java/net/minecraftforge/common/loot/LootTableIdCondition.java) to check whether the loot table in the condition is queried.

Currently however, a custom global loot modifier that uses this condition can't query another loot table in the process of adding its loot. If the custom loot modifier did that, the queried loot table would stay the same and as it uses this for it's condition, it would call itself again.

The solution is to allow changing the value in the loot context builder, so the loot modifier can make a copy of the loot context that has a different `queriedLootTableId` and then safely query other loot tables.

2022-10-15 12:37 UTC, ChampionAsh5357 commented
So, I'm failing to see the issue. Why couldn't you just reconstruct the `LootContext` for the new loot table and call the get items method to get the table data? Then you wouldn't have to worry about setting the loot table id and have to set it back afterwards.

Additionally, I do not believe exposing a public setter is a good solution here regardless.

2022-10-15 17:50 UTC, noeppi-noeppi commented
I don't get your point. Reconstructing a new `LootContext` is what I want to do. That's why I want a setter method in the `LootContext$Builder` class, so I can use the copy constructor to make a builder with all properties from the parent loot context and then change the queried loot table.

So there is no need to *set the loot table back afterwards*

2022-12-16 12:22 UTC, sciwhiz12 requested changes

2022-12-16 12:22 UTC, sciwhiz12 commented on patches/minecraft/net/minecraft/world/level/storage/loot/LootContext.java.patch
> ++
Please remove the trailing whitespace on this line, but keep the blank line.

2022-12-18 22:02 UTC, sciwhiz12 approved these changes

2022-12-19 23:18 UTC, merged