Add supplier to FlowerBlock so it works with custom MobEffects
MinecraftForge/MinecraftForge pull request #9139
Opened 2022-11-09 16:30 UTC by Minecraftschurli

2022-11-09 16:33 UTC, ChampionAsh5357 commented
This shouldn't be an issue anymore since mob effects are registered before blocks in the vanilla registry order.

2022-11-09 16:51 UTC, Minecraftschurli commented
Ok then I'll close this and just open the 1.18.x one (because it definitely is an issue there)

2022-11-18 03:35 UTC, bconlon1 commented
This is able to be reopened as mob effects are actually registered after blocks, not before.

2022-11-18 14:19 UTC, ChampionAsh5357 requested changes

2022-11-18 14:19 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/world/level/block/FlowerBlock.java.patch
> ++      this.suspiciousStewEffectSupplier = null;
This should either return the mob effect supplied in the constructor or, to support registry replacement, a delegate similar to `LiquidBlock` or just by calling `RegistryObject#of`.

2022-11-18 14:19 UTC, ChampionAsh5357 commented on patches/minecraft/net/minecraft/world/level/block/FlowerBlock.java.patch
> ++   public FlowerBlock(java.util.function.Supplier<MobEffect> suspiciousStewEffectSupplier, int p_53513_, BlockBehaviour.Properties p_53514_) {
Needs a forge.exc entry if you are going to use the param names.

2022-11-18 17:28 UTC, ChampionAsh5357 approved these changes

2022-11-30 22:04 UTC, merged