[1.19] Added Action value to PlayerInteractEvent.LeftClickEvent to expose what action fired the event
MinecraftForge/MinecraftForge pull request #9175
Opened 2022-12-08 05:32 UTC by LegoMaster3650

Added an Action value to the LeftClickEvent that specifies which action caused the event to be fired
- Start (Initial left click on a block or moving to another)
- Stop (Ceasing to left click on a block due to breaking it)
- Abort (Ceasing to left click on a block due to releasing the button or the mined block changing)
- Client Hold (Some hook call that fires left click while mining on the client side that I left in for compatibility in case someone uses it for this)

I chose to use a custom enum for this value which I don't really know if it's the best practice, but the Action enum used by the packet doesn't have a value for the random forge hook call on the client side for continuous mining, and I feel like modifying an existing enum for client-server communication to add a client-only value sounds worse to me.

I also made a new forge hook for the client hold event fire to use due to its oddly specific case that doesn't fit any of the packet action values, I can't tell if this was the best approach to this either but feel free to correct me if it's bad, I'll happily change it.

This also fixes #8643 by allowing the player to filter for certain causes of the event using the action value.

I did a quick test to verify it works by sending a chat message containing the logical side and the action.
(Order of events in screenshot was breaking a dirt block (with haste to keep it within a single chat screen), and then punching stone and quickly releasing)
![LeftClickEvent Test Screenshot](https://user-images.githubusercontent.com/37251737/206360730-b3984c4c-def7-4b95-b133-74ae9bc38786.png)

Due to having slightly breaking changes if fully implemented (removing constructor and ForgeHooks method with no action value,) I have deprecated these and marked them for removal, but I forgot 1.19.3 did just release today so if it's breaking enough maybe these could be removed completely within this PR. I don't know if it's good to do it now so I didn't yet, but if I can I'll add that in.

Hopefully I did everything right as this is my first PR and I don't know exactly how things work here or what _all_ of the exact best practices are. (I read what I could find though)

2023-05-16 15:55 UTC, ChampionAsh5357 requested changes
Would you mind adding a test mod showing off the fix in action? It's much easier to test that way. A comment should be left on test mod containing the steps to reproduce and the expected result when performing given actions

2023-05-16 15:55 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +         * @deprecated Use the other constructors instead
This can be placed in the javadoc itself.

2023-05-16 15:55 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +         * Warning: The event is fired every tick on the client under {@link Action#CLIENT_HOLD}
This warning would probably make more sense under the action itself.

2023-05-16 15:55 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +        	 * When the player stops left clicking a block by releasing the button, or no longer targeting the same block
Probably should say 'before it breaks' unless there is a scenario where both stop and abort can be called.

2023-05-16 15:55 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/event/entity/player/PlayerInteractEvent.java
> +        	 * When the player is actively mining a block on the client side
Add the warning message here that it will be called every tick as long as the block is being destroyed.

2023-07-17 23:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9175) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9175) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=9175) it.</sub>

2023-07-18 00:27 UTC, LexManos commented
cla assistant has gone crazy due to the neo changes. He has previously signed it. 
Anyways, pulled in https://github.com/MinecraftForge/MinecraftForge/commit/e6bb7eecbde4370ea772ea9866b1a4343fd060ca

2023-07-18 00:27 UTC, closed without merging