[1.19.3] Add block atlas config to register forge:white texture
MinecraftForge/MinecraftForge pull request #9187
Opened 2022-12-08 21:28 UTC by XFactHD

This PR adds an atlas config for the block atlas that registers the `forge:white` texture to be stitched onto the block atlas.
This texture is regularly used as a placeholder in block and item models or in cases where only a flat color is needed but the involved parts of the rendering system require a texture.

2022-12-09 04:12 UTC, LexManos commented
All data should be genned.

2022-12-09 12:35 UTC, Minecraftschurli requested changes

2022-12-09 12:35 UTC, Minecraftschurli commented on src/main/java/net/minecraftforge/common/data/SpriteSourceProvider.java
> +import com.mojang.serialization.*;
Wildcard import

2022-12-09 12:37 UTC, Minecraftschurli approved these changes

2022-12-09 12:38 UTC, XFactHD commented on src/main/java/net/minecraftforge/common/data/SpriteSourceProvider.java
> +import com.mojang.serialization.*;
Of course I had to miss some...

2022-12-09 12:43 UTC, TheCurle commented
Don't forget your licenses.

2022-12-12 05:07 UTC, sciwhiz12 requested changes

2022-12-12 05:07 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/common/data/SpriteSourceProvider.java
> +
Please remove this extra whitespace. This should only be a single blank line.

2022-12-12 08:33 UTC, KnightMiner commented on src/main/java/net/minecraftforge/common/data/SpriteSourceProvider.java
> +public abstract class SpriteSourceProvider extends JsonCodecProvider<List<SpriteSource>>
A javadoc might be useful here, to explain what a sprite source does, or at least link relevant classes

2022-12-13 13:59 UTC, sciwhiz12 approved these changes

2022-12-13 19:04 UTC, marchermans commented
Has this been renewed on top of the compatibility test fix?

2022-12-15 20:39 UTC, XFactHD commented
This PR is blocked by https://github.com/MinecraftForge/MinecraftForge/pull/9222 as the addition of the atlas config currently breaks all textures stitched onto the block atlas when run in a Forgedev environment.

2022-12-16 16:48 UTC, merged