[1.19.3] Add event before baked models are cached by the BlockModelShaper
MinecraftForge/MinecraftForge pull request #9190
Opened 2022-12-08 23:27 UTC by XFactHD

This PR adds an additional event to the model baking process right before the baked models are cached by the `BlockModelShaper` to allow listeners to modify the `Map<ResourceLocation, BakedModel>` stored in the `ModelManager` and `ModelBakery` without desyncing it from the `Map<BlockState, BakedModel>` stored in the `BlockModelShaper`.
Previously, the caching of the state->model map was done in the apply phase of the model manager after the existing `ModelEvent.BakingCompleted` was fired. Now this is done in the async prepare phase and therefore before said event fires.
Moving `ModelEvent.BakingCompleted` to the async part before the cache is built felt like a bad idea since there are cases where you only want to read from the map to cache the models, which would be best done where the event fires from now.

Being able to modify the model map after baking is an important feature in cases where the use of custom model loaders is not possible because the data deciding whether a model has to be modified is loaded from a different data source such as a texture metadata loader or when the context provided by a custom model loader is insufficient, such as a model not knowing which blockstate (if any) it is being baked for.

I have opted to make the map given to `ModelEvent.BakingCompleted` unmodifiable to make consumers aware of the inability to modify the map in that event. I have put this change in a separate commit in case it is undesired.

2022-12-09 18:49 UTC, shartte commented
Shouldn't the old BakingCompleted event just be moved to where you added this new event?
The existing event was used exactly for what you are describing. The only issue now is that the map of BlockState->BakedModel is created before the old event is fired.

2022-12-10 20:07 UTC, XFactHD commented
The main reasons I opted to do it this way are

1. If you use the event to retrieve models and cache them somewhere that is accessed constantly (i.e. by a BER or similar), you'd have to double buffer it
2. Moving the event from sync to async is a sneaky change which most people are unlikely to notice but has a high likelihood of causing weird intermittent issues.

If triage deems these potential issues acceptable, I'll move the existing event instead.

2022-12-11 10:15 UTC, sciwhiz12 requested changes

2022-12-11 10:15 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        ModLoader.get().postEvent(new ModelEvent.BakingCompleted(modelManager, Collections.unmodifiableMap(models), modelBakery));
Please modify the javadocs of `ModelEvent.BakingCompleted` to reflect the map's new status as unmodifiable, as well as directing users who wish to modify the map to the new event.

2022-12-11 10:15 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/event/ModelEvent.java
> +     * {@link net.minecraft.client.renderer.block.BlockModelShaper}.
Please modify this javadoc so it's first sentence clearly differentiates its purpose from `ModelEvent.BakingCompleted` (such as combining both sentences into one, or simply discarding the first sentence and using the second one with a bit of rewriting).

2022-12-11 16:13 UTC, sciwhiz12 approved these changes

2022-12-11 19:35 UTC, marchermans approved these changes

2022-12-11 19:35 UTC, merged