Introduce a `batch` parameter in @GameTestHolder
MinecraftForge/MinecraftForge pull request #9246
Opened 2022-12-20 20:56 UTC by andriihorpenko

This PR adds a `batch` parameter to the Forge's `@GameTestHolder` annotation.

## Introduction

Imagine you have a test suite with dozens of tests in it. If you decide to group them under a specific batch, you have to specify a batch for every single `@GameTest`.

This PR lets us define a common batch for all the tests under `@GameTestHolder`, so the test case becomes less crowded.

## How it works

Essentially, `@GameTestHolder#batch` will take precedence unless `@GameTest#batch` is specified. That said, you can define a custom batch per test, even if you have specified a common batch.

## Examples

### Before
```kotlin
@GameTestHolder(MOD_ID)
class TestSuite {
    @GameTest(batch = "customBatch")
    fun test1(...)

    @GameTest(batch = "customBatch")
    fun test2(...)

    @GameTest(batch = "customBatch")
    fun test3(...)
}
```

### After
```kotlin
@GameTestHolder(MOD_ID, batch = "customBatch")
class TestSuite {
    @GameTest
    fun test1(...)

    @GameTest
    fun test2(...)

    @GameTest
    fun test3(...)
}
```

## Changes

This PR invades `@GameTest` annotation, specifically it removes default batch name from the `batch` parameter. This is done in order to detect whether there is a manually specified batch.

However, as `ForgeGameTestHooks#getBatch` fallbacks to "defaultBatch" if no condition is met, this PR will not affect end-users.

## Tests

I've tested this PR on my local project in 3 different scenarios:
- No batches defined. Result: all tests are under "defaultBatch"
- Batch defined in `@GameTestHolder`. Result: all tests are under `@GameTestHolder` batch
- Batch defined in `@GameTestHolder` and `@GameTest`. Result: batches defined in `@GameTest` take precedence over those defined in `@GameTestHolder`.

2022-12-20 20:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9246) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9246) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=9246) it.</sub>

2022-12-20 21:38 UTC, sciwhiz12 requested changes
Our version policy requires that changes (new features or bugfixes) must first be integrated into the Latest version's branch before it will be merged into the LTS version's branch (unless it can be shown that the change is only relevant to the LTS branch).

In line with this, please update this PR or create a new PR targeting the Latest version.

2022-12-21 03:33 UTC, SizableShrimp approved these changes

2022-12-21 10:53 UTC, sciwhiz12 approved these changes

2023-01-04 00:53 UTC, closed without merging