Add translate key for Forge pack.mcmeta description (feature of 1.19.3)
MinecraftForge/MinecraftForge pull request #9260
Opened 2022-12-26 12:19 UTC by Mysterious-Dev

This PR add a translation key for the description of Forge pack.mcmeta (new feature of 1.19.3).

This makes it possible to be in agreement with the other data packs which also have a translation key.

2022-12-26 12:20 UTC, Mysterious-Dev commented
I didn't dare to integrate a data generator for the pack.mcmeta (like Minecraft does now). Tell me if it's better to do it or not.

2022-12-27 21:27 UTC, ChampionAsh5357 requested changes
Vanilla already has a data provider for pack metadata which Forge hooks into, so I don't think it's necessary.

2022-12-27 21:27 UTC, ChampionAsh5357 commented on src/main/resources/assets/forge/lang/en_us.json
> +  "pack.forge.description": "Forge resources pack"
```suggestion
  "pack.forge.description": "Forge resource pack"
```

2022-12-28 14:48 UTC, Mysterious-Dev commented on src/main/resources/assets/forge/lang/en_us.json
> +  "pack.forge.description": "Forge resources pack"
It's modified.

2022-12-28 18:45 UTC, ChampionAsh5357 approved these changes
@TheCurle if you pull this, can you make sure to add the key on crowdin? Thanks.

2022-12-30 19:12 UTC, merged