Rename RegisterParticleProviderEvent's register methods to describe what kind of particle providers they register (deprecating old methods to avoid breaking) and minor docs tweaks
MinecraftForge/MinecraftForge pull request #9388
Opened 2023-03-15 22:59 UTC by Commoble

The intent of this PR is to make the event's API more readable and describable (e.g. "use the register method that registers a SpriteParticleRegistration" vs. "use registerSpriteSet").

Currently going with `registerSpecial` for non-json particles (because they manually do special rendering), `registerSprite` for the single-texture-json provider we have as of 1.19.4, and `registerSpriteSet` for the multi-texture jsons, names aren't set in stone and can be improved.

2023-03-15 23:04 UTC, SizableShrimp requested changes

2023-03-15 23:04 UTC, SizableShrimp commented on src/main/java/net/minecraftforge/client/event/RegisterParticleProvidersEvent.java
> +    @Deprecated(forRemoval=true, since="1.19.4")
Annotation fields should have spaces around the =

2023-03-15 23:04 UTC, SizableShrimp commented on src/main/java/net/minecraftforge/client/event/RegisterParticleProvidersEvent.java
> +     * @param type ParticleType to register a particle prov for.
Didn't finish this

2023-03-19 14:01 UTC, sciwhiz12 requested changes

2023-03-19 14:01 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/event/RegisterParticleProvidersEvent.java
For javadocs of all methods:
 - Please move the the "There must be [a/no] particle json" paragraph to the main body of the javadoc (instead of under the `@param`), as a paragraph surrounded by `<p>...</p>`.
 - Please add a blank line between the main body and the block tags (the first `@param`) to improve readability.
 - Please move the `@deprecated` tag to the very end of the javadoc.
 - I would suggest either rewording the particle JSON paragraph for methods which require them so they are visibly different, or emphasizing the word "a"/"no" before "particle json" using `<strong>`.

2023-03-20 03:18 UTC, sciwhiz12 requested changes

2023-03-20 03:18 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/event/RegisterParticleProvidersEvent.java
> +
Please remove the whitespace in this blank line.

2023-03-22 03:25 UTC, sciwhiz12 commented on src/main/java/net/minecraftforge/client/event/RegisterParticleProvidersEvent.java
> +     *
I believe there shouldn't be whitespace after the asterisk on blank javadoc comment lines...?

2023-03-23 00:39 UTC, sciwhiz12 approved these changes

2023-03-26 02:57 UTC, merged