[1.19.x] The tint on block breaking particles is now handled in IForgeBlock
MinecraftForge/MinecraftForge pull request #9446
Opened 2023-04-08 06:08 UTC by SilverDavidMC

The goal of this PR is simple; allowing for blocks to control if their breaking particles are tinted. This is currently used by vanilla to make grass blocks not have tinted particles, despite having a tint themselves. 

The implementation moves the vanilla `!state.is(Blocks.GRASS_BLOCK)` check into `IForgeBlock.areBreakingParticlesTinted` to enable any block to determine if their particles are tinted or not. The new method passes in the `BlockState` in question, as well as the `Level` and `BlockPos` to enable special behavior.

2023-04-08 06:46 UTC, marchermans requested changes
I do not like the solution here.
We have client rendering properties on the block for a good reason. Given that this is purely a client side rendering issue, I request that you move it there.

2023-04-09 05:03 UTC, SilverDavidMC commented
Ah my bad. I always manage to forget this system exists. I'll adjust it accordingly

2023-04-09 06:56 UTC, Random832 commented
Is this necessary? Mods can easily work around this issue by not using tint index 0 for their model tints, and returning white for it in their tint function.

2023-04-09 14:43 UTC, marchermans commented
It is possible to do this via the model, but it does not have access to the level.
So there is an argument that can be made both ways

2023-04-09 18:50 UTC, Random832 commented
> It is possible to do this via the model, but it does not have access to the level. So there is an argument that can be made both ways

I'm not sure what you mean. The tint color function itself has level access, I can't think of a situation where you'd need to set the tint *index* for particles [or for them to not be tinted, which can be done by giving them a dedicated tint index for which the tint color function returns white] based on level data.

2023-04-20 07:29 UTC, marchermans commented
> > It is possible to do this via the model, but it does not have access to the level. So there is an argument that can be made both ways
> 
> I'm not sure what you mean. The tint color function itself has level access, I can't think of a situation where you'd need to set the tint _index_ for particles [or for them to not be tinted, which can be done by giving them a dedicated tint index for which the tint color function returns white] based on level data.

Can you provide an example.
Cause i like his current solution, if you want this to be extended to the model, then please provide an example of how you see this working.

2023-04-27 04:47 UTC, tmvkrpxl0 commented
Method name `areBreakingParticlesTinted` feels quite long to me. Could you shorten it, please?

2023-04-27 05:41 UTC, KnightMiner commented
I also agree that this seems unneeded. All you have to do is return `-1` for tint index 0 to have particles untinted. If you want to tint and not tint particles, just don't make any layers tint index 0, there is nothing forcing you to use it.

2023-07-14 23:06 UTC, LexManos commented
This is a simple enough hook that is already justified by what else we do in the client block extensions. 
Making a proper system where its pulled from the json would be ideal but that involves breaking more of the model format.
Not something I want to do. So im gunna pull this, and call it good for now until the refactoring.

2023-07-14 23:08 UTC, merged