Add PlayerSpawnPhantomsEvent event, add (player) spawn cause to phantoms
MinecraftForge/MinecraftForge pull request #9473
Opened 2023-04-29 08:49 UTC by DBotThePony

The event allows to control phantom spawning *per player*, so mods can disallow (or forcefully allow) phantom spawning per specific player, or adjust amount of phantoms spawned per that player.

Adds context to Phantoms themselves (`getSpawnCause`, `setSpawnCause`) which store `ServerPlayer` who is responsible for this phantom's spawn.

While both changes somewhat correlate at what they are allowing to do, (both allow to stop phantoms to spawn per-player), the event allows to ignore vanilla spawn conditions and adjust amount of phantoms spawned.

2023-04-29 08:58 UTC, Shadows-of-Fire commented
The source player must not be kept as a live reference to the entity object. It should be kept as a UUID, if necessary.

Though I must ask, what use case is there for tracking the spawn-causing player after the spawn process?

2023-04-29 22:32 UTC, Shadows-of-Fire requested changes

2023-04-29 22:32 UTC, Shadows-of-Fire commented on patches/minecraft/net/minecraft/world/entity/monster/Phantom.java.patch
> ++    * @return UUID describing what caused phantom to spawn (generally a player's UUID). null if not applicable.
```
* This value is only available on the logical server, and will always be null on the client.
* @return The UUID of the entity that caused the Phantom to spawn, or null if unknown.
```

2023-04-29 22:32 UTC, Shadows-of-Fire commented on patches/minecraft/net/minecraft/world/entity/monster/Phantom.java.patch
> ++      this.spawnCause = spawnCause;
This should be guarded to not allow changing the value once it has been set.  Specifically, it should throw `UnsupportedOperationException` if `this.spawnCause` is not null.

2023-04-29 22:32 UTC, Shadows-of-Fire commented on patches/minecraft/net/minecraft/world/entity/monster/Phantom.java.patch
> ++    * @param spawnCause UUID describing what caused phantom to spawn (generally a player's UUID).
```
/**
 * Sets the spawn cause of this phantom.
 * <p>
 * This should be called as soon as possible in the Phantom's lifecycle, to ensure it is present for event handlers.
 * @param spawnCause The UUID of the entity that caused the Phantom to spawn.
 * @throws UnsupportedOperationException if the spawn cause has already been set.
```

2023-04-29 22:32 UTC, Shadows-of-Fire commented on src/main/java/net/minecraftforge/event/entity/player/PlayerSpawnPhantomsEvent.java
> +@Event.HasResult
```
/**
 * This event is fired from {@link PhantomSpawner#tick}, once per player, when phantoms would attempt to be spawned.<br>
 * This event is not fired for spectating players.
 * <p>
 * This event is fired before any per-player checks, but after all global checks.<br>
 * The behavior of {@link PhantomSpawner} is determined by the result of this event.<br>
 * See {@link #setResult} for documentation.<br>
 * <p>
 * This event is fired on the {@link MinecraftForge#EVENT_BUS}.<br>
 * @see {@link #setResult} for the effects of each result.
 */
 ```
 
 The file should also import `net.minecraft.world.level.levelgen.PhantomSpawner` for the javadocs to resolve correctly.

2023-04-29 22:32 UTC, Shadows-of-Fire commented on src/main/java/net/minecraftforge/event/entity/player/PlayerSpawnPhantomsEvent.java
> +     * @return How many phantoms to spawn. This value varies from event to event because it represents random number game was about to spawn.
```
* @return How many phantoms will be spawned, if spawning is successful. The default value is randomly generated.
```

2023-04-29 22:32 UTC, Shadows-of-Fire commented on src/main/java/net/minecraftforge/event/entity/player/PlayerSpawnPhantomsEvent.java
> +     * @param phantomsToSpawn How many phantoms should spawn, given checks are passed.
```
* Sets the number of phantoms to be spawned.
* @param phantomsToSpawn How many phantoms should spawn, given checks are passed.
```

2023-04-29 22:32 UTC, Shadows-of-Fire commented on src/main/java/net/minecraftforge/event/entity/player/PlayerSpawnPhantomsEvent.java
> +    @Override
```
    /**
     * The result of this event controls if phantoms will be spawned.<br>
     * If the result is {@link Result#ALLOW}, phantoms will always be spawned.<br>
     * If the result is {@link Result#DENY}, phantoms will never be spawned.<br>
     * If the result is {@link Result#DEFAULT}, vanilla checks will be run to determine if the spawn may occur.
     */
```

2023-04-30 03:27 UTC, Shadows-of-Fire approved these changes

2023-05-12 18:18 UTC, LexManos commented
I still don't get the point of the cause patch. There is nothing here that needs to be persisted. You get the spawn reason in the event and you can decide in the event if the phantom needs to be powered or not. Doing it after the fact can be done in the item equip/use for any phantoms that are around.

2023-05-17 08:45 UTC, DBotThePony commented
> There is nothing here that needs to be persisted

It was added by Shadow's request:
![aUii24ePXz](https://github.com/MinecraftForge/MinecraftForge/assets/6339511/1e4c0fc2-9eae-4606-a016-3f433fafe8ef)
![JSmmW6Ysuh](https://github.com/MinecraftForge/MinecraftForge/assets/6339511/8ca324dc-46b5-4ee6-b6ca-8279043783cf)

> You get the spawn reason in the event

No, you do not, spawn cause (the player) is lost. Think about it as "phantoms spawned by mob spawner (powered spawner/dungeon spawner)" vs "PhantomSpawner spawned for player X". You can't distignish between these two, were phantoms spawned by some player nearby or something else.

2023-07-14 04:51 UTC, closed without merging