[1.19.x] Make the FireworkShapes enum extensible
MinecraftForge/MinecraftForge pull request #9486
Opened 2023-05-03 23:15 UTC by danorris709

This allows mods to extend the FireworkRocketItem.Shape enum so that they can render their own firework shapes whilst still using the firework logic (entity, and itemstack).

I changed the method in the Shape enum to use a for loop, rather than the map, as I believe the map is initialized too early for the enum to work otherwise. Not sure what other solution could be done, to reduce changes in the Minecraft code, but open to suggestions on that front.

[Example Video](https://i.gyazo.com/646d0369c89fda8f1221417e360f7261.mp4)

![video](https://i.gyazo.com/646d0369c89fda8f1221417e360f7261.gif)

2023-05-04 00:31 UTC, ChampionAsh5357 commented
This implementation won't work in general as you cannot guarantee two extended enums will not have the same id. You would basically need to extend and replace all calls to store the string representing the firework instead. See how forge handles instances when storing the `MobEffect` when only the id is stored. We essentially patch in `forge:effect_id` to load the effect based on the registry name. It would be similar, but using a unique identifier representing the shape.

2023-05-04 12:41 UTC, danorris709 commented
Yeah I see what you mean about the IDs but I'm not sure what you mean in regards to looking at how the mob effect part works? That has the benefit of being a registry so it uses ResourceLocations as the ID whereas this only has a String name which would suffer the same issue as the integer IDs (people potentially having the same two IDs).

Unless you meant for me to change them to be ResourceLocations too?

2023-05-04 13:42 UTC, ChampionAsh5357 commented
A resource location is just a formatted string. So, we could either use the string name, assuming it doesn't have much of a purpose, or the enum name during extension and tell people the value must be unique. That should already be enforced for the enum name anyways, at least semantically, since added enum constants should be in the form '<modid>_<enum_name>'.

2023-05-09 01:25 UTC, danorris709 commented
> A resource location is just a formatted string. So, we could either use the string name, assuming it doesn't have much of a purpose, or the enum name during extension and tell people the value must be unique. That should already be enforced for the enum name anyways, at least semantically, since added enum constants should be in the form '_<enum_name>'.

Yes, apologies I didn't make it clear when I was comparing the ResourceLocation and String I understand that a ResourceLocation is a string but in best practice at least mods could use their mod id as a unique identifier. 

But yes I think you are correct that the enum name being the identifying string makes most sense here.

2023-05-09 01:40 UTC, danorris709 commented
I have updated it to what I think you were looking for, the test give command now looks like this:

`/give @p firework_rocket{Fireworks:{Explosions:[{"forge:firework_shape":pikachu,Colors:[I;14602026]}]}} 1`

2023-05-10 15:45 UTC, ChampionAsh5357 requested changes
Looks better, but I think that the event itself should be replaced with a registry that maps a shape to a functional interface with the method on the mod event bus. It could even be added to one of the existing registration events (e.g., `RegisterParticleProvidersEvent`).

Additionally, this does not do anything to allow crafting the shape onto a firework star. There should probably be an extension method on the item that returns a shape or null when it should default back to the initial list.

Also, do not use a copyrighted asset as a test mod.

2023-05-10 15:45 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +            if (value.name().equals(id)) {
Probably should check `equalsIgnoreCase` instead.

2023-05-10 15:45 UTC, ChampionAsh5357 commented on src/test/java/net/minecraftforge/debug/CustomFireworkShapeTest.java
> +public class CustomFireworkShapeTest
The entirety of this test class needs more documentation, especially with that double array dump.

2023-05-10 15:45 UTC, ChampionAsh5357 commented on src/main/java/net/minecraftforge/client/event/FireworkShapeRenderEvent.java
> + * Fired when a non-default (aka non-minecraft) firework is attempting to be rendered
This does not explain anything. What is being testing and what is the expected result of the test mod?

2023-07-14 21:01 UTC, closed without merging

2023-07-14 21:02 UTC, LexManos commented
Pushed a solution, simple usecase is to create your particle shape in common code, then register your factory in client only code as it references client only classes.