[mdk] Remove Implementation-Date from manifest
MinecraftForge/MinecraftForge pull request #9598
Opened 2023-06-25 06:35 UTC by williewillus

[mdk] Remove Implementation-Date from manifest

2023-06-25 07:18 UTC, marchermans commented
## Personal opinion
Great idea, wrong approach.

## Triage opinion:
From a debugging and issue management perspective I alone have used this field many times to determine when something went wrong on my CI environment. So removing this field from the MDK hinders debugging problems that actually happen in the wild. And once they happen, you can bet that I am adding this field back into my jars instantly. That said, this field does not hinder the reproduction aspect at all. Because you made two major initial assumptions which are just wrong:
1. A build which is timestamped can not be validated, because the build timestamps are different. This is just not true. You can easily verify two jars which have this field in the manifest, by checking the JARS content, and not just the JARS themselves. Even without this field set, several JDKS will set build and generation timings in the JAR entries themselves making two JARs not directly comparable binary wise, and meaning that you will need to loop over their content anyway. Which means you can skip the content of the manifest file any still check if two build produced the same bytecode, which is what you are after anyway.
2. Forge is and will always aim for jar signing. Once that comes into play, reproducible builds are out of the question anyway. Since the jar at that point contains a MANIFEST.MF file which you can not reproduce in any way possible.

That said, as it stands right now, I don't think that merging this will happen without further justification addressing the two points above.

2023-06-25 07:23 UTC, marchermans commented on mdk/build.gradle
> -                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
This is a useful field during debugging.
And MANIFEST.MF files should be skipped during binary comparison checks anyway due to signature content which is not remotely reproducible. So whether this field exists or not is irrelevant.

2023-06-25 07:23 UTC, marchermans requested changes
See comment above.

2023-06-25 07:35 UTC, williewillus commented
> From a debugging and issue management perspective I alone have used this field many times to determine when something went wrong on my CI environment.

A larger survey here would be great. I have never used this field for anything, and I doubt most modders know of its existence.

> And once they happen, you can bet that I am adding this field back into my jars instantly.

It's your freedom to do so.

> by checking the JARS content, and not just the JARS themselves. Which means you can skip the content of the manifest file any still check if two build produced the same bytecode, which is what you are after anyway.

It's much easier to determine if two artifacts are reproducibly-equivalent by just hashing the entire thing and comparing them. Specialized java-only tooling only makes this more complicated than it needs to be.

> Forge is and will always aim for jar signing. Once that comes into play, reproducible builds are out of the question anyway. Since the jar at that point contains a MANIFEST.MF file which you can not reproduce in any way possible.

There's a whole separate problem here that is inherent in the JDK's jarsigner tooling (and cpw's decision to use it), which is that it embeds signatures instead of creating detached ones. As you've correctly pointed out, that completely precludes bit-identical builds. There's a reason why Maven Central, the preeminent repository for Java binaries, does not use any of the JDK's own jarsigner tooling and instead requires detached pgp signatures. And a reason that pretty much every single Linux package repository in the world uses detached signatures instead of embedded ones.

Reproducible builds are increasingly an expected practice of proper engineering, and the JDK's tooling is falling behind the rest of the industry here.

2023-06-25 07:47 UTC, sciwhiz12 commented
To give my 2¢ on the points raised abov:

> From a debugging and issue management perspective I alone have used this field many times to determine when something went wrong on my CI environment. So removing this field from the MDK hinders debugging problems that actually happen in the wild. And once they happen, you can bet that I am adding this field back into my jars instantly.

Personally, I have never used the `Implementation-Timestamp` that exists inside the JAR for anything, not even debugging. Usually, filesystem timestamps suffice, or renaming the file to distinguish it (`blahblah-build-1.jar`) is better instead of comparing timestamps.

And even so, as you've noted, if some developer has a clear and actual use for the timestamp, they are free to re-add it themselves (and remove it if they so choose to). Here, we're changing the MDK, the default template used by Forge mod developers, so the defaults in the MDK tend to reproducible builds rather than not.

> 1. A build which is timestamped can not be validated, because the build timestamps are different. This is just not true. You can easily verify two jars which have this field in the manifest, by checking the JARS content, and not just the JARS themselves. Which means you can skip the content of the manifest file any still check if two build produced the same bytecode, which is what you are after anyway.

One big advantage to bit-for-bit reproducible artifacts from builds is that no format-specialized tool is required to verify that bit-for-bit equality, as all you need is a tool capable of taking in data and hashing it. While that does still represent a hurdle for end users, it is a lesser hurdle (and one they may be familiar with, from other packages which do the same) than a format-specialized tool.

The format-specialized tool would need to be verified that performs its functions (JAR bytecode comparison with exclusions for certain files/data) with no issues, and that it doesn't have some issue that may represent a vector to hide data from its comparison check, and that someone can't hijack the supply chain for that tool to substitute their own (possibly backdoored) one. (Compared to a bit-level hash, where _everything_ including the timestamps in the ZIP metadata are included, and tools to hash data are field-tested, secure, and ubiquitous).

> 2. Forge is and will always aim for jar signing. Once that comes into play, reproducible builds are out of the question anyway. Since the jar at that point contains a MANIFEST.MF file which you can not reproduce in any way possible.

This point of trying to moot reproducible builds because of `jarsigner` signatures is really only relevant _if_ the mod developer specifically enables `jarsigner` for their mod, and goes through the arguably arduous process of doing so -- making their keystore, storing it somewhere safe, configuring their build, and likely configuring their CI (such as GitHub Actions). (And I don't think Forge would be in the business of forcing mod developers to sign their jars without widespread community acceptance first.)

It would be better to make the default be reproducible builds and then have developers opt-in to `jarsigner` signatures (which preclude reproducible builds), than to have the default not be reproducible builds.

2023-06-25 08:15 UTC, marchermans commented
> One big advantage to bit-for-bit reproducible artifacts from builds is that no format-specialized tool is required to verify that bit-for-bit equality, as all you need is a tool capable of taking in data and hashing it. While that does still represent a hurdle for end users, it is a lesser hurdle (and one they may be familiar with, from other packages which do the same) than a format-specialized tool.
> 
> The format-specialized tool would need to be verified that performs its functions (JAR bytecode comparison with exclusions for certain files/data) with no issues, and that it doesn't have some issue that may represent a vector to hide data from its comparison check, and that someone can't hijack the supply chain for that tool to substitute their own (possibly backdoored) one. (Compared to a bit-level hash, where _everything_ including the timestamps in the ZIP metadata are included, and tools to hash data are field-tested, secure, and ubiquitous).

We are in a damn Java world!
And this field is useful. So whether or not you want to use the tool of your choice it is your problem.
Forge already stated that this is not something they are going for. It is literally trivial to validate the build with it!

Now to the argument of useability here:
Given that you are aiming for somebody to do the validation (else this whole PR is a mood point anyway), somebody has to set the rules. In other words, you are saying that you won't validate builds that have this enabled because you are not willing to spend 30 minutes writing a damn for each hasher that calculates the class file hashes?

> This point of trying to moot reproducible builds because of jarsigner signatures is really only relevant if the mod developer specifically enables jarsigner for their mod, and goes through the arguably arduous process of doing so -- making their keystore, storing it somewhere safe, configuring their build, and likely configuring their CI (such as GitHub Actions). (And I don't think Forge would be in the business of forcing mod developers to sign their jars without widespread community acceptance first.)

Okay so let's assume we have 2 files for the signed jars. How would this work for the average player?
They would need to download the jar and the signature file! And put them in the right directory, and KNOW that this is what they need to do. Since we modders already have a problem signing and managing a SINGLE mod file, this will never happen from a useability and UX standpoint! So what are we left with: Ah right the good old JarSigner! Or rather a tool that places the signatures in a verifyable way into the distribution, and then it is not possible to do reproduceble builds.

Don't forget we have been researching this with all the platforms and people involved for nearly 10 years. We know what we are talking about! And we know why it has not happened yet!

2023-06-25 08:28 UTC, williewillus commented
> We are in a damn Java world!

The rest of the "damn Java world" does not use specialized verification tools, they hash their artifacts like the rest of the industry. So this isn't supporting your argument in the way you think it is :)

> In other words, you are saying that you won't validate builds that have this enabled because you are not willing to spend 30 minutes writing a damn for each hasher that calculates the class file hashes?

This is an incredible yeeting of the goalposts. Why is it a given that specialized tools need to be written, when the rest of the industry is just hashing their artifacts like sane people?

>  Or rather a tool that places the signatures in a verifyable way into the distribution, and then it is not possible to do reproduceble builds.
This is veering sharply out of scope for this PR (which was very small in scope to start with before immediate bikeshedding and ocean-boiling commenced), but nothing prevents launchers from also fetching signatures and verifying them for the player. There's lots of room to discuss here if people are willing.

> Don't forget we have been researching this with all the platforms and people involved for nearly 10 years.

Show the organized data and results of this "research", or it may as well not exist.


Oh well. This was worth a shot.

2023-06-25 08:28 UTC, closed without merging

2023-06-25 20:57 UTC, leo60228 commented
> We are in a damn Java world!

Archive-level comparisons are *especially* important for Java, as the zip file format's design means that it's easy to hide files from specific implementations. See [this Firefox vulnerability](https://bugzilla.mozilla.org/show_bug.cgi?id=1534483) for a specific example of this.

2023-06-29 11:17 UTC, bluelhf commented
This argument got quite heated for five lines of code. :)

Is Forge set on using embedded signatures, or is it still possible to convince you that modders can handle moving two files instead of one? Some Skript resources in the Spigot ecosystem already distribute themselves as ZIP archives containing several JARs and resources; installing them does not seem to be particularly difficult even for the average Skript user.

2023-06-29 13:06 UTC, marchermans commented
> This argument got quite heated for five lines of code. :)
> 
> Is Forge set on using embedded signatures, or is it still possible to convince you that modders can handle moving two files instead of one? Some Skript resources in the Spigot ecosystem already distribute themselves as ZIP archives containing several JARs and resources; installing them does not seem to be particularly difficult even for the average Skript user.

The problem is not modders. It is users. This validation of the jar that is running happens at runtime. The users runtime. And although i have personally no problems managing more then ond file as a modder, hell tools like maven and Gradle do it for me. That is not something all users are able to do.

So yes. Forge is focusing solely on the jar signer or in jar equivalents for signing.

2023-06-29 14:58 UTC, bluelhf commented
> > This argument got quite heated for five lines of code. :)
> > Is Forge set on using embedded signatures, or is it still possible to convince you that modders can handle moving two files instead of one? Some Skript resources in the Spigot ecosystem already distribute themselves as ZIP archives containing several JARs and resources; installing them does not seem to be particularly difficult even for the average Skript user.
> 
> The problem is not modders. It is users. This validation of the jar that is running happens at runtime. The users runtime. And although i have personally no problems managing more then ond file as a modder, hell tools like maven and Gradle do it for me. That is not something all users are able to do.
> 
> So yes. Forge is focusing solely on the jar signer or in jar equivalents for signing.

Ah, sorry, I misspoke; I meant the users of mods, regular players with no experience with coding. If Forge is indeed doubling down on embedded signatures in the interest of ease of use, then I agree that having bit-identical reproducible builds as a default probably doesn't make sense.

2023-06-29 15:52 UTC, cpw commented
Full reproducibility isn't a lot of help, in general. As Willie themselves noted, it was speculation that it might have been of use here, and in my experience it hasn't had much value.

The reality is that there are several interrelated problems, and we've kinda gotten them all mixed together under this umbrella.

1. Runtime code verification. Is the code you're running what the developer wrote? That's what jar signatures give you. They tell you that the jar, loaded into the game, is the jar the developer intended. We recommend the built-in jar signature capability for this since it's part of the runtime ecosystem already. There are other possibilities here, but none of them are particularly better, and most require additional downloads, which is probably a worse end user experience. Note: In theory just signing your jar with any random key will give you this, but ideally you want the author to actually be known too, which leads to..
2. Author verification. This is verifying the developer is who you expect it to be. In some senses, in a generally anonymous community like ours, this is an intractable problem. Why? Because the typical means of doing author identity is to use established public key infrastructure and trusted third parties to verify the identity of the person. We can, however, obtain a simulacrum of this- assuming groups distributing mods are willing to act as a trusted third party, and we're willing to accept their judgements on their identity assertations. 

Where do reproducible builds fit in? They might allow a third party to obtain some candidate source code, create a local build and verify that the built output matches or not what has been distributed. Note that their goal was to be able to match the top level artifact (do the jar checksums match), which isn't the only thing you can do here, you can easily match the contained classes and resources as well, which would have potentially matched _at the time of the incident_. This change simply makes it _more likely_ (but not guaranteed) that the top level jar matches. And if the developer follows jar signing recommended practice, that won't be true anyway, which renders this change slightly moot, in my opinion.