preserve the ability to calculate normals for block models but default to behaving like vanilla
MinecraftForge/MinecraftForge pull request #9664
Opened 2023-07-17 17:51 UTC by Kovak

This addresses #9608. 

The inherent issue is that features like the overlay for block breaking use the model normals in order to determine the placement of the effect. Blocks like the campfire do not in vanilla calculate correct normals for some parts of the geometry. For instance the flames in the campfire in vanilla receive the same normal from the direction facing as all other faces on the model, making it so that the normals for the fire are not actually the correct normals for that face.

By calculating normals for all faces we've been accidentally introducing divergent from vanilla behavior on vanilla models. This PR preserves the ability to opt into actual normal calculation while defaulting to parity with vanilla.

2023-07-17 18:02 UTC, Jonathing requested changes
a few bincompat issues, please view the comments in the files. 😎👍

2023-07-17 18:02 UTC, Jonathing commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +        }
bincompat: Include the old method with the previous signature `(int[], Direction)` and call the new method with a default argument (example: `false`).

2023-07-17 18:02 UTC, Jonathing commented on src/main/java/net/minecraftforge/client/model/ForgeFaceData.java
> +    public static final ForgeFaceData DEFAULT = new ForgeFaceData(0xFFFFFFFF, 0, 0, true, false);
bincompat: Add a constructor without the boolean parameter and give it the default value of `false`.

2023-07-17 18:12 UTC, Jonathing requested changes

2023-07-17 18:12 UTC, Jonathing commented on src/main/java/net/minecraftforge/client/ForgeHooksClient.java
> +    public static void fillNormal(int[] faceData, Direction facing) {
formatting: bracket on next line please

2023-07-17 23:23 UTC, Jonathing approved these changes
Issue fixed when running in dev environment.

2023-07-18 01:09 UTC, LexManos commented
Thanks for this, ran through some basic tests with couple of custom resource packs and weirdly shaped blocks. Seems to fix the reported issues and code wise I don't see it causing much issue.

2023-07-18 01:10 UTC, merged