add null check to TierSortingRegistry.java
MinecraftForge/MinecraftForge pull request #9895
Opened 2024-03-31 05:56 UTC by oldkingOK

if `sortedTiers` contains `null` element, that were put by some mods, it can cause the whole game to crash because of NullPointerException.

2024-03-31 05:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9895) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9895) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=9895) it.</sub>

2024-03-31 17:58 UTC, Jonathing requested changes
I don't understand why this is necessary. From how it looks, it seems like a null pointer exception is only thrown if it gets a null tier from the list. Modders are not supposed to register null tiers, so it is a fault on their part and not that of Forge. It would be much more effective to disallow mods from registering null tiers in the first place.

2024-03-31 23:42 UTC, oldkingOK commented
> Modders are not supposed to register null tiers,

Generally, yes. But when a modpack containing hundreds of mods crashed because of `null of sortedTiers.get(x)`, it would be disastrous for the user to troubleshoot which mods registered null tiers, the reason for this is that if the list contains a null element, every mod that calls this method directly or indirectly may throw the exception. 

Here is an example https://gist.github.com/oldkingOK/4e38947c722eaf0ee38c2020962772c2
Maybe a better way would be to check null when registering Tier?

2024-03-31 23:45 UTC, Jonathing commented
Yes, the better way would be to check for null when registering a Tier. It would not stop the modpack from crashing, but you would be able to identify the culprit since the game would crash when a mod attempts to register a null tier rather than merely ask for a suitable tier.

2024-04-02 01:59 UTC, oldkingOK commented
I've moved null checking to `registerTier` method. 

It's ready for review.

2024-04-02 02:01 UTC, Jonathing approved these changes
Implementation looks good. @PaintNinja can harp on specifics if he needs to.

2024-04-15 13:49 UTC, merged