[1.20.x] Add helper method to `OnDatapackSyncEvent`
MinecraftForge/MinecraftForge pull request #9901
Opened 2024-04-07 21:26 UTC by PaintNinja

Adds a small helper method that optionally makes usage more unified.

Before:
```java
if (event.getPlayer() != null) {
    // do thing with the player
} else {
    for (var serverPlayer : event.getPlayerList().getPlayers()) {
        // do thing with the players
    }
}
```

After:
```java
for (var serverPlayer : event.getRelevantPlayers()) {
    // do thing with the player(s)
}
```

2024-04-14 16:29 UTC, Jonathing commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
Ignoring bin compat obviously, would it even be necessary to expose `getPlayer()` or `getPlayerList()` for this event? Because with what you made here, it's literally a collection of players at any given time with either a list of *every* player or a singleton of the player that needs to sync with the server. Honestly at this point I'd even recommend just renaming `getRelevantPlayers()` to `getPlayers()` and deprecating the other two methods since it basically completely invalidates them.

2024-04-14 16:49 UTC, PaintNinja commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
Makes sense, although personally I'd rather avoid an unnecessary breaking change, especially as I intend to backport if accepted.

2024-04-14 16:50 UTC, Jonathing commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
Backports are whatever. I was moreso talking about if we intend to do some sort of event cleanup in the future. Which, we should.

2024-04-14 16:50 UTC, PaintNinja commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
Wait... I think I misunderstood you. Are you suggesting renaming getRelevantPlayers() to getPlayers(), or do you want to also remove the other couple of methods?

2024-04-14 16:53 UTC, Jonathing commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
Just the former. The latter would be good to consider in an event cleanup, though.

2024-04-14 16:56 UTC, PaintNinja commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
Oh I see. In that case, the reasoning for calling it relevantPlayers instead of just players is to communicate that it'll use one or the other, so that it's clearer that it may return a single player. Would you like me to rename it anyway?

2024-04-14 16:57 UTC, Jonathing commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
Yes. I think the modder should not care about how many players need to sync, since this event effectively says "hey, at least one player needs to be synced, please take care of that."

2024-04-14 17:18 UTC, Jonathing commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
One thing that I forgot to account for is that `getPlayerList()` returns an actual `PlayerList` object rather than a list of players. My friend David made the original event and I've checked for usages of that method in the projects he works on, and found that it's really only used to `getPlayers()` from it. So, I don't see any need to expose the original `PlayerList` object in a future event cleanup, especially since there shouldn't *need* to be any interaction with it when the event exists specifically to call for player synchronization. It's not important to my original argument at all, I just wanted to mention it in case this ever comes up in conversation again.

2024-04-14 17:22 UTC, Jonathing requested changes
**General Requirements**
- [X] Game loads.
- [X] World creation and load succeeds.

**PR-specific Requests**
- [ ] Rename `getRelevantPlayers()` to `getPlayers()`.
- [ ] Optionally, deprecate `getPlayerList()` and `getPlayer()` (no need to mark as for removal).

2024-04-14 17:22 UTC, Jonathing commented on src/main/java/net/minecraftforge/event/OnDatapackSyncEvent.java
> +    public List<ServerPlayer> getRelevantPlayers() {
I would still like to see this renamed to `getPlayers()` given our discussion about it earlier.

2024-04-15 12:41 UTC, Jonathing approved these changes

2024-04-15 13:47 UTC, merged