[1.20.x] Added ByteValue, ShortValue, FloatValue and code reformatting - config revisit part 1
MinecraftForge/MinecraftForge pull request #9902
Opened 2024-04-11 23:45 UTC by SrRapero720

2024-04-12 14:52 UTC, PaintNinja requested changes
Looks alright, but needs some more care to avoid unintentional breaking changes and crashes - I've commented on different parts of the PR to help you with this.

Also, if you're doing a cleanup and changing brackets, please do it for the whole file (I spotted one that was missed at the bottom of the file, may be others too).

2024-04-12 14:52 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
> +        if (obj1 instanceof String string1 && obj2 instanceof String string2) {
In your PR branch, the only usages I can find of this method always call it with String parameters, so we can simplify this...
```suggestion
    private boolean stringsMatchIgnoringNewlines(@Nullable String string1, @Nullable String string2) {
        if (string1 != null && string2 != null) {
```

2024-04-12 14:52 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
>                  String newComment = levelComments.get(parentPath);
```suggestion
                @Nullable String newComment = levelComments.get(parentPath);
```

2024-04-12 14:52 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
> +        private final static boolean USE_CACHES = true;
Minor: final after static
```suggestion
        private static final boolean USE_CACHES = true;
```

2024-04-12 14:52 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
> +        protected ForgeConfigSpec spec;
Access weakened but not used in any inheritors - please leave private until needed in future PRs

2024-04-12 14:52 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
> +                    return acceptableValues.contains(enumObj);
This might cause edge-case generics issues, leave it without the cast and <?> please

2024-04-12 14:52 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
> +        private byte castedValue;
Unused field

2024-04-12 14:52 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
> +        private short castedValue;
Unused field

2024-04-12 14:52 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
>                      list.removeIf(elementValidator.negate());
This will cause a crash if the value is an immutable list (such as `List.of()`)

2024-04-12 14:52 UTC, PaintNinja commented on settings.gradle
> +            version('night-config', '3.6.7')
Please verify that there are no binary or transitive dep breaking changes using the method inside JavaCompatibilityChecker's buildscript

2024-04-12 21:37 UTC, SrRapero720 commented on src/main/java/net/minecraftforge/common/ForgeConfigSpec.java
> +        private final static boolean USE_CACHES = true;
why i didn't spotted it before?

2024-04-12 23:37 UTC, SrRapero720 commented on settings.gradle
> +            version('night-config', '3.6.7')
![image](https://github.com/MinecraftForge/MinecraftForge/assets/29090346/9240e302-aaa3-4853-af63-24c941c467c7)
done

2024-04-13 11:34 UTC, PaintNinja approved these changes

2024-04-13 11:42 UTC, merged