Update SimpleChannel to make StreamCodecs easier
MinecraftForge/MinecraftForge pull request #9959
Opened 2024-05-05 05:23 UTC by LexManos

Split into a couple different commits, the first is the general cleanup allowing correctly types FriendlyByteBuf or RegistryFriendlyButeBuf classes to be used in encode and decode functions.

Second adds the codec(StreamCodec) function to MessageBuilder, which is shorthand for setting the encoder and decoder.
As well as fix the protocols related to Forge's packets.
And add a build() function to SimpleChannel, which prevents additional packets from being registered. Like a normal builder should...

Third expands the SimpleChannel builders to make things more streamlined, some examples of the new builders

```java

    CHANNEL = ChannelBuilder
        .named(NAME)
        .optional()
        .networkProtocolVersion(0)
        .simpleChannel()
            .handler(CONTEXT)
                .login()
                    .serverbound()
                        .add(LoginWrapper.class, LoginWrapper.STREAM_CODEC)
                    
        .buildAll();
 ```

```java

    CHANNEL = ChannelBuilder
        .named(NAME)
        .optional()
        .networkProtocolVersion(0)
        .simpleChannel()
            .handler(CONTEXT)
                .login()
                    .serverbound()
                        .add(ServerToClientLogin.class, ServerToClientLogin.STREAM_CODEC)
                    .build()
                    .clientbound()
                        .add(ClientToServerLogin.class, ClientToLoginServer.STREAM_CODEC)
                    .build()
                .build()
                .play()
                    .add(BiDirectionPlay.class, BiDirectionPlay.STREAM_CODEC)
                .build()
            .build()
            .config()
                .add(BiDirectionConfigWithoutContext.class, BiDirectionConfigWithoutContext.STREAM_CODEC, BidrectionConfig::handle)
        .buildAll();
        ```

2024-05-06 07:13 UTC, MrCrayfish commented on src/main/java/net/minecraftforge/network/NetworkDirection.java
> +    public static final NetworkDirection<FriendlyByteBuf> CONFIG_TO_SERVER = new NetworkDirection<>(NetworkProtocol.CONFIG, PacketFlow.SERVERBOUND);
Sort of out of scope of this PR but just general feedback.

In terms of networking, "config" should be expressed as its full name "configuration". It would help with readability and usability since you would not be switching between the two. This would apply everywhere in the networking code, not just these lines. Forge is also already using the fullname for the following `GatherLoginConfigurationTasksEvent`, `ConfigurationTaskContext`, and `SimpleConfigurationTask`.

2024-05-06 07:13 UTC, MrCrayfish commented on src/main/java/net/minecraftforge/network/SimpleChannel.java
> +        }
Readability wise, I think the chaining starts to go to deep. I think simplification would greatly improve this and just having a single `build` call at the end.

```java
CHANNEL = ChannelBuilder
    .named(NAME)
    .optional()
    .networkProtocolVersion(0)
    .simpleChannel()
    .login(CONTEXT) // Messages here must follow adhere to context
        .serverbound(ServerToClientLogin.class, ServerToClientLogin.STREAM_CODEC)
        .clientbound(ClientToServerLogin.class, ClientToLoginServer.STREAM_CODEC)
        .add(ClientToServerLogin.class, ClientToLoginServer.STREAM_CODEC, NetworkDirection.LOGIN_TO_SERVER) // Explicit version
    .login() // Implicitly calls protocal#build and starts a new protocol?
        .clientbound(ClientExample.class, ClientExample.STREAM_CODEC, ClientExample::handle)    
    .play(CONTEXT)
        .bidirectional(BiDirectionPlay.class, BiDirectionPlay.STREAM_CODEC) // Named "bidirectional" instead of "add"
    .configuration()
        .bidirectional(BiDirectionConfigWithoutContext.class, BiDirectionConfigWithoutContext.STREAM_CODEC, BidrectionConfig::handle)
    .build();
```
    
I realized the above might create a nightmare of a class, so using wrapping msg register under a function might be easier. However I do still think the above is cleaner and more preferable.
```java
CHANNEL = ChannelBuilder
    .named(NAME)
    .optional()
    .networkProtocolVersion(0)
    .simpleChannel()
    .login(CONTEXT, protocol -> {
        protocol.serverbound(ServerToClientLogin.class, ServerToClientLogin.STREAM_CODEC);
        protocol.clientbound(ClientToServerLogin.class, ClientToLoginServer.STREAM_CODEC);
        protocol.add(ClientToServerLogin.class, ClientToLoginServer.STREAM_CODEC, NetworkDirection.LOGIN_TO_SERVER); 
    })
    .login(protocol -> {
        protocol.clientbound(ClientExample.class, ClientExample.STREAM_CODEC, ClientExample::handle);    
    })
    .play(CONTEXT, protocol -> {
        protocol.bidirectional(BiDirectionPlay.class, BiDirectionPlay.STREAM_CODEC);  
    })
    .configuration(protocol -> {
        protocol.bidirectional(BiDirectionConfigWithoutContext.class, BiDirectionConfigWithoutContext.STREAM_CODEC, BidrectionConfig::handle);    
    })
    .build();```

2024-05-07 01:39 UTC, LexManos commented
Not arguing the config change, I dont care either way. so changed it to the full `configuration`

Not going to go with the serverbound/clientbound/bidirectional methods because it would mean that all add functions need to be duplicated for all flows. And that is just asking for code bloat {see the old MessageBuilder class}.

They are currently duplicated in Connection for bidirectional packets, but im not convinced that's the best idea. It just saves a `.flow(null)` call, which i could add as a `.unbound()` or something. Doing so would save maintenance cost.

I think this is gunna be the final design until I rip out MessageBuilder. In theory tho that old API is untouched/binary compatible {haven't tested} at the very least it's source compatible.

I think that the examples provided are clean enough. This being Forge's handler:
```java
    public static SimpleChannel CONFIG = ChannelBuilder
        .named(HANDSHAKE_NAME)
        .optional()
        .networkProtocolVersion(0)
        .simpleChannel()

            .configuration()
                .add(ModVersions.class, ModVersions.STREAM_CODEC, ctx(ForgePacketHandler::handleModVersions))
                .add(ChannelVersions.class, ChannelVersions.STREAM_CODEC, ctx(ForgePacketHandler::handleChannelVersions))
                .serverbound()
                    .add(Acknowledge.class, Acknowledge.STREAM_CODEC, ctx(ForgePacketHandler::handleClientAck))
                .build()
                .clientbound()
                    .add(RegistryList.class, RegistryList.STREAM_CODEC, ctx(ForgePacketHandler::handleRegistryList))
                    .add(RegistryData.class, RegistryData.STREAM_CODEC, ctx(ForgePacketHandler::handleRegistryData))
                    .add(ConfigData.class, ConfigData.STREAM_CODEC, ctx(ForgePacketHandler::handleConfigSync))
                    .add(MismatchData.class, MismatchData.STREAM_CODEC, ctx(ForgePacketHandler::handleModMismatchData))

        .buildAll();     
```

2024-05-07 19:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9959) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9959) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: LexManos<br/>:x: MrCrayfish<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=9959) it.</sub>

2024-05-07 19:54 UTC, LexManos commented
Alright, updated with MrCrayfish's suggestions.
It simplifies the code quite a bit not needing to pass around the parent object. At the cost of only calling build() once. 
Which isn't a big deal, with the way the system works it's basically just making disjointed builders with slightly modified contexts. 

Anyways, as soo as @MrCrayfish signs the CLA This can be pulled

2024-05-07 20:19 UTC, PaintNinja requested changes

2024-05-07 20:19 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/packets/MismatchData.java
> +    public static StreamCodec<FriendlyByteBuf, MismatchData> STREAM_CODEC = StreamCodec.ofMember(MismatchData::encode, MismatchData::decode);
```suggestion
    public static final StreamCodec<FriendlyByteBuf, MismatchData> STREAM_CODEC = StreamCodec.ofMember(MismatchData::encode, MismatchData::decode);
```
Missing final

2024-05-07 20:19 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/packets/ModVersions.java
> +    public static StreamCodec<FriendlyByteBuf, ModVersions> STREAM_CODEC = StreamCodec.ofMember(ModVersions::encode, ModVersions::decode);
```suggestion
    public static final StreamCodec<FriendlyByteBuf, ModVersions> STREAM_CODEC = StreamCodec.ofMember(ModVersions::encode, ModVersions::decode);
```
Missing final

2024-05-07 20:19 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/packets/OpenContainer.java
> +    public static StreamCodec<RegistryFriendlyByteBuf, OpenContainer> STREAM_CODEC = StreamCodec.ofMember(OpenContainer::encode, OpenContainer::decode);
```suggestion
    public static final StreamCodec<RegistryFriendlyByteBuf, OpenContainer> STREAM_CODEC = StreamCodec.ofMember(OpenContainer::encode, OpenContainer::decode);
```
Missing final

2024-05-07 20:19 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/packets/RegistryData.java
> +    public static StreamCodec<FriendlyByteBuf, RegistryData> STREAM_CODEC = StreamCodec.ofMember(RegistryData::encode, RegistryData::decode);
```suggestion
    public static final StreamCodec<FriendlyByteBuf, RegistryData> STREAM_CODEC = StreamCodec.ofMember(RegistryData::encode, RegistryData::decode);
```
Missing final

2024-05-07 20:19 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/packets/RegistryList.java
> +    public static StreamCodec<FriendlyByteBuf, RegistryList> STREAM_CODEC = StreamCodec.ofMember(RegistryList::encode, RegistryList::decode);
```suggestion
    public static final StreamCodec<FriendlyByteBuf, RegistryList> STREAM_CODEC = StreamCodec.ofMember(RegistryList::encode, RegistryList::decode);
```
Missing final

2024-05-07 20:19 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/packets/SpawnEntity.java
> +    public static StreamCodec<RegistryFriendlyByteBuf, SpawnEntity> STREAM_CODEC = StreamCodec.ofMember(SpawnEntity::encode, SpawnEntity::decode);
```suggestion
    public static final StreamCodec<RegistryFriendlyByteBuf, SpawnEntity> STREAM_CODEC = StreamCodec.ofMember(SpawnEntity::encode, SpawnEntity::decode);
```
Missing final

2024-05-07 20:37 UTC, PaintNinja requested changes

2024-05-07 20:37 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/NetworkInitialization.java
>      public static SimpleChannel LOGIN = ChannelBuilder
```suggestion
    public static final SimpleChannel LOGIN = ChannelBuilder
```
I know this is inside a class marked as internal, but would be wise to mark this as final to prevent modders from screwing with it anyway. Plus muh static finals perf

2024-05-07 20:37 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/NetworkInitialization.java
> +    public static SimpleChannel CONFIG = ChannelBuilder
```suggestion
    public static final SimpleChannel CONFIG = ChannelBuilder
```

2024-05-07 20:37 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/NetworkInitialization.java
> +    public static SimpleChannel PLAY = CONFIG;;
```suggestion
    public static final SimpleChannel PLAY = CONFIG;;
```

2024-05-07 20:37 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/NetworkInitialization.java
>  public class NetworkInitialization {
```suggestion
public final class NetworkInitialization {
```
Internal class that we don't extend, so mark as final to prevent unsupported extending of internals.

2024-05-07 20:37 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/NetworkInstance.java
>  public class NetworkInstance {
```suggestion
public final class NetworkInstance {
```
Internal class we don't extend ourselves, to make final to prevent unsupported extending of it

2024-05-07 20:37 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/packets/ConfigData.java
> +    public static StreamCodec<FriendlyByteBuf, ConfigData> STREAM_CODEC = StreamCodec.ofMember(ConfigData::encode, ConfigData::decode);
```suggestion
    public static final StreamCodec<FriendlyByteBuf, ConfigData> STREAM_CODEC = StreamCodec.ofMember(ConfigData::encode, ConfigData::decode);
```

2024-05-08 04:28 UTC, MrCrayfish commented
CLA signed. I've gone over the additional changes and everything looks good. There are some broken `@links` in the documentation of `SimpleChannel$MessageBuilder` and `SimpleConnection` that maybe you want to fix before merging.

2024-05-08 05:53 UTC, merged