Remove ICustomPacket and add PayloadChannel.
MinecraftForge/MinecraftForge pull request #9972
Opened 2024-05-13 02:16 UTC by LexManos

Removal of ICustomPacket in favor of just using a custom Payload type. This drastically simplifies the patches, as I no longer have to edit the vanilla DiscardedPayload or Custom packets.
Connection now tracks and exposes both Inbound and Outbound ProtocolInfo, just useful for utilities like PacketLogger.

The new PayloadChannel is a copy of SimpleChannel but instead of using Classes to identify the packets it forces them to be subclasses of CustomPacketPayload and uses CustomPacketPayload.Type to identify.
They are still sent over the wire using a varint discriminator, because redundant info.

I added a generic `channel(Function)` method to ChannelBuilder to allow modders to create their own channels however they want. So that we don't have to do these things in the future.

2024-05-13 11:33 UTC, PaintNinja requested changes
The reduced amount of patches and PacketLogger utilities are nice, likewise for supporting `CustomPacketPayload.Type` and the generic channel method.

Added some general feedback/code review, but not experienced with the networking myself, so leaving the more architectural side of things to others like crayfish.

2024-05-13 11:33 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/PayloadChannel.java
> +        protected Object2ObjectMap<CustomPacketPayload.Type<?>, Message<?, ?>> byType = new Object2ObjectArrayMap<>();
This Map is updated by the add(Message) method but never queried or used outside of that

2024-05-13 11:33 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/util/PacketLogger.java
> +        }
This can be a pattern matching switch in Java 21, like this:
```java
switch (packet) {
    case ClientboundCustomPayloadPacket custom -> {
        channel = custom.payload().type().id().toString();
        hex = hex(protocol, packet);
    }
    case ServerboundCustomPayloadPacket custom -> {
        channel = custom.payload().type().id().toString();
        hex = hex(protocol, packet);
    }
    case ClientboundCustomQueryPacket custom -> {
        channel = custom.payload().id().toString() + " id " + custom.transactionId();
        hex = hex(protocol, packet);
    }
    case ServerboundCustomQueryAnswerPacket custom -> {
        channel = packet.getClass().getName() + " id " + custom.transactionId();
        hex = hex(protocol, packet);
    }
    default -> {}
}
```

2024-05-13 11:33 UTC, PaintNinja commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +    public static <B extends FriendlyByteBuf> StreamCodec<B, ? extends CustomPacketPayload> getCustomPayloadCodec(ResourceLocation id, int max) {
Marked as nullable but I can't see where it would return null... possible mistake?

2024-05-13 11:33 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/PayloadChannel.java
> +    private interface ProtocolFactory<BUF extends FriendlyByteBuf, BASE extends CustomPacketPayload> extends PayloadConnection<BASE>, PayloadBuildable {
Possible candidate for `sealed` keyword (`permits` can be omitted in this case)

2024-05-13 11:33 UTC, PaintNinja commented on src/main/java/net/minecraftforge/network/PayloadChannel.java
> +        PacketFlow direction,
These two record components can be marked with `@Nullable` as they're sometimes fed nulls and have null handling

2024-05-13 11:33 UTC, PaintNinja commented on src/main/java/net/minecraftforge/event/network/CustomPayloadEvent.java
> +        this.data = payload instanceof ForgePayload forge ? forge.data() : null;
Would it make sense to also `instanceof FriendlyByteBuf` and use directly if available instead of null?

2024-05-13 15:30 UTC, LexManos commented on src/main/java/net/minecraftforge/network/PayloadChannel.java
> +        protected Object2ObjectMap<CustomPacketPayload.Type<?>, Message<?, ?>> byType = new Object2ObjectArrayMap<>();
Right, meant to copy them in the channel constructor. Didn't write a test of this code so didn't catch that.

2024-05-13 15:37 UTC, LexManos commented on src/main/java/net/minecraftforge/network/PayloadChannel.java
> +    private interface ProtocolFactory<BUF extends FriendlyByteBuf, BASE extends CustomPacketPayload> extends PayloadConnection<BASE>, PayloadBuildable {
It's private, what would the benefit of sealed without permits be?

2024-05-13 15:41 UTC, LexManos commented on src/main/java/net/minecraftforge/event/network/CustomPayloadEvent.java
> +        this.data = payload instanceof ForgePayload forge ? forge.data() : null;
No, the payload will always be an instance of CustomPacketPayload. As a matter of fact I should change the parameter type.

2024-05-14 13:45 UTC, MrCrayfish commented on src/main/java/net/minecraftforge/network/NetworkProtocol.java
> +    public <T extends PacketListener, MSG> Packet<T> buildPacket(PacketFlow direction, ResourceLocation name, Consumer<FriendlyByteBuf> encoder) {
MSG is now unused here

2024-05-14 13:47 UTC, MrCrayfish commented on src/main/java/net/minecraftforge/network/NetworkProtocol.java
>  public class NetworkProtocol<B extends FriendlyByteBuf> {
`B` is now unused, however I understand that removing this would break everything. Could this be incorporated into the consumer of `buildPacket`?

2024-05-14 15:36 UTC, merged