Modded Biome Decoration Crash Fix
MinecraftForge/MinecraftForge pull request #9975
Opened 2024-05-17 23:24 UTC by ianvivi13

Previously, the game would crash sometimes when attempting to generate modded biome decorations. This could be replicated by creating a custom biome decoration and having it generate in the world (ore for example), creating a new world, exiting the world, reloading the world, and entering a new chunk where the biome decoration has not yet been generated. The game would crash while attempting to generate the modded biome decoration.

This PR introduces a simple fix for this bug. This code was tested with my own mod that was having this issue prior to implementing this solution. After making these code changes, the issue was resolved. I have attached the crash log that I received prior to implementing the fix so you can see the error for yourself.
[crash-2024-05-17_15.01.27-server.txt](https://github.com/MinecraftForge/MinecraftForge/files/15358794/crash-2024-05-17_15.01.27-server.txt)

2024-05-17 23:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9975) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MinecraftForge/MinecraftForge?pullRequest=9975) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MinecraftForge/MinecraftForge?pullRequest=9975) it.</sub>

2024-05-18 00:35 UTC, ianvivi13 commented
Attached below is an Example Mod that creates a block and generates it throughout the world (I only included the src folder as the zip of the entire mod was too big to upload. To replicate the crash, repeat the following steps:

1. Create a new world and load into it
2. Exit the world to the main menu
3. Rejoin the world
4. Load a new chunk that has not been generated yet

Source Code: [src.zip](https://github.com/MinecraftForge/MinecraftForge/files/15358972/src.zip)

2024-05-20 15:00 UTC, mysticdrew requested changes

2024-05-20 15:00 UTC, mysticdrew commented on src/main/java/net/minecraftforge/server/ServerLifecycleHooks.java
> -import java.util.concurrent.atomic.AtomicBoolean;
you probably did not intend to change the import order?

2024-05-20 15:00 UTC, mysticdrew commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> -
What's with all the import order changes?

2024-05-20 16:31 UTC, ianvivi13 commented on mdk/build.gradle
This file has no actual changes, my editor just keeps removing the white spaces despite my attempts to revert it to it's previous state

2024-05-20 17:12 UTC, Jonathing commented on mdk/build.gradle
If that's the case, then please don't stage or commit them. Most Git GUIs can allow you to stage or unstage specific hunks of data and not commit the entire file. Keeping the PR clean will make this entire process easier for everyone.

2024-05-20 19:08 UTC, ianvivi13 commented on mdk/build.gradle
I changed the file originally in an older commit but when I tried to revert it, it did that

2024-05-20 22:07 UTC, Jonathing requested changes
Your heart is in the right place with this PR. But, in the code sector of things, there is quite a bit of gunk. There are a handful of variables and files that did not need editing, and there just needs to be an overall better aspect of polish. Feel free to continue discussions in the Discord server on how to best polish this PR for merging, or if you want to help @RealMangorage with his solution in #9980.

2024-05-20 22:07 UTC, Jonathing commented on src/main/java/net/minecraftforge/common/util/NonNullLazy.java
> +        Lazy<T> lazy = Lazy.of(supplier::get);
Why did you change this? This PR does not contain any changes to the base `Lazy` class that would justify not using `Lazy.concurrentOf` in this method like before.

2024-05-20 22:07 UTC, Jonathing commented on src/main/java/net/minecraftforge/common/util/Lazier.java
Please add a comment or javadoc that describes the purpose of this class as compared to `Lazy`.

2024-05-20 22:07 UTC, Jonathing commented on mdk/build.gradle
Since it is just whitespace changes, I won't be anal about it. However, please be careful regarding editing unrelated files in PRs moving forward.

2024-05-20 22:07 UTC, Jonathing commented on src/main/java/net/minecraftforge/common/ForgeHooks.java
> +    private static final Lazier<Map<String, StructuresBecomeConfiguredFix.Conversion>> FORGE_CONVERSION_MAP = Lazier.of(() -> {
Why are you converting this map into a Lazier? It does not have any explicit usages anywhere in this PR. It is a private variable that is only used in [getStructureConversion(...)](https://github.com/MinecraftForge/MinecraftForge/blob/7bd99ee73838ca2f38cb16453f2b5d23b80678bc/src/main/java/net/minecraftforge/common/ForgeHooks.java#L997-L1000), and that method is also not called anywhere else in this PR.

2024-05-20 22:11 UTC, ianvivi13 commented on src/main/java/net/minecraftforge/common/util/NonNullLazy.java
> +        Lazy<T> lazy = Lazy.of(supplier::get);
That's my bad. In my original implementation, I modified the Lazy class and forgot to change that back after reverting that change

2024-05-20 22:45 UTC, closed without merging